// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** Deutsch: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'observation.title': 'Beobachtungen',
  'observation.close': 'Beobachtungen schließen',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyse',
  'observation.new': 'Neue Beobachtung',
  'observation.newTitleField': 'Titel',
  'observation.newTitleHelp': 'Sagen Sie in einem Satz, was gesehen wurde: „Der nächtliche Schadenlauf reicht bis in die Bürozeit“.',
  'observation.newWhereField': 'Wo es gesehen wurde',
  'observation.newImpactField': 'Auswirkung',
  'observation.newShareField': 'Mit den Scopes darüber teilen',
  'observation.newByField': 'Beobachtet von',
  'observation.create': 'Festhalten',
  'observation.newCause': 'Neue Ursache',
  'observation.newCauseHelp': 'Sagen Sie, was dahintersteckt: „Das Batchfenster ist auf die Mengen von 2019 ausgelegt“.',
  'observation.createCause': 'Hinzufügen',
  'observation.searchPlaceholder': 'Beobachtungen und Ursachen durchsuchen',
  'observation.searchField': 'Beobachtungen suchen',
  'observation.listEmpty': 'Hier wurde noch nichts beobachtet.',
  'observation.searchEmpty': 'Nichts passt zu „{query}“.',
  'observation.noneSelected': 'Wählen Sie eine Beobachtung oder eine Ursache, oder halten Sie eine fest.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Wo',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Auswirkung',
  'observation.colSeen': 'Gesehen',
  'observation.colCauses': 'Analysiert zu',
  'observation.scopeHere': 'Dieser Scope',
  'observation.fromBelow': 'Geteilt aus {scope}',
  'observation.sharedMark': 'Geteilt',
  'observation.showMerged': 'Zusammengeführte zeigen',
  'observation.showArchived': 'Archivierte zeigen',
  'observation.archivedMark': 'Archiviert',
  'observation.notAnalysed': 'noch nicht',
  'observation.impactMinor': 'Gering',
  'observation.impactMajor': 'Erheblich',
  'observation.impactCritical': 'Kritisch',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lesen',
  'observation.edit': 'Bearbeiten',
  'observation.source': 'Quelltext der Beobachtung',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Wo gesehen',
  'observation.byField': 'Beobachtet von',
  'observation.dateField': 'Datum gesehen',
  'observation.impactField': 'Auswirkung',
  'observation.seenAgain': 'Erneut gesehen',
  'observation.share': 'Mit den Scopes darüber teilen',
  'observation.unshare': 'Nicht mehr teilen',
  'observation.shared': 'Mit den Scopes darüber geteilt',
  'observation.local': 'Lokal in diesem Scope',
  'observation.shareHelp': 'Geteilt liest jeder Scope über diesem sie, kann sie mit einer eigenen Ursache verknüpfen und in eine eigene Beobachtung zusammenführen. Lokal ist die Vorgabe.',
  'observation.merge': 'Zusammenführen mit…',
  'observation.mergeTitle': '{name} mit einer anderen Beobachtung zusammenführen',
  'observation.mergeBody': 'Die Sichtungen und die Ursachen gehen auf die gewählte Beobachtung über, und beide Datensätze sagen das mit dem heutigen Datum. Der zusammengeführte Datensatz bleibt, als Geschichte.',
  'observation.mergePick': 'Die Beobachtung, mit der sie identisch ist',
  'observation.mergeConfirm': 'Zusammenführen',
  'observation.mergedInto': 'Zusammengeführt mit {name}',
  'observation.mergedAbove': 'Zusammengeführt mit {name} in {scope} am {date}',
  'observation.archive': 'Archivieren…',
  'observation.archiveTitle': '{name} archivieren?',
  'observation.archiveBody': 'Behoben, angegangen oder nicht mehr relevant: der Eintrag bleibt, als Geschichte, und verlässt die Analyse. Wiederherstellen bringt ihn zurück.',
  'observation.archiveNote': 'Warum (optional)',
  'observation.archiveConfirm': 'Archivieren',
  'observation.restore': 'Wiederherstellen',
  'observation.archivedOn': 'Archiviert am {date}',
  'observation.history': 'Geschichte',
  'observation.eventRecorded': 'Festgehalten',
  'observation.eventSeen': 'Erneut gesehen',
  'observation.eventShared': 'Mit den Scopes darüber geteilt',
  'observation.eventUnshared': 'Teilen beendet',
  'observation.eventArchived': 'Archiviert',
  'observation.eventRestored': 'Wiederhergestellt',
  'observation.eventAbsorbed': '{name} aufgenommen ({count}-mal gesehen)',
  'observation.eventMerged': 'Zusammengeführt mit {name}',
  'observation.fromScope': 'Diese Beobachtung gehört zu {scope}. Hier wird sie gelesen und verknüpft; dort wird sie geändert.',
  'observation.openScope': '{scope} öffnen',
  'observation.delete': 'Löschen',
  'observation.deleteTitle': '{name} löschen?',
  'observation.deleteBody': 'Der Datensatz verschwindet, mit jeder Verknüpfung, die eine Ursache darauf hatte. Die Nummer wird nie wiederverwendet.',
  'observation.causes': 'Ursachen',
  'observation.cause': 'Ursache',
  'observation.rootCause': 'Grundursache',
  'observation.rootCauses': 'Grundursachen',
  'observation.causeSource': 'Quelltext der Ursache',
  'observation.stateAssumed': 'Angenommen',
  'observation.stateVerified': 'Verifiziert',
  'observation.verify': 'Als verifiziert markieren',
  'observation.unverify': 'Zurück zu angenommen',
  'observation.explains': 'Erklärt',
  'observation.explainedBy': 'Erklärt durch',
  'observation.noLinks': 'Noch nichts',
  'observation.link': 'Mit einer Ursache verknüpfen…',
  'observation.linkDeeper': 'Mit einer tieferen Ursache verknüpfen…',
  'observation.linkTitle': 'Was steckt hinter {name}?',
  'observation.linkPick': 'Ursache',
  'observation.linkNew': 'Eine neue Ursache…',
  'observation.linkNewTitle': 'Ursache benennen',
  'observation.linkStrength': 'Zusammenhang',
  'observation.linkConfirm': 'Verknüpfen',
  'observation.unlink': 'Verknüpfung lösen',
  'observation.strengthStrong': 'Stark',
  'observation.strengthNormal': 'Normal',
  'observation.strengthWeak': 'Schwach',
  'observation.deleteCauseTitle': '{name} löschen?',
  'observation.deleteCauseBody': 'Die Verknüpfungen von ihr und zu ihr gehen mit.',
  'observation.rootNote': 'Hinter dieser Ursache wurde noch nichts gefunden. Verknüpfen Sie sie mit einer tieferen, und sie ist keine Grundursache mehr.',
  'observation.tplSaw': 'Was wir gesehen haben',
  'observation.tplEvidence': 'Belege',
  'observation.tplThoughts': 'Erste Gedanken',
  'observation.tplWhy': 'Warum wir das annehmen',
  'observation.tplVerify': 'Wie zu verifizieren',
  'observation.laneObservations': 'Beobachtungen',
  'observation.laneCauses': 'Ursachen',
  'observation.laneRoots': 'Grundursachen',
  'observation.legendImpact': 'Größe: Auswirkung',
  'observation.legendSeen': 'Tönung: wie oft gesehen',
  'observation.legendAssumed': 'Gestrichelt: angenommen',
  'observation.legendVerified': 'Durchgezogen: verifiziert',
  'observation.legendRoot': 'Grundursache',
  'observation.legendStrength': 'Stark · normal · schwach',
  'observation.phaseObserved': 'beobachtet',
  'observation.phaseAnalysed': 'analysiert',
  'observation.phaseAssumed': 'angenommen',
  'observation.phaseVerified': 'verifiziert',
  'observation.phaseRoots': 'Grundursachen',
  'observation.toAnalyse': 'Noch nicht analysiert',
  'observation.graphEmpty': 'Noch nichts zu zeichnen. Halten Sie eine Beobachtung fest und verknüpfen Sie sie mit einer Ursache.',
  'observation.resizeReader': 'Lesebereich in der Größe ändern',


  // --- solutions (ADR-0026) -----------------------------------------------------------------
  'solution.tab': 'Lösungen',
  'solution.new': 'Neue Lösung',
  'solution.newTitleField': 'Titel',
  'solution.newTitleHelp': 'Sagen Sie, was die Ursache beseitigt: „Eine Lieferprognose für jeden Kanal“.',
  'solution.newCauseField': 'Für die Ursache',
  'solution.noCause': 'Noch keine Ursache',
  'solution.create': 'Vorschlagen',
  'solution.laneDirections': 'Richtungen',
  'solution.laneExperiments': 'Experimente',
  'solution.laneStructural': 'Strukturell',
  'solution.wholeChain': 'Ganze Kette',
  'solution.showDropped': 'Verworfene zeigen',
  'solution.coverage': '{count} von {total} Grundursachen haben eine aktive Lösung',
  'solution.graphEmpty': 'Noch nichts zu zeichnen. Schlagen Sie eine Lösung für eine Grundursache vor.',
  'solution.solutions': 'Lösungen',
  'solution.experiments': 'Experimente',
  'solution.legendWidth': 'Breite: erwarteter Nutzen',
  'solution.legendFill': 'Füllung: wie weit sie ist',
  'solution.legendAddresses': 'Linie: behebt eine Ursache',
  'solution.legendTests': 'Gestrichelt: testet',
  'solution.flagNoSolution': 'Eine Grundursache, an der noch niemand arbeitet',
  'solution.flag': 'Braucht Aufmerksamkeit',
  // --- phases, sizes, outcomes
  'solution.phaseIdea': 'Idee',
  'solution.phaseShaped': 'Ausgearbeitet',
  'solution.phaseTesting': 'Im Test',
  'solution.phaseProven': 'Bewährt',
  'solution.phaseAdopted': 'Beschlossen',
  'solution.phaseImplemented': 'Umgesetzt',
  'solution.phaseDropped': 'Verworfen',
  'solution.sizeSmall': 'Klein',
  'solution.sizeMedium': 'Mittel',
  'solution.sizeLarge': 'Groß',
  'solution.outcomePlanned': 'Geplant',
  'solution.outcomeRunning': 'Läuft',
  'solution.outcomeConfirmed': 'Bestätigt',
  'solution.outcomeRefuted': 'Widerlegt',
  'solution.outcomeInconclusive': 'Ergebnislos',
  // --- one solution
  'solution.source': 'Quelltext der Lösung',
  'solution.titleField': 'Titel',
  'solution.benefitField': 'Erwarteter Nutzen',
  'solution.costField': 'Grobe Kosten',
  'solution.unset': 'Nicht angegeben',
  'solution.addresses': 'Behebt',
  'solution.addressCause': 'Eine Ursache angehen…',
  'solution.addressTitle': 'Welche Ursache behebt {name}?',
  'solution.addressPick': 'Ursache',
  'solution.addressConfirm': 'Angehen',
  'solution.gateTitle': 'Um weiterzugehen zu {state}',
  'solution.moveOn': 'Weiter zu {state}',
  'solution.moveBack': 'Zurück zu {state}',
  'solution.toGo': 'noch {count}',
  'solution.gateAddresses': 'Behebt mindestens eine Ursache',
  'solution.gateBenefit': 'Erwarteter Nutzen',
  'solution.gateCost': 'Grobe Kosten',
  'solution.gateValidatedWith': 'Mit jemandem geprüft, der damit leben muss',
  'solution.gateTriedBefore': 'Wurde das schon einmal versucht?',
  'solution.gateWhyNow': 'Warum es jetzt funktioniert, wenn es damals nicht ging',
  'solution.gateExperimentPlanned': 'Ein Experiment ist geplant oder läuft',
  'solution.gateExperimentConfirmed': 'Ein Experiment hat es bestätigt, oder es wurde begründet übersprungen',
  'solution.gateDecisionAccepted': 'Eine Entscheidung, angenommen',
  'solution.validatedWith': 'Geprüft mit',
  'solution.validatedField': 'Ein Name, eine Rolle oder ein Team',
  'solution.add': 'Hinzufügen',
  'solution.remove': 'Entfernen',
  'solution.attempts': 'Früher versucht',
  'solution.noneKnown': 'Nichts bekannt',
  'solution.notAnswered': 'Nicht beantwortet',
  'solution.attemptAdd': 'Früheren Versuch hinzufügen',
  'solution.attemptWhen': 'Wann',
  'solution.attemptWhat': 'Was versucht wurde',
  'solution.attemptWhy': 'Warum es nicht hielt',
  'solution.whyNow': 'Warum jetzt',
  'solution.whyNowField': 'Was diesmal anders ist',
  'solution.save': 'Speichern',
  'solution.waive': 'Überspringen',
  'solution.waiveField': 'Warum kein Experiment nötig ist',
  'solution.waived': 'Experiment übersprungen: {reason}',
  'solution.planExperiment': 'Ein Experiment planen…',
  'solution.proposeDecision': 'Die Entscheidung vorschlagen',
  'solution.decision': 'Entscheidung',
  'solution.decisionStatus': '{label} ist {status}',
  'solution.open': 'Öffnen',
  'solution.plan': 'Plan',
  'solution.startPlan': 'Einen Plan beginnen',
  'solution.noPlan': 'Noch kein Plan',
  'solution.didItWork': 'Hat es gewirkt?',
  'solution.didItWorkHelp': 'Die Beobachtungen unter dem, was sie behebt. Keine sollte mehr auftreten.',
  'solution.seenSince': 'Erneut gesehen am {date}',
  'solution.heldSince': 'Seit {date} nicht mehr gesehen',
  'solution.alternatives': 'Alternativen zu denselben Ursachen',
  'solution.none': 'Keine',
  'solution.drop': 'Verwerfen…',
  'solution.dropTitle': '{name} verwerfen?',
  'solution.dropBody': 'Sie bleibt als erwogene Alternative in der Liste. Sagen Sie warum, damit die Nächsten es nicht blind erneut versuchen.',
  'solution.dropNote': 'Warum',
  'solution.dropConfirm': 'Verwerfen',
  'solution.restore': 'Wiederherstellen',
  'solution.droppedNote': 'Verworfen: {note}',
  'solution.questionWorksAround': 'Umgeht, statt zu lösen: sie behebt keine Grundursache. Als Notlösung in Ordnung; sagen Sie das, oder gehen Sie auch die Grundursache an.',
  'solution.questionAddsOnly': 'Fügt hinzu, ohne aufzuräumen: der Plan führt ein und löst nichts ab. Was macht das überflüssig?',
  'solution.questionAdoptedUnplanned': 'Beschlossen, nicht geplant: noch baut kein Plan sie.',
  'solution.findingSeenAgain': 'Seit der Umsetzung erneut gesehen: {names}. Hat es gewirkt?',
  'solution.eventProposed': 'Vorgeschlagen',
  'solution.eventMoved': 'Weiter zu {state}',
  'solution.eventWaived': 'Experiment übersprungen',
  'solution.eventLinked': '{name} verknüpft',
  'solution.eventDropped': 'Verworfen',
  'solution.eventRestored': 'Wiederhergestellt',
  'solution.deleteTitle': '{name} löschen?',
  'solution.deleteBody': 'Der Eintrag verschwindet, auch aus jedem Experiment, das ihn testete. Die Nummer wird nie wieder vergeben.',
  'solution.deleteExperimentBody': 'Der Eintrag verschwindet. Die Nummer wird nie wieder vergeben.',
  'solution.forCause': 'Lösungen dafür',
  'solution.proposeForCause': 'Eine Lösung vorschlagen…',
  // --- one experiment
  'solution.experimentSource': 'Quelltext des Experiments',
  'solution.tests': 'Testet',
  'solution.hypothesis': 'Hypothese',
  'solution.hypothesisHelp': 'Wenn wir …, dann … um …',
  'solution.measure': 'Wie es gemessen wird',
  'solution.whereField': 'Wo',
  'solution.byField': 'Von',
  'solution.fromField': 'Von',
  'solution.toField': 'Bis',
  'solution.result': 'Ergebnis',
  'solution.outcome': 'Ausgang',
  'solution.newExperiment': 'Ein Experiment planen',
  'solution.createExperiment': 'Planen',
  'solution.refutedNote': 'Ein widerlegtes Experiment bleibt. Es ist der Beleg, nach dem die Nächsten fragen.',
  // --- the templates
  'solution.tplIdea': 'Die Idee',
  'solution.tplCosts': 'Kosten und Nutzen',
  'solution.tplWhyHere': 'Warum dieser Bereich',
  'solution.tplAlternatives': 'Alternativen',
  'solution.tplRisks': 'Risiken',
  'solution.tplSetup': 'Wie es aufgebaut ist',
  'solution.tplLearned': 'Was wir gelernt haben',
  'solution.decisionAddresses': 'Sie behebt:',
  'solution.decisionAlternatives': 'Für dieselben Ursachen erwogen:',
  'solution.decisionDropped': 'verworfen: {note}',
}
