// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** Deutsch: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'observation.title': 'Beobachtungen',
  'observation.close': 'Beobachtungen schließen',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyse',
  'observation.new': 'Neue Beobachtung',
  'observation.newTitleField': 'Titel',
  'observation.newTitleHelp': 'Sagen Sie in einem Satz, was gesehen wurde: „Der nächtliche Schadenlauf reicht bis in die Bürozeit“.',
  'observation.newWhereField': 'Wo es gesehen wurde',
  'observation.newImpactField': 'Auswirkung',
  'observation.newShareField': 'Mit den Scopes darüber teilen',
  'observation.newByField': 'Beobachtet von',
  'observation.create': 'Festhalten',
  'observation.newCause': 'Neue Ursache',
  'observation.newCauseHelp': 'Sagen Sie, was dahintersteckt: „Das Batchfenster ist auf die Mengen von 2019 ausgelegt“.',
  'observation.createCause': 'Hinzufügen',
  'observation.searchPlaceholder': 'Beobachtungen und Ursachen durchsuchen',
  'observation.searchField': 'Beobachtungen suchen',
  'observation.listEmpty': 'Hier wurde noch nichts beobachtet.',
  'observation.searchEmpty': 'Nichts passt zu „{query}“.',
  'observation.noneSelected': 'Wählen Sie eine Beobachtung oder eine Ursache, oder halten Sie eine fest.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Wo',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Auswirkung',
  'observation.colSeen': 'Gesehen',
  'observation.colCauses': 'Analysiert zu',
  'observation.scopeHere': 'Dieser Scope',
  'observation.fromBelow': 'Geteilt aus {scope}',
  'observation.sharedMark': 'Geteilt',
  'observation.showMerged': 'Zusammengeführte zeigen',
  'observation.showArchived': 'Archivierte zeigen',
  'observation.archivedMark': 'Archiviert',
  'observation.notAnalysed': 'noch nicht',
  'observation.impactMinor': 'Gering',
  'observation.impactMajor': 'Erheblich',
  'observation.impactCritical': 'Kritisch',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lesen',
  'observation.edit': 'Bearbeiten',
  'observation.source': 'Quelltext der Beobachtung',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Wo gesehen',
  'observation.byField': 'Beobachtet von',
  'observation.dateField': 'Datum gesehen',
  'observation.impactField': 'Auswirkung',
  'observation.seenAgain': 'Erneut gesehen',
  'observation.share': 'Mit den Scopes darüber teilen',
  'observation.unshare': 'Nicht mehr teilen',
  'observation.shared': 'Mit den Scopes darüber geteilt',
  'observation.local': 'Lokal in diesem Scope',
  'observation.shareHelp': 'Geteilt liest jeder Scope über diesem sie, kann sie mit einer eigenen Ursache verknüpfen und in eine eigene Beobachtung zusammenführen. Lokal ist die Vorgabe.',
  'observation.merge': 'Zusammenführen mit…',
  'observation.mergeTitle': '{name} mit einer anderen Beobachtung zusammenführen',
  'observation.mergeBody': 'Die Sichtungen und die Ursachen gehen auf die gewählte Beobachtung über, und beide Datensätze sagen das mit dem heutigen Datum. Der zusammengeführte Datensatz bleibt, als Geschichte.',
  'observation.mergePick': 'Die Beobachtung, mit der sie identisch ist',
  'observation.mergeConfirm': 'Zusammenführen',
  'observation.mergedInto': 'Zusammengeführt mit {name}',
  'observation.mergedAbove': 'Zusammengeführt mit {name} in {scope} am {date}',
  'observation.archive': 'Archivieren…',
  'observation.archiveTitle': '{name} archivieren?',
  'observation.archiveBody': 'Behoben, angegangen oder nicht mehr relevant: der Eintrag bleibt, als Geschichte, und verlässt die Analyse. Wiederherstellen bringt ihn zurück.',
  'observation.archiveNote': 'Warum (optional)',
  'observation.archiveConfirm': 'Archivieren',
  'observation.restore': 'Wiederherstellen',
  'observation.archivedOn': 'Archiviert am {date}',
  'observation.history': 'Geschichte',
  'observation.eventRecorded': 'Festgehalten',
  'observation.eventSeen': 'Erneut gesehen',
  'observation.eventShared': 'Mit den Scopes darüber geteilt',
  'observation.eventUnshared': 'Teilen beendet',
  'observation.eventArchived': 'Archiviert',
  'observation.eventRestored': 'Wiederhergestellt',
  'observation.eventAbsorbed': '{name} aufgenommen ({count}-mal gesehen)',
  'observation.eventMerged': 'Zusammengeführt mit {name}',
  'observation.fromScope': 'Diese Beobachtung gehört zu {scope}. Hier wird sie gelesen und verknüpft; dort wird sie geändert.',
  'observation.openScope': '{scope} öffnen',
  'observation.delete': 'Löschen',
  'observation.deleteTitle': '{name} löschen?',
  'observation.deleteBody': 'Der Datensatz verschwindet, mit jeder Verknüpfung, die eine Ursache darauf hatte. Die Nummer wird nie wiederverwendet.',
  'observation.causes': 'Ursachen',
  'observation.cause': 'Ursache',
  'observation.rootCause': 'Grundursache',
  'observation.rootCauses': 'Grundursachen',
  'observation.causeSource': 'Quelltext der Ursache',
  'observation.stateAssumed': 'Angenommen',
  'observation.stateVerified': 'Verifiziert',
  'observation.verify': 'Als verifiziert markieren',
  'observation.unverify': 'Zurück zu angenommen',
  'observation.explains': 'Erklärt',
  'observation.explainedBy': 'Erklärt durch',
  'observation.noLinks': 'Noch nichts',
  'observation.link': 'Mit einer Ursache verknüpfen…',
  'observation.linkDeeper': 'Mit einer tieferen Ursache verknüpfen…',
  'observation.linkTitle': 'Was steckt hinter {name}?',
  'observation.linkPick': 'Ursache',
  'observation.linkNew': 'Eine neue Ursache…',
  'observation.linkNewTitle': 'Ursache benennen',
  'observation.linkStrength': 'Zusammenhang',
  'observation.linkConfirm': 'Verknüpfen',
  'observation.unlink': 'Verknüpfung lösen',
  'observation.strengthStrong': 'Stark',
  'observation.strengthNormal': 'Normal',
  'observation.strengthWeak': 'Schwach',
  'observation.deleteCauseTitle': '{name} löschen?',
  'observation.deleteCauseBody': 'Die Verknüpfungen von ihr und zu ihr gehen mit.',
  'observation.rootNote': 'Hinter dieser Ursache wurde noch nichts gefunden. Verknüpfen Sie sie mit einer tieferen, und sie ist keine Grundursache mehr.',
  'observation.tplSaw': 'Was wir gesehen haben',
  'observation.tplEvidence': 'Belege',
  'observation.tplThoughts': 'Erste Gedanken',
  'observation.tplWhy': 'Warum wir das annehmen',
  'observation.tplVerify': 'Wie zu verifizieren',
  'observation.laneObservations': 'Beobachtungen',
  'observation.laneCauses': 'Ursachen',
  'observation.laneRoots': 'Grundursachen',
  'observation.legendImpact': 'Größe: Auswirkung',
  'observation.legendSeen': 'Tönung: wie oft gesehen',
  'observation.legendAssumed': 'Gestrichelt: angenommen',
  'observation.legendVerified': 'Durchgezogen: verifiziert',
  'observation.legendRoot': 'Grundursache',
  'observation.legendStrength': 'Stark · normal · schwach',
  'observation.phaseObserved': 'beobachtet',
  'observation.phaseAnalysed': 'analysiert',
  'observation.phaseAssumed': 'angenommen',
  'observation.phaseVerified': 'verifiziert',
  'observation.phaseRoots': 'Grundursachen',
  'observation.toAnalyse': 'Noch nicht analysiert',
  'observation.graphEmpty': 'Noch nichts zu zeichnen. Halten Sie eine Beobachtung fest und verknüpfen Sie sie mit einer Ursache.',
  'observation.resizeReader': 'Lesebereich in der Größe ändern',
}
