// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** Deutsch: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'observation.title': 'Beobachtungen',
  'observation.close': 'Beobachtungen schließen',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyse',
  'observation.new': 'Neue Beobachtung',
  'observation.newWhereField': 'Wo es gesehen wurde',
  'observation.newImpactField': 'Auswirkung',
  'observation.newByField': 'Beobachtet von',
  'observation.newCause': 'Neue Ursache',
  'observation.searchPlaceholder': 'Beobachtungen und Ursachen durchsuchen',
  'observation.searchField': 'Beobachtungen suchen',
  'observation.listEmpty': 'Hier wurde noch nichts beobachtet.',
  'observation.searchEmpty': 'Nichts passt zu „{query}“.',
  'observation.noneSelected': 'Wählen Sie eine Beobachtung oder eine Ursache, oder halten Sie eine fest.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Wo',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Auswirkung',
  'observation.colSeen': 'Gesehen',
  'observation.colCauses': 'Analysiert zu',
  'observation.scopeHere': 'Dieser Scope',
  'observation.fromBelow': 'Lokal in {scope}',
  'observation.showMerged': 'Zusammengeführte zeigen',
  'observation.showArchived': 'Archivierte zeigen',
  'observation.archivedMark': 'Archiviert',
  'observation.notAnalysed': 'noch nicht',
  'observation.impactMinor': 'Gering',
  'observation.impactMajor': 'Erheblich',
  'observation.impactCritical': 'Kritisch',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lesen',
  'observation.edit': 'Bearbeiten',
  'observation.source': 'Quelltext der Beobachtung',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Wo gesehen',
  'observation.byField': 'Beobachtet von',
  'observation.dateField': 'Datum gesehen',
  'observation.impactField': 'Auswirkung',
  'observation.seenAgain': 'Erneut gesehen',
  'observation.local': 'Lokal in diesem Scope',
  'observation.merge': 'Zusammenführen mit…',
  'observation.mergeTitle': '{name} mit einer anderen Beobachtung zusammenführen',
  'observation.mergeBody': 'Die Sichtungen und die Ursachen gehen auf die gewählte Beobachtung über, und beide Datensätze sagen das mit dem heutigen Datum. Der zusammengeführte Datensatz bleibt, als Geschichte.',
  'observation.mergePick': 'Die Beobachtung, mit der sie identisch ist',
  'observation.mergeConfirm': 'Zusammenführen',
  'observation.mergedInto': 'Zusammengeführt mit {name}',
  'observation.mergedAbove': 'Zusammengeführt mit {name} in {scope} am {date}',
  'observation.archive': 'Archivieren…',
  'observation.archiveTitle': '{name} archivieren?',
  'observation.archiveBody': 'Behoben, angegangen oder nicht mehr relevant: der Eintrag bleibt, als Geschichte, und verlässt die Analyse. Wiederherstellen bringt ihn zurück.',
  'observation.archiveNote': 'Warum (optional)',
  'observation.archiveConfirm': 'Archivieren',
  'observation.restore': 'Wiederherstellen',
  'observation.archivedOn': 'Archiviert am {date}',
  'observation.history': 'Geschichte',
  'observation.eventRecorded': 'Festgehalten',
  'observation.eventSeen': 'Erneut gesehen',
  'observation.eventShared': 'Mit den Scopes darüber geteilt',
  'observation.eventUnshared': 'Teilen beendet',
  'observation.eventArchived': 'Archiviert',
  'observation.eventRestored': 'Wiederhergestellt',
  'observation.eventAbsorbed': '{name} aufgenommen ({count}-mal gesehen)',
  'observation.eventMerged': 'Zusammengeführt mit {name}',
  'observation.fromScope': 'Lokal in {scope}. Was Sie hier hinzufügen, wird in {scope} angelegt, als Schritt dort; geändert wird es dort.',
  'observation.openScope': '{scope} öffnen',
  'observation.delete': 'Löschen',
  'observation.deleteTitle': '{name} löschen?',
  'observation.deleteBody': 'Der Datensatz verschwindet, mit jeder Verknüpfung, die eine Ursache darauf hatte. Die Nummer wird nie wiederverwendet.',
  'observation.causes': 'Ursachen',
  'observation.cause': 'Ursache',
  'observation.rootCause': 'Grundursache',
  'observation.rootCauses': 'Grundursachen',
  'observation.causeSource': 'Quelltext der Ursache',
  'observation.stateAssumed': 'Angenommen',
  'observation.stateVerified': 'Verifiziert',
  'observation.verify': 'Als verifiziert markieren',
  'observation.unverify': 'Zurück zu angenommen',
  'observation.makeRoot': 'Zur Grundursache machen',
  'observation.makeCause': 'Zur Ursache machen',
  'observation.refusedRootExplained': '{names} erklärt sie. Lösen Sie diese Verknüpfung, oder machen Sie diese zur Grundursache.',
  'observation.refusedRootAddressed': '{names} zielt darauf. Verschieben Sie diese zuerst auf eine andere Grundursache, oder lösen Sie sie.',
  'observation.explains': 'Erklärt',
  'observation.explainedBy': 'Erklärt durch',
  'observation.noLinks': 'Noch nichts',
  'observation.link': 'Mit einer Ursache verknüpfen…',
  'observation.linkDeeper': 'Mit einer tieferen Ursache verknüpfen…',
  'observation.linkStrength': 'Zusammenhang',
  'observation.linkConfirm': 'Verknüpfen',
  'observation.unlink': 'Verknüpfung lösen',
  'observation.strengthStrong': 'Stark',
  'observation.strengthNormal': 'Normal',
  'observation.strengthWeak': 'Schwach',
  'observation.deleteCauseTitle': '{name} löschen?',
  'observation.deleteCauseBody': 'Die Verknüpfungen von ihr und zu ihr gehen mit.',
  'observation.rootNote': 'Mit einer Grundursache endet die Kette: nichts erklärt sie. Wer sagen will, dass etwas dahinter liegt, macht sie zuerst wieder zur Ursache.',
  'observation.tplSaw': 'Was wir gesehen haben',
  'observation.tplEvidence': 'Belege',
  'observation.tplAffected': 'Wen oder was es betraf',
  'observation.tplWhy': 'Warum wir das annehmen',
  'observation.tplVerify': 'Wie es sich überprüfen lässt',
  'observation.laneObservations': 'Beobachtungen',
  'observation.laneCauses': 'Ursachen',
  'observation.laneRoots': 'Grundursachen',
  'observation.legendImpact': 'Größe: Auswirkung',
  'observation.legendSeen': 'Tönung: wie oft gesehen',
  'observation.legendAssumed': 'Gestrichelt: angenommen',
  'observation.legendVerified': 'Durchgezogen: verifiziert',
  'observation.legendRoot': 'Grundursache',
  'observation.legendStrength': 'Stark · normal · schwach',
  'observation.phaseObserved': 'beobachtet',
  'observation.phaseAnalysed': 'analysiert',
  'observation.phaseAssumed': 'angenommen',
  'observation.phaseVerified': 'verifiziert',
  'observation.phaseRoots': 'Grundursachen',
  'observation.toAnalyse': 'Noch nicht analysiert',
  'observation.graphEmpty': 'Noch nichts zu zeichnen. Halten Sie eine Beobachtung fest und verknüpfen Sie sie mit einer Ursache.',
  'observation.resizeReader': 'Lesebereich in der Größe ändern',


  // --- solutions (ADR-0026) -----------------------------------------------------------------
  'solution.tab': 'Lösungen',
  'solution.new': 'Neue Lösung',
  'solution.newTitleField': 'Titel',
  'solution.newTitleHelp': 'Sagen Sie, was die Ursache beseitigt: „Eine Lieferprognose für jeden Kanal“.',
  'solution.laneDirections': 'Richtungen',
  'solution.laneExperiments': 'Experimente',
  'solution.laneStructural': 'Strukturell',
  'solution.wholeChain': 'Ganze Kette',
  'solution.showDropped': 'Verworfene zeigen',
  'solution.coverage': '{count} von {total} Grundursachen haben eine aktive Lösung',
  'solution.graphEmpty': 'Noch nichts zu zeichnen. Schlagen Sie eine Lösung für eine Grundursache vor.',
  'solution.solutions': 'Lösungen',
  'solution.experiments': 'Experimente',
  'solution.legendWidth': 'Breite: erwarteter Nutzen',
  'solution.legendFill': 'Füllung: wie weit sie ist',
  'solution.legendAddresses': 'Linie: behebt eine Ursache',
  'solution.legendTests': 'Gestrichelt: testet',
  'solution.legendProves': 'Durchgezogen: hat es bestätigt',
  'solution.legendTrail': 'Verblasst: die Richtung, die es war',
  'solution.trail': 'als Richtung',
  'solution.flagNoSolution': 'Eine Grundursache, an der noch niemand arbeitet',
  'solution.flag': 'Braucht Aufmerksamkeit',
  // --- phases, sizes, outcomes
  'solution.phaseIdea': 'Idee',
  'solution.phaseShaped': 'Ausgearbeitet',
  'solution.phaseTesting': 'Im Test',
  'solution.phaseProven': 'Bewährt',
  'solution.phaseAdopted': 'Beschlossen',
  'solution.phaseImplemented': 'Umgesetzt',
  'solution.phaseDropped': 'Verworfen',
  'solution.sizeSmall': 'Klein',
  'solution.sizeMedium': 'Mittel',
  'solution.sizeLarge': 'Groß',
  'solution.outcomePlanned': 'Geplant',
  'solution.outcomeRunning': 'Läuft',
  'solution.outcomeConfirmed': 'Bestätigt',
  'solution.outcomeRefuted': 'Widerlegt',
  'solution.outcomeInconclusive': 'Ergebnislos',
  // --- one solution
  'solution.source': 'Quelltext der Lösung',
  'solution.titleField': 'Titel',
  'solution.benefitField': 'Erwarteter Nutzen',
  'solution.costField': 'Grobe Kosten',
  'solution.unset': 'Nicht angegeben',
  'solution.addresses': 'Behebt',
  'solution.addressCause': 'Eine Ursache angehen…',
  'solution.addressTitle': 'Welche Ursache behebt {name}?',
  'solution.addressPick': 'Ursache',
  'solution.addressConfirm': 'Angehen',
  'solution.gateTitle': 'Um weiterzugehen zu {state}',
  'solution.moveOn': 'Weiter zu {state}',
  'solution.moveBack': 'Zurück zu {state}',
  'solution.toGo': 'noch {count}',
  'solution.gateAddresses': 'Behebt mindestens eine Ursache',
  'solution.gateBenefit': 'Erwarteter Nutzen',
  'solution.gateCost': 'Grobe Kosten',
  'solution.gateValidatedWith': 'Mit jemandem geprüft, der damit leben muss',
  'solution.gateTriedBefore': 'Wurde das schon einmal versucht?',
  'solution.gateWhyNow': 'Warum es jetzt funktioniert, obwohl es damals nicht funktionierte',
  'solution.gateExperimentPlanned': 'Ein Experiment testet es: geplant, laufend oder bestätigt',
  'solution.gateExperimentConfirmed': 'Ein Experiment hat es bestätigt, oder es wurde begründet übersprungen',
  'solution.gateDecisionAccepted': 'Eine Entscheidung, angenommen',
  'solution.gateHint.addresses': 'Verknüpfen Sie unter „Behebt“ eine Ursache, mit „Eine Ursache angehen…“.',
  'solution.gateHint.benefit': 'Wählen Sie einen erwarteten Nutzen, auch grob.',
  'solution.gateHint.cost': 'Wählen Sie grobe Kosten, auch geschätzt.',
  'solution.gateHint.validatedWith': 'Nennen Sie unter „Geprüft mit“ jemanden: eine Person, eine Rolle oder ein Team, das damit leben muss.',
  'solution.gateHint.triedBefore': 'Fügen Sie unter „Früher versucht“ den früheren Versuch hinzu, oder kreuzen Sie „Nichts bekannt“ an. „Nichts bekannt“ beantwortet auch die Zeile darunter.',
  'solution.gateHint.whyNow': 'Steht ein früherer Versuch da, sagen Sie unter „Warum jetzt“, was diesmal anders ist. Steht keiner da, beantwortet „Nichts bekannt“ diese Zeile und die darüber.',
  'solution.gateHint.experimentPlanned': 'Ein Experiment, das diese Lösung testet, geplant, laufend oder bestätigt. „Ein Experiment planen…“ legt eines an.',
  'solution.gateHint.experimentConfirmed': 'Ein Experiment, das sie testet, mit dem Ergebnis Bestätigt; oder ein Grund unter „Warum kein Experiment nötig ist“ und übersprungen.',
  'solution.gateHint.decisionAccepted': 'Die Entscheidung, die diese Lösung nennt, angenommen auf der Entscheidungsseite. „Die Entscheidung vorschlagen“ schreibt eine.',
  'solution.gateWhyNowNoneKnown': 'Warum es jetzt funktioniert, obwohl es damals nicht funktionierte — „Nichts bekannt“ beantwortet auch das',
  'solution.validatedWith': 'Geprüft mit',
  'solution.validatedField': 'Ein Name, eine Rolle oder ein Team',
  'solution.add': 'Hinzufügen',
  'solution.remove': 'Entfernen',
  'solution.attempts': 'Früher versucht',
  'solution.noneKnown': 'Nichts bekannt',
  'solution.notAnswered': 'Nicht beantwortet',
  'solution.attemptAdd': 'Früheren Versuch hinzufügen',
  'solution.attemptWhen': 'Wann',
  'solution.attemptWhat': 'Was versucht wurde',
  'solution.attemptWhy': 'Warum es nicht hielt',
  'solution.whyNow': 'Warum jetzt',
  'solution.whyNowField': 'Was diesmal anders ist',
  'solution.save': 'Speichern',
  'solution.waive': 'Überspringen',
  'solution.waiveField': 'Warum kein Experiment nötig ist',
  'solution.waived': 'Experiment übersprungen: {reason}',
  'solution.planExperiment': 'Ein Experiment planen…',
  'solution.proposeDecision': 'Die Entscheidung vorschlagen',
  'solution.decision': 'Entscheidung',
  'solution.decisionStatus': '{label} ist {status}',
  'solution.open': 'Öffnen',
  'solution.plan': 'Plan',
  'solution.startPlan': 'Einen Plan beginnen',
  'solution.noPlan': 'Noch kein Plan',
  'solution.didItWork': 'Hat es gewirkt?',
  'solution.didItWorkHelp': 'Die Beobachtungen unter dem, was sie behebt. Keine sollte mehr auftreten.',
  'solution.seenSince': 'Erneut gesehen am {date}',
  'solution.heldSince': 'Keine Sichtung nach dem {date}',
  'solution.alternatives': 'Alternativen zu denselben Ursachen',
  'solution.none': 'Keine',
  'solution.drop': 'Verwerfen…',
  'solution.dropTitle': '{name} verwerfen?',
  'solution.dropBody': 'Sie bleibt als erwogene Alternative in der Liste. Sagen Sie warum, damit die Nächsten es nicht blind erneut versuchen.',
  'solution.dropNote': 'Warum',
  'solution.dropConfirm': 'Verwerfen',
  'solution.restore': 'Wiederherstellen',
  'solution.droppedNote': 'Verworfen: {note}',
  'solution.questionWorksAround': 'Umgeht, statt zu lösen: sie behebt keine Grundursache. Als Notlösung in Ordnung; sagen Sie das, oder gehen Sie auch die Grundursache an.',
  'solution.questionAddsOnly': 'Fügt hinzu, ohne aufzuräumen: der Plan führt ein und löst nichts ab. Was macht das überflüssig?',
  'solution.questionAdoptedUnplanned': 'Beschlossen, nicht geplant: noch baut kein Plan sie.',
  'solution.findingSeenAgain': 'Seit der Umsetzung erneut gesehen: {names}. Hat es gewirkt?',
  'solution.eventProposed': 'Vorgeschlagen',
  'solution.eventMoved': 'Weiter zu {state}',
  'solution.eventWaived': 'Experiment übersprungen',
  'solution.eventLinked': '{name} verknüpft',
  'solution.eventDropped': 'Verworfen',
  'solution.eventRestored': 'Wiederhergestellt',
  'solution.deleteTitle': '{name} löschen?',
  'solution.deleteBody': 'Der Eintrag verschwindet, auch aus jedem Experiment, das ihn testete. Die Nummer wird nie wieder vergeben.',
  'solution.deleteExperimentBody': 'Der Eintrag verschwindet. Die Nummer wird nie wieder vergeben.',
  'solution.forCause': 'Lösungen dafür',
  'solution.proposeForCause': 'Eine Lösung vorschlagen…',
  'solution.proposeAtRoot': 'Lösungen setzen an einer Grundursache an: schlagen Sie eine bei dem vor, was dies erklärt',
  // --- one experiment
  'solution.experimentSource': 'Quelltext des Experiments',
  'solution.tests': 'Testet',
  'solution.hypothesis': 'Hypothese',
  'solution.hypothesisHelp': 'Wenn wir …, dann … um …',
  'solution.measure': 'Wie es gemessen wird',
  'solution.whereField': 'Wo',
  'solution.byField': 'Von',
  'solution.fromField': 'Von',
  'solution.toField': 'Bis',
  'solution.result': 'Ergebnis',
  'solution.outcome': 'Ausgang',
  'solution.newExperiment': 'Ein Experiment planen',
  'solution.createExperiment': 'Planen',
  'solution.refutedNote': 'Ein widerlegtes Experiment bleibt. Es ist der Beleg, nach dem die Nächsten fragen.',
  // --- the templates
  'solution.tplIdea': 'Die Idee',
  'solution.tplCosts': 'Kosten und Nutzen',
  'solution.tplWhyHere': 'Warum dieser Bereich',
  'solution.tplAlternatives': 'Alternativen',
  'solution.tplRisks': 'Risiken',
  'solution.tplSetup': 'Wie es aufgebaut ist',
  'solution.tplLearned': 'Was wir gelernt haben',
  'solution.decisionAddresses': 'Sie behebt:',
  'solution.decisionDropped': 'verworfen: {note}',
  'solution.decisionLeaveAsIs': 'So lassen, wie es ist: nichts wird geändert, und die Ursachen oben bleiben, wie sie sind',
  'observation.listArchivedOnly': 'Hier gibt es keine offenen Beobachtungen · {count} archiviert',
  'observation.more': 'Weitere Aktionen',
  'observation.seenTitle': 'Wann wurde {name} erneut gesehen?',
  'observation.seenBody': 'Der Zähler steigt um eins, und der Tag und die Notiz bleiben in der Historie.',
  'observation.seenDate': 'Gesehen am',
  'observation.seenNote': 'Notiz (optional)',
  'observation.seenFuture': 'Nicht in der Zukunft.',
  'observation.seenBeforeFirst': 'Nicht vor dem Tag, an dem es zuerst gesehen wurde: {date}.',
  'observation.verifyTitle': 'Was hat {name} bestätigt?',
  'observation.verifyBody': 'Der Text sagt noch nicht zugleich, warum wir das annehmen und wie es verifiziert wurde. Sagen Sie, was es bestätigt hat: Die Antwort kommt mit dem heutigen Datum unter Wie es sich überprüfen lässt.',
  'observation.verifyField': 'Was hat es bestätigt?',
  'solution.seenSameDay': 'Gesehen am {date}, dem Tag der Umsetzung',
  'solution.questionProofWithdrawn': 'Ihr Nachweis ist entfallen: Kein bestätigtes Experiment testet sie mehr, und sie wurde nicht begründet übersprungen. Bestätigen Sie erneut eines oder überspringen Sie es begründet; bis dahin kann sie nicht beschlossen werden.',
  'solution.reopenBySuperseding': 'Zum Wiederöffnen {label} auf der Entscheidungsseite ablösen.',
  'solution.experimentMoves': 'Das Experiment verschieben',
  'solution.moveStart': 'Starten',
  'solution.moveToPlanned': 'Zurück zu geplant',
  'solution.moveConclude': '{outcome}…',
  'solution.moveReopen': 'Wieder öffnen…',
  'solution.concludeTitle': '{name} abschließen: {outcome}',
  'solution.concludeResultHelp': 'Was geschah, in Zahlen, wo es Zahlen gibt.',
  'solution.concludeBeforeFrom': 'Nicht vor dem Start am {date}.',
  'solution.concludeConfirm': 'Abschließen',
  'solution.reopenTitle': '{name} wieder öffnen?',
  'solution.reopenBody': 'Es läuft wieder, und das Enddatum entfällt. Das Ergebnis bleibt, bis es erneut abgeschlossen wird.',
  'solution.reopenWithdraws': '{names} ist durch dieses Experiment bewährt; das Wiederöffnen zieht diesen Nachweis zurück.',
  'solution.reopenWithdrawsMany': '{names} sind durch dieses Experiment bewährt; das Wiederöffnen zieht diesen Nachweis zurück.',
  'solution.reopenConfirm': 'Wieder öffnen',
  'solution.decisionDriverBenefit': 'Erwarteter Nutzen: {size}',
  'solution.decisionDriverCost': 'Grobe Kosten: {size}',
  'solution.decisionChosen': 'Gewählte Option: „{option}“, weil {because}',
  'solution.decisionBecauseConfirmed': '{experiment} sie bestätigt hat: {result}',
  'solution.decisionBecauseConfirmedBare': '{experiment} sie bestätigt hat.',
  'solution.decisionBecauseWaived': 'kein Experiment nötig war: {reason}',
  'solution.decisionGood': 'Gut, weil der erwartete Nutzen {size} ist.',
  'solution.decisionBad': 'Schlecht, weil die groben Kosten {size} sind.',
  'solution.decisionConfirmation': 'Sobald sie gebaut ist, sollten {observations} nicht mehr auftreten. Der Reiter Lösungen fragt, ob das so ist.',
  'solution.decisionConfirmationBare': 'Sobald sie gebaut ist, sollte nicht mehr auftreten, was sie behebt. Der Reiter Lösungen fragt, ob das so ist.',
  'solution.decisionMore': 'Vorgeschlagen aus {label} im Reiter Lösungen.',

  // --- die Aktionen in einer Ansicht (ADR-0032 §7) -----------------------------------------
  'observation.actions': 'Aktionen für {name}',
  'observation.fromScopeActions': 'Der Scope, in dem es liegt',
  'observation.thisScope': 'diesem Scope',
  'observation.actCause': 'Ursache',
  'observation.actMerge': 'Zusammenführen',
  'observation.actArchive': 'Archivieren',
  'observation.actDeeper': 'Tiefere Ursache',
  'observation.actMakeRoot': 'Zum Grund machen',
  'observation.actVerify': 'Verifizieren',
  'observation.actSolution': 'Lösung',
  'observation.actOrg': 'Org-Ursache',
  'observation.actLocal': 'Lokale Ursache',
  'observation.tipSeen': 'Erfassen, dass dies erneut gesehen wurde. Es fügt dieser Beobachtung eine Sichtung hinzu; es wird nichts Neues erfasst.',
  'observation.tipCause': 'Die Ursache hinzufügen, die diese Beobachtung erklärt: eine neue, oder eine, die in {scope} schon aufgeschrieben ist.',
  'observation.tipMerge': 'Mit einer anderen Beobachtung zusammenführen, die dasselbe festhält. Beide Verläufe bleiben erhalten.',
  'observation.tipArchive': 'Es geschieht nicht mehr. Die Beobachtung bleibt im Verlauf und kann wiederhergestellt werden.',
  'observation.tipEdit': 'Titel, wo, wer, wann, Auswirkung und Beschreibung bearbeiten.',
  'observation.tipEditCause': 'Titel und Beschreibung bearbeiten.',
  'observation.tipRead': 'Zurück zum Lesen. Was Sie getippt haben, bleibt erhalten.',
  'observation.tipDelete': 'Die Beobachtung löschen, mit jeder Verknüpfung, die eine Ursache zu ihr hatte. Ihre Nummer wird nie wieder vergeben. Archivieren Sie sie lieber, wenn es nur nicht mehr geschieht.',
  'observation.tipDeleteCause': 'Die Ursache löschen, mit jeder Verknüpfung von ihr und zu ihr.',
  'observation.tipDeeper': 'Noch einmal warum fragen: die Ursache hinter dieser Ursache hinzufügen, neu oder vorhanden, im selben Scope.',
  'observation.tipRoot': 'Die Grundursache verknüpfen, in der diese Kette endet, neu oder vorhanden, im selben Scope.',
  'observation.tipMakeRoot': 'Zur Grundursache machen: Die Kette endet hier, und Lösungen dürfen sie angehen. {label} wird {next}. Abgelehnt, solange eine Ursache sie erklärt.',
  'observation.tipMakeCause': 'Wieder zur Ursache machen, damit eine tiefere Ursache dahinter verknüpft werden kann. {label} wird {next}. Abgelehnt, solange eine Lösung sie angeht.',
  'observation.tipVerify': 'Als verifiziert markieren, sobald „Warum wir das annehmen“ und „Wie zu verifizieren“ sagen, was geprüft wurde, oder jetzt sagen, was es bestätigt hat.',
  'observation.tipAssumed': 'Zurück zu angenommen: Die Belege tragen nicht mehr.',
  'observation.tipSolution': 'Eine Lösung vorschlagen, die diese Grundursache angeht.',
  'observation.tipOrg': 'Eine Ursache von {scope} verknüpfen, die diese lokale Ursache erklärt. Die Verknüpfung liegt bei jener Ursache, in {scope}. Abgelehnt bei einer Grundursache.',
  'observation.tipLocal': 'Eine Ursache eines Scopes darunter verknüpfen, die diese Ursache erklärt. Die Verknüpfung liegt bei dieser Ursache.',
  'observation.tipRestore': 'Zurück in die Analyse holen.',
  'observation.tipOpenScope': 'Die Beobachtungen von {scope} öffnen, wo dieser Datensatz liegt.',
  'observation.tipUnlink': 'Verknüpfung lösen: {from} erklärt {to} nicht mehr.',
  'observation.makeRootAsk': '{label} zur Grundursache machen? Sie wird {next}. Die Kette endet hier: Nichts kann dahinter verknüpft werden, und Lösungen dürfen sie angehen.',
  'observation.makeCauseAsk': '{label} wieder zur Ursache machen? Sie wird {next}, und eine tiefere Ursache kann dahinter verknüpft werden.',
  'observation.makeRootRefused': '{label} kann keine Grundursache werden, solange eine Ursache sie erklärt.',
  'observation.makeCauseRefused': '{label} kann nicht wieder Ursache werden, solange eine Lösung sie angeht.',
  'observation.orgRefused': '{label} ist eine Grundursache: Nichts erklärt sie. Machen Sie sie zuerst wieder zur Ursache, in ihrem eigenen Scope, und verknüpfen Sie dann die Ursache dahinter.',
  'observation.ok': 'OK',
  'solution.actExperiment': 'Experiment',
  'solution.actDrop': 'Verwerfen',
  'solution.tipAddress': 'Eine weitere Grundursache dieses Scopes angehen. Angeboten, solange sie eine Idee oder ausgearbeitet ist.',
  'solution.tipExperiment': 'Ein Experiment planen, das prüft, ob diese Lösung hilft. Angeboten, solange sie ausgearbeitet ist oder im Test.',
  'solution.tipDrop': 'Verwerfen, mit einem Grund. Sie bleibt als erwogene Alternative und kann wiederhergestellt werden.',
  'solution.tipDelete': 'Die Lösung löschen und aus jedem Experiment nehmen, das sie getestet hat. Verwerfen Sie sie lieber, um sie als erwogene Alternative zu behalten.',
  'solution.tipRestore': 'In den Zustand zurückholen, aus dem sie verworfen wurde.',
  'solution.tipEdit': 'Titel und Beschreibung bearbeiten.',
  'solution.tipUnaddress': 'Verknüpfung lösen: {from} geht {to} nicht mehr an.',
  'solution.tipStart': 'Heute beginnen.',
  'solution.tipReopen': 'Wieder öffnen: Es läuft wieder, und sein Endtag wird gelöscht.',
  'solution.tipToPlanned': 'Zurück zu geplant: Es hat doch nicht begonnen.',
  'solution.tipConfirmed': 'Es hat die Lösung bestätigt: Sagen Sie das Ergebnis und den Tag, an dem es endete.',
  'solution.tipRefuted': 'Es hat die Lösung widerlegt: Sagen Sie das Ergebnis. Ein widerlegtes Experiment bleibt, als Beleg.',
  'solution.tipInconclusive': 'Es hat nichts entschieden, in keine Richtung: Sagen Sie das Ergebnis.',
  'solution.tipExperimentEdit': 'Titel, Hypothese, Messung, wo, wer, wann und Ergebnis bearbeiten.',
  'solution.tipDeleteExperiment': 'Das Experiment löschen. Seine Nummer wird nie wieder vergeben.',

  // --- die Formulare (ADR-0032 §6) --------------------------------------------------------------
  'observation.formIntro': 'Eine Tatsache: was gesehen wurde, wo, wann und von wem, in neutralen Worten. Erklärungen, Schuld und Lösungen bleiben draußen; das Warum gehört in die Ursachen unten.',
  'observation.formScope': 'Scope',
  'observation.formScopeHere': '{name} (dieser Scope)',
  'observation.formScopeBelow': '{name} (lokal)',
  'observation.formScopeHelp': 'Wohin die Beobachtung gehört. Ein Scope darunter macht sie dort lokal, mit ihren Ursachen.',
  'observation.formScopeDropped': 'Die Verknüpfungen mit Ursachen des zuvor gewählten Scopes wurden entfernt: Eine Ursache wird in ihrem eigenen Scope verknüpft.',
  'observation.formTitleExample': 'Was gesehen wurde, in einem Satz. Z. B. Der nächtliche Schadenbatch läuft bis in die Bürozeit',
  'observation.formWhereExample': 'Ein Ort, ein Bildschirm oder ein Schritt. Z. B. EDI-Eingang, die Auftragsmaske, Kommissionierplatz 3',
  'observation.formByExample': 'Wer es gesehen hat: ein Team, eine Rolle oder eine Person. Z. B. Frachtführerverwaltung, die Nachtschicht',
  'observation.formDateField': 'Wann gesehen',
  'observation.formDateExample': 'Der Tag, an dem es zuerst gesehen wurde. Z. B. 4. Juni 2026',
  'observation.formImpactExample': 'Wie sehr es schadet. Z. B. Erheblich: Kunden merken es',
  'observation.formTitleMissing': 'Sagen Sie in einem Satz, was gesehen wurde.',
  'observation.formWhereMissing': 'Sagen Sie, wo es gesehen wurde.',
  'observation.formByMissing': 'Sagen Sie, wer es gesehen hat.',
  'observation.formDateMissing': 'Geben Sie den Tag an, an dem es zuerst gesehen wurde.',
  'observation.formDateFuture': 'Der Tag kann nicht in der Zukunft liegen. Es ist der Tag, an dem es zuerst gesehen wurde.',
  'observation.formProblemsOne': '1 Feld muss noch ausgefüllt werden.',
  'observation.formProblemsMany': '{count} Felder müssen noch ausgefüllt werden.',
  'observation.formDescription': 'Beschreibung (optional)',
  'observation.formDescriptionExample': 'Markdown. Z. B. unter Was wir gesehen haben: Drei Frachtführer unterschrieben im Frühjahr, und das erste Etikett kam neun Wochen nach jedem Vertrag.',
  'observation.formDescriptionMode': 'Die Beschreibung schreiben oder ansehen',
  'observation.formEdit': 'Bearbeiten',
  'observation.formPreview': 'Vorschau',
  'observation.formNothingWritten': 'Noch nichts geschrieben.',
  'observation.formSeenBefore': 'Schon einmal gesehen?',
  'observation.formSeenAgainTip': 'Bei {name} eine Sichtung hinzufügen, statt eine neue Beobachtung zu erfassen. Es wird nichts Neues erfasst.',
  'observation.formWordingHint': '„{word}“ klingt nach einer Ursache, einer Lösung oder nach Schuld. Halten Sie den Titel bei dem, was gesehen wurde, und tragen Sie das Warum unten als Ursache ein.',
  /** Wörter, die in einem Titel nach Ursache, Lösung oder Schuld klingen, mit `|` dazwischen: ein Hinweis, nie eine Ablehnung. */
  'observation.formHintWords': 'weil|wegen|aufgrund|verursacht durch|sollte|sollten|muss|müssen|beheben|behoben|reparieren|Schuld|Fehler von|fahrlässig|faul|schlampig|inkompetent',
  'observation.formCauses': 'Ursachen',
  'observation.formCausesNote': 'optional · beim Erfassen angelegt',
  'observation.formNewCauseTip': 'Eine neue Ursache für diese Beobachtung schreiben. Sie wird beim Erfassen angelegt.',
  'observation.formExistingCause': 'Vorhandene Ursache',
  'observation.formExistingCauseTip': 'Eine Ursache verknüpfen, die in diesem Scope schon aufgeschrieben ist. Beim Erfassen wird nur die Verknüpfung angelegt.',
  'observation.formColCause': 'Ursache',
  'observation.formColKind': 'Art',
  'observation.formColStrength': 'Stärke',
  'observation.formColRemove': 'Entfernen',
  'observation.formKindNew': 'Neu',
  'observation.formKindExisting': 'Vorhanden',
  'observation.formKindRoot': 'Grund',
  'observation.formStrengthOf': 'Stärke von {name}',
  'observation.formNoCauses': 'Noch keine Ursache. Erfassen Sie die Beobachtung jetzt und analysieren Sie später, oder fügen Sie hinzu, was Sie schon wissen.',
  'observation.formRemoveRow': '{name} von der Liste nehmen',
  'observation.formRecord': 'Beobachtung erfassen',
  'observation.formRecordWith': 'Beobachtung erfassen mit {what}',
  'observation.formNewCausesOne': '1 neuen Ursache',
  'observation.formNewCausesMany': '{count} neuen Ursachen',
  'observation.formLinksOne': '1 Verknüpfung',
  'observation.formLinksMany': '{count} Verknüpfungen',
  'observation.formAnd': '{first} und {second}',
  'observation.causeTitleExample': 'Warum es geschieht, in einem Satz. Z. B. Jedes EDI-Mapping eines Frachtführers wird von Hand geschrieben',
  'observation.causeTitleMissing': 'Sagen Sie in einem Satz, warum es geschieht.',
  'observation.causeWhy': 'Warum wir das annehmen (optional)',
  'observation.causeWhyExample': 'Z. B. Die Frachtführerverwaltung führt einen Ordner mit handgemachten Mappings',
  'observation.causeRoot': 'Es ist eine Grundursache: Die Kette endet hier',
  'observation.causeStrength': 'Stärke',
  'observation.causeStrengthExample': 'Wie viel davon diese Ursache erklärt.',
  'observation.causeAlike': 'Schon aufgeschrieben?',
  'observation.causeUse': 'Diese verwenden',
  'observation.causeAddToList': 'Zur Liste hinzufügen',
  'observation.causeFind': 'Eine Ursache nach Nummer oder Wörtern suchen',
  'observation.causeAdd': 'Hinzufügen',
  'observation.causeAdded': 'Hinzugefügt',
  'observation.causeNoMatch': 'Keine Ursache passt.',
  'observation.causeBody': 'Text (optional)',
  'observation.causeBodyExample': 'Markdown. Z. B. unter Wie zu verifizieren: die Mappings des letzten Monats mit denen des Frachtführers vergleichen.',
  'observation.causeLinks': 'Womit sie verknüpft wird',
  'observation.causeExplainsRow': 'Erklärt',
  'observation.causeBehind': 'Dahinter',
  'observation.causeBehindAdd': 'Vorhandene Ursache dahinter',
  'observation.causeBehindTip': 'Eine schon aufgeschriebene Ursache verknüpfen, die diese neue erklärt. Die Verknüpfung wird mit ihr angelegt.',
  'observation.existingIn': 'Vorhandene Ursache in {scope}',
  'observation.madeAs': 'Angelegt in {scope} als {label}.',
  'observation.linkCauseTitle': 'Ursache für {name}',
  'observation.linkCauseIntro': 'Warum geschieht das? Fügen Sie eine neue Ursache hinzu, oder verknüpfen Sie eine, die in ihrem Scope schon aufgeschrieben ist.',
  'observation.linkDeeperTitle': 'Tiefere Ursache für {name}',
  'observation.linkDeeperIntro': 'Fragen Sie noch einmal warum: Was steckt hinter dieser Ursache?',
  'observation.linkRootTitle': 'Grundursache für {name}',
  'observation.linkRootIntro': 'Wo endet diese Kette? Bei einer Grundursache hört das Warum auf, und eine Lösung kann beginnen.',
  'observation.linkOrgTitle': 'Eine Ursache von {scope} für {name}',
  'observation.linkOrgIntro': 'Welche Ursache von {scope} erklärt diese Ursache von {below}? Die Verknüpfung liegt bei der Ursache von {scope}.',
  'observation.linkLocalTitle': 'Lokale Ursache, die {name} erklärt',
  'observation.linkLocalIntro': 'Welche Ursache eines Scopes darunter erklärt diese Ursache? Eine lokale Ursache wird in ihrem eigenen Scope angelegt; hier verknüpfen Sie eine vorhandene. Eine Grundursache darunter beendet ihre Kette und wird nicht angeboten.',
  'observation.linkTabs': 'Eine neue Ursache oder eine vorhandene',
  'observation.linkTabNew': 'Neue Ursache',
  'observation.linkTabExisting': 'Vorhandene Ursache ({count})',
  'observation.linkAdd': 'Ursache hinzufügen',
  'observation.linkNone': 'Hier gibt es keine Ursache zum Verknüpfen.',
  'observation.linkPickMissing': 'Wählen Sie eine Ursache zum Verknüpfen.',
  'observation.linkUseTip': 'Diese Ursache verknüpfen, statt eine neue zu schreiben.',
  'observation.madeBelow': 'Angelegt in {scope}. Es steht dort in der Liste Aktivität und wird dort rückgängig gemacht.',
  'observation.belowReadOnly': 'In {scope} wurde nichts angelegt: Er darf von hier aus nicht geändert werden.',
  'observation.belowRefused': 'In {scope} wurde nichts angelegt: Seine eigenen Regeln haben die Änderung abgelehnt.',
  'observation.belowNotMade': 'In {scope} wurde nichts angelegt.',
  'solution.formIntro': 'Was eine Grundursache beseitigen würde. Es beginnt als Idee; seine Schranken fragen nach dem Rest.',
  'solution.formTitleMissing': 'Sagen Sie in einem Satz, was die Lösung ist.',
  'solution.formBody': 'Text (optional)',
  'solution.formBodyExample': 'Markdown. Z. B. unter Die Idee: Ein Dienst berechnet die Prognose, und jeder Kanal liest sie.',
  'solution.formAddresses': 'Grundursachen, die sie angeht',
  'solution.formAddressesNote': 'beim Vorschlagen angelegt',
  'solution.formAddRootTip': 'Eine Grundursache dieses Scopes hinzufügen, die sie angeht. Eine Lösung geht nur Grundursachen an.',
  'solution.formNoRoots': 'Noch keine Grundursache. Schlagen Sie sie jetzt vor und verknüpfen Sie später eine, oder fügen Sie die Grundursachen hinzu, die sie beseitigt.',
  'solution.formPropose': 'Lösung vorschlagen',
  'solution.formProposeOne': 'Lösung für 1 Grundursache vorschlagen',
  'solution.formProposeMany': 'Lösung für {count} Grundursachen vorschlagen',
  'solution.experimentTitleExample': 'Was ausprobiert wird, in wenigen Worten. Z. B. Zwei Wochen an einem Schalter',
  'solution.experimentTitleMissing': 'Sagen Sie, was das Experiment ist.',
}
