// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/**
 * English, for observations and causes: the page, the register, the picture.
 *
 * `as const`, so this slice is the schema for its own keys: `nl.ts` beside it
 * cannot be missing one and cannot invent one. The registry composes every
 * module's slice into the table `t()` reads (`i18n/strings.ts`).
 */
export const EN = {

  // --- the page ---------------------------------------------------------------
  'observation.title': 'Observations',
  'observation.close': 'Close observations',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analysis',
  'observation.new': 'New observation',
  'observation.newTitleField': 'Title',
  'observation.newTitleHelp': 'Say what was seen, as one sentence: “The nightly claims batch runs into office hours”.',
  'observation.newWhereField': 'Where it was seen',
  'observation.newImpactField': 'Impact',
  'observation.newShareField': 'Share with the scopes above',
  'observation.newByField': 'Observed by',
  'observation.create': 'Record',
  'observation.newCause': 'New cause',
  'observation.newCauseHelp': 'Say what lies behind it: “The batch window was sized for 2019 volumes”.',
  'observation.createCause': 'Add',
  'observation.searchPlaceholder': 'Search observations and causes',
  'observation.searchField': 'Search observations',
  'observation.listEmpty': 'Nothing observed here yet.',
  'observation.searchEmpty': 'Nothing matches “{query}”.',
  'observation.noneSelected': 'Pick an observation or a cause, or record one.',

  // --- the register ---------------------------------------------------------------
  'observation.colNumber': 'No.',
  'observation.colTitle': 'Title',
  'observation.colDate': 'Date',
  'observation.colWhere': 'Where',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Impact',
  'observation.colSeen': 'Seen',
  'observation.colCauses': 'Analysed into',
  'observation.scopeHere': 'This scope',
  /** The heading over what a scope below shared (ADR-0021). */
  'observation.fromBelow': 'Shared from {scope}',
  'observation.sharedMark': 'Shared',
  'observation.showMerged': 'Show merged',
  'observation.showArchived': 'Show archived',
  'observation.archivedMark': 'Archived',
  'observation.notAnalysed': 'not yet',
  'observation.impactMinor': 'Minor',
  'observation.impactMajor': 'Major',
  'observation.impactCritical': 'Critical',
  'observation.seenTimes': '{count}×',

  // --- one observation ---------------------------------------------------------------
  'observation.read': 'Read',
  'observation.edit': 'Edit',
  'observation.source': 'Observation source',
  'observation.titleField': 'Title',
  'observation.whereField': 'Where seen',
  'observation.byField': 'Observed by',
  'observation.dateField': 'Date seen',
  'observation.impactField': 'Impact',
  'observation.seenAgain': 'Seen again',
  'observation.share': 'Share with the scopes above',
  'observation.unshare': 'Stop sharing',
  'observation.shared': 'Shared with the scopes above',
  'observation.local': 'Local to this scope',
  'observation.shareHelp': 'Shared, every scope above this one reads it, may link it to a cause of its own and may merge it into one of its own. Local is the default.',
  'observation.merge': 'Merge into…',
  'observation.mergeTitle': 'Merge {name} into another observation',
  'observation.mergeBody': 'Its sightings and its causes move to the one you choose, and both records say so with today’s date. The merged record stays, as history.',
  'observation.mergePick': 'The observation it is the same as',
  'observation.mergeConfirm': 'Merge',
  'observation.mergedInto': 'Merged into {name}',
  'observation.mergedAbove': 'Merged into {name} at {scope} on {date}',
  'observation.archive': 'Archive…',
  'observation.archiveTitle': 'Archive {name}?',
  'observation.archiveBody': 'Fixed, addressed or no longer relevant: the record stays, as history, and leaves the analysis. Restore brings it back.',
  'observation.archiveNote': 'Why (optional)',
  'observation.archiveConfirm': 'Archive',
  'observation.restore': 'Restore',
  'observation.archivedOn': 'Archived on {date}',
  'observation.history': 'History',
  'observation.eventRecorded': 'Recorded',
  'observation.eventSeen': 'Seen again',
  'observation.eventShared': 'Shared with the scopes above',
  'observation.eventUnshared': 'Sharing stopped',
  'observation.eventArchived': 'Archived',
  'observation.eventRestored': 'Restored',
  'observation.eventAbsorbed': 'Absorbed {name} ({count} seen)',
  'observation.eventMerged': 'Merged into {name}',
  'observation.fromScope': 'This observation belongs to {scope}. It is read here and linked here; it is changed there.',
  'observation.openScope': 'Open {scope}',
  'observation.delete': 'Delete',
  'observation.deleteTitle': 'Delete {name}?',
  'observation.deleteBody': 'The record goes, and every link a cause had to it. Its number is never reused.',

  // --- causes ------------------------------------------------------------------------------
  'observation.causes': 'Causes',
  'observation.cause': 'Cause',
  'observation.rootCause': 'Root cause',
  'observation.rootCauses': 'Root causes',
  'observation.causeSource': 'Cause source',
  'observation.stateAssumed': 'Assumed',
  'observation.stateVerified': 'Verified',
  'observation.verify': 'Mark verified',
  'observation.unverify': 'Back to assumed',
  'observation.explains': 'Explains',
  'observation.explainedBy': 'Explained by',
  'observation.noLinks': 'Nothing yet',
  'observation.link': 'Link to a cause…',
  'observation.linkDeeper': 'Link to a deeper cause…',
  'observation.linkTitle': 'What lies behind {name}?',
  'observation.linkPick': 'Cause',
  'observation.linkNew': 'A new cause…',
  'observation.linkNewTitle': 'Name the cause',
  'observation.linkStrength': 'Relationship',
  'observation.linkConfirm': 'Link',
  'observation.unlink': 'Unlink',
  'observation.strengthStrong': 'Strong',
  'observation.strengthNormal': 'Normal',
  'observation.strengthWeak': 'Weak',
  'observation.deleteCauseTitle': 'Delete {name}?',
  'observation.deleteCauseBody': 'The links from it and to it go with it.',
  'observation.rootNote': 'Nothing has been found behind this cause. Link it to a deeper one and it stops being a root.',

  // --- the template ----------------------------------------------------------------------
  'observation.tplSaw': 'What we saw',
  'observation.tplEvidence': 'Evidence',
  'observation.tplThoughts': 'First thoughts',
  'observation.tplWhy': 'Why we think so',
  'observation.tplVerify': 'How to verify',

  // --- the picture -------------------------------------------------------------------------
  'observation.laneObservations': 'Observations',
  'observation.laneCauses': 'Causes',
  'observation.laneRoots': 'Root causes',
  'observation.legendImpact': 'Size: impact',
  'observation.legendSeen': 'Tint: times seen',
  'observation.legendAssumed': 'Dashed: assumed',
  'observation.legendVerified': 'Solid: verified',
  'observation.legendRoot': 'Root cause',
  'observation.legendStrength': 'Strong · normal · weak',
  'observation.phaseObserved': 'observed',
  'observation.phaseAnalysed': 'analysed',
  'observation.phaseAssumed': 'assumed',
  'observation.phaseVerified': 'verified',
  'observation.phaseRoots': 'root causes',
  'observation.toAnalyse': 'Not yet analysed',
  'observation.graphEmpty': 'Nothing to draw yet. Record an observation, then link it to a cause.',
  'observation.resizeReader': 'Resize the reading pane',


  // --- solutions (ADR-0026) -----------------------------------------------------------------
  'solution.tab': 'Solutions',
  'solution.new': 'New solution',
  'solution.newTitleField': 'Title',
  'solution.newTitleHelp': 'Say what would take the cause away: “One delivery estimate for every channel”.',
  'solution.newCauseField': 'For the cause',
  'solution.noCause': 'No cause yet',
  'solution.create': 'Propose',
  'solution.laneDirections': 'Directions',
  'solution.laneExperiments': 'Experiments',
  'solution.laneStructural': 'Structural',
  'solution.wholeChain': 'Whole chain',
  'solution.showDropped': 'Show dropped',
  'solution.coverage': '{count} of {total} root causes have a live solution',
  'solution.graphEmpty': 'Nothing to draw yet. Propose a solution for a root cause.',
  'solution.solutions': 'Solutions',
  'solution.experiments': 'Experiments',
  'solution.legendWidth': 'Width: expected benefit',
  'solution.legendFill': 'Fill: how far it has got',
  'solution.legendAddresses': 'Line: addresses a cause',
  'solution.legendTests': 'Dashed: tests',
  'solution.flagNoSolution': 'A root cause nobody is working on yet',
  'solution.flag': 'Needs attention',
  // --- phases, sizes, outcomes
  'solution.phaseIdea': 'Idea',
  'solution.phaseShaped': 'Shaped',
  'solution.phaseTesting': 'Testing',
  'solution.phaseProven': 'Proven',
  'solution.phaseAdopted': 'Adopted',
  'solution.phaseImplemented': 'Implemented',
  'solution.phaseDropped': 'Dropped',
  'solution.sizeSmall': 'Small',
  'solution.sizeMedium': 'Medium',
  'solution.sizeLarge': 'Large',
  'solution.outcomePlanned': 'Planned',
  'solution.outcomeRunning': 'Running',
  'solution.outcomeConfirmed': 'Confirmed',
  'solution.outcomeRefuted': 'Refuted',
  'solution.outcomeInconclusive': 'Inconclusive',
  // --- one solution
  'solution.source': 'Solution source',
  'solution.titleField': 'Title',
  'solution.benefitField': 'Expected benefit',
  'solution.costField': 'Rough cost',
  'solution.unset': 'Not said',
  'solution.addresses': 'Addresses',
  'solution.addressCause': 'Address a cause…',
  'solution.addressTitle': 'Which cause does {name} address?',
  'solution.addressPick': 'Cause',
  'solution.addressConfirm': 'Address',
  'solution.gateTitle': 'To move on to {state}',
  'solution.moveOn': 'Move to {state}',
  'solution.moveBack': 'Back to {state}',
  'solution.toGo': '{count} to go',
  'solution.gateAddresses': 'Addresses at least one cause',
  'solution.gateBenefit': 'Expected benefit',
  'solution.gateCost': 'Rough cost',
  'solution.gateValidatedWith': 'Checked with somebody who would live with it',
  'solution.gateTriedBefore': 'Was this tried before?',
  'solution.gateWhyNow': 'Why it works now, when it did not then',
  'solution.gateExperimentPlanned': 'An experiment is planned or running',
  'solution.gateExperimentConfirmed': 'An experiment confirmed it, or it was waived with a reason',
  'solution.gateDecisionAccepted': 'A decision record, accepted',
  'solution.validatedWith': 'Checked with',
  'solution.validatedField': 'A name, a role or a team',
  'solution.add': 'Add',
  'solution.remove': 'Remove',
  'solution.attempts': 'Tried before',
  'solution.noneKnown': 'None known',
  'solution.notAnswered': 'Not answered',
  'solution.attemptAdd': 'Add an earlier attempt',
  'solution.attemptWhen': 'When',
  'solution.attemptWhat': 'What was tried',
  'solution.attemptWhy': 'Why it did not stick',
  'solution.whyNow': 'Why now',
  'solution.whyNowField': 'What is different this time',
  'solution.save': 'Save',
  'solution.waive': 'Waive',
  'solution.waiveField': 'Why no experiment is needed',
  'solution.waived': 'Experiment waived: {reason}',
  'solution.planExperiment': 'Plan an experiment…',
  'solution.proposeDecision': 'Propose the decision record',
  'solution.decision': 'Decision',
  'solution.decisionStatus': '{label} is {status}',
  'solution.open': 'Open',
  'solution.plan': 'Plan',
  'solution.startPlan': 'Start a plan',
  'solution.noPlan': 'No plan yet',
  'solution.didItWork': 'Did it work?',
  'solution.didItWorkHelp': 'The observations under what it addresses. Each should stop being seen.',
  'solution.seenSince': 'Seen again on {date}',
  'solution.heldSince': 'Not seen since {date}',
  'solution.alternatives': 'Alternatives on the same causes',
  'solution.none': 'None',
  'solution.drop': 'Drop…',
  'solution.dropTitle': 'Drop {name}?',
  'solution.dropBody': 'It stays in the list as an alternative that was considered. Say why, so the next person does not try it blind.',
  'solution.dropNote': 'Why',
  'solution.dropConfirm': 'Drop',
  'solution.restore': 'Restore',
  'solution.droppedNote': 'Dropped: {note}',
  'solution.questionWorksAround': 'Works around, not through: it addresses no root cause. Fine as a stopgap; say so, or address the root as well.',
  'solution.questionAddsOnly': 'Adds without clearing up: its plan introduces and retires nothing. What does this make redundant?',
  'solution.questionAdoptedUnplanned': 'Decided, not planned: no plan builds it yet.',
  'solution.findingSeenAgain': 'Seen again since it was implemented: {names}. Did it work?',
  'solution.eventProposed': 'Proposed',
  'solution.eventMoved': 'Moved to {state}',
  'solution.eventWaived': 'Experiment waived',
  'solution.eventLinked': 'Linked {name}',
  'solution.eventDropped': 'Dropped',
  'solution.eventRestored': 'Restored',
  'solution.deleteTitle': 'Delete {name}?',
  'solution.deleteBody': 'The record goes, and it leaves every experiment that tested it. Its number is never reused.',
  'solution.deleteExperimentBody': 'The record goes. Its number is never reused.',
  'solution.forCause': 'Solutions for it',
  'solution.proposeForCause': 'Propose a solution…',
  // --- one experiment
  'solution.experimentSource': 'Experiment source',
  'solution.tests': 'Tests',
  'solution.hypothesis': 'Hypothesis',
  'solution.hypothesisHelp': 'If we …, then … by …',
  'solution.measure': 'How it is measured',
  'solution.whereField': 'Where',
  'solution.byField': 'By',
  'solution.fromField': 'From',
  'solution.toField': 'To',
  'solution.result': 'Result',
  'solution.outcome': 'Outcome',
  'solution.newExperiment': 'Plan an experiment',
  'solution.createExperiment': 'Plan',
  'solution.refutedNote': 'A refuted experiment stays. It is the evidence the next person asks for.',
  // --- the templates
  'solution.tplIdea': 'The idea',
  'solution.tplCosts': 'Costs and benefits',
  'solution.tplWhyHere': 'Why this scope',
  'solution.tplAlternatives': 'Alternatives',
  'solution.tplRisks': 'Risks',
  'solution.tplSetup': 'How it is set up',
  'solution.tplLearned': 'What we learned',
  'solution.decisionAddresses': 'It addresses:',
  'solution.decisionAlternatives': 'Considered for the same causes:',
  'solution.decisionDropped': 'dropped: {note}',
} as const
