// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/**
 * English, for observations and causes: the page, the register, the picture.
 *
 * `as const`, so this slice is the schema for its own keys: `nl.ts` beside it
 * cannot be missing one and cannot invent one. The registry composes every
 * module's slice into the table `t()` reads (`i18n/strings.ts`).
 */
export const EN = {

  // --- the page ---------------------------------------------------------------
  'observation.title': 'Observations',
  'observation.close': 'Close observations',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analysis',
  'observation.new': 'New observation',
  'observation.newWhereField': 'Where it was seen',
  'observation.newImpactField': 'Impact',
  'observation.newByField': 'Observed by',
  'observation.newCause': 'New cause',
  'observation.searchPlaceholder': 'Search observations and causes',
  'observation.searchField': 'Search observations',
  'observation.listEmpty': 'Nothing observed here yet.',
  'observation.searchEmpty': 'Nothing matches “{query}”.',
  'observation.noneSelected': 'Pick an observation or a cause, or record one.',

  // --- the register ---------------------------------------------------------------
  'observation.colNumber': 'No.',
  'observation.colTitle': 'Title',
  'observation.colDate': 'Date',
  'observation.colWhere': 'Where',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Impact',
  'observation.colSeen': 'Seen',
  'observation.colCauses': 'Analysed into',
  'observation.scopeHere': 'This scope',
  /** The heading over what a scope below holds, local to it (ADR-0032 §1). */
  'observation.fromBelow': 'Local to {scope}',
  'observation.showMerged': 'Show merged',
  'observation.mergedFromHeading': 'Merged from {label}',
  'observation.mergedFromHeadingScope': 'Merged from {label} in {scope}',
  'observation.acrossBarrier': 'That step changed other scopes as well, so it cannot be taken back here. Change it back in each scope it changed.',
  'observation.showArchived': 'Show archived',
  'observation.archivedMark': 'Archived',
  'observation.notAnalysed': 'not yet',
  'observation.impactMinor': 'Minor',
  'observation.impactMajor': 'Major',
  'observation.impactCritical': 'Critical',
  'observation.seenTimes': '{count}×',

  // --- one observation ---------------------------------------------------------------
  'observation.read': 'Read',
  'observation.edit': 'Edit',
  'observation.source': 'Observation source',
  'observation.titleField': 'Title',
  'observation.whereField': 'Where seen',
  'observation.byField': 'Observed by',
  'observation.dateField': 'Date seen',
  'observation.impactField': 'Impact',
  'observation.seenAgain': 'Seen again',
  'observation.local': 'Local to this scope',
  'observation.merge': 'Merge into…',
  'observation.mergeTitle': 'Merge {name} into another observation',
  'observation.mergeBody': 'Its sightings and its causes move to the one you choose, and both records say so with today’s date. The merged record stays, as history.',
  'observation.mergePick': 'The observation it is the same as',
  'observation.mergeConfirm': 'Merge',
  'observation.mergedInto': 'Merged into {name}',
  'observation.mergedAbove': 'Merged into {name} at {scope} on {date}',
  'observation.archive': 'Archive…',
  'observation.archiveTitle': 'Archive {name}?',
  'observation.archiveBody': 'Fixed, addressed or no longer relevant: the record stays, as history, and leaves the analysis. Restore brings it back.',
  'observation.archiveNote': 'Why (optional)',
  'observation.archiveConfirm': 'Archive',
  'observation.restore': 'Restore',
  'observation.archivedOn': 'Archived on {date}',
  'observation.history': 'History',
  'observation.eventRecorded': 'Recorded',
  'observation.eventSeen': 'Seen again',
  /** Two events a record written before ADR-0032 may hold, read as history. */
  'observation.eventShared': 'Shared with the scopes above',
  'observation.eventUnshared': 'Sharing stopped',
  'observation.eventArchived': 'Archived',
  'observation.eventRestored': 'Restored',
  'observation.eventAbsorbed': 'Absorbed {name} ({count} seen)',
  'observation.eventMerged': 'Merged into {name}',
  'observation.fromScope': 'Local to {scope}. What you add to it here is made in {scope}, as a step there; it is changed there.',
  'observation.openScope': 'Open {scope}',
  'observation.delete': 'Delete',
  'observation.deleteTitle': 'Delete {name}?',
  'observation.deleteBody': 'The record goes, and every link a cause had to it. Its number is never reused.',

  // --- causes ------------------------------------------------------------------------------
  'observation.causes': 'Causes',
  'observation.cause': 'Cause',
  'observation.rootCause': 'Root cause',
  'observation.rootCauses': 'Root causes',
  'observation.causeSource': 'Cause source',
  'observation.stateAssumed': 'Assumed',
  'observation.stateVerified': 'Verified',
  'observation.verify': 'Mark verified',
  'observation.unverify': 'Back to assumed',
  'observation.makeRoot': 'Make root cause',
  'observation.makeCause': 'Make cause',
  'observation.refusedRootExplained': '{names} explains it. Unlink that, or make that one the root cause instead.',
  'observation.refusedRootAddressed': '{names} addresses it. Move that to another root cause, or unlink it, first.',
  'observation.explains': 'Explains',
  'observation.explainedBy': 'Explained by',
  'observation.noLinks': 'Nothing yet',
  'observation.link': 'Link to a cause…',
  'observation.linkDeeper': 'Link to a deeper cause…',
  'observation.linkOrg': 'Link to a cause of {scope}…',
  'observation.linkStrength': 'Relationship',
  'observation.linkConfirm': 'Link',
  'observation.unlink': 'Unlink',
  'observation.strengthStrong': 'Strong',
  'observation.strengthNormal': 'Normal',
  'observation.strengthWeak': 'Weak',
  'observation.deleteCauseTitle': 'Delete {name}?',
  'observation.deleteCauseBody': 'The links from it and to it go with it.',
  'observation.rootNote': 'A root cause ends the chain: nothing explains it. To say something lies behind it, make it a cause first.',

  // --- the template ----------------------------------------------------------------------
  'observation.tplSaw': 'What we saw',
  'observation.tplEvidence': 'Evidence',
  'observation.tplAffected': 'Who or what it affected',
  'observation.tplWhy': 'Why we think so',
  'observation.tplVerify': 'How to verify',

  // --- the picture -------------------------------------------------------------------------
  'observation.laneObservations': 'Observations',
  'observation.laneCauses': 'Causes',
  'observation.laneRoots': 'Root causes',
  'observation.legendImpact': 'Size: impact',
  'observation.legendSeen': 'Tint: times seen',
  'observation.legendAssumed': 'Dashed: assumed',
  'observation.legendVerified': 'Solid: verified',
  'observation.legendRoot': 'Root cause',
  'observation.legendStrength': 'Strong · normal · weak',
  'observation.phaseObserved': 'observed',
  'observation.phaseAnalysed': 'analysed',
  'observation.phaseAssumed': 'assumed',
  'observation.phaseVerified': 'verified',
  'observation.phaseRoots': 'root causes',
  'observation.toAnalyse': 'Not yet analysed',
  'observation.graphEmpty': 'Nothing to draw yet. Record an observation, then link it to a cause.',
  'observation.resizeReader': 'Resize the reading pane',


  // --- solutions (ADR-0026) -----------------------------------------------------------------
  'solution.tab': 'Solutions',
  'solution.new': 'New solution',
  'solution.newTitleField': 'Title',
  'solution.newTitleHelp': 'Say what would take the cause away: “One delivery estimate for every channel”.',
  'solution.laneDirections': 'Directions',
  'solution.laneExperiments': 'Experiments',
  'solution.laneStructural': 'Structural',
  'solution.wholeChain': 'Whole chain',
  'solution.showDropped': 'Show dropped',
  'solution.coverage': '{count} of {total} root causes have a live solution',
  'solution.graphEmpty': 'Nothing to draw yet. Propose a solution for a root cause.',
  'solution.solutions': 'Solutions',
  'solution.experiments': 'Experiments',
  'solution.legendWidth': 'Width: expected benefit',
  'solution.legendFill': 'Fill: how far it has got',
  'solution.legendAddresses': 'Line: addresses a cause',
  'solution.legendTests': 'Dashed: tests',
  'solution.legendProves': 'Solid: confirmed it',
  'solution.legendTrail': 'Faded: the direction it was',
  'solution.trail': 'as a direction',
  'solution.flagNoSolution': 'A root cause nobody is working on yet',
  'solution.flag': 'Needs attention',
  // --- phases, sizes, outcomes
  'solution.phaseIdea': 'Idea',
  'solution.phaseShaped': 'Shaped',
  'solution.phaseTesting': 'Testing',
  'solution.phaseProven': 'Proven',
  'solution.phaseAdopted': 'Adopted',
  'solution.phaseImplemented': 'Implemented',
  'solution.phaseDropped': 'Dropped',
  'solution.sizeSmall': 'Small',
  'solution.sizeMedium': 'Medium',
  'solution.sizeLarge': 'Large',
  'solution.outcomePlanned': 'Planned',
  'solution.outcomeRunning': 'Running',
  'solution.outcomeConfirmed': 'Confirmed',
  'solution.outcomeRefuted': 'Refuted',
  'solution.outcomeInconclusive': 'Inconclusive',
  // --- one solution
  'solution.source': 'Solution source',
  'solution.titleField': 'Title',
  'solution.benefitField': 'Expected benefit',
  'solution.costField': 'Rough cost',
  'solution.unset': 'Not said',
  'solution.addresses': 'Addresses',
  'solution.addressCause': 'Address a cause…',
  'solution.addressTitle': 'Which cause does {name} address?',
  'solution.addressPick': 'Cause',
  'solution.addressConfirm': 'Address',
  'solution.gateTitle': 'To move on to {state}',
  'solution.moveOn': 'Move to {state}',
  'solution.moveBack': 'Back to {state}',
  'solution.toGo': '{count} to go',
  'solution.gateAddresses': 'Addresses at least one cause',
  'solution.gateBenefit': 'Expected benefit',
  'solution.gateCost': 'Rough cost',
  'solution.gateValidatedWith': 'Checked with somebody who would live with it',
  'solution.gateTriedBefore': 'Was this tried before?',
  'solution.gateWhyNow': 'Why it works now, when it did not then',
  'solution.gateExperimentPlanned': 'An experiment tests it: planned, running or confirmed',
  'solution.gateExperimentConfirmed': 'An experiment confirmed it, or it was waived with a reason',
  'solution.gateDecisionAccepted': 'A decision record, accepted',
  // What each line of the gate asks, on hover and on focus: where it is answered.
  'solution.gateHint.addresses': 'Link a cause under “Addresses”, with “Address a cause…”.',
  'solution.gateHint.benefit': 'Pick an expected benefit, even a rough one.',
  'solution.gateHint.cost': 'Pick a rough cost, even a guess.',
  'solution.gateHint.validatedWith': 'Name somebody under “Checked with”: a person, a role or a team who would live with it.',
  'solution.gateHint.triedBefore': 'Under “Tried before”, add the earlier attempt, or tick “None known”. “None known” also answers the line below.',
  'solution.gateHint.whyNow': 'With an earlier attempt listed, say under “Why now” what is different this time. With none listed, ticking “None known” answers this line and the one above.',
  'solution.gateHint.experimentPlanned': 'An experiment that tests this solution, planned, running or confirmed. “Plan an experiment…” starts one.',
  'solution.gateHint.experimentConfirmed': 'An experiment that tests it, with the outcome Confirmed; or a reason written in “Why no experiment is needed” and waived.',
  'solution.gateHint.decisionAccepted': 'The decision record this solution names, accepted on the decisions page. “Propose the decision record” writes one.',
  'solution.gateWhyNowNoneKnown': 'Why it works now, when it did not then — “None known” answers this too',
  'solution.validatedWith': 'Checked with',
  'solution.validatedField': 'A name, a role or a team',
  'solution.add': 'Add',
  'solution.remove': 'Remove',
  'solution.attempts': 'Tried before',
  'solution.noneKnown': 'None known',
  'solution.notAnswered': 'Not answered',
  'solution.attemptAdd': 'Add an earlier attempt',
  'solution.attemptWhen': 'When',
  'solution.attemptWhat': 'What was tried',
  'solution.attemptWhy': 'Why it did not stick',
  'solution.whyNow': 'Why now',
  'solution.whyNowField': 'What is different this time',
  'solution.save': 'Save',
  'solution.waive': 'Waive',
  'solution.waiveField': 'Why no experiment is needed',
  'solution.waived': 'Experiment waived: {reason}',
  'solution.planExperiment': 'Plan an experiment…',
  'solution.proposeDecision': 'Propose the decision record',
  'solution.decision': 'Decision',
  'solution.decisionStatus': '{label} is {status}',
  'solution.open': 'Open',
  'solution.plan': 'Plan',
  'solution.startPlan': 'Start a plan',
  'solution.noPlan': 'No plan yet',
  'solution.didItWork': 'Did it work?',
  'solution.didItWorkHelp': 'The observations under what it addresses. Each should stop being seen.',
  'solution.seenSince': 'Seen again on {date}',
  'solution.heldSince': 'No sighting after {date}',
  'solution.alternatives': 'Alternatives on the same causes',
  'solution.none': 'None',
  'solution.drop': 'Drop…',
  'solution.dropTitle': 'Drop {name}?',
  'solution.dropBody': 'It stays in the list as an alternative that was considered. Say why, so the next person does not try it blind.',
  'solution.dropNote': 'Why',
  'solution.dropConfirm': 'Drop',
  'solution.restore': 'Restore',
  'solution.droppedNote': 'Dropped: {note}',
  'solution.questionWorksAround': 'Works around, not through: it addresses no root cause. Fine as a stopgap; say so, or address the root as well.',
  'solution.questionAddsOnly': 'Adds without clearing up: its plan introduces and retires nothing. What does this make redundant?',
  'solution.questionAdoptedUnplanned': 'Decided, not planned: no plan builds it yet.',
  'solution.findingSeenAgain': 'Seen again since it was implemented: {names}. Did it work?',
  'solution.eventProposed': 'Proposed',
  'solution.eventMoved': 'Moved to {state}',
  'solution.eventWaived': 'Experiment waived',
  'solution.eventLinked': 'Linked {name}',
  'solution.eventDropped': 'Dropped',
  'solution.eventRestored': 'Restored',
  'solution.deleteTitle': 'Delete {name}?',
  'solution.deleteBody': 'The record goes, and it leaves every experiment that tested it. Its number is never reused.',
  'solution.deleteExperimentBody': 'The record goes. Its number is never reused.',
  'solution.forCause': 'Solutions for it',
  'solution.proposeForCause': 'Propose a solution…',
  'solution.proposeAtRoot': 'Solutions address a root cause: propose one on what explains this',
  // --- one experiment
  'solution.experimentSource': 'Experiment source',
  'solution.tests': 'Tests',
  'solution.hypothesis': 'Hypothesis',
  'solution.hypothesisHelp': 'If we …, then … by …',
  'solution.measure': 'How it is measured',
  'solution.whereField': 'Where',
  'solution.byField': 'By',
  'solution.fromField': 'From',
  'solution.toField': 'To',
  'solution.result': 'Result',
  'solution.outcome': 'Outcome',
  'solution.newExperiment': 'Plan an experiment',
  'solution.createExperiment': 'Plan',
  'solution.refutedNote': 'A refuted experiment stays. It is the evidence the next person asks for.',
  // --- the templates
  'solution.tplIdea': 'The idea',
  'solution.tplCosts': 'Costs and benefits',
  'solution.tplWhyHere': 'Why this scope',
  'solution.tplAlternatives': 'Alternatives',
  'solution.tplRisks': 'Risks',
  'solution.tplSetup': 'How it is set up',
  'solution.tplLearned': 'What we learned',
  'solution.decisionAddresses': 'It addresses:',
  'solution.decisionDropped': 'dropped: {note}',
  'solution.decisionLeaveAsIs': 'Leave it as it is: nothing is changed, and the causes above stay as they are',
  'observation.listArchivedOnly': 'No open observations here · {count} archived',
  'observation.more': 'More actions',
  'observation.seenTitle': 'When was {name} seen again?',
  'observation.seenBody': 'The count goes up by one, and the day and the note are kept in its history.',
  'observation.seenDate': 'Day seen',
  'observation.seenNote': 'Note (optional)',
  'observation.seenFuture': 'Not in the future.',
  'observation.seenBeforeFirst': 'Not before it was first seen, on {date}.',
  'observation.verifyTitle': 'What confirmed {name}?',
  'observation.verifyBody': 'Its body does not yet say both why we think so and how it was verified. Say what confirmed it: the answer is added under How to verify, with today’s date.',
  'observation.verifyField': 'What confirmed it?',
  'solution.seenSameDay': 'Seen on {date}, the day it was implemented',
  'solution.questionProofWithdrawn': 'Its proof is withdrawn: no confirmed experiment tests it any more, and it was not waived. Confirm one again or waive it with a reason; until then it cannot be adopted.',
  'solution.reopenBySuperseding': 'To reopen, supersede {label} on the Decisions page.',
  'solution.experimentMoves': 'Move the experiment',
  'solution.moveStart': 'Start',
  'solution.moveToPlanned': 'Back to planned',
  'solution.moveConclude': '{outcome}…',
  'solution.moveReopen': 'Reopen…',
  'solution.concludeTitle': 'Conclude {name}: {outcome}',
  'solution.concludeResultHelp': 'What happened, in numbers where there are numbers.',
  'solution.concludeBeforeFrom': 'Not before it started, on {date}.',
  'solution.concludeConfirm': 'Conclude',
  'solution.reopenTitle': 'Reopen {name}?',
  'solution.reopenBody': 'It goes back to running and its end day is cleared. The result stays until it is concluded again.',
  'solution.reopenWithdraws': '{names} is proven on this experiment; reopening it withdraws that proof.',
  'solution.reopenWithdrawsMany': '{names} are proven on this experiment; reopening it withdraws that proof.',
  'solution.reopenConfirm': 'Reopen',
  'solution.decisionDriverBenefit': 'Expected benefit: {size}',
  'solution.decisionDriverCost': 'Rough cost: {size}',
  'solution.decisionChosen': 'Chosen option: “{option}”, because {because}',
  'solution.decisionBecauseConfirmed': '{experiment} confirmed it: {result}',
  'solution.decisionBecauseConfirmedBare': '{experiment} confirmed it.',
  'solution.decisionBecauseWaived': 'no experiment was needed: {reason}',
  'solution.decisionGood': 'Good, because the expected benefit is {size}.',
  'solution.decisionBad': 'Bad, because the rough cost is {size}.',
  'solution.decisionConfirmation': 'Once it is built, {observations} should stop being seen. The Solutions tab asks whether they did.',
  'solution.decisionConfirmationBare': 'Once it is built, what it addresses should stop being seen. The Solutions tab asks whether it did.',
  'solution.decisionMore': 'Proposed from {label} on the Solutions tab.',

  // --- the actions on a reader (ADR-0032 §7) ------------------------------------------------
  'observation.actions': 'Actions on {name}',
  'observation.fromScopeActions': 'The scope it lives in',
  'observation.thisScope': 'this scope',
  'observation.actCause': 'Cause',
  'observation.actMerge': 'Merge',
  'observation.actArchive': 'Archive',
  'observation.actDeeper': 'Deeper cause',
  'observation.actMakeRoot': 'Make root',
  'observation.actVerify': 'Verify',
  'observation.actSolution': 'Solution',
  'observation.actOrg': 'Org cause',
  'observation.actLocal': 'Local cause',
  'observation.tipSeen': 'Record that this was seen again. It adds a sighting to this observation; nothing new is recorded.',
  'observation.tipCause': 'Add the cause that explains this observation: a new one, or one already written down in {scope}.',
  'observation.tipMerge': 'Merge into another observation that records the same thing. Both histories are kept.',
  'observation.tipArchive': 'It no longer happens. The observation stays in the history and can be restored.',
  'observation.tipEdit': 'Edit the title, where, who, when, impact and description.',
  'observation.tipEditCause': 'Edit the title and the description.',
  'observation.tipRead': 'Back to reading. What you typed is kept.',
  'observation.tipDelete': 'Delete the observation, and every link a cause had to it. Its number is never reused. Archive it instead when it only stopped happening.',
  'observation.tipDeleteCause': 'Delete the cause, with every link from it and to it.',
  'observation.tipDeeper': 'Ask why again: add the cause behind this cause, new or existing, in the same scope.',
  'observation.tipRoot': 'Link the root cause this chain ends in, new or existing, in the same scope.',
  'observation.tipMakeRoot': 'Make this a root cause: the chain ends here, and solutions may address it. {label} becomes {next}. Refused while a cause explains it.',
  'observation.tipMakeCause': 'Make this a cause again, so a deeper cause can be linked behind it. {label} becomes {next}. Refused while a solution addresses it.',
  'observation.tipVerify': 'Mark it verified once “Why we think so” and “How to verify” say what was checked, or say now what confirmed it.',
  'observation.tipAssumed': 'Set it back to assumed: the evidence no longer holds.',
  'observation.tipSolution': 'Propose a solution that addresses this root cause.',
  'observation.tipOrg': 'Link a cause of {scope} that explains this local cause. The link is kept on that cause, in {scope}. Refused on a root cause.',
  'observation.tipLocal': 'Link a cause of a scope below that this cause explains. The link is kept on this cause.',
  'observation.tipRestore': 'Bring it back into the analysis.',
  'observation.tipOpenScope': 'Open the observations of {scope}, where this record lives.',
  'observation.tipUnlink': 'Unlink: {from} no longer explains {to}.',
  'observation.makeRootAsk': 'Make {label} a root cause? It becomes {next}. The chain ends here: nothing can be linked behind it, and solutions may address it.',
  'observation.makeCauseAsk': 'Make {label} a cause again? It becomes {next}, and a deeper cause can be linked behind it.',
  'observation.makeRootRefused': '{label} can’t become a root cause while a cause explains it.',
  'observation.makeCauseRefused': '{label} can’t go back to a cause while a solution addresses it.',
  'observation.orgRefused': '{label} is a root cause: nothing explains it. Make it a cause first, in its own scope, then link the cause that lies behind it.',
  'observation.ok': 'OK',
  'solution.actExperiment': 'Experiment',
  'solution.actDrop': 'Drop',
  'solution.tipAddress': 'Address another root cause of this scope. Offered while it is an idea or shaped.',
  'solution.tipExperiment': 'Plan an experiment that tests whether this solution helps. Offered while it is shaped or testing.',
  'solution.tipDrop': 'Drop it, with a reason. It stays as an alternative that was considered, and can be restored.',
  'solution.tipDelete': 'Delete the solution, and take it out of every experiment that tested it. Drop it instead to keep it as a considered alternative.',
  'solution.tipRestore': 'Bring it back to the state it was dropped from.',
  'solution.tipEdit': 'Edit the title and the description.',
  'solution.tipUnaddress': 'Unlink: {from} no longer addresses {to}.',
  'solution.tipStart': 'Start it today.',
  'solution.tipReopen': 'Reopen it: it runs again, and its end day is cleared.',
  'solution.tipToPlanned': 'Back to planned: it has not started after all.',
  'solution.tipConfirmed': 'It confirmed the solution: say the result and the day it ended.',
  'solution.tipRefuted': 'It refuted the solution: say the result. A refuted experiment stays, as evidence.',
  'solution.tipInconclusive': 'It settled nothing either way: say the result.',
  'solution.tipExperimentEdit': 'Edit the title, the hypothesis, the measure, where, who, when and the result.',
  'solution.tipDeleteExperiment': 'Delete the experiment. Its number is never reused.',

  // --- the forms (ADR-0032 §6) ------------------------------------------------------------------
  'observation.formIntro': 'A fact: what was seen, where, when and by whom, in neutral words. Explanations, blame and fixes stay out; the why goes in the causes below.',
  'observation.formScope': 'Scope',
  'observation.formScopeHere': '{name} (this scope)',
  'observation.formScopeBelow': '{name} (local)',
  'observation.formScopeHelp': 'Where the observation belongs. A scope below makes it local there, with its causes.',
  'observation.formScopeDropped': 'The links to causes of the scope chosen before were taken off: a cause is linked in its own scope.',
  'observation.formTitleExample': 'What was seen, as one sentence. e.g. The nightly claims batch runs into office hours',
  'observation.formWhereExample': 'A place, a screen or a step. e.g. EDI intake, the order screen, pick station 3',
  'observation.formByExample': 'Who saw it: a team, a role or a person. e.g. Carrier management, the night shift',
  'observation.formDateField': 'When seen',
  'observation.formDateExample': 'The day it was first seen. e.g. 4 June 2026',
  'observation.formImpactExample': 'How much it hurts. e.g. Major: customers notice',
  'observation.formTitleMissing': 'Say what was seen, in one sentence.',
  'observation.formWhereMissing': 'Say where it was seen.',
  'observation.formByMissing': 'Say who saw it.',
  'observation.formDateMissing': 'Give the day it was first seen.',
  'observation.formDateFuture': 'The day can’t be in the future. It is the day it was first seen.',
  'observation.formProblemsOne': '1 field needs filling in.',
  'observation.formProblemsMany': '{count} fields need filling in.',
  'observation.formDescription': 'Description',
  'observation.formSawExample': 'Markdown. e.g. Three carriers signed in spring, and the first label came nine weeks after each contract.',
  'observation.formEvidenceExample': 'What shows it: a log, a report, a count. e.g. The contract register and the first shipment per carrier',
  'observation.formAffectedExample': 'Who or what it touched, and how. e.g. New carriers: nine weeks without shipments',
  'observation.formAffectedMissing': 'Say who or what it affected.',
  'observation.formDescriptionMode': 'Write or preview the description',
  'observation.formEdit': 'Edit',
  'observation.formPreview': 'Preview',
  'observation.formNothingWritten': 'Nothing written yet.',
  'observation.formSeenBefore': 'Seen before?',
  'observation.formSeenAgainTip': 'Add a sighting to {name} instead of recording a new observation. Nothing new is recorded.',
  'observation.formWordingHint': '“{word}” reads like a cause, a fix or blame. Keep the title to what was seen, and add the why as a cause below.',
  /** Words that read as a cause, a fix or blame in a title, `|` between them: a hint, never a refusal. */
  'observation.formHintWords': 'because|due to|caused by|should|must|need to|needs to|fix|fixed|broken by|fault|blame|lazy|careless|incompetent',
  'observation.formCauses': 'Causes',
  'observation.formCausesNote': 'optional · made when you record',
  'observation.formNewCauseTip': 'Write a new cause for this observation. It is made when you record.',
  'observation.formExistingCause': 'Existing cause',
  'observation.formExistingCauseTip': 'Link a cause already written down in this scope. Only the link is made when you record.',
  'observation.formColCause': 'Cause',
  'observation.formColKind': 'Kind',
  'observation.formColStrength': 'Strength',
  'observation.formColRemove': 'Take off',
  'observation.formKindNew': 'New',
  'observation.formKindExisting': 'Existing',
  'observation.formKindRoot': 'Root',
  'observation.formStrengthOf': 'Strength of {name}',
  'observation.formNoCauses': 'No cause yet. Record the observation now and analyse it later, or add what you already know.',
  'observation.formRemoveRow': 'Take {name} off the list',
  'observation.formRecord': 'Record observation',
  'observation.formRecordWith': 'Record observation with {what}',
  'observation.formNewCausesOne': '1 new cause',
  'observation.formNewCausesMany': '{count} new causes',
  'observation.formLinksOne': '1 link',
  'observation.formLinksMany': '{count} links',
  'observation.formAnd': '{first} and {second}',
  'observation.causeTitleExample': 'Why it happens, in one sentence. e.g. Every carrier’s EDI mapping is written by hand',
  'observation.causeTitleMissing': 'Say why it happens, in one sentence.',
  'observation.causeWhy': 'Why we think so (optional)',
  'observation.causeWhyExample': 'e.g. Carrier management keeps a folder of hand-made mappings',
  'observation.causeRoot': 'It is a root cause: the chain ends here',
  'observation.causeStrength': 'Strength',
  'observation.causeStrengthExample': 'How much of it this cause explains.',
  'observation.causeAlike': 'Already written down?',
  'observation.causeUse': 'Use this one',
  'observation.causeAddToList': 'Add to the list',
  'observation.causeFind': 'Find a cause by number or words',
  'observation.causeAdd': 'Add',
  'observation.causeAdded': 'Added',
  'observation.causeNoMatch': 'No cause matches.',
  'observation.causeBody': 'Body (optional)',
  'observation.causeBodyExample': 'Markdown. e.g. under How to verify: compare last month’s mappings with the carrier’s own.',
  'observation.causeLinks': 'What it links to',
  'observation.causeExplainsRow': 'Explains',
  'observation.causeBehind': 'Behind it',
  'observation.causeBehindAdd': 'Existing cause behind it',
  'observation.causeBehindTip': 'Link a cause already written down that explains this new one. The link is made with it.',
  'observation.existingIn': 'Existing cause in {scope}',
  'observation.madeAs': 'Made in {scope} as {label}.',
  'observation.linkCauseTitle': 'Cause for {name}',
  'observation.linkCauseIntro': 'Why does this happen? Add a new cause, or link one already written down in its scope.',
  'observation.linkDeeperTitle': 'Deeper cause for {name}',
  'observation.linkDeeperIntro': 'Ask why again: what lies behind this cause?',
  'observation.linkRootTitle': 'Root cause for {name}',
  'observation.linkRootIntro': 'Where does this chain end? A root cause is where the why stops and a solution can start.',
  'observation.linkOrgTitle': 'A cause of {scope} for {name}',
  'observation.linkOrgIntro': 'Which cause of {scope} explains this cause of {below}? The link is kept on the cause of {scope}.',
  'observation.linkLocalTitle': 'Local cause explained by {name}',
  'observation.linkLocalIntro': 'Which cause of a scope below does this cause explain? A local cause is made in its own scope; here you link one that exists. A root cause below ends its chain, and is not offered.',
  'observation.linkTabs': 'A new cause or an existing one',
  'observation.linkTabNew': 'New cause',
  'observation.linkTabExisting': 'Existing cause ({count})',
  'observation.linkAdd': 'Add cause',
  'observation.linkNone': 'No cause to link here.',
  'observation.linkPickMissing': 'Choose a cause to link.',
  'observation.linkUseTip': 'Link this cause instead of writing a new one.',
  'observation.madeBelow': 'Made in {scope}, as a step of that scope. Undo here does not reach it: to take it back, change it back.',
  'observation.belowReadOnly': 'Nothing was made in {scope}: it may not be changed from here.',
  'observation.belowNotYours': 'Nothing was made in {scope}: you may read it, but not change it.',
  'observation.belowRefused': 'Nothing was made in {scope}: its own rules refused the change.',
  'observation.belowNotMade': 'Nothing was made in {scope}.',
  'solution.formIntro': 'What would take a root cause away. It starts as an idea; its gates ask for the rest.',
  'solution.formTitleMissing': 'Say what the solution is, in one sentence.',
  'solution.formBody': 'Body (optional)',
  'solution.formBodyExample': 'Markdown. e.g. under The idea: one service computes the estimate, and every channel reads it.',
  'solution.formAddresses': 'Root causes it addresses',
  'solution.formAddressesNote': 'made when you propose',
  'solution.formAddRootTip': 'Add a root cause of this scope that it addresses. A solution addresses root causes only.',
  'solution.formNoRoots': 'No root cause yet. Propose it now and link one later, or add the root causes it takes away.',
  'solution.formPropose': 'Propose solution',
  'solution.formProposeOne': 'Propose solution for 1 root cause',
  'solution.formProposeMany': 'Propose solution for {count} root causes',
  'solution.experimentTitleExample': 'What is tried, in a few words. e.g. Two weeks at one desk',
  'solution.experimentTitleMissing': 'Say what the experiment is.',

  // --- the picture's controls, filters and views (ADR-0032 §8) --------------
  'observation.filters': 'Filters',
  'observation.filtersShow': 'Show the filter row',
  'observation.filtersHide': 'Hide the filter row',
  'observation.filtersClear': 'Clear filters',
  'observation.viewLocal': 'View local',
  'observation.viewLocalTip': 'Show the analysis of the scopes below, each in a boundary of its own to the left of this scope’s.',
  'observation.viewLocalNone': 'There are no scopes below this one.',
  'observation.localHidden': '{count} local records hidden',
  'observation.size': 'Size',
  'observation.sizeLarge': 'Large',
  'observation.sizeLargeTip': 'Every record as a card with its label and title',
  'observation.sizeSmall': 'Small',
  'observation.sizeSmallTip': 'Every record as a circle, to see more at once',
  'observation.zoomFit': 'Fit the picture to the window',
  'observation.zoomIn': 'Zoom in (⌘ or Ctrl and the scroll wheel)',
  'observation.zoomOut': 'Zoom out (⌘ or Ctrl and the scroll wheel)',
  'observation.shownOf': '{shown} of {total} shown',
  'observation.shownAll': '{count} records',
  'observation.filterScopes': 'Scopes',
  'observation.filterScopesOn': '{on} of {total}',
  'observation.filterScopesTip': 'Choose which scopes are shown. Type to find a scope in a long list.',
  'observation.filterScopesFind': 'Find a scope',
  'observation.filterScopesNone': 'No scope matches.',
  'observation.filterScopesAll': 'All',
  'observation.filterScopesOnly': 'Only this scope',
  'observation.filterScopeHere': 'this scope',
  'observation.filterScopeLocal': 'local',
  'observation.filterObs': 'Obs',
  'observation.filterObsField': 'Filter by text in observations',
  'observation.filterObsTip': 'Observations whose text matches, with the causes, root causes and solutions behind them. The rest is hidden.',
  'observation.filterObsExample': 'e.g. invoice',
  'observation.filterCause': 'Cause',
  'observation.filterCauseField': 'Filter by text in causes',
  'observation.filterCauseTip': 'Causes whose text matches, with everything they explain and everything behind them.',
  'observation.filterCauseExample': 'e.g. by hand',
  'observation.filterRoot': 'RC',
  'observation.filterRootField': 'Filter by text in root causes',
  'observation.filterRootTip': 'Root causes whose text matches, with every chain that leads to them and their solutions.',
  'observation.filterRootExample': 'e.g. owner',
  'observation.filterSearchField': 'Search everything',
  'observation.filterSearchTip': 'Search every record, solutions included. Shows what is found and what is linked to it.',
  'observation.filterNothing': 'Nothing matches these filters. Loosen one, or clear them all with × in the toolbar.',
  'observation.savedFilters': 'Saved filters',
  'observation.savedFiltersTip': 'Save the filters that are on under a short name, or recall one you saved.',
  'observation.savedNone': 'Nothing saved yet.',
  'observation.savedName': 'Save the filters that are on now',
  'observation.savedNameExample': 'A short name, e.g. Pricing chain',
  'observation.savedNeedsFilter': 'Set a filter first',
  'observation.savedSave': 'Save',
  'observation.savedNote': 'Saved for you, and offered in every scope.',
  'observation.savedDelete': 'Delete “{name}”',
  'observation.savedScopesOff': 'Scopes off: {count}',
  'observation.laneDeeper': 'Deeper causes',
  'observation.laneSolutions': 'Solutions',
  'observation.pictureLocal': 'Local · scopes below',
  'observation.pictureGlobal': 'Global · the organisation',
  'observation.pictureThisScope': 'This scope · {scope}',
  'observation.pictureBoxCounts': 'Observations {observations} · causes {causes}',
  'observation.pictureOpenEnd': 'No root cause yet: nothing explains this cause, and it is not a root cause.',
  'observation.pictureFromAbove': '↗ {label} {scope}',
  'observation.pictureToBelow': '↙ {count} local',
  'observation.pictureTraced': '{label} · {kind} · {scope}',
  'observation.phaseOpenEnds': 'open ends',
  'observation.legendStripe': 'Stripe: impact',
  'observation.legendSolution': 'Solution',
  'observation.legendScopeBelow': 'Scope below',
  'observation.legendOpenEnd': 'No root cause yet',
  'observation.legendAcross': 'A cause above explains a cause below',
  'observation.legendCircle': 'Observation: size is impact',
  'observation.legendHollow': 'Cause: hollow',
  'observation.legendDoubleRing': 'Root cause: a double ring',
  'observation.legendSquare': 'Solution: a square',

  // --- the merge screen (ADR-0035) ------------------------------------------------
  'observation.mergeTitleObservations': 'Merge observations',
  'observation.mergeTitleCauses': 'Merge causes',
  'observation.mergeClose': 'Close without merging',
  'observation.mergeIntro': 'Pick the records that say the same thing, choose the one that keeps standing, and say what it says. The others stay as history, each saying where it went.',
  'observation.mergeWhat': 'What to merge',
  'observation.mergeSearchObservations': 'Find observations by number, title or place',
  'observation.mergeSearchCauses': 'Find causes by number or title',
  'observation.mergeAcross': 'Across scopes',
  'observation.mergeAcrossHint': 'Every scope you can read, nearest first.',
  'observation.mergePicked': 'Picked',
  'observation.mergeSurvivor': 'Keeps standing',
  'observation.mergeRemove': 'Take {label} out of the merge',
  'observation.mergeFound': 'Found',
  'observation.mergeNoHits': 'Nothing found.',
  'observation.mergeMoreHits': '{count} more: search to narrow them down.',
  'observation.mergeNotYoursRow': 'You may read {scope}, not change it.',
  'observation.mergeSays': 'What the survivor says',
  'observation.mergeSaysHint': 'Pick any record’s value, or type your own.',
  'observation.mergeUse': '{label}: {value}',
  'observation.mergeUseTip': 'Use what {label} says',
  'observation.mergeFirstSeen': 'First seen',
  'observation.mergeStateField': 'Assumed or verified',
  'observation.mergeNotRootValue': 'Not a root cause',
  'observation.mergeSeenSum': 'Seen {count} times, all of them together',
  'observation.mergeBodyExample': 'Markdown. The survivor’s own description; the others keep theirs either way.',
  'observation.mergeAddOthers': 'Add the others’ descriptions',
  'observation.mergeMoves': 'What moves with it',
  'observation.mergeNoLinks': 'No link names a record being merged.',
  'observation.mergeLinkExplains': '{holder} explains {target}',
  'observation.mergeLinkAddresses': '{holder} addresses {target}',
  'observation.mergeLinkAfter': 'After the merge: {holder} → {target}',
  'observation.mergeLinkMove': 'Move: {text}',
  'observation.mergeLinkStrength': 'Strength',
  'observation.mergeLinkSelf': 'It would name itself, so it stays on the merged record.',
  'observation.mergeLinkLoop': 'It would make a loop, so it stays on the merged record.',
  'observation.mergeLinkRoot': 'Nothing may explain a root cause, so it stays on the merged record.',
  'observation.mergeLinkUpward': 'A cause explains what lies in its own scope or below it, never above, so it stays on the merged record.',
  'observation.mergeLinkSideways': 'A cause explains what lies in its own scope or below it, never beside it, so it stays on the merged record.',
  'observation.mergeLinkObservationBelow': 'An observation is explained in its own scope, not from above, so it stays on the merged record.',
  'observation.mergeLinkMerged': 'It names a record that was merged already, so it stays as it is.',
  'observation.mergeLinkUnknown': 'It names a record that cannot be read from here, so it stays as it is.',
  'observation.mergeLinkObservationElsewhere': 'A cause explains observations of its own scope only, so it stays on the merged record.',
  'observation.mergeLinkSolutionElsewhere': 'A solution addresses causes of its own scope only, so it stays on the merged record.',
  'observation.mergeLinkNotRoot': 'A solution addresses a root cause, and the survivor will not be one, so it stays on the merged record.',
  'observation.mergeNothing': 'Pick at least one more record to merge into the survivor.',
  'observation.mergeMissing': 'One of the records is no longer there. Close the screen and open it again.',
  'observation.mergeAlreadyMerged': 'One of the records was merged into another already.',
  'observation.mergeArchived': 'One of the observations is archived. Restore it first.',
  'observation.mergeSurvivorAbsorbed': 'The survivor cannot be merged into itself.',
  'observation.mergeNotADay': 'The day first seen is not a day.',
  'observation.mergeUnverified': 'A verified cause says why: write in the description what confirmed it, or keep it assumed.',
  'observation.mergeReadOnly': 'Nothing may be changed from here.',
  'observation.mergeNotYours': 'You may read {scope}, but not change it, so this merge cannot be made.',
  'observation.mergeNotFromHere': 'This merge changes other scopes, and only this one may be changed from here.',
  'observation.mergeObservationOne': 'Merge {count} observation into {label}',
  'observation.mergeObservationMany': 'Merge {count} observations into {label}',
  'observation.mergeCauseOne': 'Merge {count} cause into {label}',
  'observation.mergeCauseMany': 'Merge {count} causes into {label}',
  'observation.mergeList': '{names} and {last}',
  'observation.mergedAcross': 'Merged. It changed {scopes}, each as a step of its own scope. Undo here does not take it back: to take it back, change it back.',
  'observation.mergedUnsaved': 'This scope’s part is not written yet; it is written with the next save.',
  'observation.mergedPartial': '{scopes} were changed, but this scope refused its part. Change them back, or merge again.',
  'observation.mergeNotMadeWhy': 'Nothing was merged: {why}',
  'observation.mergeNotMadeYours': 'Nothing was merged: you may read {scope}, but not change it.',
  'observation.mergeNotMadeMoved': 'Nothing was merged: a scope changed while the merge was being written. Try again.',
  'observation.mergeNotMade': 'Nothing was merged.',
  'observation.tipMergeCause': 'Merge with other causes that say the same thing, here or in another scope. Every history is kept.',
} as const
