/**
 * English, for observations and causes: the page, the register, the picture.
 *
 * `as const`, so this slice is the schema for its own keys: `nl.ts` beside it
 * cannot be missing one and cannot invent one. The registry composes every
 * module's slice into the table `t()` reads (`i18n/strings.ts`).
 */
export const EN = {

  // --- the page ---------------------------------------------------------------
  'observation.title': 'Observations',
  'observation.close': 'Close observations',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analysis',
  'observation.new': 'New observation',
  'observation.newTitleField': 'Title',
  'observation.newTitleHelp': 'Say what was seen, as one sentence: “The nightly claims batch runs into office hours”.',
  'observation.newWhereField': 'Where it was seen',
  'observation.newImpactField': 'Impact',
  'observation.newShareField': 'Share with the scopes above',
  'observation.create': 'Record',
  'observation.newCause': 'New cause',
  'observation.newCauseHelp': 'Say what lies behind it: “The batch window was sized for 2019 volumes”.',
  'observation.createCause': 'Add',
  'observation.searchPlaceholder': 'Search observations and causes',
  'observation.searchField': 'Search observations',
  'observation.listEmpty': 'Nothing observed here yet.',
  'observation.searchEmpty': 'Nothing matches “{query}”.',
  'observation.noneSelected': 'Pick an observation or a cause, or record one.',

  // --- the register ---------------------------------------------------------------
  'observation.colNumber': 'No.',
  'observation.colTitle': 'Title',
  'observation.colDate': 'Date',
  'observation.colWhere': 'Where',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Impact',
  'observation.colSeen': 'Seen',
  'observation.colCauses': 'Analysed into',
  'observation.scopeHere': 'This scope',
  /** The heading over what a scope below shared (ADR-0021). */
  'observation.fromBelow': 'Shared from {scope}',
  'observation.sharedMark': 'Shared',
  'observation.showMerged': 'Show merged',
  'observation.notAnalysed': 'not yet',
  'observation.impactMinor': 'Minor',
  'observation.impactMajor': 'Major',
  'observation.impactCritical': 'Critical',
  'observation.seenTimes': '{count}×',

  // --- one observation ---------------------------------------------------------------
  'observation.read': 'Read',
  'observation.edit': 'Edit',
  'observation.source': 'Observation source',
  'observation.titleField': 'Title',
  'observation.whereField': 'Where seen',
  'observation.dateField': 'Date seen',
  'observation.impactField': 'Impact',
  'observation.seenAgain': 'Seen again',
  'observation.share': 'Share with the scopes above',
  'observation.unshare': 'Stop sharing',
  'observation.shared': 'Shared with the scopes above',
  'observation.local': 'Local to this scope',
  'observation.shareHelp': 'Shared, every scope above this one reads it, may link it to a cause of its own and may merge it into one of its own. Local is the default.',
  'observation.merge': 'Merge into…',
  'observation.mergeTitle': 'Merge {name} into another observation',
  'observation.mergeBody': 'Its sightings and its causes move to the one you choose, and both records say so with today’s date. The merged record stays, as history.',
  'observation.mergePick': 'The observation it is the same as',
  'observation.mergeConfirm': 'Merge',
  'observation.mergedInto': 'Merged into {name}',
  'observation.mergedAbove': 'Merged into {name} at {scope} on {date}',
  'observation.history': 'History',
  'observation.eventRecorded': 'Recorded',
  'observation.eventSeen': 'Seen again',
  'observation.eventShared': 'Shared with the scopes above',
  'observation.eventUnshared': 'Sharing stopped',
  'observation.eventAbsorbed': 'Absorbed {name} ({count} seen)',
  'observation.eventMerged': 'Merged into {name}',
  'observation.fromScope': 'This observation belongs to {scope}. It is read here and linked here; it is changed there.',
  'observation.openScope': 'Open {scope}',
  'observation.delete': 'Delete',
  'observation.deleteTitle': 'Delete {name}?',
  'observation.deleteBody': 'The record goes, and every link a cause had to it. Its number is never reused.',

  // --- causes ------------------------------------------------------------------------------
  'observation.causes': 'Causes',
  'observation.cause': 'Cause',
  'observation.rootCause': 'Root cause',
  'observation.rootCauses': 'Root causes',
  'observation.causeSource': 'Cause source',
  'observation.stateAssumed': 'Assumed',
  'observation.stateVerified': 'Verified',
  'observation.verify': 'Mark verified',
  'observation.unverify': 'Back to assumed',
  'observation.explains': 'Explains',
  'observation.explainedBy': 'Explained by',
  'observation.noLinks': 'Nothing yet',
  'observation.link': 'Link to a cause…',
  'observation.linkDeeper': 'Link to a deeper cause…',
  'observation.linkTitle': 'What lies behind {name}?',
  'observation.linkPick': 'Cause',
  'observation.linkNew': 'A new cause…',
  'observation.linkNewTitle': 'Name the cause',
  'observation.linkStrength': 'Relationship',
  'observation.linkConfirm': 'Link',
  'observation.unlink': 'Unlink',
  'observation.strengthStrong': 'Strong',
  'observation.strengthNormal': 'Normal',
  'observation.strengthWeak': 'Weak',
  'observation.deleteCauseTitle': 'Delete {name}?',
  'observation.deleteCauseBody': 'The links from it and to it go with it.',
  'observation.rootNote': 'Nothing has been found behind this cause. Link it to a deeper one and it stops being a root.',

  // --- the template ----------------------------------------------------------------------
  'observation.tplSaw': 'What we saw',
  'observation.tplEvidence': 'Evidence',
  'observation.tplThoughts': 'First thoughts',
  'observation.tplWhy': 'Why we think so',
  'observation.tplVerify': 'How to verify',

  // --- the picture -------------------------------------------------------------------------
  'observation.laneObservations': 'Observations',
  'observation.laneCauses': 'Causes',
  'observation.laneRoots': 'Root causes',
  'observation.legendImpact': 'Size: impact',
  'observation.legendSeen': 'Tint: times seen',
  'observation.legendAssumed': 'Dashed: assumed',
  'observation.legendVerified': 'Solid: verified',
  'observation.legendRoot': 'Root cause',
  'observation.legendStrength': 'Strong · normal · weak',
  'observation.phaseObserved': 'observed',
  'observation.phaseAnalysed': 'analysed',
  'observation.phaseAssumed': 'assumed',
  'observation.phaseVerified': 'verified',
  'observation.phaseRoots': 'root causes',
  'observation.toAnalyse': 'Not yet analysed',
  'observation.graphEmpty': 'Nothing to draw yet. Record an observation, then link it to a cause.',
  'observation.resizeReader': 'Resize the reading pane',
} as const
