// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** Frysk: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'observation.title': 'Waarnimmings',
  'observation.close': 'Waarnimmings slute',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyze',
  'observation.new': 'Nije waarnimming',
  'observation.newTitleField': 'Titel',
  'observation.newTitleHelp': 'Sis wat der sjoen is, yn ien sin: “De nachtlike skeabatch rint troch oant yn kantoaroeren”.',
  'observation.newWhereField': 'Wêr’t it sjoen is',
  'observation.newImpactField': 'Ympakt',
  'observation.newShareField': 'Diele mei de scopes derboppe',
  'observation.newByField': 'Waarnommen troch',
  'observation.create': 'Fêstlizze',
  'observation.newCause': 'Nije oarsaak',
  'observation.newCauseHelp': 'Sis wat derefter sit: “It batchfinster is bemetten op de folumes fan 2019”.',
  'observation.createCause': 'Tafoegje',
  'observation.searchPlaceholder': 'Sykje yn waarnimmings en oarsaken',
  'observation.searchField': 'Waarnimmings sykje',
  'observation.listEmpty': 'Hjir is noch neat waarnommen.',
  'observation.searchEmpty': 'Neat komt oerien mei “{query}”.',
  'observation.noneSelected': 'Kies in waarnimming of in oarsaak, of lis der ien fêst.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Wêr',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Ympakt',
  'observation.colSeen': 'Sjoen',
  'observation.colCauses': 'Analysearre nei',
  'observation.scopeHere': 'Dizze scope',
  'observation.fromBelow': 'Dield út {scope}',
  'observation.sharedMark': 'Dield',
  'observation.showMerged': 'Gearfoege toane',
  'observation.showArchived': 'Argivearre toane',
  'observation.archivedMark': 'Argivearre',
  'observation.notAnalysed': 'noch net',
  'observation.impactMinor': 'Lyts',
  'observation.impactMajor': 'Grut',
  'observation.impactCritical': 'Krityk',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lêze',
  'observation.edit': 'Bewurkje',
  'observation.source': 'Boarnetekst fan de waarnimming',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Wêr sjoen',
  'observation.byField': 'Waarnommen troch',
  'observation.dateField': 'Datum sjoen',
  'observation.impactField': 'Ympakt',
  'observation.seenAgain': 'Opnij sjoen',
  'observation.share': 'Diele mei de scopes derboppe',
  'observation.unshare': 'Net mear diele',
  'observation.shared': 'Dield mei de scopes derboppe',
  'observation.local': 'Lokaal yn dizze scope',
  'observation.shareHelp': 'Dield lêst elke scope boppe dizze him, kin him oan in eigen oarsaak keppelje en kin him gearfoegje mei in eigen waarnimming. Lokaal is de standert.',
  'observation.merge': 'Gearfoegje mei…',
  'observation.mergeTitle': '{name} gearfoegje mei in oare waarnimming',
  'observation.mergeBody': 'De kearen dat it sjoen is en de oarsaken geane oer nei de waarnimming dy’t jo kieze, en beide records sizze dat mei de datum fan hjoed. It gearfoege record bliuwt, as skiednis.',
  'observation.mergePick': 'De waarnimming dêr’t it deselde fan is',
  'observation.mergeConfirm': 'Gearfoegje',
  'observation.mergedInto': 'Gearfoege mei {name}',
  'observation.mergedAbove': 'Gearfoege mei {name} yn {scope} op {date}',
  'observation.archive': 'Argivearje…',
  'observation.archiveTitle': '{name} argivearje?',
  'observation.archiveBody': 'Oplost, oanpakt of net mear relevant: it rekord bliuwt, as skiednis, en ferdwynt út de analyze. Werom helje bringt it werom.',
  'observation.archiveNote': 'Wêrom (opsjoneel)',
  'observation.archiveConfirm': 'Argivearje',
  'observation.restore': 'Werom helje',
  'observation.archivedOn': 'Argivearre op {date}',
  'observation.history': 'Skiednis',
  'observation.eventRecorded': 'Fêstlein',
  'observation.eventSeen': 'Opnij sjoen',
  'observation.eventShared': 'Dield mei de scopes derboppe',
  'observation.eventUnshared': 'Dielen stoppe',
  'observation.eventArchived': 'Argivearre',
  'observation.eventRestored': 'Werom helle',
  'observation.eventAbsorbed': '{name} opnommen ({count} kear sjoen)',
  'observation.eventMerged': 'Gearfoege mei {name}',
  'observation.fromScope': 'Dizze waarnimming heart by {scope}. Hjir wurdt se lêzen en keppele; dêr wurdt se wizige.',
  'observation.openScope': '{scope} iepenje',
  'observation.delete': 'Fuortsmite',
  'observation.deleteTitle': '{name} fuortsmite?',
  'observation.deleteBody': 'It record ferdwynt, mei elke keppeling dy’t in oarsaak dernei hie. It nûmer wurdt nea opnij brûkt.',
  'observation.causes': 'Oarsaken',
  'observation.cause': 'Oarsaak',
  'observation.rootCause': 'Grûnoarsaak',
  'observation.rootCauses': 'Grûnoarsaken',
  'observation.causeSource': 'Boarnetekst fan de oarsaak',
  'observation.stateAssumed': 'Oannommen',
  'observation.stateVerified': 'Ferifiearre',
  'observation.verify': 'Markearje as ferifiearre',
  'observation.unverify': 'Werom nei oannommen',
  'observation.explains': 'Ferklearret',
  'observation.explainedBy': 'Ferklearre troch',
  'observation.noLinks': 'Noch neat',
  'observation.link': 'Keppelje oan in oarsaak…',
  'observation.linkDeeper': 'Keppelje oan in djippere oarsaak…',
  'observation.linkTitle': 'Wat sit der efter {name}?',
  'observation.linkPick': 'Oarsaak',
  'observation.linkNew': 'In nije oarsaak…',
  'observation.linkNewTitle': 'Neam de oarsaak',
  'observation.linkStrength': 'Ferbân',
  'observation.linkConfirm': 'Keppelje',
  'observation.unlink': 'Ûntkeppelje',
  'observation.strengthStrong': 'Sterk',
  'observation.strengthNormal': 'Normaal',
  'observation.strengthWeak': 'Swak',
  'observation.deleteCauseTitle': '{name} fuortsmite?',
  'observation.deleteCauseBody': 'De keppelings derfan en dernei geane mei.',
  'observation.rootNote': 'Efter dizze oarsaak is noch neat fûn. Keppelje him oan in djippere en hy is gjin grûnoarsaak mear.',
  'observation.tplSaw': 'Wat wy seagen',
  'observation.tplEvidence': 'Bewiis',
  'observation.tplAffected': 'Wa of wat it rekke',
  'observation.tplWhy': 'Wêrom’t wy dat tinke',
  'observation.tplVerify': 'Hoe te ferifiearjen',
  'observation.laneObservations': 'Waarnimmings',
  'observation.laneCauses': 'Oarsaken',
  'observation.laneRoots': 'Grûnoarsaken',
  'observation.legendImpact': 'Grutte: ympakt',
  'observation.legendSeen': 'Tint: kearen sjoen',
  'observation.legendAssumed': 'Streke: oannommen',
  'observation.legendVerified': 'Trochlutsen: ferifiearre',
  'observation.legendRoot': 'Grûnoarsaak',
  'observation.legendStrength': 'Sterk · normaal · swak',
  'observation.phaseObserved': 'waarnommen',
  'observation.phaseAnalysed': 'analysearre',
  'observation.phaseAssumed': 'oannommen',
  'observation.phaseVerified': 'ferifiearre',
  'observation.phaseRoots': 'grûnoarsaken',
  'observation.toAnalyse': 'Noch net analysearre',
  'observation.graphEmpty': 'Noch neat te tekenjen. Lis in waarnimming fêst en keppelje dy oan in oarsaak.',
  'observation.resizeReader': 'Lêspaniel fan grutte feroarje',


  // --- solutions (ADR-0026) -----------------------------------------------------------------
  'solution.tab': 'Oplossingen',
  'solution.new': 'Nije oplossing',
  'solution.newTitleField': 'Titel',
  'solution.newTitleHelp': 'Sis wat de oarsaak weinimt: “Ien leveringsskatting foar elk kanaal”.',
  'solution.newCauseField': 'Foar de oarsaak',
  'solution.noCause': 'Noch gjin oarsaak',
  'solution.create': 'Foarstelle',
  'solution.laneDirections': 'Rjochtingen',
  'solution.laneExperiments': 'Eksperiminten',
  'solution.laneStructural': 'Struktureel',
  'solution.wholeChain': 'Hiele keten',
  'solution.showDropped': 'Litten falle toane',
  'solution.coverage': '{count} fan {total} grûnoarsaken hawwe in libbene oplossing',
  'solution.graphEmpty': 'Noch neat te tekenjen. Stel in oplossing foar by in grûnoarsaak.',
  'solution.solutions': 'Oplossingen',
  'solution.experiments': 'Eksperiminten',
  'solution.legendWidth': 'Breedte: ferwachte baat',
  'solution.legendFill': 'Folling: hoe fier it is',
  'solution.legendAddresses': 'Line: pakt in oarsaak oan',
  'solution.legendTests': 'Stippele: test',
  'solution.legendProves': 'Trochlutsen: befestige it',
  'solution.legendTrail': 'Ferbleke: de rjochting dy’t it wie',
  'solution.trail': 'as rjochting',
  'solution.flagNoSolution': 'In grûnoarsaak dêr\'t noch nimmen oan wurket',
  'solution.flag': 'Freget omtinken',
  // --- phases, sizes, outcomes
  'solution.phaseIdea': 'Idee',
  'solution.phaseShaped': 'Utwurke',
  'solution.phaseTesting': 'Wurdt test',
  'solution.phaseProven': 'Bewiisd',
  'solution.phaseAdopted': 'Oannommen',
  'solution.phaseImplemented': 'Ynfierd',
  'solution.phaseDropped': 'Litten falle',
  'solution.sizeSmall': 'Lyts',
  'solution.sizeMedium': 'Middel',
  'solution.sizeLarge': 'Grut',
  'solution.outcomePlanned': 'Pland',
  'solution.outcomeRunning': 'Rint',
  'solution.outcomeConfirmed': 'Befestige',
  'solution.outcomeRefuted': 'Wjerlein',
  'solution.outcomeInconclusive': 'Net beslist',
  // --- one solution
  'solution.source': 'Boarne fan de oplossing',
  'solution.titleField': 'Titel',
  'solution.benefitField': 'Ferwachte baat',
  'solution.costField': 'Growwe kosten',
  'solution.unset': 'Net sein',
  'solution.addresses': 'Pakt oan',
  'solution.addressCause': 'In oarsaak oanpakke…',
  'solution.addressTitle': 'Hokker oarsaak pakt {name} oan?',
  'solution.addressPick': 'Oarsaak',
  'solution.addressConfirm': 'Oanpakke',
  'solution.gateTitle': 'Om troch te gean nei {state}',
  'solution.moveOn': 'Nei {state}',
  'solution.moveBack': 'Werom nei {state}',
  'solution.toGo': 'noch {count}',
  'solution.gateAddresses': 'Pakt teminsten ien oarsaak oan',
  'solution.gateBenefit': 'Ferwachte baat',
  'solution.gateCost': 'Growwe kosten',
  'solution.gateValidatedWith': 'Hifke by ien dy\'t der mei libje moat',
  'solution.gateTriedBefore': 'Is dit earder besocht?',
  'solution.gateWhyNow': 'Wêrom it no wurket, as it doe net wurke',
  'solution.gateExperimentPlanned': 'In eksperimint test it: pland, dwaande of befestige',
  'solution.gateExperimentConfirmed': 'In eksperimint befestige it, of it is mei reden oerslein',
  'solution.gateDecisionAccepted': 'In beslút, oannommen',
  'solution.validatedWith': 'Hifke by',
  'solution.validatedField': 'In namme, in rol of in team',
  'solution.add': 'Tafoegje',
  'solution.remove': 'Fuortsmite',
  'solution.attempts': 'Earder besocht',
  'solution.noneKnown': 'Neat bekend',
  'solution.notAnswered': 'Net beantwurde',
  'solution.attemptAdd': 'Eardere poging tafoegje',
  'solution.attemptWhen': 'Wannear',
  'solution.attemptWhat': 'Wat is besocht',
  'solution.attemptWhy': 'Wêrom it net bleau',
  'solution.whyNow': 'Wêrom no',
  'solution.whyNowField': 'Wat is der dizze kear oars',
  'solution.save': 'Bewarje',
  'solution.waive': 'Oerslaan',
  'solution.waiveField': 'Wêrom gjin eksperimint nedich is',
  'solution.waived': 'Eksperimint oerslein: {reason}',
  'solution.planExperiment': 'In eksperimint planne…',
  'solution.proposeDecision': 'It beslút foarstelle',
  'solution.decision': 'Beslút',
  'solution.decisionStatus': '{label} is {status}',
  'solution.open': 'Iepenje',
  'solution.plan': 'Plan',
  'solution.startPlan': 'In plan begjinne',
  'solution.noPlan': 'Noch gjin plan',
  'solution.didItWork': 'Hat it wurke?',
  'solution.didItWorkHelp': 'De waarnimmingen ûnder wat it oanpakt. Dy soene net mear sjoen wurde moatte.',
  'solution.seenSince': 'Op \'e nij sjoen op {date}',
  'solution.heldSince': 'Net mear sjoen sûnt {date}',
  'solution.alternatives': 'Alternativen foar deselde oarsaken',
  'solution.none': 'Gjin',
  'solution.drop': 'Litte falle…',
  'solution.dropTitle': '{name} litte falle?',
  'solution.dropBody': 'It bliuwt yn de list as alternatyf dat oerwoegen is. Sis wêrom, sadat de folgjende it net blyn op \'e nij besiket.',
  'solution.dropNote': 'Wêrom',
  'solution.dropConfirm': 'Litte falle',
  'solution.restore': 'Weromsette',
  'solution.droppedNote': 'Litten falle: {note}',
  'solution.questionWorksAround': 'Wurket der omhinne, net trochhinne: it pakt gjin grûnoarsaak oan. Goed as needoplossing; sis dat, of pak ek de grûnoarsaak oan.',
  'solution.questionAddsOnly': 'Foeget ta sûnder op te rêden: it plan fiert yn mar fazeart neat út. Wat makket dit oerstallich?',
  'solution.questionAdoptedUnplanned': 'Besletten, net pland: noch gjin plan bout it.',
  'solution.findingSeenAgain': 'Op \'e nij sjoen sûnt de ynfiering: {names}. Hat it wurke?',
  'solution.eventProposed': 'Foarsteld',
  'solution.eventMoved': 'Nei {state}',
  'solution.eventWaived': 'Eksperimint oerslein',
  'solution.eventLinked': '{name} keppele',
  'solution.eventDropped': 'Litten falle',
  'solution.eventRestored': 'Weromset',
  'solution.deleteTitle': '{name} fuortsmite?',
  'solution.deleteBody': 'It rekord ferdwynt, en út elk eksperimint dat it teste. It nûmer wurdt nea wer brûkt.',
  'solution.deleteExperimentBody': 'It rekord ferdwynt. It nûmer wurdt nea wer brûkt.',
  'solution.forCause': 'Oplossingen hjirfoar',
  'solution.proposeForCause': 'In oplossing foarstelle…',
  'solution.proposeAtRoot': 'Oplossingen pakke in grûnoarsaak oan: stel der ien foar op wat dit ferklearret',
  // --- one experiment
  'solution.experimentSource': 'Boarne fan it eksperimint',
  'solution.tests': 'Test',
  'solution.hypothesis': 'Hypoteze',
  'solution.hypothesisHelp': 'As wy …, dan … mei …',
  'solution.measure': 'Hoe\'t it metten wurdt',
  'solution.whereField': 'Wêr',
  'solution.byField': 'Troch',
  'solution.fromField': 'Fan',
  'solution.toField': 'Oant',
  'solution.result': 'Resultaat',
  'solution.outcome': 'Útkomst',
  'solution.newExperiment': 'In eksperimint planne',
  'solution.createExperiment': 'Planne',
  'solution.refutedNote': 'In wjerlein eksperimint bliuwt stean. It is it bewiis dêr\'t de folgjende om freget.',
  // --- the templates
  'solution.tplIdea': 'It idee',
  'solution.tplCosts': 'Kosten en baten',
  'solution.tplWhyHere': 'Wêrom dit domein',
  'solution.tplAlternatives': 'Alternativen',
  'solution.tplRisks': 'Risiko\'s',
  'solution.tplSetup': 'Hoe\'t it opset is',
  'solution.tplLearned': 'Wat wy learden',
  'solution.decisionAddresses': 'It pakt oan:',
  'solution.decisionAlternatives': 'Oerwoegen foar deselde oarsaken:',
  'solution.decisionDropped': 'litten falle: {note}',
}
