/** Frysk: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'observation.title': 'Waarnimmings',
  'observation.close': 'Waarnimmings slute',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyze',
  'observation.new': 'Nije waarnimming',
  'observation.newTitleField': 'Titel',
  'observation.newTitleHelp': 'Sis wat der sjoen is, yn ien sin: “De nachtlike skeabatch rint troch oant yn kantoaroeren”.',
  'observation.newWhereField': 'Wêr’t it sjoen is',
  'observation.newImpactField': 'Ympakt',
  'observation.newShareField': 'Diele mei de scopes derboppe',
  'observation.newByField': 'Waarnommen troch',
  'observation.create': 'Fêstlizze',
  'observation.newCause': 'Nije oarsaak',
  'observation.newCauseHelp': 'Sis wat derefter sit: “It batchfinster is bemetten op de folumes fan 2019”.',
  'observation.createCause': 'Tafoegje',
  'observation.searchPlaceholder': 'Sykje yn waarnimmings en oarsaken',
  'observation.searchField': 'Waarnimmings sykje',
  'observation.listEmpty': 'Hjir is noch neat waarnommen.',
  'observation.searchEmpty': 'Neat komt oerien mei “{query}”.',
  'observation.noneSelected': 'Kies in waarnimming of in oarsaak, of lis der ien fêst.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Wêr',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Ympakt',
  'observation.colSeen': 'Sjoen',
  'observation.colCauses': 'Analysearre nei',
  'observation.scopeHere': 'Dizze scope',
  'observation.fromBelow': 'Dield út {scope}',
  'observation.sharedMark': 'Dield',
  'observation.showMerged': 'Gearfoege toane',
  'observation.showArchived': 'Argivearre toane',
  'observation.archivedMark': 'Argivearre',
  'observation.notAnalysed': 'noch net',
  'observation.impactMinor': 'Lyts',
  'observation.impactMajor': 'Grut',
  'observation.impactCritical': 'Krityk',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lêze',
  'observation.edit': 'Bewurkje',
  'observation.source': 'Boarnetekst fan de waarnimming',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Wêr sjoen',
  'observation.byField': 'Waarnommen troch',
  'observation.dateField': 'Datum sjoen',
  'observation.impactField': 'Ympakt',
  'observation.seenAgain': 'Opnij sjoen',
  'observation.share': 'Diele mei de scopes derboppe',
  'observation.unshare': 'Net mear diele',
  'observation.shared': 'Dield mei de scopes derboppe',
  'observation.local': 'Lokaal yn dizze scope',
  'observation.shareHelp': 'Dield lêst elke scope boppe dizze him, kin him oan in eigen oarsaak keppelje en kin him gearfoegje mei in eigen waarnimming. Lokaal is de standert.',
  'observation.merge': 'Gearfoegje mei…',
  'observation.mergeTitle': '{name} gearfoegje mei in oare waarnimming',
  'observation.mergeBody': 'De kearen dat it sjoen is en de oarsaken geane oer nei de waarnimming dy’t jo kieze, en beide records sizze dat mei de datum fan hjoed. It gearfoege record bliuwt, as skiednis.',
  'observation.mergePick': 'De waarnimming dêr’t it deselde fan is',
  'observation.mergeConfirm': 'Gearfoegje',
  'observation.mergedInto': 'Gearfoege mei {name}',
  'observation.mergedAbove': 'Gearfoege mei {name} yn {scope} op {date}',
  'observation.archive': 'Argivearje…',
  'observation.archiveTitle': '{name} argivearje?',
  'observation.archiveBody': 'Oplost, oanpakt of net mear relevant: it rekord bliuwt, as skiednis, en ferdwynt út de analyze. Werom helje bringt it werom.',
  'observation.archiveNote': 'Wêrom (opsjoneel)',
  'observation.archiveConfirm': 'Argivearje',
  'observation.restore': 'Werom helje',
  'observation.archivedOn': 'Argivearre op {date}',
  'observation.history': 'Skiednis',
  'observation.eventRecorded': 'Fêstlein',
  'observation.eventSeen': 'Opnij sjoen',
  'observation.eventShared': 'Dield mei de scopes derboppe',
  'observation.eventUnshared': 'Dielen stoppe',
  'observation.eventArchived': 'Argivearre',
  'observation.eventRestored': 'Werom helle',
  'observation.eventAbsorbed': '{name} opnommen ({count} kear sjoen)',
  'observation.eventMerged': 'Gearfoege mei {name}',
  'observation.fromScope': 'Dizze waarnimming heart by {scope}. Hjir wurdt se lêzen en keppele; dêr wurdt se wizige.',
  'observation.openScope': '{scope} iepenje',
  'observation.delete': 'Fuortsmite',
  'observation.deleteTitle': '{name} fuortsmite?',
  'observation.deleteBody': 'It record ferdwynt, mei elke keppeling dy’t in oarsaak dernei hie. It nûmer wurdt nea opnij brûkt.',
  'observation.causes': 'Oarsaken',
  'observation.cause': 'Oarsaak',
  'observation.rootCause': 'Grûnoarsaak',
  'observation.rootCauses': 'Grûnoarsaken',
  'observation.causeSource': 'Boarnetekst fan de oarsaak',
  'observation.stateAssumed': 'Oannommen',
  'observation.stateVerified': 'Ferifiearre',
  'observation.verify': 'Markearje as ferifiearre',
  'observation.unverify': 'Werom nei oannommen',
  'observation.explains': 'Ferklearret',
  'observation.explainedBy': 'Ferklearre troch',
  'observation.noLinks': 'Noch neat',
  'observation.link': 'Keppelje oan in oarsaak…',
  'observation.linkDeeper': 'Keppelje oan in djippere oarsaak…',
  'observation.linkTitle': 'Wat sit der efter {name}?',
  'observation.linkPick': 'Oarsaak',
  'observation.linkNew': 'In nije oarsaak…',
  'observation.linkNewTitle': 'Neam de oarsaak',
  'observation.linkStrength': 'Ferbân',
  'observation.linkConfirm': 'Keppelje',
  'observation.unlink': 'Ûntkeppelje',
  'observation.strengthStrong': 'Sterk',
  'observation.strengthNormal': 'Normaal',
  'observation.strengthWeak': 'Swak',
  'observation.deleteCauseTitle': '{name} fuortsmite?',
  'observation.deleteCauseBody': 'De keppelings derfan en dernei geane mei.',
  'observation.rootNote': 'Efter dizze oarsaak is noch neat fûn. Keppelje him oan in djippere en hy is gjin grûnoarsaak mear.',
  'observation.tplSaw': 'Wat wy seagen',
  'observation.tplEvidence': 'Bewiis',
  'observation.tplThoughts': 'Earste gedachten',
  'observation.tplWhy': 'Wêrom’t wy dat tinke',
  'observation.tplVerify': 'Hoe te ferifiearjen',
  'observation.laneObservations': 'Waarnimmings',
  'observation.laneCauses': 'Oarsaken',
  'observation.laneRoots': 'Grûnoarsaken',
  'observation.legendImpact': 'Grutte: ympakt',
  'observation.legendSeen': 'Tint: kearen sjoen',
  'observation.legendAssumed': 'Streke: oannommen',
  'observation.legendVerified': 'Trochlutsen: ferifiearre',
  'observation.legendRoot': 'Grûnoarsaak',
  'observation.legendStrength': 'Sterk · normaal · swak',
  'observation.phaseObserved': 'waarnommen',
  'observation.phaseAnalysed': 'analysearre',
  'observation.phaseAssumed': 'oannommen',
  'observation.phaseVerified': 'ferifiearre',
  'observation.phaseRoots': 'grûnoarsaken',
  'observation.toAnalyse': 'Noch net analysearre',
  'observation.graphEmpty': 'Noch neat te tekenjen. Lis in waarnimming fêst en keppelje dy oan in oarsaak.',
  'observation.resizeReader': 'Lêspaniel fan grutte feroarje',
}
