/** Nederlands: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'observation.title': 'Waarnemingen',
  'observation.close': 'Waarnemingen sluiten',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyse',
  'observation.new': 'Nieuwe waarneming',
  'observation.newTitleField': 'Titel',
  'observation.newTitleHelp': 'Zeg wat er gezien is, in één zin: “De nachtelijke schadebatch loopt door tot in kantooruren”.',
  'observation.newWhereField': 'Waar het gezien is',
  'observation.newImpactField': 'Impact',
  'observation.newShareField': 'Delen met de scopes erboven',
  'observation.create': 'Vastleggen',
  'observation.newCause': 'Nieuwe oorzaak',
  'observation.newCauseHelp': 'Zeg wat erachter zit: “Het batchvenster is bemeten op de volumes van 2019”.',
  'observation.createCause': 'Toevoegen',
  'observation.searchPlaceholder': 'Zoek in waarnemingen en oorzaken',
  'observation.searchField': 'Waarnemingen zoeken',
  'observation.listEmpty': 'Hier is nog niets waargenomen.',
  'observation.searchEmpty': 'Niets komt overeen met “{query}”.',
  'observation.noneSelected': 'Kies een waarneming of een oorzaak, of leg er een vast.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Waar',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Impact',
  'observation.colSeen': 'Gezien',
  'observation.colCauses': 'Geanalyseerd naar',
  'observation.scopeHere': 'Deze scope',
  'observation.fromBelow': 'Gedeeld vanuit {scope}',
  'observation.sharedMark': 'Gedeeld',
  'observation.showMerged': 'Samengevoegde tonen',
  'observation.notAnalysed': 'nog niet',
  'observation.impactMinor': 'Klein',
  'observation.impactMajor': 'Groot',
  'observation.impactCritical': 'Kritiek',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lezen',
  'observation.edit': 'Bewerken',
  'observation.source': 'Brontekst van de waarneming',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Waar gezien',
  'observation.dateField': 'Datum gezien',
  'observation.impactField': 'Impact',
  'observation.seenAgain': 'Opnieuw gezien',
  'observation.share': 'Delen met de scopes erboven',
  'observation.unshare': 'Niet meer delen',
  'observation.shared': 'Gedeeld met de scopes erboven',
  'observation.local': 'Lokaal in deze scope',
  'observation.shareHelp': 'Gedeeld leest elke scope boven deze hem, kan hem aan een eigen oorzaak koppelen en kan hem samenvoegen met een eigen waarneming. Lokaal is de standaard.',
  'observation.merge': 'Samenvoegen met…',
  'observation.mergeTitle': '{name} samenvoegen met een andere waarneming',
  'observation.mergeBody': 'De keren dat het gezien is en de oorzaken gaan over naar de waarneming die je kiest, en beide records zeggen dat met de datum van vandaag. Het samengevoegde record blijft, als geschiedenis.',
  'observation.mergePick': 'De waarneming waar het dezelfde van is',
  'observation.mergeConfirm': 'Samenvoegen',
  'observation.mergedInto': 'Samengevoegd met {name}',
  'observation.mergedAbove': 'Samengevoegd met {name} in {scope} op {date}',
  'observation.history': 'Geschiedenis',
  'observation.eventRecorded': 'Vastgelegd',
  'observation.eventSeen': 'Opnieuw gezien',
  'observation.eventShared': 'Gedeeld met de scopes erboven',
  'observation.eventUnshared': 'Delen gestopt',
  'observation.eventAbsorbed': '{name} opgenomen ({count} keer gezien)',
  'observation.eventMerged': 'Samengevoegd met {name}',
  'observation.fromScope': 'Deze waarneming hoort bij {scope}. Hier wordt ze gelezen en gekoppeld; daar wordt ze gewijzigd.',
  'observation.openScope': '{scope} openen',
  'observation.delete': 'Verwijderen',
  'observation.deleteTitle': '{name} verwijderen?',
  'observation.deleteBody': 'Het record verdwijnt, met elke koppeling die een oorzaak ernaar had. Het nummer wordt nooit hergebruikt.',
  'observation.causes': 'Oorzaken',
  'observation.cause': 'Oorzaak',
  'observation.rootCause': 'Grondoorzaak',
  'observation.rootCauses': 'Grondoorzaken',
  'observation.causeSource': 'Brontekst van de oorzaak',
  'observation.stateAssumed': 'Aangenomen',
  'observation.stateVerified': 'Geverifieerd',
  'observation.verify': 'Markeren als geverifieerd',
  'observation.unverify': 'Terug naar aangenomen',
  'observation.explains': 'Verklaart',
  'observation.explainedBy': 'Verklaard door',
  'observation.noLinks': 'Nog niets',
  'observation.link': 'Koppelen aan een oorzaak…',
  'observation.linkDeeper': 'Koppelen aan een diepere oorzaak…',
  'observation.linkTitle': 'Wat zit er achter {name}?',
  'observation.linkPick': 'Oorzaak',
  'observation.linkNew': 'Een nieuwe oorzaak…',
  'observation.linkNewTitle': 'Benoem de oorzaak',
  'observation.linkStrength': 'Verband',
  'observation.linkConfirm': 'Koppelen',
  'observation.unlink': 'Ontkoppelen',
  'observation.strengthStrong': 'Sterk',
  'observation.strengthNormal': 'Normaal',
  'observation.strengthWeak': 'Zwak',
  'observation.deleteCauseTitle': '{name} verwijderen?',
  'observation.deleteCauseBody': 'De koppelingen ervan en ernaartoe gaan mee.',
  'observation.rootNote': 'Achter deze oorzaak is nog niets gevonden. Koppel hem aan een diepere en hij is geen grondoorzaak meer.',
  'observation.tplSaw': 'Wat we zagen',
  'observation.tplEvidence': 'Bewijs',
  'observation.tplThoughts': 'Eerste gedachten',
  'observation.tplWhy': 'Waarom we dat denken',
  'observation.tplVerify': 'Hoe te verifiëren',
  'observation.laneObservations': 'Waarnemingen',
  'observation.laneCauses': 'Oorzaken',
  'observation.laneRoots': 'Grondoorzaken',
  'observation.legendImpact': 'Grootte: impact',
  'observation.legendSeen': 'Tint: keren gezien',
  'observation.legendAssumed': 'Gestreept: aangenomen',
  'observation.legendVerified': 'Doorgetrokken: geverifieerd',
  'observation.legendRoot': 'Grondoorzaak',
  'observation.legendStrength': 'Sterk · normaal · zwak',
  'observation.phaseObserved': 'waargenomen',
  'observation.phaseAnalysed': 'geanalyseerd',
  'observation.phaseAssumed': 'aangenomen',
  'observation.phaseVerified': 'geverifieerd',
  'observation.phaseRoots': 'grondoorzaken',
  'observation.toAnalyse': 'Nog niet geanalyseerd',
  'observation.graphEmpty': 'Nog niets te tekenen. Leg een waarneming vast en koppel die aan een oorzaak.',
  'observation.resizeReader': 'Leespaneel van grootte veranderen',
}
