// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** Nederlands: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'observation.title': 'Waarnemingen',
  'observation.close': 'Waarnemingen sluiten',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyse',
  'observation.new': 'Nieuwe waarneming',
  'observation.newWhereField': 'Waar het gezien is',
  'observation.newImpactField': 'Impact',
  'observation.newByField': 'Waargenomen door',
  'observation.newCause': 'Nieuwe oorzaak',
  'observation.searchPlaceholder': 'Zoek in waarnemingen en oorzaken',
  'observation.searchField': 'Waarnemingen zoeken',
  'observation.listEmpty': 'Hier is nog niets waargenomen.',
  'observation.searchEmpty': 'Niets komt overeen met “{query}”.',
  'observation.noneSelected': 'Kies een waarneming of een oorzaak, of leg er een vast.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Waar',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Impact',
  'observation.colSeen': 'Gezien',
  'observation.colCauses': 'Geanalyseerd naar',
  'observation.scopeHere': 'Deze scope',
  'observation.fromBelow': 'Lokaal in {scope}',
  'observation.showMerged': 'Samengevoegde tonen',
  'observation.showArchived': 'Gearchiveerde tonen',
  'observation.archivedMark': 'Gearchiveerd',
  'observation.notAnalysed': 'nog niet',
  'observation.impactMinor': 'Klein',
  'observation.impactMajor': 'Groot',
  'observation.impactCritical': 'Kritiek',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lezen',
  'observation.edit': 'Bewerken',
  'observation.source': 'Brontekst van de waarneming',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Waar gezien',
  'observation.byField': 'Waargenomen door',
  'observation.dateField': 'Datum gezien',
  'observation.impactField': 'Impact',
  'observation.seenAgain': 'Opnieuw gezien',
  'observation.local': 'Lokaal in deze scope',
  'observation.merge': 'Samenvoegen met…',
  'observation.mergeTitle': '{name} samenvoegen met een andere waarneming',
  'observation.mergeBody': 'De keren dat het gezien is en de oorzaken gaan over naar de waarneming die je kiest, en beide records zeggen dat met de datum van vandaag. Het samengevoegde record blijft, als geschiedenis.',
  'observation.mergePick': 'De waarneming die hetzelfde beschrijft',
  'observation.mergeConfirm': 'Samenvoegen',
  'observation.mergedInto': 'Samengevoegd met {name}',
  'observation.mergedAbove': 'Samengevoegd met {name} in {scope} op {date}',
  'observation.archive': 'Archiveren…',
  'observation.archiveTitle': '{name} archiveren?',
  'observation.archiveBody': 'Opgelost, aangepakt of niet meer relevant: het record blijft, als geschiedenis, en verdwijnt uit de analyse. Terughalen brengt het terug.',
  'observation.archiveNote': 'Waarom (optioneel)',
  'observation.archiveConfirm': 'Archiveren',
  'observation.restore': 'Terughalen',
  'observation.archivedOn': 'Gearchiveerd op {date}',
  'observation.history': 'Geschiedenis',
  'observation.eventRecorded': 'Vastgelegd',
  'observation.eventSeen': 'Opnieuw gezien',
  'observation.eventShared': 'Gedeeld met de scopes erboven',
  'observation.eventUnshared': 'Delen gestopt',
  'observation.eventArchived': 'Gearchiveerd',
  'observation.eventRestored': 'Teruggehaald',
  'observation.eventAbsorbed': '{name} opgenomen ({count} keer gezien)',
  'observation.eventMerged': 'Samengevoegd met {name}',
  'observation.fromScope': 'Lokaal in {scope}. Wat je er hier aan toevoegt, wordt in {scope} gemaakt, als stap daar; gewijzigd wordt het daar.',
  'observation.openScope': '{scope} openen',
  'observation.delete': 'Verwijderen',
  'observation.deleteTitle': '{name} verwijderen?',
  'observation.deleteBody': 'Het record verdwijnt, met elke koppeling die een oorzaak ernaar had. Het nummer wordt nooit hergebruikt.',
  'observation.causes': 'Oorzaken',
  'observation.cause': 'Oorzaak',
  'observation.rootCause': 'Grondoorzaak',
  'observation.rootCauses': 'Grondoorzaken',
  'observation.causeSource': 'Brontekst van de oorzaak',
  'observation.stateAssumed': 'Aangenomen',
  'observation.stateVerified': 'Geverifieerd',
  'observation.verify': 'Markeren als geverifieerd',
  'observation.unverify': 'Terug naar aangenomen',
  'observation.makeRoot': 'Tot grondoorzaak maken',
  'observation.makeCause': 'Tot oorzaak maken',
  'observation.refusedRootExplained': '{names} verklaart hem. Ontkoppel die, of maak die tot grondoorzaak.',
  'observation.refusedRootAddressed': '{names} richt zich erop. Verplaats die eerst naar een andere grondoorzaak, of ontkoppel hem.',
  'observation.explains': 'Verklaart',
  'observation.explainedBy': 'Verklaard door',
  'observation.noLinks': 'Nog niets',
  'observation.link': 'Koppelen aan een oorzaak…',
  'observation.linkDeeper': 'Koppelen aan een diepere oorzaak…',
  'observation.linkStrength': 'Verband',
  'observation.linkConfirm': 'Koppelen',
  'observation.unlink': 'Ontkoppelen',
  'observation.strengthStrong': 'Sterk',
  'observation.strengthNormal': 'Normaal',
  'observation.strengthWeak': 'Zwak',
  'observation.deleteCauseTitle': '{name} verwijderen?',
  'observation.deleteCauseBody': 'De koppelingen ervan en ernaartoe gaan mee.',
  'observation.rootNote': 'Bij een grondoorzaak houdt de keten op: niets verklaart hem. Wie wil zeggen dat er iets achter zit, maakt er eerst weer een oorzaak van.',
  'observation.tplSaw': 'Wat we zagen',
  'observation.tplEvidence': 'Bewijs',
  'observation.tplAffected': 'Wie of wat het raakte',
  'observation.tplWhy': 'Waarom we dat denken',
  'observation.tplVerify': 'Hoe te verifiëren',
  'observation.laneObservations': 'Waarnemingen',
  'observation.laneCauses': 'Oorzaken',
  'observation.laneRoots': 'Grondoorzaken',
  'observation.legendImpact': 'Grootte: impact',
  'observation.legendSeen': 'Tint: keren gezien',
  'observation.legendAssumed': 'Gestreept: aangenomen',
  'observation.legendVerified': 'Doorgetrokken: geverifieerd',
  'observation.legendRoot': 'Grondoorzaak',
  'observation.legendStrength': 'Sterk · normaal · zwak',
  'observation.phaseObserved': 'waargenomen',
  'observation.phaseAnalysed': 'geanalyseerd',
  'observation.phaseAssumed': 'aangenomen',
  'observation.phaseVerified': 'geverifieerd',
  'observation.phaseRoots': 'grondoorzaken',
  'observation.toAnalyse': 'Nog niet geanalyseerd',
  'observation.graphEmpty': 'Nog niets te tekenen. Leg een waarneming vast en koppel die aan een oorzaak.',
  'observation.resizeReader': 'Leespaneel van grootte veranderen',


  // --- solutions (ADR-0026) -----------------------------------------------------------------
  'solution.tab': 'Oplossingen',
  'solution.new': 'Nieuwe oplossing',
  'solution.newTitleField': 'Titel',
  'solution.newTitleHelp': 'Zeg wat de oorzaak wegneemt: “Eén levertijdschatting voor elk kanaal”.',
  'solution.laneDirections': 'Richtingen',
  'solution.laneExperiments': 'Experimenten',
  'solution.laneStructural': 'Structureel',
  'solution.wholeChain': 'Hele keten',
  'solution.showDropped': 'Verworpen oplossingen tonen',
  'solution.coverage': '{count} van {total} grondoorzaken hebben een levende oplossing',
  'solution.graphEmpty': 'Nog niets te tekenen. Stel een oplossing voor bij een grondoorzaak.',
  'solution.solutions': 'Oplossingen',
  'solution.experiments': 'Experimenten',
  'solution.legendWidth': 'Breedte: verwachte baat',
  'solution.legendFill': 'Vulling: hoe ver het is',
  'solution.legendAddresses': 'Lijn: pakt een oorzaak aan',
  'solution.legendTests': 'Gestreept: test',
  'solution.legendProves': 'Doorgetrokken: bevestigde het',
  'solution.legendTrail': 'Vervaagd: de richting die het was',
  'solution.trail': 'als richting',
  'solution.flagNoSolution': 'Een grondoorzaak waar nog niemand aan werkt',
  'solution.flag': 'Vraagt aandacht',
  // --- phases, sizes, outcomes
  'solution.phaseIdea': 'Idee',
  'solution.phaseShaped': 'Uitgewerkt',
  'solution.phaseTesting': 'Wordt getest',
  'solution.phaseProven': 'Bewezen',
  'solution.phaseAdopted': 'Overgenomen',
  'solution.phaseImplemented': 'Ingevoerd',
  'solution.phaseDropped': 'Laten vallen',
  'solution.sizeSmall': 'Klein',
  'solution.sizeMedium': 'Middel',
  'solution.sizeLarge': 'Groot',
  'solution.outcomePlanned': 'Gepland',
  'solution.outcomeRunning': 'Loopt',
  'solution.outcomeConfirmed': 'Bevestigd',
  'solution.outcomeRefuted': 'Weerlegd',
  'solution.outcomeInconclusive': 'Onbeslist',
  // --- one solution
  'solution.source': 'Bron van de oplossing',
  'solution.titleField': 'Titel',
  'solution.benefitField': 'Verwachte baat',
  'solution.costField': 'Grove kosten',
  'solution.unset': 'Niet gezegd',
  'solution.addresses': 'Pakt aan',
  'solution.addressCause': 'Een oorzaak aanpakken…',
  'solution.addressTitle': 'Welke oorzaak pakt {name} aan?',
  'solution.addressPick': 'Oorzaak',
  'solution.addressConfirm': 'Aanpakken',
  'solution.gateTitle': 'Om door te gaan naar {state}',
  'solution.moveOn': 'Naar {state}',
  'solution.moveBack': 'Terug naar {state}',
  'solution.toGo': 'nog {count}',
  'solution.gateAddresses': 'Pakt minstens één oorzaak aan',
  'solution.gateBenefit': 'Verwachte baat',
  'solution.gateCost': 'Grove kosten',
  'solution.gateValidatedWith': 'Getoetst bij iemand die ermee moet leven',
  'solution.gateTriedBefore': 'Is dit eerder geprobeerd?',
  'solution.gateWhyNow': 'Waarom het nu werkt, terwijl het toen niet werkte',
  'solution.gateExperimentPlanned': 'Een experiment test het: gepland, bezig of bevestigd',
  'solution.gateExperimentConfirmed': 'Een experiment bevestigde het, of het is met reden overgeslagen',
  'solution.gateDecisionAccepted': 'Een besluit, aanvaard',
  'solution.gateHint.addresses': 'Koppel een oorzaak onder “Pakt aan”, met “Een oorzaak aanpakken…”.',
  'solution.gateHint.benefit': 'Kies een verwachte baat, al is het een ruwe.',
  'solution.gateHint.cost': 'Kies grove kosten, al is het een gok.',
  'solution.gateHint.validatedWith': 'Noem iemand onder “Getoetst bij”: een persoon, een rol of een team dat ermee moet leven.',
  'solution.gateHint.triedBefore': 'Voeg onder “Eerder geprobeerd” de eerdere poging toe, of vink “Niets bekend” aan. “Niets bekend” beantwoordt ook de regel hieronder.',
  'solution.gateHint.whyNow': 'Staat er een eerdere poging, zeg dan onder “Waarom nu” wat er deze keer anders is. Staat er geen, dan beantwoordt “Niets bekend” deze regel en die erboven.',
  'solution.gateHint.experimentPlanned': 'Een experiment dat deze oplossing test, gepland, bezig of bevestigd. “Een experiment plannen…” begint er een.',
  'solution.gateHint.experimentConfirmed': 'Een experiment dat het test, met de uitkomst Bevestigd; of een reden bij “Waarom geen experiment nodig is” en overgeslagen.',
  'solution.gateHint.decisionAccepted': 'Het besluit dat deze oplossing noemt, aanvaard op de besluitenpagina. “Het besluit voorstellen” schrijft er een.',
  'solution.gateWhyNowNoneKnown': 'Waarom het nu werkt, terwijl het toen niet werkte — “Niets bekend” beantwoordt ook dit',
  'solution.validatedWith': 'Getoetst bij',
  'solution.validatedField': 'Een naam, een rol of een team',
  'solution.add': 'Toevoegen',
  'solution.remove': 'Verwijderen',
  'solution.attempts': 'Eerder geprobeerd',
  'solution.noneKnown': 'Niets bekend',
  'solution.notAnswered': 'Niet beantwoord',
  'solution.attemptAdd': 'Eerdere poging toevoegen',
  'solution.attemptWhen': 'Wanneer',
  'solution.attemptWhat': 'Wat is geprobeerd',
  'solution.attemptWhy': 'Waarom het niet beklijfde',
  'solution.whyNow': 'Waarom nu',
  'solution.whyNowField': 'Wat is er deze keer anders',
  'solution.save': 'Opslaan',
  'solution.waive': 'Overslaan',
  'solution.waiveField': 'Waarom geen experiment nodig is',
  'solution.waived': 'Experiment overgeslagen: {reason}',
  'solution.planExperiment': 'Een experiment plannen…',
  'solution.proposeDecision': 'Het besluit voorstellen',
  'solution.decision': 'Besluit',
  'solution.decisionStatus': '{label} is {status}',
  'solution.open': 'Openen',
  'solution.plan': 'Plan',
  'solution.startPlan': 'Een plan starten',
  'solution.noPlan': 'Nog geen plan',
  'solution.didItWork': 'Heeft het gewerkt?',
  'solution.didItWorkHelp': 'De waarnemingen onder wat het aanpakt. Die zouden niet meer gezien moeten worden.',
  'solution.seenSince': 'Opnieuw gezien op {date}',
  'solution.heldSince': 'Geen waarneming meer na {date}',
  'solution.alternatives': 'Alternatieven voor dezelfde oorzaken',
  'solution.none': 'Geen',
  'solution.drop': 'Laten vallen…',
  'solution.dropTitle': '{name} laten vallen?',
  'solution.dropBody': 'Het blijft in de lijst als alternatief dat is overwogen. Zeg waarom, zodat de volgende het niet blind opnieuw probeert.',
  'solution.dropNote': 'Waarom',
  'solution.dropConfirm': 'Laten vallen',
  'solution.restore': 'Terugzetten',
  'solution.droppedNote': 'Laten vallen: {note}',
  'solution.questionWorksAround': 'Werkt eromheen, niet erdoorheen: het pakt geen grondoorzaak aan. Prima als noodoplossing; zeg dat, of pak ook de grondoorzaak aan.',
  'solution.questionAddsOnly': 'Voegt toe zonder op te ruimen: het plan introduceert maar faseert niets uit. Wat maakt dit overbodig?',
  'solution.questionAdoptedUnplanned': 'Besloten, niet gepland: nog geen plan bouwt het.',
  'solution.findingSeenAgain': 'Opnieuw gezien sinds de invoering: {names}. Heeft het gewerkt?',
  'solution.eventProposed': 'Voorgesteld',
  'solution.eventMoved': 'Naar {state}',
  'solution.eventWaived': 'Experiment overgeslagen',
  'solution.eventLinked': '{name} gekoppeld',
  'solution.eventDropped': 'Laten vallen',
  'solution.eventRestored': 'Teruggezet',
  'solution.deleteTitle': '{name} verwijderen?',
  'solution.deleteBody': 'Het record verdwijnt, ook uit elk experiment dat het testte. Het nummer wordt nooit hergebruikt.',
  'solution.deleteExperimentBody': 'Het record verdwijnt. Het nummer wordt nooit hergebruikt.',
  'solution.forCause': 'Oplossingen hiervoor',
  'solution.proposeForCause': 'Een oplossing voorstellen…',
  'solution.proposeAtRoot': 'Oplossingen pakken een grondoorzaak aan: stel er een voor op wat dit verklaart',
  // --- one experiment
  'solution.experimentSource': 'Bron van het experiment',
  'solution.tests': 'Test',
  'solution.hypothesis': 'Hypothese',
  'solution.hypothesisHelp': 'Als we …, dan … met …',
  'solution.measure': 'Hoe het gemeten wordt',
  'solution.whereField': 'Waar',
  'solution.byField': 'Door',
  'solution.fromField': 'Van',
  'solution.toField': 'Tot',
  'solution.result': 'Resultaat',
  'solution.outcome': 'Uitkomst',
  'solution.newExperiment': 'Een experiment plannen',
  'solution.createExperiment': 'Plannen',
  'solution.refutedNote': 'Een weerlegd experiment blijft staan. Het is het bewijs waar de volgende om vraagt.',
  // --- the templates
  'solution.tplIdea': 'Het idee',
  'solution.tplCosts': 'Kosten en baten',
  'solution.tplWhyHere': 'Waarom dit domein',
  'solution.tplAlternatives': 'Alternatieven',
  'solution.tplRisks': 'Risico\'s',
  'solution.tplSetup': 'Hoe het is opgezet',
  'solution.tplLearned': 'Wat we leerden',
  'solution.decisionAddresses': 'Het pakt aan:',
  'solution.decisionDropped': 'laten vallen: {note}',
  'solution.decisionLeaveAsIs': 'Laten zoals het is: er verandert niets, en de oorzaken hierboven blijven zoals ze zijn',
  'observation.listArchivedOnly': 'Hier staan geen open waarnemingen · {count} gearchiveerd',
  'observation.more': 'Meer acties',
  'observation.seenTitle': 'Wanneer is {name} opnieuw gezien?',
  'observation.seenBody': 'De telling gaat met één omhoog, en de dag en de notitie blijven in de geschiedenis staan.',
  'observation.seenDate': 'Dag gezien',
  'observation.seenNote': 'Notitie (optioneel)',
  'observation.seenFuture': 'Niet in de toekomst.',
  'observation.seenBeforeFirst': 'Niet vóór de dag dat het voor het eerst gezien is, {date}.',
  'observation.verifyTitle': 'Wat bevestigde {name}?',
  'observation.verifyBody': 'De tekst zegt nog niet zowel waarom we dat denken als hoe het geverifieerd is. Zeg wat het bevestigde: het antwoord komt onder Hoe te verifiëren, met de datum van vandaag.',
  'observation.verifyField': 'Wat bevestigde het?',
  'solution.seenSameDay': 'Gezien op {date}, de dag van de invoering',
  'solution.questionProofWithdrawn': 'Het bewijs is vervallen: geen bevestigd experiment test het nog, en het is niet overgeslagen. Bevestig er opnieuw een of sla het met reden over; tot dan kan het niet worden overgenomen.',
  'solution.reopenBySuperseding': 'Om te heropenen: vervang {label} op de besluitenpagina.',
  'solution.experimentMoves': 'Het experiment verplaatsen',
  'solution.moveStart': 'Starten',
  'solution.moveToPlanned': 'Terug naar gepland',
  'solution.moveConclude': '{outcome}…',
  'solution.moveReopen': 'Heropenen…',
  'solution.concludeTitle': '{name} afronden: {outcome}',
  'solution.concludeResultHelp': 'Wat er gebeurde, in getallen waar er getallen zijn.',
  'solution.concludeBeforeFrom': 'Niet vóór de start, {date}.',
  'solution.concludeConfirm': 'Afronden',
  'solution.reopenTitle': '{name} heropenen?',
  'solution.reopenBody': 'Het loopt weer en de einddatum vervalt. Het resultaat blijft staan tot het opnieuw wordt afgerond.',
  'solution.reopenWithdraws': '{names} is op dit experiment bewezen; heropenen trekt dat bewijs in.',
  'solution.reopenWithdrawsMany': '{names} zijn op dit experiment bewezen; heropenen trekt dat bewijs in.',
  'solution.reopenConfirm': 'Heropenen',
  'solution.decisionDriverBenefit': 'Verwachte baat: {size}',
  'solution.decisionDriverCost': 'Grove kosten: {size}',
  'solution.decisionChosen': 'Gekozen optie: “{option}”, omdat {because}',
  'solution.decisionBecauseConfirmed': '{experiment} het bevestigde: {result}',
  'solution.decisionBecauseConfirmedBare': '{experiment} het bevestigde.',
  'solution.decisionBecauseWaived': 'er geen experiment nodig was: {reason}',
  'solution.decisionGood': 'Goed, omdat de verwachte baat {size} is.',
  'solution.decisionBad': 'Slecht, omdat de grove kosten {size} zijn.',
  'solution.decisionConfirmation': 'Als het gebouwd is, zouden {observations} niet meer gezien moeten worden. Het tabblad Oplossingen vraagt of dat zo is.',
  'solution.decisionConfirmationBare': 'Als het gebouwd is, zou wat het aanpakt niet meer gezien moeten worden. Het tabblad Oplossingen vraagt of dat zo is.',
  'solution.decisionMore': 'Voorgesteld vanuit {label} op het tabblad Oplossingen.',

  // --- de acties in een lezer (ADR-0032 §7) ------------------------------------------------
  'observation.actions': 'Acties op {name}',
  'observation.fromScopeActions': 'De scope waar het thuishoort',
  'observation.thisScope': 'deze scope',
  'observation.actCause': 'Oorzaak',
  'observation.actMerge': 'Samenvoegen',
  'observation.actArchive': 'Archiveren',
  'observation.actDeeper': 'Diepere oorzaak',
  'observation.actMakeRoot': 'Grond maken',
  'observation.actVerify': 'Verifiëren',
  'observation.actSolution': 'Oplossing',
  'observation.actOrg': 'Org-oorzaak',
  'observation.actLocal': 'Lokale oorzaak',
  'observation.tipSeen': 'Leg vast dat dit opnieuw gezien is. Het telt een waarneming bij deze op; er wordt niets nieuws vastgelegd.',
  'observation.tipCause': 'Voeg de oorzaak toe die deze waarneming verklaart: een nieuwe, of een die al in {scope} is opgeschreven.',
  'observation.tipMerge': 'Samenvoegen met een andere waarneming die hetzelfde vastlegt. Beide geschiedenissen blijven bewaard.',
  'observation.tipArchive': 'Het gebeurt niet meer. De waarneming blijft in de geschiedenis en kan worden teruggehaald.',
  'observation.tipEdit': 'De titel, waar, wie, wanneer, de impact en de beschrijving bewerken.',
  'observation.tipEditCause': 'De titel en de beschrijving bewerken.',
  'observation.tipRead': 'Terug naar lezen. Wat je getypt hebt, blijft bewaard.',
  'observation.tipDelete': 'De waarneming verwijderen, en elke koppeling die een oorzaak ermee had. Het nummer wordt nooit opnieuw gebruikt. Archiveer haar liever als het alleen niet meer gebeurt.',
  'observation.tipDeleteCause': 'De oorzaak verwijderen, met elke koppeling van en naar haar.',
  'observation.tipDeeper': 'Vraag nog eens waarom: voeg de oorzaak achter deze oorzaak toe, nieuw of bestaand, in dezelfde scope.',
  'observation.tipRoot': 'Koppel de grondoorzaak waar deze keten op uitkomt, nieuw of bestaand, in dezelfde scope.',
  'observation.tipMakeRoot': 'Maak hier een grondoorzaak van: de keten houdt hier op, en oplossingen mogen haar aanpakken. {label} wordt {next}. Geweigerd zolang een oorzaak haar verklaart.',
  'observation.tipMakeCause': 'Maak hier weer een oorzaak van, zodat er een diepere oorzaak achter gekoppeld kan worden. {label} wordt {next}. Geweigerd zolang een oplossing haar aanpakt.',
  'observation.tipVerify': 'Markeer haar als geverifieerd zodra “Waarom we dat denken” en “Hoe te verifiëren” zeggen wat er gecontroleerd is, of zeg nu wat het bevestigde.',
  'observation.tipAssumed': 'Terug naar aangenomen: het bewijs houdt geen stand meer.',
  'observation.tipSolution': 'Stel een oplossing voor die deze grondoorzaak aanpakt.',
  'observation.tipOrg': 'Koppel een oorzaak van {scope} die deze lokale oorzaak verklaart. De koppeling staat op die oorzaak, in {scope}. Geweigerd op een grondoorzaak.',
  'observation.tipLocal': 'Koppel een oorzaak van een scope eronder die deze oorzaak verklaart. De koppeling staat op deze oorzaak.',
  'observation.tipRestore': 'Haal haar terug in de analyse.',
  'observation.tipOpenScope': 'De waarnemingen van {scope} openen, waar dit record thuishoort.',
  'observation.tipUnlink': 'Ontkoppelen: {from} verklaart {to} niet meer.',
  'observation.makeRootAsk': '{label} tot grondoorzaak maken? Ze wordt {next}. De keten houdt hier op: er kan niets achter gekoppeld worden, en oplossingen mogen haar aanpakken.',
  'observation.makeCauseAsk': '{label} weer tot oorzaak maken? Ze wordt {next}, en er kan een diepere oorzaak achter gekoppeld worden.',
  'observation.makeRootRefused': '{label} kan geen grondoorzaak worden zolang een oorzaak haar verklaart.',
  'observation.makeCauseRefused': '{label} kan niet terug naar oorzaak zolang een oplossing haar aanpakt.',
  'observation.orgRefused': '{label} is een grondoorzaak: niets verklaart haar. Maak er eerst weer een oorzaak van, in haar eigen scope, en koppel dan de oorzaak die erachter zit.',
  'observation.ok': 'OK',
  'solution.actExperiment': 'Experiment',
  'solution.actDrop': 'Laten vallen',
  'solution.tipAddress': 'Pak nog een grondoorzaak van deze scope aan. Aangeboden zolang ze een idee is of uitgewerkt.',
  'solution.tipExperiment': 'Plan een experiment dat test of deze oplossing helpt. Aangeboden zolang ze uitgewerkt is of getest wordt.',
  'solution.tipDrop': 'Laat haar vallen, met een reden. Ze blijft als overwogen alternatief, en kan worden teruggehaald.',
  'solution.tipDelete': 'De oplossing verwijderen, en haar uit elk experiment halen dat haar testte. Laat haar liever vallen om haar als overwogen alternatief te houden.',
  'solution.tipRestore': 'Haal haar terug naar de toestand waaruit ze viel.',
  'solution.tipEdit': 'De titel en de beschrijving bewerken.',
  'solution.tipUnaddress': 'Ontkoppelen: {from} pakt {to} niet meer aan.',
  'solution.tipStart': 'Vandaag beginnen.',
  'solution.tipReopen': 'Heropenen: het loopt weer, en de einddag wordt gewist.',
  'solution.tipToPlanned': 'Terug naar gepland: het is toch niet begonnen.',
  'solution.tipConfirmed': 'Het bevestigde de oplossing: zeg de uitkomst en de dag waarop het eindigde.',
  'solution.tipRefuted': 'Het weerlegde de oplossing: zeg de uitkomst. Een weerlegd experiment blijft, als bewijs.',
  'solution.tipInconclusive': 'Het besliste niets, in geen van beide richtingen: zeg de uitkomst.',
  'solution.tipExperimentEdit': 'De titel, de hypothese, de meting, waar, wie, wanneer en de uitkomst bewerken.',
  'solution.tipDeleteExperiment': 'Het experiment verwijderen. Het nummer wordt nooit opnieuw gebruikt.',

  // --- de formulieren (ADR-0032 §6) -------------------------------------------------------------
  'observation.formIntro': 'Een feit: wat er gezien is, waar, wanneer en door wie, in neutrale woorden. Verklaringen, schuld en oplossingen blijven erbuiten; het waarom staat in de oorzaken hieronder.',
  'observation.formScope': 'Scope',
  'observation.formScopeHere': '{name} (deze scope)',
  'observation.formScopeBelow': '{name} (lokaal)',
  'observation.formScopeHelp': 'Waar de waarneming thuishoort. Een scope eronder maakt haar daar lokaal, met haar oorzaken.',
  'observation.formScopeDropped': 'De koppelingen met oorzaken van de eerder gekozen scope zijn eraf gehaald: een oorzaak wordt in haar eigen scope gekoppeld.',
  'observation.formTitleExample': 'Wat er gezien is, in één zin. Bijv. De nachtelijke schadebatch loopt door tot in kantooruren',
  'observation.formWhereExample': 'Een plek, een scherm of een stap. Bijv. EDI-intake, het orderscherm, pickstation 3',
  'observation.formByExample': 'Wie het zag: een team, een rol of een persoon. Bijv. Vervoerdersbeheer, de nachtdienst',
  'observation.formDateField': 'Wanneer gezien',
  'observation.formDateExample': 'De dag waarop het voor het eerst gezien is. Bijv. 4 juni 2026',
  'observation.formImpactExample': 'Hoeveel pijn het doet. Bijv. Groot: klanten merken het',
  'observation.formTitleMissing': 'Zeg wat er gezien is, in één zin.',
  'observation.formWhereMissing': 'Zeg waar het gezien is.',
  'observation.formByMissing': 'Zeg wie het zag.',
  'observation.formDateMissing': 'Geef de dag waarop het voor het eerst gezien is.',
  'observation.formDateFuture': 'De dag kan niet in de toekomst liggen. Het is de dag waarop het voor het eerst gezien is.',
  'observation.formProblemsOne': '1 veld moet nog worden ingevuld.',
  'observation.formProblemsMany': '{count} velden moeten nog worden ingevuld.',
  'observation.formDescription': 'Beschrijving (optioneel)',
  'observation.formDescriptionExample': 'Markdown. Bijv. onder Wat we zagen: drie vervoerders tekenden in het voorjaar, en het eerste label kwam negen weken na elk contract.',
  'observation.formDescriptionMode': 'De beschrijving schrijven of bekijken',
  'observation.formEdit': 'Bewerken',
  'observation.formPreview': 'Voorbeeld',
  'observation.formNothingWritten': 'Nog niets geschreven.',
  'observation.formSeenBefore': 'Al eerder gezien?',
  'observation.formSeenAgainTip': 'Tel een waarneming bij {name} op in plaats van een nieuwe vast te leggen. Er wordt niets nieuws vastgelegd.',
  'observation.formWordingHint': '“{word}” klinkt als een oorzaak, een oplossing of schuld. Houd de titel bij wat er gezien is, en zet het waarom hieronder als oorzaak.',
  /** Woorden die in een titel klinken als een oorzaak, een oplossing of schuld, met `|` ertussen: een hint, nooit een weigering. */
  'observation.formHintWords': 'omdat|doordat|vanwege|veroorzaakt door|zou moeten|moet|moeten|oplossen|opgelost|repareren|fout van|schuld|nalatig|lui|slordig|onbekwaam',
  'observation.formCauses': 'Oorzaken',
  'observation.formCausesNote': 'optioneel · gemaakt bij het vastleggen',
  'observation.formNewCauseTip': 'Schrijf een nieuwe oorzaak voor deze waarneming. Ze wordt gemaakt bij het vastleggen.',
  'observation.formExistingCause': 'Bestaande oorzaak',
  'observation.formExistingCauseTip': 'Koppel een oorzaak die al in deze scope is opgeschreven. Alleen de koppeling wordt gemaakt bij het vastleggen.',
  'observation.formColCause': 'Oorzaak',
  'observation.formColKind': 'Soort',
  'observation.formColStrength': 'Sterkte',
  'observation.formColRemove': 'Eraf halen',
  'observation.formKindNew': 'Nieuw',
  'observation.formKindExisting': 'Bestaand',
  'observation.formKindRoot': 'Grond',
  'observation.formStrengthOf': 'Sterkte van {name}',
  'observation.formNoCauses': 'Nog geen oorzaak. Leg de waarneming nu vast en analyseer later, of voeg toe wat je al weet.',
  'observation.formRemoveRow': '{name} van de lijst halen',
  'observation.formRecord': 'Waarneming vastleggen',
  'observation.formRecordWith': 'Waarneming vastleggen met {what}',
  'observation.formNewCausesOne': '1 nieuwe oorzaak',
  'observation.formNewCausesMany': '{count} nieuwe oorzaken',
  'observation.formLinksOne': '1 koppeling',
  'observation.formLinksMany': '{count} koppelingen',
  'observation.formAnd': '{first} en {second}',
  'observation.causeTitleExample': 'Waarom het gebeurt, in één zin. Bijv. Elke EDI-mapping van een vervoerder wordt met de hand geschreven',
  'observation.causeTitleMissing': 'Zeg waarom het gebeurt, in één zin.',
  'observation.causeWhy': 'Waarom we dat denken (optioneel)',
  'observation.causeWhyExample': 'Bijv. Vervoerdersbeheer houdt een map met handgemaakte mappings bij',
  'observation.causeRoot': 'Het is een grondoorzaak: de keten houdt hier op',
  'observation.causeStrength': 'Sterkte',
  'observation.causeStrengthExample': 'Hoeveel ervan deze oorzaak verklaart.',
  'observation.causeAlike': 'Al opgeschreven?',
  'observation.causeUse': 'Deze gebruiken',
  'observation.causeAddToList': 'Aan de lijst toevoegen',
  'observation.causeFind': 'Zoek een oorzaak op nummer of woorden',
  'observation.causeAdd': 'Toevoegen',
  'observation.causeAdded': 'Toegevoegd',
  'observation.causeNoMatch': 'Geen oorzaak komt overeen.',
  'observation.causeBody': 'Tekst (optioneel)',
  'observation.causeBodyExample': 'Markdown. Bijv. onder Hoe te verifiëren: vergelijk de mappings van vorige maand met die van de vervoerder zelf.',
  'observation.causeLinks': 'Waar ze mee gekoppeld wordt',
  'observation.causeExplainsRow': 'Verklaart',
  'observation.causeBehind': 'Erachter',
  'observation.causeBehindAdd': 'Bestaande oorzaak erachter',
  'observation.causeBehindTip': 'Koppel een oorzaak die al is opgeschreven en deze nieuwe verklaart. De koppeling wordt met haar gemaakt.',
  'observation.existingIn': 'Bestaande oorzaak in {scope}',
  'observation.madeAs': 'Gemaakt in {scope} als {label}.',
  'observation.linkCauseTitle': 'Oorzaak van {name}',
  'observation.linkCauseIntro': 'Waarom gebeurt dit? Voeg een nieuwe oorzaak toe, of koppel er een die al in haar scope is opgeschreven.',
  'observation.linkDeeperTitle': 'Diepere oorzaak van {name}',
  'observation.linkDeeperIntro': 'Vraag nog eens waarom: wat zit er achter deze oorzaak?',
  'observation.linkRootTitle': 'Grondoorzaak van {name}',
  'observation.linkRootIntro': 'Waar houdt deze keten op? Bij een grondoorzaak stopt het waarom en kan een oplossing beginnen.',
  'observation.linkOrgTitle': 'Een oorzaak van {scope} voor {name}',
  'observation.linkOrgIntro': 'Welke oorzaak van {scope} verklaart deze oorzaak van {below}? De koppeling staat op de oorzaak van {scope}.',
  'observation.linkLocalTitle': 'Lokale oorzaak die {name} verklaart',
  'observation.linkLocalIntro': 'Welke oorzaak van een scope eronder verklaart deze oorzaak? Een lokale oorzaak wordt in haar eigen scope gemaakt; hier koppel je er een die bestaat. Een grondoorzaak eronder beëindigt haar keten en wordt niet aangeboden.',
  'observation.linkTabs': 'Een nieuwe oorzaak of een bestaande',
  'observation.linkTabNew': 'Nieuwe oorzaak',
  'observation.linkTabExisting': 'Bestaande oorzaak ({count})',
  'observation.linkAdd': 'Oorzaak toevoegen',
  'observation.linkNone': 'Hier is geen oorzaak om te koppelen.',
  'observation.linkPickMissing': 'Kies een oorzaak om te koppelen.',
  'observation.linkUseTip': 'Koppel deze oorzaak in plaats van een nieuwe te schrijven.',
  'observation.madeBelow': 'Gemaakt in {scope}. Het staat daar in de lijst Activiteit, en wordt daar ongedaan gemaakt.',
  'observation.belowReadOnly': 'Er is niets gemaakt in {scope}: die mag van hieruit niet gewijzigd worden.',
  'observation.belowRefused': 'Er is niets gemaakt in {scope}: haar eigen regels weigerden de wijziging.',
  'observation.belowNotMade': 'Er is niets gemaakt in {scope}.',
  'solution.formIntro': 'Wat een grondoorzaak zou wegnemen. Het begint als idee; de poorten vragen om de rest.',
  'solution.formTitleMissing': 'Zeg wat de oplossing is, in één zin.',
  'solution.formBody': 'Tekst (optioneel)',
  'solution.formBodyExample': 'Markdown. Bijv. onder Het idee: één dienst berekent de schatting, en elk kanaal leest die.',
  'solution.formAddresses': 'Grondoorzaken die ze aanpakt',
  'solution.formAddressesNote': 'gemaakt bij het voorstellen',
  'solution.formAddRootTip': 'Voeg een grondoorzaak van deze scope toe die ze aanpakt. Een oplossing pakt alleen grondoorzaken aan.',
  'solution.formNoRoots': 'Nog geen grondoorzaak. Stel haar nu voor en koppel er later een, of voeg de grondoorzaken toe die ze wegneemt.',
  'solution.formPropose': 'Oplossing voorstellen',
  'solution.formProposeOne': 'Oplossing voorstellen voor 1 grondoorzaak',
  'solution.formProposeMany': 'Oplossing voorstellen voor {count} grondoorzaken',
  'solution.experimentTitleExample': 'Wat er geprobeerd wordt, in een paar woorden. Bijv. Twee weken aan één balie',
  'solution.experimentTitleMissing': 'Zeg wat het experiment is.',
}
