// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** Nederlands: the same keys as `en.ts`, which is the schema. */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'observation.title': 'Waarnemingen',
  'observation.close': 'Waarnemingen sluiten',
  'observation.tabRegister': 'Register',
  'observation.tabAnalysis': 'Analyse',
  'observation.new': 'Nieuwe waarneming',
  'observation.newTitleField': 'Titel',
  'observation.newTitleHelp': 'Zeg wat er gezien is, in één zin: “De nachtelijke schadebatch loopt door tot in kantooruren”.',
  'observation.newWhereField': 'Waar het gezien is',
  'observation.newImpactField': 'Impact',
  'observation.newShareField': 'Delen met de scopes erboven',
  'observation.newByField': 'Waargenomen door',
  'observation.create': 'Vastleggen',
  'observation.newCause': 'Nieuwe oorzaak',
  'observation.newCauseHelp': 'Zeg wat erachter zit: “Het batchvenster is bemeten op de volumes van 2019”.',
  'observation.createCause': 'Toevoegen',
  'observation.searchPlaceholder': 'Zoek in waarnemingen en oorzaken',
  'observation.searchField': 'Waarnemingen zoeken',
  'observation.listEmpty': 'Hier is nog niets waargenomen.',
  'observation.searchEmpty': 'Niets komt overeen met “{query}”.',
  'observation.noneSelected': 'Kies een waarneming of een oorzaak, of leg er een vast.',
  'observation.colNumber': 'Nr.',
  'observation.colTitle': 'Titel',
  'observation.colDate': 'Datum',
  'observation.colWhere': 'Waar',
  'observation.colScope': 'Scope',
  'observation.colImpact': 'Impact',
  'observation.colSeen': 'Gezien',
  'observation.colCauses': 'Geanalyseerd naar',
  'observation.scopeHere': 'Deze scope',
  'observation.fromBelow': 'Gedeeld vanuit {scope}',
  'observation.sharedMark': 'Gedeeld',
  'observation.showMerged': 'Samengevoegde tonen',
  'observation.showArchived': 'Gearchiveerde tonen',
  'observation.archivedMark': 'Gearchiveerd',
  'observation.notAnalysed': 'nog niet',
  'observation.impactMinor': 'Klein',
  'observation.impactMajor': 'Groot',
  'observation.impactCritical': 'Kritiek',
  'observation.seenTimes': '{count}×',
  'observation.read': 'Lezen',
  'observation.edit': 'Bewerken',
  'observation.source': 'Brontekst van de waarneming',
  'observation.titleField': 'Titel',
  'observation.whereField': 'Waar gezien',
  'observation.byField': 'Waargenomen door',
  'observation.dateField': 'Datum gezien',
  'observation.impactField': 'Impact',
  'observation.seenAgain': 'Opnieuw gezien',
  'observation.share': 'Delen met de scopes erboven',
  'observation.unshare': 'Niet meer delen',
  'observation.shared': 'Gedeeld met de scopes erboven',
  'observation.local': 'Lokaal in deze scope',
  'observation.shareHelp': 'Gedeeld leest elke scope boven deze hem, kan hem aan een eigen oorzaak koppelen en kan hem samenvoegen met een eigen waarneming. Lokaal is de standaard.',
  'observation.merge': 'Samenvoegen met…',
  'observation.mergeTitle': '{name} samenvoegen met een andere waarneming',
  'observation.mergeBody': 'De keren dat het gezien is en de oorzaken gaan over naar de waarneming die je kiest, en beide records zeggen dat met de datum van vandaag. Het samengevoegde record blijft, als geschiedenis.',
  'observation.mergePick': 'De waarneming waar het dezelfde van is',
  'observation.mergeConfirm': 'Samenvoegen',
  'observation.mergedInto': 'Samengevoegd met {name}',
  'observation.mergedAbove': 'Samengevoegd met {name} in {scope} op {date}',
  'observation.archive': 'Archiveren…',
  'observation.archiveTitle': '{name} archiveren?',
  'observation.archiveBody': 'Opgelost, aangepakt of niet meer relevant: het record blijft, als geschiedenis, en verdwijnt uit de analyse. Terughalen brengt het terug.',
  'observation.archiveNote': 'Waarom (optioneel)',
  'observation.archiveConfirm': 'Archiveren',
  'observation.restore': 'Terughalen',
  'observation.archivedOn': 'Gearchiveerd op {date}',
  'observation.history': 'Geschiedenis',
  'observation.eventRecorded': 'Vastgelegd',
  'observation.eventSeen': 'Opnieuw gezien',
  'observation.eventShared': 'Gedeeld met de scopes erboven',
  'observation.eventUnshared': 'Delen gestopt',
  'observation.eventArchived': 'Gearchiveerd',
  'observation.eventRestored': 'Teruggehaald',
  'observation.eventAbsorbed': '{name} opgenomen ({count} keer gezien)',
  'observation.eventMerged': 'Samengevoegd met {name}',
  'observation.fromScope': 'Deze waarneming hoort bij {scope}. Hier wordt ze gelezen en gekoppeld; daar wordt ze gewijzigd.',
  'observation.openScope': '{scope} openen',
  'observation.delete': 'Verwijderen',
  'observation.deleteTitle': '{name} verwijderen?',
  'observation.deleteBody': 'Het record verdwijnt, met elke koppeling die een oorzaak ernaar had. Het nummer wordt nooit hergebruikt.',
  'observation.causes': 'Oorzaken',
  'observation.cause': 'Oorzaak',
  'observation.rootCause': 'Grondoorzaak',
  'observation.rootCauses': 'Grondoorzaken',
  'observation.causeSource': 'Brontekst van de oorzaak',
  'observation.stateAssumed': 'Aangenomen',
  'observation.stateVerified': 'Geverifieerd',
  'observation.verify': 'Markeren als geverifieerd',
  'observation.unverify': 'Terug naar aangenomen',
  'observation.explains': 'Verklaart',
  'observation.explainedBy': 'Verklaard door',
  'observation.noLinks': 'Nog niets',
  'observation.link': 'Koppelen aan een oorzaak…',
  'observation.linkDeeper': 'Koppelen aan een diepere oorzaak…',
  'observation.linkTitle': 'Wat zit er achter {name}?',
  'observation.linkPick': 'Oorzaak',
  'observation.linkNew': 'Een nieuwe oorzaak…',
  'observation.linkNewTitle': 'Benoem de oorzaak',
  'observation.linkStrength': 'Verband',
  'observation.linkConfirm': 'Koppelen',
  'observation.unlink': 'Ontkoppelen',
  'observation.strengthStrong': 'Sterk',
  'observation.strengthNormal': 'Normaal',
  'observation.strengthWeak': 'Zwak',
  'observation.deleteCauseTitle': '{name} verwijderen?',
  'observation.deleteCauseBody': 'De koppelingen ervan en ernaartoe gaan mee.',
  'observation.rootNote': 'Achter deze oorzaak is nog niets gevonden. Koppel hem aan een diepere en hij is geen grondoorzaak meer.',
  'observation.tplSaw': 'Wat we zagen',
  'observation.tplEvidence': 'Bewijs',
  'observation.tplThoughts': 'Eerste gedachten',
  'observation.tplWhy': 'Waarom we dat denken',
  'observation.tplVerify': 'Hoe te verifiëren',
  'observation.laneObservations': 'Waarnemingen',
  'observation.laneCauses': 'Oorzaken',
  'observation.laneRoots': 'Grondoorzaken',
  'observation.legendImpact': 'Grootte: impact',
  'observation.legendSeen': 'Tint: keren gezien',
  'observation.legendAssumed': 'Gestreept: aangenomen',
  'observation.legendVerified': 'Doorgetrokken: geverifieerd',
  'observation.legendRoot': 'Grondoorzaak',
  'observation.legendStrength': 'Sterk · normaal · zwak',
  'observation.phaseObserved': 'waargenomen',
  'observation.phaseAnalysed': 'geanalyseerd',
  'observation.phaseAssumed': 'aangenomen',
  'observation.phaseVerified': 'geverifieerd',
  'observation.phaseRoots': 'grondoorzaken',
  'observation.toAnalyse': 'Nog niet geanalyseerd',
  'observation.graphEmpty': 'Nog niets te tekenen. Leg een waarneming vast en koppel die aan een oorzaak.',
  'observation.resizeReader': 'Leespaneel van grootte veranderen',


  // --- solutions (ADR-0026) -----------------------------------------------------------------
  'solution.tab': 'Oplossingen',
  'solution.new': 'Nieuwe oplossing',
  'solution.newTitleField': 'Titel',
  'solution.newTitleHelp': 'Zeg wat de oorzaak wegneemt: “Eén levertijdschatting voor elk kanaal”.',
  'solution.newCauseField': 'Voor de oorzaak',
  'solution.noCause': 'Nog geen oorzaak',
  'solution.create': 'Voorstellen',
  'solution.laneDirections': 'Richtingen',
  'solution.laneExperiments': 'Experimenten',
  'solution.laneStructural': 'Structureel',
  'solution.wholeChain': 'Hele keten',
  'solution.showDropped': 'Laten vallen tonen',
  'solution.coverage': '{count} van {total} grondoorzaken hebben een levende oplossing',
  'solution.graphEmpty': 'Nog niets te tekenen. Stel een oplossing voor bij een grondoorzaak.',
  'solution.solutions': 'Oplossingen',
  'solution.experiments': 'Experimenten',
  'solution.legendWidth': 'Breedte: verwachte baat',
  'solution.legendFill': 'Vulling: hoe ver het is',
  'solution.legendAddresses': 'Lijn: pakt een oorzaak aan',
  'solution.legendTests': 'Gestreept: test',
  'solution.legendProves': 'Doorgetrokken: bevestigde het',
  'solution.legendTrail': 'Vervaagd: de richting die het was',
  'solution.trail': 'als richting',
  'solution.flagNoSolution': 'Een grondoorzaak waar nog niemand aan werkt',
  'solution.flag': 'Vraagt aandacht',
  // --- phases, sizes, outcomes
  'solution.phaseIdea': 'Idee',
  'solution.phaseShaped': 'Uitgewerkt',
  'solution.phaseTesting': 'Wordt getest',
  'solution.phaseProven': 'Bewezen',
  'solution.phaseAdopted': 'Aangenomen',
  'solution.phaseImplemented': 'Ingevoerd',
  'solution.phaseDropped': 'Laten vallen',
  'solution.sizeSmall': 'Klein',
  'solution.sizeMedium': 'Middel',
  'solution.sizeLarge': 'Groot',
  'solution.outcomePlanned': 'Gepland',
  'solution.outcomeRunning': 'Loopt',
  'solution.outcomeConfirmed': 'Bevestigd',
  'solution.outcomeRefuted': 'Weerlegd',
  'solution.outcomeInconclusive': 'Onbeslist',
  // --- one solution
  'solution.source': 'Bron van de oplossing',
  'solution.titleField': 'Titel',
  'solution.benefitField': 'Verwachte baat',
  'solution.costField': 'Grove kosten',
  'solution.unset': 'Niet gezegd',
  'solution.addresses': 'Pakt aan',
  'solution.addressCause': 'Een oorzaak aanpakken…',
  'solution.addressTitle': 'Welke oorzaak pakt {name} aan?',
  'solution.addressPick': 'Oorzaak',
  'solution.addressConfirm': 'Aanpakken',
  'solution.gateTitle': 'Om door te gaan naar {state}',
  'solution.moveOn': 'Naar {state}',
  'solution.moveBack': 'Terug naar {state}',
  'solution.toGo': 'nog {count}',
  'solution.gateAddresses': 'Pakt minstens één oorzaak aan',
  'solution.gateBenefit': 'Verwachte baat',
  'solution.gateCost': 'Grove kosten',
  'solution.gateValidatedWith': 'Getoetst bij iemand die ermee moet leven',
  'solution.gateTriedBefore': 'Is dit eerder geprobeerd?',
  'solution.gateWhyNow': 'Waarom het nu werkt, als het toen niet werkte',
  'solution.gateExperimentPlanned': 'Een experiment test het: gepland, bezig of bevestigd',
  'solution.gateExperimentConfirmed': 'Een experiment bevestigde het, of het is met reden overgeslagen',
  'solution.gateDecisionAccepted': 'Een besluit, aangenomen',
  'solution.validatedWith': 'Getoetst bij',
  'solution.validatedField': 'Een naam, een rol of een team',
  'solution.add': 'Toevoegen',
  'solution.remove': 'Verwijderen',
  'solution.attempts': 'Eerder geprobeerd',
  'solution.noneKnown': 'Niets bekend',
  'solution.notAnswered': 'Niet beantwoord',
  'solution.attemptAdd': 'Eerdere poging toevoegen',
  'solution.attemptWhen': 'Wanneer',
  'solution.attemptWhat': 'Wat is geprobeerd',
  'solution.attemptWhy': 'Waarom het niet beklijfde',
  'solution.whyNow': 'Waarom nu',
  'solution.whyNowField': 'Wat is er deze keer anders',
  'solution.save': 'Opslaan',
  'solution.waive': 'Overslaan',
  'solution.waiveField': 'Waarom geen experiment nodig is',
  'solution.waived': 'Experiment overgeslagen: {reason}',
  'solution.planExperiment': 'Een experiment plannen…',
  'solution.proposeDecision': 'Het besluit voorstellen',
  'solution.decision': 'Besluit',
  'solution.decisionStatus': '{label} is {status}',
  'solution.open': 'Openen',
  'solution.plan': 'Plan',
  'solution.startPlan': 'Een plan starten',
  'solution.noPlan': 'Nog geen plan',
  'solution.didItWork': 'Heeft het gewerkt?',
  'solution.didItWorkHelp': 'De waarnemingen onder wat het aanpakt. Die zouden niet meer gezien moeten worden.',
  'solution.seenSince': 'Opnieuw gezien op {date}',
  'solution.heldSince': 'Niet meer gezien sinds {date}',
  'solution.alternatives': 'Alternatieven voor dezelfde oorzaken',
  'solution.none': 'Geen',
  'solution.drop': 'Laten vallen…',
  'solution.dropTitle': '{name} laten vallen?',
  'solution.dropBody': 'Het blijft in de lijst als alternatief dat is overwogen. Zeg waarom, zodat de volgende het niet blind opnieuw probeert.',
  'solution.dropNote': 'Waarom',
  'solution.dropConfirm': 'Laten vallen',
  'solution.restore': 'Terugzetten',
  'solution.droppedNote': 'Laten vallen: {note}',
  'solution.questionWorksAround': 'Werkt eromheen, niet erdoorheen: het pakt geen grondoorzaak aan. Prima als noodoplossing; zeg dat, of pak ook de grondoorzaak aan.',
  'solution.questionAddsOnly': 'Voegt toe zonder op te ruimen: het plan introduceert maar faseert niets uit. Wat maakt dit overbodig?',
  'solution.questionAdoptedUnplanned': 'Besloten, niet gepland: nog geen plan bouwt het.',
  'solution.findingSeenAgain': 'Opnieuw gezien sinds de invoering: {names}. Heeft het gewerkt?',
  'solution.eventProposed': 'Voorgesteld',
  'solution.eventMoved': 'Naar {state}',
  'solution.eventWaived': 'Experiment overgeslagen',
  'solution.eventLinked': '{name} gekoppeld',
  'solution.eventDropped': 'Laten vallen',
  'solution.eventRestored': 'Teruggezet',
  'solution.deleteTitle': '{name} verwijderen?',
  'solution.deleteBody': 'Het record verdwijnt, en uit elk experiment dat het testte. Het nummer wordt nooit hergebruikt.',
  'solution.deleteExperimentBody': 'Het record verdwijnt. Het nummer wordt nooit hergebruikt.',
  'solution.forCause': 'Oplossingen hiervoor',
  'solution.proposeForCause': 'Een oplossing voorstellen…',
  // --- one experiment
  'solution.experimentSource': 'Bron van het experiment',
  'solution.tests': 'Test',
  'solution.hypothesis': 'Hypothese',
  'solution.hypothesisHelp': 'Als we …, dan … met …',
  'solution.measure': 'Hoe het gemeten wordt',
  'solution.whereField': 'Waar',
  'solution.byField': 'Door',
  'solution.fromField': 'Van',
  'solution.toField': 'Tot',
  'solution.result': 'Resultaat',
  'solution.outcome': 'Uitkomst',
  'solution.newExperiment': 'Een experiment plannen',
  'solution.createExperiment': 'Plannen',
  'solution.refutedNote': 'Een weerlegd experiment blijft staan. Het is het bewijs waar de volgende om vraagt.',
  // --- the templates
  'solution.tplIdea': 'Het idee',
  'solution.tplCosts': 'Kosten en baten',
  'solution.tplWhyHere': 'Waarom dit domein',
  'solution.tplAlternatives': 'Alternatieven',
  'solution.tplRisks': 'Risico\'s',
  'solution.tplSetup': 'Hoe het is opgezet',
  'solution.tplLearned': 'Wat we leerden',
  'solution.decisionAddresses': 'Het pakt aan:',
  'solution.decisionAlternatives': 'Overwogen voor dezelfde oorzaken:',
  'solution.decisionDropped': 'laten vallen: {note}',
}
