/**
 * German, for the canvas and everything docked to it — menus, inspectors, the toolbar.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a German screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'kind.domainGroup': 'Domänengruppe',

  'newName.actor': 'Neuer Akteur',
  'newName.step': 'Neuer Schritt',
  'newName.function': 'Neue Funktion',
  'newName.process': 'Neuer Prozess',
  'newName.application': 'Neue Anwendung',
  'newName.component': 'Neue Komponente',
  'newName.domainGroup': 'Neue Gruppe',

  'lifecycle.planned': 'Geplant',
  'lifecycle.live': 'Aktiv',
  'lifecycle.retiring': 'Auslaufend',
  'lifecycle.retired': 'Abgeschaltet',
  'lifecycleNote.planned': 'kommt noch, noch nicht aktiv',
  'lifecycleNote.live': 'in Betrieb — ohne Abzeichen dargestellt',
  'lifecycleNote.retiring': 'wird abgebaut',
  'lifecycleNote.retired': 'außer Dienst, abgeblendet',

  'aspect.managed': 'Verwaltet',
  'aspect.partial': 'Teilweise',
  'aspect.atRisk': 'Gefährdet',
  'aspect.none': 'Keiner',

  'side.auto': 'Automatisch',
  'side.top': 'Oben',
  'side.right': 'Rechts',
  'side.bottom': 'Unten',
  'side.left': 'Links',

  'shape.smooth': 'Weich',
  'shape.orthogonal': 'Rechtwinklig',
  'shape.straight': 'Gerade',
  'shape.curved': 'Gebogen',

  'align.left': 'Links',
  'align.centerX': 'Mitte',
  'align.right': 'Rechts',
  'align.top': 'Oben',
  'align.centerY': 'Mitte',
  'align.bottom': 'Unten',
  'zone.resizeBand': 'Größe des Bands {name} ändern',
  'zone.resizeCanvas': 'Größe der Zeichenfläche {name} ändern',

  'menu.openContainer': 'Container-Diagramm öffnen',
  'menu.createContainer': 'Container-Diagramm erstellen',
  'menu.rename': 'Umbenennen',
  'menu.startConnection': 'Verbindung beginnen zu…',
  'menu.icon': 'Symbol…',
  'menu.lifecycle': 'Lebenszyklus',
  'menu.moveToZone': 'In Zone verschieben',
  'menu.changeKind': 'Art ändern',
  'menu.domainGroup': 'Domänengruppe',
  'menu.duplicate': 'Duplizieren',
  'menu.copy': 'Kopieren',
  'menu.cut': 'Ausschneiden',
  'menu.removeFromDiagram': 'Aus dem Diagramm entfernen',
  'menu.deleteFromModel': 'Aus dem Modell löschen…',
  'menu.boundaryApplication': 'Diese Anwendung ist die Grenze dieses Diagramms',
  'menu.addBend': 'Hier einen Knickpunkt einfügen',
  'menu.removeBend': 'Knickpunkt entfernen',
  'menu.removeAllBends': 'Alle Knickpunkte entfernen',
  'menu.noBendPoints': 'Diese Linie hat keine Knickpunkte',
  'menu.pinRoute': 'Route fixieren',
  'menu.unpinRoute': 'Route lösen',
  'menu.resetRoute': 'Zurück zur automatischen Route',
  'menu.layoutBusy': 'Eine Layout-Aktion läuft gerade',
  'menu.attachAt': 'Anheften an',
  'menu.attachSource': 'Quelle',
  'menu.attachTarget': 'Ziel',
  'menu.lineShape': 'Linienform',
  'menu.direction': 'Richtung',
  'menu.oneWay': 'Einseitig',
  'menu.twoWay': 'Beidseitig',
  'menu.reverse': 'Umkehren',
  'menu.editLabel': 'Beschriftung bearbeiten',
  'menu.resetLabelPosition': 'Beschriftungsposition zurücksetzen',
  'menu.labelAutomatic': 'Die Beschriftung steht an ihrer automatischen Position',
  'menu.deleteConnection': 'Verbindung löschen',
  'menu.pasteHere': 'Hier einfügen',
  'menu.nothingToPaste': 'Nichts zum Einfügen',
  'menu.addHere': 'Hier hinzufügen',
  'menu.addDomainGroupHere': 'Hier eine Domänengruppe hinzufügen',
  'menu.selectAll': 'Alles auswählen',
  'menu.tidy': 'Layout aufräumen',
  'menu.routeConnections': 'Verbindungen routen',
  'menu.routeConnectionsAll': 'Alles neu routen (Fixierungen ignorieren)',
  'menu.fitView': 'Einpassen',
  'menu.showGrid': 'Raster anzeigen',
  'menu.snapToGrid': 'Am Raster ausrichten',
  'menu.align': 'Ausrichten',
  'menu.distribute': 'Verteilen',
  'menu.distributeHorizontally': 'Horizontal',
  'menu.distributeVertically': 'Vertikal',
  'menu.needThreeElements': 'Wählen Sie mindestens drei Elemente aus',
  'menu.groupIntoDomainGroup': 'In neue Domänengruppe zusammenfassen',
  'menu.needLandscapeElements': 'Wählen Sie Elemente auf der Anwendungslandschaft aus',
  'menu.delete': 'Löschen',
  'menu.tidyGroup': 'Diese Gruppe aufräumen',
  'menu.groupColor': 'Gruppenfarbe…',
  'menu.selectMembers': 'Mitglieder auswählen',
  'menu.removeGroup': 'Gruppe entfernen',
  'menu.renameDiagram': 'Diagramm umbenennen…',
  'menu.diagramSettings': 'Diagrammeinstellungen…',
  'menu.duplicateDiagram': 'Diagramm duplizieren',
  'menu.duplicateDiagramAsOf': 'Duplizieren zum Stand…',
  'menu.deleteDiagram': 'Diagramm löschen…',
  'menu.lastLandscape': 'Die letzte Landschaft kann nicht gelöscht werden',
  'menu.nodeLabel': 'Elementmenü',
  'menu.edgeLabel': 'Verbindungsmenü',
  'menu.paneLabel': 'Zeichenflächenmenü',
  'menu.groupLabel': 'Domänengruppenmenü',
  'menu.selectionLabel': 'Auswahlmenü',
  'menu.tabLabel': 'Diagrammmenü',
  'menu.contextLabel': 'Kontextmenü',
  'menu.shortcutAria': 'Tastenkürzel {keys}',

  'palette.aside': 'Elementpalette',
  'palette.addToCanvas': 'Zur Zeichenfläche hinzufügen',
  'palette.expand': 'Palette ausklappen',
  'palette.collapse': 'Palette einklappen',
  'palette.place': 'Platzieren',
  'palette.add': '{name} hinzufügen',
  'palette.openOptions': 'Optionen für {name} öffnen',
  'palette.nameField': 'Name für {name}',
  'palette.logo': 'Logo',
  'palette.colour': 'Farbe',
  'palette.groupColour': 'Farbe der Domänengruppe',
  'palette.resize': 'Breite der Palette anpassen',
  'palette.search': 'Palette durchsuchen',
  'palette.searchPlaceholder': 'Suchen…',
  'palette.noMatches': 'Nichts passt zu „{query}“',
  'palette.section.systems': 'Anwendungen & Komponenten',
  'palette.section.people': 'Personen & Kontext',
  'paletteDescription.application': 'Ein System, das die Organisation betreibt oder bezieht',
  'paletteDescription.component': 'Ein Teil innerhalb einer Anwendung',
  'paletteDescription.actor': 'Eine Person oder Rolle, die die Landschaft nutzt',
  'paletteDescription.domainGroup': 'Ein beschrifteter Bereich, der die Landschaft gruppiert',

  'toolbar.newDiagram': 'Neues Layer-7-Diagramm',
  'toolbar.newLandscape': 'Landschaft',
  'toolbar.newSheet': 'Geschäftsarchitektur',
  'toolbar.newMap': 'Unternehmenskarte',
  'toolbar.readOnly': 'Schreibgeschützt',
  'toolbar.undo': 'Rückgängig',
  'toolbar.undoTip': 'Rückgängig (⌘Z)',
  'toolbar.redo': 'Wiederholen',
  'toolbar.redoTip': 'Wiederholen (⌘⇧Z)',
  'toolbar.tidy': 'Layout aufräumen',
  'toolbar.tidyTip': 'Layout aufräumen (ELK)',
  'toolbar.cancelTidy': 'Aufräumen abbrechen',
  'toolbar.tidySettings': 'Einstellungen zum Aufräumen',
  'toolbar.routeOnly': 'Nur Verbindungen routen',
  'toolbar.routeOnlyTip': 'Nur Verbindungen routen (Elemente bleiben stehen)',
  'toolbar.autoRoute': 'Verbindungen automatisch routen',
  'toolbar.autoRouteOn':
    'Automatisch routen: an — Linien folgen, wenn Sie ein Element verschieben',
  'toolbar.autoRouteOff': 'Automatisch routen: aus',
  'toolbar.fitView': 'Einpassen',
  'toolbar.exportPng': 'PNG exportieren',
  'toolbar.exportingPng': 'PNG wird exportiert…',
  'export.dialogTitle': 'PNG exportieren',
  'export.theme': 'Farbschema',
  'export.themeLight': 'Hell',
  'export.themeDark': 'Dunkel',
  'export.labels': 'Linienbeschriftungen',
  'export.labelsHelp': 'Jede Beschriftung im Bild, nicht nur die unter dem Zeiger.',
  'export.titleBlock': 'Titelblock',
  'export.titleBlockHelp': 'Kunde, Autor und Datum am unteren Rand.',
  'export.legend': 'Legende',
  'export.legendHelp': 'Was die Abzeichenfarben bedeuten, unter dem Titelblock.',
  'export.lifecycle': 'LEBENSZYKLUS',
  'export.preview': 'Vorschau des Exports',
  'export.previewBusy': 'Vorschau wird gezeichnet…',
  'export.size': '{width} × {height} Pixel, etwa {megapixels} Megapixel.',
  'export.largeBody':
    'Das ist ein großes Bild. Das Zeichnen kann eine Weile dauern, und das Fenster reagiert so lange nicht.',
  'export.confirm': 'Exportieren',
  'export.largeConfirm': 'Trotzdem exportieren',
  'toolbar.lifecycleBadges': 'Lebenszyklus-Abzeichen ein- oder ausblenden',
  'toolbar.asOf': 'Zeigt',
  'toolbar.asOfToday': 'Heute',
  'toolbar.asOfSet': 'Dieses Board zeigt die Landschaft, wie sie am {date} steht.',
  'toolbar.asOfHelp': 'Dieses Board zeichnen, wie die Landschaft an einem gewählten Tag stand oder stehen wird.',
  'toolbar.asOfClear': 'Heute zeigen',
  'toolbar.shortcuts': 'Tastenkürzel',
  'toolbar.search': 'Element suchen',
  'toolbar.searchTip': 'Ein Element suchen (⌘F)',
  'toolbar.minimap': 'Übersichtskarte ein- oder ausblenden',
  'toolbar.minimapOn': 'Übersichtskarte: an',
  'toolbar.minimapOff': 'Übersichtskarte: aus',
  'toolbar.edgeLabels': 'Linienbeschriftungen ein- oder ausblenden',
  'toolbar.edgeLabelsOn': 'Linienbeschriftungen: immer',
  'toolbar.edgeLabelsOff': 'Linienbeschriftungen: nur beim Zeigen',
  'toolbar.languageTip': 'Sprache — {name}',
  'toolbar.containerDiagrams': 'Container-Diagramme auf dieser Landschaft',
  'toolbar.containerDiagramsOf': 'Container-Diagramme von {name}',
  'toolbar.diagramSettings': 'Diagrammeinstellungen, einschließlich der Reifegradspalten',
  'toolbar.diagramSettingsOf': 'Einstellungen von {name}',
  'toolbar.containerView': 'Container-Ansicht',
  'toolbar.backTo': 'Zurück zu {name}',
  'toolbar.backToLandscape': 'Zurück zur Landschaft',

  'canvas.connectHint': 'Klicken Sie ein Zielelement an — Esc bricht ab',
  'canvas.gridOn': 'Raster: an',
  'canvas.gridOff': 'Raster: aus',
  'canvas.gridToggle': 'Raster ein- oder ausblenden',
  'canvas.snapOn': 'Am Raster ausrichten: an',
  'canvas.snapOff': 'Am Raster ausrichten: aus',
  'canvas.snapToggle': 'Am Raster ausrichten ein- oder ausschalten',
  'canvas.alignLeft': 'Links ausrichten',
  'canvas.alignCenterX': 'Horizontal zentrieren',
  'canvas.alignRight': 'Rechts ausrichten',
  'canvas.alignTop': 'Oben ausrichten',
  'canvas.alignCenterY': 'Vertikal zentrieren',
  'canvas.alignBottom': 'Unten ausrichten',
  'canvas.distributeHorizontally': 'Horizontal verteilen',
  'canvas.distributeVertically': 'Vertikal verteilen',
  'canvas.groupName': 'Name der Domänengruppe',
  'canvas.groupNamed': 'Domänengruppe {name}',
  'canvas.resizeGroup': 'Größe der Domänengruppe {name} ändern',
  'canvas.groupColour': 'Gruppenfarbe',
  'canvas.minimap': 'Übersichtskarte',
  'node.actorFigure': 'Akteurfigur',
  'node.external': 'EXTERN',
  'node.hasContainer': 'Hat ein Container-Diagramm — Doppelklick zum Öffnen',
  'node.lifecycleAria': 'Lebenszyklus: {name}',
  'edge.labelPlaceholder': 'Beschreibung der Schnittstelle…',

  'inspector.aside': 'Inspektor',
  'inspector.expand': 'Inspektor ausklappen',
  'inspector.collapse': 'Inspektor einklappen',
  'inspector.resize': 'Breite des Inspektors anpassen',
  'inspector.empty':
    'Wählen Sie ein Element oder eine Verbindung aus, um die Eigenschaften zu bearbeiten. Doppelklicken Sie eine Anwendung, um ihr Container-Diagramm zu öffnen.',
  'inspector.aspectBadges': 'ASPEKT-ABZEICHEN',
  'inspector.selected': '{count} ausgewählt',
  'inspector.elementsOne': '{count} Element',
  'inspector.elementsOther': '{count} Elemente',
  'inspector.connectionsOne': '{count} Verbindung',
  'inspector.connectionsOther': '{count} Verbindungen',
  'inspector.groupsOne': '{count} Domänengruppe',
  'inspector.groupsOther': '{count} Domänengruppen',
  'inspector.multiHint':
    'Ziehen Sie ein ausgewähltes Element, um alle gemeinsam zu verschieben. Umschalt-Klick fügt hinzu oder entfernt; Escape hebt die Auswahl auf.',
  'inspector.bulkTitle': 'AUF ALLE ANWENDEN',
  'inspector.bulkLifecycle': 'Lebenszyklus',
  'inspector.bulkColour': 'Akzentfarbe',
  'inspector.bulkColourAria': 'Akzentfarbe für die Auswahl',
  'inspector.bulkIcon': 'Symbol',
  'inspector.bulkDomainGroup': 'Domänengruppe',
  'inspector.bulkNoChange': 'Unverändert lassen',
  'inspector.bulkNote': 'Jede Änderung ist ein Rückgängig-Schritt über die ganze Auswahl.',

  'field.name': 'Name',
  'field.category': 'Kategorie',
  'field.vendor': 'Anbieter',
  'field.technology': 'Technologie',
  'field.lifecycle': 'Lebenszyklus',
  'field.date.live': 'Aktiv ab',
  'field.date.retiring': 'Auslaufend ab',
  'field.date.retired': 'Abgeschaltet am',
  'field.successor': 'Ersetzt durch',
  'field.owner': 'Verantwortlicher',
  'field.outside': 'Au\u00dferhalb der Organisation',
  'field.party': 'Geh\u00f6rt zu',
  'field.partyNone': 'Nicht angegeben',
  'record.title': 'Stammdaten',
  'record.open': 'Details',
  'record.empty': 'Noch keine Stammdaten',
  'record.outsideOf': 'Extern \u00b7 {name}',
  'field.replace': 'Ersetzen…',
  'edge.replaces': 'ersetzt',
  'field.validFrom': 'Linie gültig ab',
  'field.validUntil': 'Linie gültig bis',
  'field.managed': 'Verwaltet',
  'field.domainGroup': 'Domänengruppe',
  'field.domainGroupPlaceholder': 'z. B. Handel',
  'field.accentColour': 'Akzentfarbe',
  'field.shape': 'Form',
  'field.icon': 'Symbol',
  'field.iconSize': 'Symbolgröße',
  'field.iconFirst': 'Wählen Sie zuerst ein Symbol',
  'field.placement': 'Platzierung',
  'field.zone': 'Zone: {name}',
  'field.note': 'Notiz',
  'field.notePlaceholder': 'z. B. AKS, GitHub Actions',
  'field.noteAria': 'Notiz zu {name}',
  'field.notSet': 'Nicht gesetzt',
  'field.label': 'Beschriftung',
  'field.labelPlaceholder': 'z. B. Sendet Aufträge',
  'field.labelHelp': 'Zeilenumbrüche brechen die Beschriftung im Diagramm um; das Protokoll steht darunter',
  'field.protocol': 'Protokoll',
  'field.protocolPlaceholder': 'z. B. EDI, Kafka, REST',
  'field.direction': 'Richtung',
  'field.directionHelp': 'Legt die Standard-Pfeilspitzen fest; je Ende unter Darstellung übersteuerbar',
  'field.oneWay': 'Einseitig →',
  'field.bidirectional': 'Beidseitig ↔',
  'field.colour': 'Farbe',
  'field.edgeColour': 'Linienfarbe',
  'field.lineStyle': 'Linienstil',
  'field.routing': 'Leitungsführung',
  'field.routingHelp': 'Manuelle Wegpunkte gehen, wenn vorhanden, hierüber',
  'field.source': 'Quelle',
  'field.target': 'Ziel',
  'field.leavesFrom': 'Verlässt bei',
  'field.arrivesAt': 'Kommt an bei',
  'field.resetDefault': 'Auf Standard zurücksetzen',
  'field.clear': '{name} leeren',

  'tab.general': 'Allgemein',
  'tab.appearance': 'Darstellung',
  'tab.data': 'Daten',

  'option.default': 'Standard',
  'option.rounded': 'Abgerundet',
  'option.sharp': 'Eckig',
  'option.subtle': 'Dezent',
  'option.stickman': 'Strichmännchen',
  'option.iconSmall': 'Klein (Kopfzeile)',
  'option.iconLarge': 'Groß (Rumpf)',
  'option.solidDefault': 'Durchgezogen (Standard)',
  'option.dashed': 'Gestrichelt',
  'option.dotted': 'Gepunktet',
  'option.smoothDefault': 'Weich (Standard)',
  'option.arrow': 'Pfeil',

  'section.operationalAspects': 'BETRIEBLICHE ASPEKTE',
  'section.domainGroup': 'DOMÄNENGRUPPE',
  'section.tidyGroup': 'GRUPPE AUFRÄUMEN',
  'section.connection': 'Verbindung',
  'section.route': 'Route',

  'element.noData': 'Keine Betriebsdaten für dieses Element.',
  'element.deleteApplication': 'Anwendung löschen…',
  'element.removeDelete': 'Entfernen / löschen…',

  'group.membersOne': '{count} Element darin',
  'group.membersOther': '{count} Elemente darin',
  'group.remove': 'Gruppe entfernen',
  'group.removeNote':
    'Das Entfernen des Rahmens lässt die Elemente auf der Zeichenfläche — sie gehören nur nicht mehr zu einer Gruppe.',
  'group.tidyApply': '{name} aufräumen',
  'group.tidyApplyAny': 'Gruppe aufräumen',

  'route.none': 'Keine',
  'route.auto': 'Automatisch',
  'route.manual': 'Von Hand',
  'route.noteNone': 'Gerade zwischen den beiden Elementen gezeichnet; ein Routing-Lauf kann sie biegen.',
  'route.noteAuto': 'Vom Router gelegt; der nächste Routing-Lauf kann sie verschieben.',
  'route.noteManual': 'Automatisches Routen lässt diese Linie, wo Sie sie gelegt haben.',
  'route.bendsOne': '1 Knick',
  'route.bendsOther': '{count} Knicke',
  'route.pinned': 'fixiert',
  'route.pin': 'Fixieren',
  'route.unpin': 'Lösen',
  'route.resetToAutomatic': 'Zurück auf automatisch',
  'route.leavesFromSide': 'Verlässt bei {name}',
  'route.arrivesAtSide': 'Kommt an bei {name}',
  'route.deleteConnection': 'Verbindung löschen',

  'tidy.direction': 'Richtung',
  'tidy.auto': 'Auto',
  'tidy.across': 'Quer',
  'tidy.down': 'Abwärts',
  'tidy.hybrid': 'Gemischt',
  'tidy.hybridTip': 'Gruppen nebeneinander, die Anwendungen in jeder Gruppe untereinander',
  'tidy.density': 'Dichte',
  'tidy.compact': 'Kompakt',
  'tidy.normal': 'Normal',
  'tidy.spacious': 'Weiträumig',
  'tidy.pinAnchors': 'Ankerpunkte fixieren',
  'tidy.pinAnchorsNote': 'Knickpunkte und Beschriftungen, die Sie selbst gesetzt haben, bleiben unangetastet.',
  'tidy.pinBoundary': 'Die Anwendungsgrenze fixieren',
  'tidy.pinBoundaryNote': 'Die Grenze bleibt stehen; nur ihr Inhalt wird neu angeordnet.',
  'tidy.pinGroups': 'Gruppenpositionen fixieren',
  'tidy.pinGroupsNote': 'Gruppen bleiben stehen; nur ihr Inhalt wird neu angeordnet.',
  'tidy.pinBoundaryContents': 'Ihren Inhalt fixieren',
  'tidy.pinBoundaryContentsNote':
    'Die Komponenten behalten ihre Anordnung; die Grenze darf sich noch bewegen.',
  'tidy.pinGroupContents': 'Gruppeninhalt fixieren',
  'tidy.pinGroupContentsNote': 'Was in jeder Gruppe liegt, behält seine Anordnung.',

  'logo.search': 'Symbole suchen',
  'logo.none': 'Keins',
  'logo.upload': 'Ein Logo hochladen',
  'logo.picker': 'Symbolauswahl',
  'logo.category.uploaded': 'Hochgeladen',
  'logo.noMatches': 'Keine Symbole passen zu „{query}“.',
  'dialog.deleteTitle': '{what} löschen?',
  'dialog.deleteThisConnection': 'diese Verbindung',
  'dialog.deleteFromModel': 'Löscht {what} aus dem Modell. ',
  'dialog.deleteThemFromModel': 'Löscht sie aus dem Modell. ',
  'dialog.cascadeOne': '1 daran hängende Verbindung geht mit. ',
  'dialog.cascadeOther': '{count} daran hängende Verbindungen gehen mit. ',
  'dialog.groupBoxesRemoved': 'Gruppenrahmen werden entfernt; die Elemente darin bleiben. ',
  'dialog.canUndo': 'Sie können dies rückgängig machen.',
  'dialog.deleteElementTitle': '„{name}“ löschen?',
  'dialog.deleteElementKeeps': 'behält das Element im Modell (und auf allen anderen Diagrammen).',
  'dialog.deleteElementRemoves': 'entfernt es überall, einschließlich seiner Verbindungen.',
  'dialog.removeFromDiagram': 'Aus dem Diagramm entfernen',
  'dialog.deleteFromModelButton': 'Aus dem Modell löschen',
  'dialog.deleteComponentsFirst': 'Löschen Sie zuerst ihre Komponenten oder hängen Sie sie um',
  'dialog.renameDiagram': 'Diagramm umbenennen',

  'diagramSettings.title': 'Diagrammeinstellungen',
  'diagramSettings.presentation': 'AUF DER ZEICHNUNG',
  'diagramSettings.presentationHelp':
    'Was das exportierte PNG über dieses Diagramm sagt. Nichts hiervon ändert das Modell.',
  'diagramSettings.author': 'Autor',
  'diagramSettings.authorPlaceholder': 'Wer es gezeichnet hat',
  'diagramSettings.client': 'Kunde',
  'diagramSettings.clientHelp': 'Leer lassen, um {name} zu verwenden.',
  'diagramSettings.date': 'Datum',
  'diagramSettings.dateHelp': 'Leer lassen, um den Tag des Exports zu stempeln.',
  'diagramSettings.showTitleBlock': 'Titelblock zeichnen',
  'diagramSettings.aspects': 'REIFEGRADSPALTEN',
  'diagramSettings.aspectsHelp':
    'Die Abzeichen unter jeder Anwendung, in dieser Reihenfolge. Benennen Sie sie nach Ihrer eigenen Zuordnung um, geben Sie einem Abzeichen ein eigenes Kürzel oder lassen Sie weg, was Sie nicht erfassen.',
  'diagramSettings.showAspects': 'Reifegrad-Abzeichen anzeigen',
  'diagramSettings.hiddenNote': 'Ausgeblendet. Die Spalten unten bleiben erhalten und kommen zurück, wenn Sie dies wieder einschalten.',
  'diagramSettings.columnLabel': 'Spalte',
  'diagramSettings.columnCode': 'Abzeichen',
  'diagramSettings.codePlaceholder': 'auto',
  'diagramSettings.addStandard': 'Standard hinzufügen…',
  'diagramSettings.addCustom': 'Eigene hinzufügen',
  'diagramSettings.newColumn': 'Neue Spalte',
  'diagramSettings.reset': 'Zurück zu den fünf Standardspalten',
  'diagramSettings.remove': '{name} entfernen',
  'diagramSettings.moveUp': '{name} nach oben',
  'diagramSettings.moveDown': '{name} nach unten',
  'diagramSettings.noColumns': 'Keine Spalten. Anwendungen zeigen gar keine Reifegrad-Abzeichen.',
  'diagramSettings.allStandardUsed': 'Jede Standardspalte ist bereits vorhanden',

  'help.title': 'Tastenkürzel',
  'help.intro':
    'Klicken Sie mit rechts auf ein Element, eine Linie, eine Domänengruppe, einen Diagrammreiter oder die leere Zeichenfläche für ein Menü mit allem, was dort möglich ist. Die Tastenkürzel unten stehen neben den passenden Menüeinträgen.',
  'shortcutGroup.selection': 'Auswahl',
  'shortcutGroup.edit': 'Bearbeiten',
  'shortcutGroup.view': 'Ansicht',
  'shortcutGroup.general': 'Allgemein',
  'shortcut.select-all': 'Alles auswählen',
  'shortcut.deselect': 'Auswahl aufheben',
  'shortcut.copy': 'Kopieren',
  'shortcut.paste': 'Einfügen',
  'shortcut.cut': 'Ausschneiden',
  'shortcut.duplicate': 'An Ort und Stelle duplizieren',
  'shortcut.delete': 'Löschen',
  'shortcut.rename': 'Umbenennen',
  'shortcut.nudge': 'Verschieben (Rasterschritt)',
  'shortcut.nudge-fine': 'Verschieben (1px)',
  'shortcut.undo': 'Rückgängig',
  'shortcut.redo': 'Wiederholen',
  'shortcut.zoom-in': 'Vergrößern',
  'shortcut.zoom-out': 'Verkleinern',
  'shortcut.fit-view': 'Einpassen',
  'shortcut.zoom-100': 'Zoom auf 100 %',
  'shortcut.force-save': 'Jetzt speichern',
  'shortcut.context-menu': 'Kontextmenü öffnen',
  'shortcut.help': 'Tastenkürzel',
  'shortcut.find': 'Element suchen',

  'error.diagramNotFound': 'Diagramm nicht gefunden — übergeben Sie eine gültige activeDiagramId.',
  'error.overCap':
    'Dieses Diagramm hat eine Gruppe von {total} Verbindungen; das Routing schafft bis zu {max} auf einmal, daher konnten diese Linien nicht automatisch geroutet werden.',
  'error.tidyRoutingUnattended':
    'Dieses Diagramm wurde angeordnet, aber seine Verbindungen konnten nicht geroutet werden.',
  'error.tidyRouting':
    'Die Elemente wurden aufgeräumt, aber die Verbindungen konnten nicht geroutet werden. Laden Sie die Seite neu und versuchen Sie es erneut.',
  'error.tidyUnattended': 'Dieses Diagramm konnte nicht automatisch angeordnet werden.',
  'error.tidy': 'Aufräumen ist fehlgeschlagen. Laden Sie die Seite neu und versuchen Sie es erneut.',
  'error.tidyTooLarge':
    'Dieses Diagramm ist zu groß zum Aufräumen: es hat {count} Kästen, und Aufräumen ordnet '
    + 'höchstens {limit} an. Fassen Sie es in Gruppen zusammen oder verteilen Sie es auf mehrere Diagramme.',
  'error.tidyGroup':
    'Die Gruppe wurde aufgeräumt, aber die Verbindungen konnten nicht geroutet werden. Laden Sie die Seite neu und versuchen Sie es erneut.',
  'error.tidyGroupFailed':
    'Das Aufräumen der Gruppe ist fehlgeschlagen. Laden Sie die Seite neu und versuchen Sie es erneut.',
  'error.route':
    'Die Verbindungen konnten nicht geroutet werden. Laden Sie die Seite neu und versuchen Sie es erneut.',
  'error.routeOne':
    'Die Verbindung konnte nicht geroutet werden. Laden Sie die Seite neu und versuchen Sie es erneut.',
  'error.export': 'Der PNG-Export ist fehlgeschlagen. Laden Sie die Seite neu und versuchen Sie es erneut.',
  'note.overCap': 'dieses Diagramm hat mehr Verbindungen, als das Routing bewältigt',
  'note.reclassify':
    'drücken Sie einmal auf „Verbindungen routen“, damit sich die bestehenden Linien dieses Diagramms bewegen dürfen',

  'format.perMonth': '{amount}/Mon.',
  'export.client': 'KUNDE',
  'export.title': 'TITEL',
  'export.author': 'AUTOR',
  'export.date': 'DATUM',
  'export.asOf': 'Stand {date}',
  'export.aspects': 'ASPEKTE',

  // --- The C4 corner of a container diagram --------------------------------
  'c4.containerTitle': '[Container] {name}',
  'c4.containerDescription': 'Das Container-Diagramm von {name}.',
  'c4.applicationTag': '{name} [Anwendung]',

  'menu.openDocumentation': 'Dokumentation öffnen',
  'shortcut.open-documentation': 'Dokumentation öffnen',
  'node.hasDocumentation': 'Hat Dokumentation — Rechtsklick zum Öffnen',
}
