/**
 * English, for the canvas and everything docked to it — menus, inspectors, the toolbar.
 *
 * `as const`, so this slice is the schema for its own keys: `nl.ts` beside it
 * cannot be missing one and cannot invent one. The registry composes every
 * module's slice into the table `t()` reads (`i18n/strings.ts`).
 */
export const EN = {
  'kind.domainGroup': 'Domain group',

  /**
   * The name something is BORN with, when the palette's name field was left
   * empty. It is a placeholder you are expected to type over, but it is also
   * real content the moment you don't — it goes into the model, onto the card,
   * and into the export. So it follows the UI language like any other word,
   * and (unlike `kind.*`, which names a category) it reads as a name.
   */
  'newName.actor': 'New actor',
  'newName.application': 'New application',
  'newName.component': 'New component',
  'newName.externalSystem': 'New external system',
  'newName.inputChannel': 'New input channel',
  'newName.managementTool': 'New management tool',
  'newName.domainGroup': 'New group',

  'lifecycle.planned': 'Planned',
  'lifecycle.live': 'Live',
  'lifecycle.retiring': 'Retiring',
  'lifecycle.retired': 'Retired',
  'lifecycleNote.planned': 'upcoming, not yet live',
  'lifecycleNote.live': 'active — shown without a badge',
  'lifecycleNote.retiring': 'being sunset',
  'lifecycleNote.retired': 'decommissioned, dimmed',

  'aspect.managed': 'Managed',
  'aspect.partial': 'Partial',
  'aspect.atRisk': 'At risk',
  'aspect.none': 'None',

  'side.auto': 'Automatic',
  'side.top': 'Top',
  'side.right': 'Right',
  'side.bottom': 'Bottom',
  'side.left': 'Left',

  'shape.smooth': 'Smooth',
  'shape.orthogonal': 'Orthogonal',
  'shape.straight': 'Straight',
  'shape.curved': 'Curved',

  'align.left': 'Left',
  'align.centerX': 'Centre',
  'align.right': 'Right',
  'align.top': 'Top',
  'align.centerY': 'Middle',
  'align.bottom': 'Bottom',
  'zone.resizeBand': 'Resize {name} band',
  'zone.resizeCanvas': 'Resize canvas {name}',

  // --- context menus -------------------------------------------------------
  'menu.openContainer': 'Open container diagram',
  'menu.createContainer': 'Create container diagram',
  'menu.rename': 'Rename',
  'menu.startConnection': 'Start connection to…',
  'menu.icon': 'Icon…',
  'menu.lifecycle': 'Lifecycle',
  'menu.moveToZone': 'Move to zone',
  'menu.changeKind': 'Change kind',
  'menu.domainGroup': 'Domain group',
  'menu.duplicate': 'Duplicate',
  'menu.copy': 'Copy',
  'menu.cut': 'Cut',
  'menu.removeFromDiagram': 'Remove from diagram',
  'menu.deleteFromModel': 'Delete from model…',
  'menu.boundaryApplication': 'This application is the boundary of this diagram',
  'menu.addBend': 'Add bend point here',
  'menu.removeBend': 'Remove bend point',
  'menu.removeAllBends': 'Remove all bend points',
  'menu.noBendPoints': 'This line has no bend points',
  'menu.pinRoute': 'Pin route',
  'menu.unpinRoute': 'Unpin route',
  'menu.resetRoute': 'Reset to automatic route',
  'menu.layoutBusy': 'A layout action is running',
  'menu.attachAt': 'Attach at',
  'menu.attachSource': 'Source',
  'menu.attachTarget': 'Target',
  'menu.lineShape': 'Line shape',
  'menu.direction': 'Direction',
  'menu.oneWay': 'One-way',
  'menu.twoWay': 'Two-way',
  'menu.reverse': 'Reverse',
  'menu.editLabel': 'Edit label',
  'menu.resetLabelPosition': 'Reset label position',
  'menu.labelAutomatic': 'The label is at its automatic position',
  'menu.deleteConnection': 'Delete connection',
  'menu.pasteHere': 'Paste here',
  'menu.nothingToPaste': 'Nothing to paste',
  'menu.addHere': 'Add here',
  'menu.addDomainGroupHere': 'Add domain group here',
  'menu.selectAll': 'Select all',
  'menu.tidy': 'Tidy layout',
  'menu.routeConnections': 'Route connections',
  'menu.routeConnectionsAll': 'Re-route everything (ignore pins)',
  'menu.fitView': 'Fit view',
  'menu.showGrid': 'Show grid',
  'menu.snapToGrid': 'Snap to grid',
  'menu.align': 'Align',
  'menu.distribute': 'Distribute',
  'menu.distributeHorizontally': 'Horizontally',
  'menu.distributeVertically': 'Vertically',
  'menu.needThreeElements': 'Select at least three elements',
  'menu.groupIntoDomainGroup': 'Group into new domain group',
  'menu.needLandscapeElements': 'Select elements on the application landscape',
  'menu.delete': 'Delete',
  'menu.tidyGroup': 'Tidy this group',
  'menu.groupColor': 'Group colour…',
  'menu.selectMembers': 'Select members',
  'menu.removeGroup': 'Remove group',
  'menu.renameDiagram': 'Rename diagram…',
  'menu.diagramSettings': 'Diagram settings…',
  'menu.duplicateDiagram': 'Duplicate diagram',
  'menu.deleteDiagram': 'Delete diagram…',
  'menu.lastLandscape': 'The last landscape cannot be deleted',
  'menu.nodeLabel': 'Element menu',
  'menu.edgeLabel': 'Connection menu',
  'menu.paneLabel': 'Canvas menu',
  'menu.groupLabel': 'Domain group menu',
  'menu.selectionLabel': 'Selection menu',
  'menu.tabLabel': 'Diagram menu',
  /** The menu's name when a caller passes none of the six above. */
  'menu.contextLabel': 'Context menu',
  /** Read out for the `kbd` hint beside an item, e.g. "Shortcut ⌘C". */
  'menu.shortcutAria': 'Shortcut {keys}',

  // --- palette -------------------------------------------------------------
  'palette.aside': 'Element palette',
  'palette.addToCanvas': 'Add to canvas',
  'palette.expand': 'Expand palette',
  'palette.collapse': 'Collapse palette',
  'palette.place': 'Place',
  'palette.add': 'Add {name}',
  'palette.openOptions': 'Open {name} options',
  'palette.nameField': '{name} name',
  'palette.logo': 'Logo',
  'palette.colour': 'Colour',
  'palette.groupColour': 'Domain group colour',
  'palette.resize': 'Resize palette',
  'palette.search': 'Search the palette',
  'palette.searchPlaceholder': 'Search…',
  'palette.noMatches': 'Nothing matches “{query}”',
  'palette.section.systems': 'Applications & components',
  'palette.section.integration': 'Integration',
  'palette.section.people': 'People & context',
  'paletteDescription.application': 'A system the customer runs or buys',
  'paletteDescription.component': 'A part inside one application',
  'paletteDescription.inputChannel': 'How work and data enter the landscape',
  'paletteDescription.externalSystem': 'A system outside the customer’s control',
  'paletteDescription.managementTool': 'Tooling that runs and watches the landscape',
  'paletteDescription.actor': 'A person or role using the landscape',
  'paletteDescription.domainGroup': 'A labelled area grouping the landscape',

  // --- toolbar -------------------------------------------------------------
  'toolbar.newDiagram': 'New Layer 7 diagram',
  'toolbar.readOnly': 'Read-only',
  'toolbar.undo': 'Undo',
  'toolbar.undoTip': 'Undo (⌘Z)',
  'toolbar.redo': 'Redo',
  'toolbar.redoTip': 'Redo (⌘⇧Z)',
  'toolbar.tidy': 'Tidy layout',
  'toolbar.tidyTip': 'Tidy layout (ELK)',
  'toolbar.tidySettings': 'Tidy settings',
  'toolbar.routeOnly': 'Route connections only',
  'toolbar.routeOnlyTip': 'Route connections only (keeps node positions)',
  'toolbar.autoRoute': 'Auto-route connections',
  'toolbar.autoRouteOn': 'Auto-route connections: on — lines re-route when you move a node',
  'toolbar.autoRouteOff': 'Auto-route connections: off',
  'toolbar.fitView': 'Fit view',
  'toolbar.exportPng': 'Export PNG',
  'toolbar.exportingPng': 'Exporting PNG…',
  'toolbar.lifecycleBadges': 'Toggle lifecycle badges',
  'toolbar.shortcuts': 'Keyboard shortcuts',
  'toolbar.search': 'Find element',
  'toolbar.searchTip': 'Find an element (⌘F)',
  'toolbar.minimap': 'Toggle minimap',
  'toolbar.minimapOn': 'Minimap: on',
  'toolbar.minimapOff': 'Minimap: off',
  'toolbar.languageTip': 'Language — {name}',
  'toolbar.containerDiagrams': 'Container diagrams on this landscape',
  'toolbar.containerDiagramsOf': 'Container diagrams of {name}',
  'toolbar.diagramSettings': 'Diagram settings, including the maturity columns',
  'toolbar.diagramSettingsOf': 'Settings of {name}',
  'toolbar.containerView': 'Container view',
  'toolbar.backTo': 'Back to {name}',
  'toolbar.backToLandscape': 'Back to landscape',

  // --- canvas --------------------------------------------------------------
  'canvas.connectHint': 'Click a target element — Esc cancels',
  'canvas.gridOn': 'Show grid: on',
  'canvas.gridOff': 'Show grid: off',
  'canvas.gridToggle': 'Toggle grid visibility',
  'canvas.snapOn': 'Snap to grid: on',
  'canvas.snapOff': 'Snap to grid: off',
  'canvas.snapToggle': 'Toggle snap to grid',
  'canvas.alignLeft': 'Align left',
  'canvas.alignCenterX': 'Align horizontal centres',
  'canvas.alignRight': 'Align right',
  'canvas.alignTop': 'Align top',
  'canvas.alignCenterY': 'Align vertical centres',
  'canvas.alignBottom': 'Align bottom',
  'canvas.distributeHorizontally': 'Distribute horizontally',
  'canvas.distributeVertically': 'Distribute vertically',
  'canvas.groupName': 'Domain group name',
  'canvas.groupNamed': 'Domain group {name}',
  'canvas.resizeGroup': 'Resize domain group {name}',
  'canvas.groupColour': 'Group colour',
  'canvas.minimap': 'Minimap',
  'node.actorFigure': 'Actor figure',
  'node.external': 'EXTERNAL',
  'node.hasContainer': 'Has a container diagram — double-click to open',
  'node.lifecycleAria': 'Lifecycle: {name}',
  'edge.labelPlaceholder': 'Interface description…',

  // --- inspector -----------------------------------------------------------
  'inspector.aside': 'Inspector',
  'inspector.expand': 'Expand inspector',
  'inspector.collapse': 'Collapse inspector',
  'inspector.resize': 'Resize inspector',
  'inspector.empty':
    'Select an element or connection to edit its properties. Double-click an application to open its container diagram.',
  'inspector.aspectBadges': 'ASPECT BADGES',
  'inspector.selected': '{count} selected',
  'inspector.elementsOne': '{count} element',
  'inspector.elementsOther': '{count} elements',
  'inspector.connectionsOne': '{count} connection',
  'inspector.connectionsOther': '{count} connections',
  'inspector.groupsOne': '{count} domain group',
  'inspector.groupsOther': '{count} domain groups',
  'inspector.multiHint':
    'Drag any selected node to move them together. Shift-click to add or remove items; Escape to clear.',
  'inspector.bulkTitle': 'APPLY TO ALL',
  'inspector.bulkLifecycle': 'Lifecycle',
  'inspector.bulkColour': 'Accent colour',
  'inspector.bulkColourAria': 'Accent colour for the selection',
  'inspector.bulkIcon': 'Icon',
  'inspector.bulkDomainGroup': 'Domain group',
  'inspector.bulkNoChange': 'Leave unchanged',
  'inspector.bulkNote': 'Each change is one undo step over the whole selection.',

  'field.name': 'Name',
  'field.category': 'Category',
  'field.vendor': 'Vendor',
  'field.technology': 'Technology',
  'field.lifecycle': 'Lifecycle',
  'field.managed': 'Managed',
  'field.domainGroup': 'Domain group',
  'field.domainGroupPlaceholder': 'e.g. Commerce',
  'field.accentColour': 'Accent colour',
  'field.shape': 'Shape',
  'field.icon': 'Icon',
  'field.iconSize': 'Icon size',
  'field.iconFirst': 'Pick an icon first',
  'field.placement': 'Placement',
  'field.zone': 'Zone: {name}',
  'field.note': 'Note',
  'field.notePlaceholder': 'e.g. AKS, GitHub Actions',
  'field.noteAria': '{name} note',
  'field.notSet': 'Not set',
  'field.label': 'Label',
  'field.labelPlaceholder': 'e.g. Sends orders',
  'field.labelHelp': 'Newlines wrap the label on the diagram; the protocol renders below it',
  'field.protocol': 'Protocol',
  'field.protocolPlaceholder': 'e.g. EDI, Kafka, REST',
  'field.direction': 'Direction',
  'field.directionHelp': 'Sets the default arrowheads; override per end under Appearance',
  'field.oneWay': 'One-way →',
  'field.bidirectional': 'Bidirectional ↔',
  'field.colour': 'Colour',
  'field.edgeColour': 'Edge colour',
  'field.lineStyle': 'Line style',
  'field.routing': 'Routing',
  'field.routingHelp': 'Manual waypoints, when present, override this',
  'field.source': 'Source',
  'field.target': 'Target',
  'field.leavesFrom': 'Leaves from',
  'field.arrivesAt': 'Arrives at',
  'field.resetDefault': 'Reset to default',
  'field.clear': 'Clear {name}',

  'tab.general': 'General',
  'tab.appearance': 'Appearance',
  'tab.data': 'Data',

  'option.default': 'Default',
  'option.rounded': 'Rounded',
  'option.sharp': 'Sharp',
  'option.subtle': 'Subtle',
  'option.stickman': 'Stickman',
  'option.iconSmall': 'Small (header)',
  'option.iconLarge': 'Large (body)',
  'option.solidDefault': 'Solid (default)',
  'option.dashed': 'Dashed',
  'option.dotted': 'Dotted',
  'option.smoothDefault': 'Smooth (default)',
  'option.arrow': 'Arrow',

  'section.operationalAspects': 'OPERATIONAL ASPECTS',
  'section.parameters': 'PARAMETERS',
  'section.domainGroup': 'DOMAIN GROUP',
  'section.tidyGroup': 'TIDY GROUP',
  'section.connection': 'Connection',
  'section.route': 'Route',

  'element.noData': 'No operational data for this element.',
  'element.deleteApplication': 'Delete application…',
  'element.removeDelete': 'Remove / delete…',

  'group.membersOne': '{count} element inside',
  'group.membersOther': '{count} elements inside',
  'group.remove': 'Remove group',
  'group.removeNote':
    'Removing the box leaves its elements on the canvas — they just stop belonging to a group.',
  'group.tidyApply': 'Tidy {name}',
  /** The same button before a group is picked — the popover has no name yet. */
  'group.tidyApplyAny': 'Tidy group',

  'route.none': 'None',
  'route.auto': 'Automatic',
  'route.manual': 'Hand-drawn',
  'route.noteNone': 'Drawn straight between the two elements; a routing pass may bend it.',
  'route.noteAuto': 'Placed by the router; the next routing pass may move it.',
  'route.noteManual': 'Automatic routing leaves this line where you put it.',
  'route.bendsOne': '1 bend',
  'route.bendsOther': '{count} bends',
  'route.pinned': 'pinned',
  'route.pin': 'Pin',
  'route.unpin': 'Unpin',
  'route.resetToAutomatic': 'Reset to automatic',
  'route.leavesFromSide': 'Leaves from {name}',
  'route.arrivesAtSide': 'Arrives at {name}',
  'route.deleteConnection': 'Delete connection',

  // --- tidy settings -------------------------------------------------------
  'tidy.direction': 'Direction',
  'tidy.auto': 'Auto',
  'tidy.across': 'Across',
  'tidy.down': 'Down',
  'tidy.hybrid': 'Hybrid',
  'tidy.hybridTip': 'Groups across, the applications inside each one down',
  'tidy.density': 'Density',
  'tidy.compact': 'Compact',
  'tidy.normal': 'Normal',
  'tidy.spacious': 'Spacious',
  'tidy.pinAnchors': 'Pin anchor points',
  'tidy.pinAnchorsNote': 'Bend points and labels you positioned yourself are left alone.',
  'tidy.pinBoundary': 'Pin the application boundary',
  'tidy.pinBoundaryNote': 'The boundary stays put; only what’s inside it is re-laid-out.',
  'tidy.pinGroups': 'Pin group placements',
  'tidy.pinGroupsNote': "Groups stay put; only what's inside them is re-laid-out.",
  'tidy.pinBoundaryContents': 'Pin its contents',
  'tidy.pinBoundaryContentsNote':
    'The components keep their arrangement; the boundary may still move.',
  'tidy.pinGroupContents': 'Pin group contents',
  'tidy.pinGroupContentsNote': "What's inside each group keeps its arrangement.",

  // --- logo picker ---------------------------------------------------------
  'logo.search': 'Search icons',
  'logo.none': 'None',
  'logo.upload': 'Upload a logo',
  'logo.picker': 'Icon picker',
  'logo.category.uploaded': 'Uploaded',
  'logo.noMatches': 'No icons match “{query}”.',
  'dialog.deleteTitle': 'Delete {what}?',
  'dialog.deleteThisConnection': 'this connection',
  'dialog.deleteFromModel': 'Deletes {what} from the model. ',
  'dialog.deleteThemFromModel': 'Deletes them from the model. ',
  'dialog.cascadeOne': '1 connection attached to them goes too. ',
  'dialog.cascadeOther': '{count} connections attached to them go too. ',
  'dialog.groupBoxesRemoved': 'Group boxes are removed; the elements inside them stay. ',
  'dialog.canUndo': 'You can undo this.',
  'dialog.deleteElementTitle': 'Delete “{name}”?',
  'dialog.deleteElementKeeps': 'keeps the element in the model (and on any other diagram).',
  'dialog.deleteElementRemoves': 'removes it everywhere, including its connections.',
  'dialog.removeFromDiagram': 'Remove from diagram',
  'dialog.deleteFromModelButton': 'Delete from model',
  'dialog.deleteComponentsFirst': 'Delete or re-parent its components first',
  'dialog.renameDiagram': 'Rename diagram',

  'diagramSettings.title': 'Diagram settings',
  'diagramSettings.presentation': 'ON THE DRAWING',
  'diagramSettings.presentationHelp':
    'What the exported PNG says about this diagram. Nothing here changes the model.',
  'diagramSettings.author': 'Author',
  'diagramSettings.authorPlaceholder': 'Who drew it',
  'diagramSettings.client': 'Client',
  'diagramSettings.clientHelp': 'Leave empty to use {name}.',
  'diagramSettings.date': 'Date',
  'diagramSettings.dateHelp': 'Leave empty to stamp the day it is exported.',
  'diagramSettings.showTitleBlock': 'Draw the title block',
  'diagramSettings.aspects': 'MATURITY COLUMNS',
  'diagramSettings.aspectsHelp':
    'The badges under every application, in this order. Rename them to your own mapping, give a badge its own short code, or drop the ones you do not track.',
  'diagramSettings.showAspects': 'Show maturity badges',
  'diagramSettings.hiddenNote': 'Hidden. The columns below are kept, and come back when you switch this on.',
  'diagramSettings.columnLabel': 'Column',
  'diagramSettings.columnCode': 'Badge',
  'diagramSettings.codePlaceholder': 'auto',
  'diagramSettings.addStandard': 'Add standard…',
  'diagramSettings.addCustom': 'Add your own',
  'diagramSettings.newColumn': 'New column',
  'diagramSettings.reset': 'Reset to the standard five',
  'diagramSettings.remove': 'Remove {name}',
  'diagramSettings.moveUp': 'Move {name} up',
  'diagramSettings.moveDown': 'Move {name} down',
  'diagramSettings.noColumns': 'No columns. Applications show no maturity badges at all.',
  'diagramSettings.allStandardUsed': 'Every standard column is already here',

  'help.title': 'Keyboard shortcuts',
  'help.intro':
    'Right-click an element, a line, a domain group, a diagram tab or the empty canvas for a menu of everything you can do there. The shortcuts below appear beside the matching menu entries.',
  'shortcutGroup.selection': 'Selection',
  'shortcutGroup.edit': 'Edit',
  'shortcutGroup.view': 'View',
  'shortcutGroup.general': 'General',
  'shortcut.select-all': 'Select all',
  'shortcut.deselect': 'Deselect',
  'shortcut.copy': 'Copy',
  'shortcut.paste': 'Paste',
  'shortcut.cut': 'Cut',
  'shortcut.duplicate': 'Duplicate in place',
  'shortcut.delete': 'Delete',
  'shortcut.rename': 'Rename',
  'shortcut.nudge': 'Nudge (grid step)',
  'shortcut.nudge-fine': 'Nudge (1px)',
  'shortcut.undo': 'Undo',
  'shortcut.redo': 'Redo',
  'shortcut.zoom-in': 'Zoom in',
  'shortcut.zoom-out': 'Zoom out',
  'shortcut.fit-view': 'Fit to view',
  'shortcut.zoom-100': 'Zoom to 100%',
  'shortcut.force-save': 'Force save',
  'shortcut.context-menu': 'Open context menu',
  'shortcut.help': 'Keyboard shortcuts',
  'shortcut.find': 'Find element',

  // --- editor messages -----------------------------------------------------
  'error.diagramNotFound': 'Diagram not found — pass a valid activeDiagramId.',
  'error.overCap':
    'This diagram has a group of {total} connections; routing handles up to {max} at a time, so those lines could not be routed automatically.',
  'error.tidyRoutingUnattended': 'This diagram was laid out but its connections could not be routed.',
  'error.tidyRouting':
    'The nodes were tidied but the connections could not be routed. Reload the page and try again.',
  'error.tidyUnattended': 'This diagram could not be laid out automatically.',
  'error.tidy': 'Tidy failed. Reload the page and try again.',
  'error.tidyGroup':
    'The group was tidied but the connections could not be routed. Reload the page and try again.',
  'error.tidyGroupFailed': 'Tidying the group failed. Reload the page and try again.',
  'error.route': 'The connections could not be routed. Reload the page and try again.',
  'error.routeOne': 'The connection could not be routed. Reload the page and try again.',
  'error.export': 'The PNG export failed. Reload the page and try again.',
  'note.overCap': 'this diagram has more connections than routing can handle',
  'note.reclassify': "press 'Route connections' once so this diagram's existing lines can move",

  // --- PNG title block -----------------------------------------------------
  'format.perMonth': '{amount}/mo',
  'export.client': 'CLIENT',
  'export.title': 'TITLE',
  'export.author': 'AUTHOR',
  'export.date': 'DATE',
  'export.aspects': 'ASPECTS',

  // The documentation page and its doors.
  'menu.openDocumentation': 'Open documentation',
  'shortcut.open-documentation': 'Open documentation',
  'node.hasDocumentation': 'Has documentation — right-click to open',
} as const
