/**
 * Frisian, for the canvas and everything docked to it — menus, inspectors, the toolbar.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a Frisian screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'kind.domainGroup': 'Domeingroep',

  'newName.actor': 'Nije akteur',
  'newName.step': 'Nije stap',
  'newName.function': 'Nije funksje',
  'newName.process': 'Nij proses',
  'newName.application': 'Nije applikaasje',
  'newName.component': 'Nij komponint',
  'newName.domainGroup': 'Nije groep',

  'lifecycle.planned': 'Pland',
  'lifecycle.live': 'Aktyf',
  'lifecycle.retiring': 'Ôfboud wurdend',
  'lifecycle.retired': 'Ôfboud',
  'lifecycleNote.planned': 'komt deroan, noch net aktyf',
  'lifecycleNote.live': 'aktyf — sûnder badge toand',
  'lifecycleNote.retiring': 'wurdt ôfboud',
  'lifecycleNote.retired': 'út tsjinst, dimd',

  'aspect.managed': 'Beheard',
  'aspect.partial': 'Foar in part',
  'aspect.atRisk': 'Op risiko',
  'aspect.none': 'Gjin',

  'side.auto': 'Automatysk',
  'side.top': 'Boppe',
  'side.right': 'Rjochts',
  'side.bottom': 'Ûnder',
  'side.left': 'Links',

  'shape.smooth': 'Floeiend',
  'shape.orthogonal': 'Heaksk',
  'shape.straight': 'Rjocht',
  'shape.curved': 'Bûgd',

  'align.left': 'Links',
  'align.centerX': 'Midden',
  'align.right': 'Rjochts',
  'align.top': 'Boppe',
  'align.centerY': 'Midden',
  'align.bottom': 'Ûnder',
  'zone.resizeBand': 'Bân {name} fan grutte feroarje',
  'zone.resizeCanvas': 'Tekenflak {name} fan grutte feroarje',

  'menu.openContainer': 'Containerdiagram iepenje',
  'menu.createContainer': 'Containerdiagram meitsje',
  'menu.openOwner': 'Iepenje dêr\'t it definiearre is',
  'menu.rename': 'Omneame',
  'menu.startConnection': 'Ferbining begjinne nei…',
  'menu.icon': 'Ikoan…',
  'menu.lifecycle': 'Libbenssyklus',
  'menu.moveToZone': 'Nei sône ferpleatse',
  'menu.changeKind': 'Soarte feroarje',
  'menu.domainGroup': 'Domeingroep',
  'menu.duplicate': 'Duplisearje',
  'menu.copy': 'Kopiearje',
  'menu.cut': 'Knippe',
  'menu.removeFromDiagram': 'Út it diagram helje',
  'menu.deleteFromModel': 'Út it model fuortsmite…',
  'menu.boundaryApplication': 'Dizze applikaasje is de grins fan dit diagram',
  'menu.addBend': 'Hjir in knikpunt taheakje',
  'menu.removeBend': 'Knikpunt fuorthelje',
  'menu.removeAllBends': 'Alle knikpunten fuorthelje',
  'menu.noBendPoints': 'Dizze line hat gjin knikpunten',
  'menu.pinRoute': 'Rûte fêstsette',
  'menu.unpinRoute': 'Rûte losmeitsje',
  'menu.resetRoute': 'Werom nei automatyske rûte',
  'menu.layoutBusy': 'Der rint in yndielingsaksje',
  'menu.attachAt': 'Oanhechtsje oan',
  'menu.attachSource': 'Boarne',
  'menu.attachTarget': 'Doel',
  'menu.lineShape': 'Linefoarm',
  'menu.direction': 'Rjochting',
  'menu.oneWay': 'Ienrjochting',
  'menu.twoWay': 'Twarjochting',
  'menu.reverse': 'Omdraaie',
  'menu.editLabel': 'Label bewurkje',
  'menu.resetLabelPosition': 'Labelposysje werstelle',
  'menu.labelAutomatic': 'It label stiet op syn automatyske plak',
  'menu.deleteConnection': 'Ferbining fuortsmite',
  'menu.pasteHere': 'Hjir plakke',
  'menu.nothingToPaste': 'Neat om te plakken',
  'menu.addHere': 'Hjir taheakje',
  'menu.addDomainGroupHere': 'Hjir in domeingroep taheakje',
  'menu.selectAll': 'Alles selektearje',
  'menu.tidy': 'Yndieling oprêde',
  'menu.routeConnections': 'Ferbiningen rûtsje',
  'menu.routeConnectionsAll': 'Alles opnij rûtsje (fêstsette rûtes negearje)',
  'menu.fitView': 'Passend meitsje',
  'menu.showGrid': 'Roaster toane',
  'menu.snapToGrid': 'Útlinje op roaster',
  'menu.align': 'Útlinje',
  'menu.distribute': 'Ferdiele',
  'menu.distributeHorizontally': 'Horizontaal',
  'menu.distributeVertically': 'Fertikaal',
  'menu.needThreeElements': 'Selektearje op syn minst trije eleminten',
  'menu.groupIntoDomainGroup': 'Gearfoegje yn in nije domeingroep',
  'menu.needLandscapeElements': 'Selektearje eleminten op it applikaasjelânskip',
  'menu.delete': 'Fuortsmite',
  'menu.tidyGroup': 'Dizze groep oprêde',
  'menu.groupColor': 'Groepskleur…',
  'menu.selectMembers': 'Leden selektearje',
  'menu.removeGroup': 'Groep fuorthelje',
  'menu.renameDiagram': 'Diagram omneame…',
  'menu.diagramSettings': 'Diagramynstellingen…',
  'menu.duplicateDiagram': 'Diagram duplisearje',
  'menu.duplicateDiagramAsOf': 'Duplisearje per datum…',
  'menu.deleteDiagram': 'Diagram fuortsmite…',
  'menu.lastLandscape': 'It lêste lânskip kin net fuortsmiten wurde',
  'menu.nodeLabel': 'Elemintmenu',
  'menu.edgeLabel': 'Ferbiningsmenu',
  'menu.paneLabel': 'Tekenflakmenu',
  'menu.groupLabel': 'Domeingroepmenu',
  'menu.selectionLabel': 'Seleksjemenu',
  'menu.tabLabel': 'Diagrammenu',
  'menu.contextLabel': 'Kontekstmenu',
  'menu.shortcutAria': 'Fluchtoets {keys}',

  'palette.aside': 'Elemintepalet',
  'palette.addToCanvas': 'Oan it tekenflak taheakje',
  'palette.expand': 'Palet útklappe',
  'palette.collapse': 'Palet ynklappe',
  'palette.place': 'Pleatse',
  'palette.add': '{name} taheakje',
  'palette.openOptions': 'Opsjes foar {name} iepenje',
  'palette.nameField': 'Namme fan {name}',
  'palette.logo': 'Logo',
  'palette.colour': 'Kleur',
  'palette.groupColour': 'Kleur fan de domeingroep',
  'palette.resize': 'Breedte fan it palet oanpasse',
  'palette.search': 'Yn it palet sykje',
  'palette.searchPlaceholder': 'Sykje…',
  'palette.noMatches': 'Neat komt oerien mei “{query}”',
  'palette.section.systems': 'Applikaasjes & komponinten',
  'palette.section.people': 'Minsken & kontekst',
  'paletteDescription.application': 'In systeem dat de organisaasje draait of ôfnimt',
  'paletteDescription.component': 'In ûnderdiel binnen ien applikaasje',
  'paletteDescription.actor': 'In persoan of rol dy’t it lânskip brûkt',
  'paletteDescription.domainGroup': 'In beneamd flak dat it lânskip groepearret',
  'palette.existing': 'Besteande applikaasje…',
  'paletteDescription.existing': 'In applikaasje dy\'t de organisaasje al hat, hjir tekene',

  'toolbar.newDiagram': 'Nij Layer 7-diagram',
  'toolbar.newLandscape': 'Lânskip',
  'toolbar.newSheet': 'Bedriuwsarsjitektuer',
  'toolbar.newMap': 'Bedriuwskaart',
  'toolbar.readOnly': 'Allinnich-lêze',
  'toolbar.undo': 'Ûngedien meitsje',
  'toolbar.undoTip': 'Ûngedien meitsje (⌘Z)',
  'toolbar.redo': 'Opnij dwaan',
  'toolbar.redoTip': 'Opnij dwaan (⌘⇧Z)',
  'toolbar.tidy': 'Yndieling oprêde',
  'toolbar.tidyTip': 'Yndieling oprêde (ELK)',
  'toolbar.cancelTidy': 'Oprêden annulearje',
  'toolbar.tidySettings': 'Ynstellingen foar oprêden',
  'toolbar.routeOnly': 'Allinnich ferbiningen rûtsje',
  'toolbar.routeOnlyTip': 'Allinnich ferbiningen rûtsje (eleminten bliuwe stean)',
  'toolbar.autoRoute': 'Ferbiningen automatysk rûtsje',
  'toolbar.autoRouteOn':
    'Automatysk rûtsje: oan — linen rinne mei as jo in elemint ferpleatse',
  'toolbar.autoRouteOff': 'Automatysk rûtsje: út',
  'toolbar.fitView': 'Passend meitsje',
  'toolbar.exportPng': 'PNG eksportearje',
  'toolbar.exportingPng': 'Dwaande mei PNG eksportearjen…',
  'export.dialogTitle': 'PNG eksportearje',
  'export.theme': 'Tema',
  'export.themeLight': 'Ljocht',
  'export.themeDark': 'Tsjuster',
  'export.labels': 'Linelabels',
  'export.labelsHelp': 'Elk label op de ôfbylding, net allinnich dy ûnder de mûs.',
  'export.titleBlock': 'Titelblok',
  'export.titleBlockHelp': 'Klant, auteur en datum ûnderoan.',
  'export.legend': 'Leginda',
  'export.legendHelp': 'Wat de badgekleuren betsjutte, ûnder it titelblok.',
  'export.lifecycle': 'LIBBENSSYKLUS',
  'export.preview': 'Foarbyld fan de eksport',
  'export.previewBusy': 'Foarbyld wurdt tekene…',
  'export.size': '{width} × {height} piksels, sawat {megapixels} megapiksels.',
  'export.largeBody':
    'Dat is in grutte ôfbylding. Tekenjen kin efkes duorje en it finster reagearret yntusken net.',
  'export.confirm': 'Eksportearje',
  'export.largeConfirm': 'Dochs eksportearje',
  'toolbar.lifecycleBadges': 'Libbenssyklusbadges toane of ferbergje',
  'toolbar.asOf': 'Toant',
  'toolbar.asOfToday': 'Hjoed',
  'toolbar.asOfSet': 'Dit boerd toant it lânskip sa’t it op {date} is.',
  'toolbar.asOfHelp': 'Teken dit boerd sa’t it lânskip der op in keazen dei útseach of útsjen sil.',
  'toolbar.asOfClear': 'Hjoed toane',
  'toolbar.shortcuts': 'Fluchtoetsen',
  'toolbar.search': 'Elemint sykje',
  'toolbar.searchTip': 'In elemint sykje (⌘F)',
  'toolbar.minimap': 'Oersichtskaart toane of ferbergje',
  'toolbar.minimapOn': 'Oersichtskaart: oan',
  'toolbar.minimapOff': 'Oersichtskaart: út',
  'toolbar.edgeLabels': 'Linelabels toane of ferbergje',
  'toolbar.edgeLabelsOn': 'Linelabels: altyd',
  'toolbar.edgeLabelsOff': 'Linelabels: allinnich by oanwizen',
  'toolbar.languageTip': 'Taal — {name}',
  'toolbar.containerDiagrams': 'Containerdiagrammen op dit lânskip',
  'toolbar.containerDiagramsOf': 'Containerdiagrammen fan {name}',
  'toolbar.diagramSettings': 'Diagramynstellingen, mei de ripenskolommen',
  'toolbar.diagramSettingsOf': 'Ynstellingen fan {name}',
  'toolbar.containerView': 'Containerwerjefte',
  'toolbar.backTo': 'Werom nei {name}',
  'toolbar.backToLandscape': 'Werom nei it lânskip',

  'canvas.connectHint': 'Klik in doelelemint oan — Esc annulearret',
  'canvas.gridOn': 'Roaster: oan',
  'canvas.gridOff': 'Roaster: út',
  'canvas.gridToggle': 'Roaster toane of ferbergje',
  'canvas.snapOn': 'Útlinje op roaster: oan',
  'canvas.snapOff': 'Útlinje op roaster: út',
  'canvas.snapToggle': 'Útlinje op roaster oan of út',
  'canvas.alignLeft': 'Links útlinje',
  'canvas.alignCenterX': 'Horizontale middens útlinje',
  'canvas.alignRight': 'Rjochts útlinje',
  'canvas.alignTop': 'Boppe útlinje',
  'canvas.alignCenterY': 'Fertikale middens útlinje',
  'canvas.alignBottom': 'Ûnder útlinje',
  'canvas.distributeHorizontally': 'Horizontaal ferdiele',
  'canvas.distributeVertically': 'Fertikaal ferdiele',
  'canvas.groupName': 'Namme fan de domeingroep',
  'canvas.groupNamed': 'Domeingroep {name}',
  'canvas.resizeGroup': 'Domeingroep {name} fan grutte feroarje',
  'canvas.groupColour': 'Groepskleur',
  'canvas.minimap': 'Oersichtskaart',
  'node.actorFigure': 'Akteurfiguer',
  'node.external': 'EKSTERN',
  'node.hasContainer': 'Hat in containerdiagram — dûbelklik om te iepenjen',
  'node.lifecycleAria': 'Libbenssyklus: {name}',
  'edge.labelPlaceholder': 'Beskriuwing fan it keppelflak…',

  'inspector.aside': 'Ynspektor',
  'inspector.expand': 'Ynspektor útklappe',
  'inspector.collapse': 'Ynspektor ynklappe',
  'inspector.resize': 'Breedte fan de ynspektor oanpasse',
  'inspector.empty':
    'Selektearje in elemint of ferbining om de eigenskippen te bewurkjen. Dûbelklik in applikaasje om har containerdiagram te iepenjen.',
  'inspector.aspectBadges': 'ASPEKTBADGES',
  'inspector.selected': '{count} selektearre',
  'inspector.elementsOne': '{count} elemint',
  'inspector.elementsOther': '{count} eleminten',
  'inspector.connectionsOne': '{count} ferbining',
  'inspector.connectionsOther': '{count} ferbiningen',
  'inspector.groupsOne': '{count} domeingroep',
  'inspector.groupsOther': '{count} domeingroepen',
  'inspector.multiHint':
    'Sleep in selektearre elemint om se tegearre te ferpleatsen. Shift-klik heakket ta of hellet fuort; Escape makket de seleksje leech.',
  'inspector.bulkTitle': 'OP ALLES TAPASSE',
  'inspector.bulkLifecycle': 'Libbenssyklus',
  'inspector.bulkColour': 'Aksintkleur',
  'inspector.bulkColourAria': 'Aksintkleur foar de seleksje',
  'inspector.bulkIcon': 'Ikoan',
  'inspector.bulkDomainGroup': 'Domeingroep',
  'inspector.bulkNoChange': 'Sa litte',
  'inspector.bulkNote': 'Elke feroaring is ien stap yn Ûngedien meitsje oer de hiele seleksje.',

  'field.name': 'Namme',
  'field.category': 'Kategory',
  'field.vendor': 'Leveransier',
  'field.technology': 'Technology',
  'field.lifecycle': 'Libbenssyklus',
  'field.date.live': 'Aktyf fan',
  'field.date.retiring': 'Ôfboud wurdend fan',
  'field.date.retired': 'Fuort op',
  'field.successor': 'Ferfongen troch',
  'field.owner': 'Eigner',
  'field.outside': 'B\u00fbten de organisaasje',
  'field.party': 'Heart by',
  'field.partyNone': 'Net sein',
  'record.title': 'St\u00e2mgegevens',
  'record.open': 'Details',
  'record.empty': 'Noch gjin st\u00e2mgegevens',
  'record.outsideOf': 'Ekstern \u00b7 {name}',
  'field.replace': 'Ferfange…',
  'edge.replaces': 'ferfangt',
  'field.validFrom': 'Line jildich fan',
  'field.validUntil': 'Line jildich oant',
  'field.managed': 'Beheard',
  'field.domainGroup': 'Domeingroep',
  'field.domainGroupPlaceholder': 'bgl. Hannel',
  'field.accentColour': 'Aksintkleur',
  'field.shape': 'Foarm',
  'field.icon': 'Ikoan',
  'field.iconSize': 'Ikoangrutte',
  'field.iconFirst': 'Kies earst in ikoan',
  'field.placement': 'Pleatsing',
  'field.zone': 'Sône: {name}',
  'field.note': 'Oantekening',
  'field.notePlaceholder': 'bgl. AKS, GitHub Actions',
  'field.noteAria': 'Oantekening by {name}',
  'field.notSet': 'Net ynfolle',
  'field.label': 'Label',
  'field.labelPlaceholder': 'bgl. Stjoert oarders',
  'field.labelHelp': 'Rigeleinen brekke it label op de tekening ôf; it protokol stiet derûnder',
  'field.protocol': 'Protokol',
  'field.protocolPlaceholder': 'bgl. EDI, Kafka, REST',
  'field.direction': 'Rjochting',
  'field.directionHelp': 'Bepaalt de standertpylkpunten; per ein te oerskriuwen ûnder Werjefte',
  'field.oneWay': 'Ienrjochting →',
  'field.bidirectional': 'Twarjochting ↔',
  'field.colour': 'Kleur',
  'field.edgeColour': 'Linekleur',
  'field.lineStyle': 'Linestyl',
  'field.routing': 'Rûtearring',
  'field.routingHelp': 'Hânmjittige knikpunten geane hjir, as se der binne, oerhinne',
  'field.source': 'Boarne',
  'field.target': 'Doel',
  'field.leavesFrom': 'Fertrekt fan',
  'field.arrivesAt': 'Komt oan by',
  'field.resetDefault': 'Werom nei standert',
  'field.clear': '{name} wiskje',

  'tab.general': 'Algemien',
  'tab.appearance': 'Werjefte',
  'tab.data': 'Gegevens',

  'option.default': 'Standert',
  'option.rounded': 'Ôfrûne',
  'option.sharp': 'Skerp',
  'option.subtle': 'Beskieden',
  'option.stickman': 'Stokpopke',
  'option.iconSmall': 'Lyts (kop)',
  'option.iconLarge': 'Grut (romp)',
  'option.solidDefault': 'Trochlutsen (standert)',
  'option.dashed': 'Streekjes',
  'option.dotted': 'Stippen',
  'option.smoothDefault': 'Floeiend (standert)',
  'option.arrow': 'Pylk',

  'section.operationalAspects': 'OPERASJONELE ASPEKTEN',
  'section.domainGroup': 'DOMEINGROEP',
  'section.tidyGroup': 'GROEP OPRÊDE',
  'section.connection': 'Ferbining',
  'section.route': 'Rûte',

  'element.noData': 'Gjin operasjonele gegevens foar dit elemint.',
  'element.deleteApplication': 'Applikaasje fuortsmite…',
  'element.removeDelete': 'Fuorthelje / fuortsmite…',

  'group.membersOne': '{count} elemint deryn',
  'group.membersOther': '{count} eleminten deryn',
  'group.remove': 'Groep fuorthelje',
  'group.removeNote':
    'It flak fuorthelje lit de eleminten op it tekenflak stean — se hearre allinnich net mear by in groep.',
  'group.tidyApply': '{name} oprêde',
  'group.tidyApplyAny': 'Groep oprêde',

  'route.none': 'Gjin',
  'route.auto': 'Automatysk',
  'route.manual': 'Mei de hân',
  'route.noteNone': 'Rjocht tusken de twa eleminten tekene; in rûtearslach kin him bûge.',
  'route.noteAuto': 'Troch de router lein; de folgjende rûtearslach kin him ferpleatse.',
  'route.noteManual': 'Automatysk rûtsjen lit dizze line stean wêr’t jo him lein hawwe.',
  'route.bendsOne': '1 knik',
  'route.bendsOther': '{count} knikken',
  'route.pinned': 'fêstset',
  'route.pin': 'Fêstsette',
  'route.unpin': 'Losmeitsje',
  'route.resetToAutomatic': 'Werom nei automatysk',
  'route.leavesFromSide': 'Fertrekt fan {name}',
  'route.arrivesAtSide': 'Komt oan by {name}',
  'route.deleteConnection': 'Ferbining fuortsmite',

  'tidy.direction': 'Rjochting',
  'tidy.auto': 'Auto',
  'tidy.across': 'Breed',
  'tidy.down': 'Djip',
  'tidy.hybrid': 'Mingd',
  'tidy.hybridTip': 'Groepen neist elkoar, de applikaasjes yn elke groep ûnder elkoar',
  'tidy.density': 'Tichtens',
  'tidy.compact': 'Kompakt',
  'tidy.normal': 'Normaal',
  'tidy.spacious': 'Rom',
  'tidy.pinAnchors': 'Ankerpunten fêstsette',
  'tidy.pinAnchorsNote': 'Knikpunten en labels dy’t jo sels lein hawwe, bliuwe stean.',
  'tidy.pinBoundary': 'De applikaasjegrins fêstsette',
  'tidy.pinBoundaryNote': 'De grins bliuwt stean; allinnich wat deryn sit wurdt opnij yndield.',
  'tidy.pinGroups': 'Groepsflakken fêstsette',
  'tidy.pinGroupsNote': 'Groepen bliuwe stean; allinnich wat deryn sit wurdt opnij yndield.',
  'tidy.pinBoundaryContents': 'De ynhâld fêstsette',
  'tidy.pinBoundaryContentsNote':
    'De komponinten hâlde har yndieling; de grins mei noch ferskowe.',
  'tidy.pinGroupContents': 'Groepsynhâld fêstsette',
  'tidy.pinGroupContentsNote': 'Wat der yn elke groep sit, hâldt syn yndieling.',

  'logo.search': 'Ikoanen sykje',
  'logo.none': 'Gjin',
  'logo.upload': 'In logo oplade',
  'logo.picker': 'Ikoankiezer',
  'logo.category.uploaded': 'Opladen',
  'logo.noMatches': 'Gjin ikoanen komme oerien mei “{query}”.',
  'dialog.deleteTitle': '{what} fuortsmite?',
  'dialog.deleteThisConnection': 'dizze ferbining',
  'dialog.deleteFromModel': 'Smyt {what} út it model fuort. ',
  'dialog.deleteThemFromModel': 'Smyt se út it model fuort. ',
  'dialog.cascadeOne': '1 ferbining dy’t deroan hinget giet mei. ',
  'dialog.cascadeOther': '{count} ferbiningen dy’t deroan hingje geane mei. ',
  'dialog.groupBoxesRemoved': 'Groepsflakken ferdwine; de eleminten deryn bliuwe. ',
  'dialog.canUndo': 'Jo kinne dit ûngedien meitsje.',
  'dialog.deleteElementTitle': '“{name}” fuortsmite?',
  'dialog.deleteElementKeeps': 'hâldt it elemint yn it model (en op oare diagrammen).',
  'dialog.deleteElementRemoves': 'hellet it oeral fuort, ynklusyf de ferbiningen.',
  'dialog.removeFromDiagram': 'Út it diagram helje',
  'dialog.deleteFromModelButton': 'Út it model fuortsmite',
  'dialog.deleteComponentsFirst': 'Smyt earst har komponinten fuort of hingje se earne oars ûnder',
  'dialog.renameDiagram': 'Diagram omneame',

  'diagramSettings.title': 'Diagramynstellingen',
  'diagramSettings.presentation': 'OP DE TEKENING',
  'diagramSettings.presentationHelp':
    'Wat de eksportearre PNG oer dit diagram fermeldt. Neat hjirfan feroaret it model.',
  'diagramSettings.author': 'Auteur',
  'diagramSettings.authorPlaceholder': 'Wa’t it tekene hat',
  'diagramSettings.client': 'Klant',
  'diagramSettings.clientHelp': 'Lit leech foar {name}.',
  'diagramSettings.date': 'Datum',
  'diagramSettings.dateHelp': 'Lit leech om de dei fan eksportearjen te stimpeljen.',
  'diagramSettings.showTitleBlock': 'Titelblok tekenje',
  'diagramSettings.aspects': 'RIPENSKOLOMMEN',
  'diagramSettings.aspectsHelp':
    'De badges ûnder elke applikaasje, yn dizze folchoarder. Neam se om nei jo eigen yndieling, jou in badge in eigen koade, of lit fuort wat jo net byhâlde.',
  'diagramSettings.showAspects': 'Ripensbadges toane',
  'diagramSettings.hiddenNote': 'Ferburgen. De kolommen hjirûnder bliuwe bewarre en komme werom as jo dit wer oansette.',
  'diagramSettings.columnLabel': 'Kolom',
  'diagramSettings.columnCode': 'Badge',
  'diagramSettings.codePlaceholder': 'auto',
  'diagramSettings.addStandard': 'Standert taheakje…',
  'diagramSettings.addCustom': 'Sels taheakje',
  'diagramSettings.newColumn': 'Nije kolom',
  'diagramSettings.reset': 'Werom nei de standert fiif',
  'diagramSettings.remove': '{name} fuorthelje',
  'diagramSettings.moveUp': '{name} omheech',
  'diagramSettings.moveDown': '{name} omleech',
  'diagramSettings.noColumns': 'Gjin kolommen. Applikaasjes toane hielendal gjin ripensbadges.',
  'diagramSettings.allStandardUsed': 'Elke standertkolom stiet der al',

  'help.title': 'Fluchtoetsen',
  'help.intro':
    'Klik mei rjochts op in elemint, in line, in domeingroep, in diagramtabblêd of it lege tekenflak foar in menu mei alles wat dêr kin. De fluchtoetsen hjirûnder steane neist de byhearrende menu-yngongen.',
  'shortcutGroup.selection': 'Seleksje',
  'shortcutGroup.edit': 'Bewurkje',
  'shortcutGroup.view': 'Byld',
  'shortcutGroup.general': 'Algemien',
  'shortcut.select-all': 'Alles selektearje',
  'shortcut.deselect': 'Seleksje opheffe',
  'shortcut.copy': 'Kopiearje',
  'shortcut.paste': 'Plakke',
  'shortcut.cut': 'Knippe',
  'shortcut.duplicate': 'Op it plak duplisearje',
  'shortcut.delete': 'Fuortsmite',
  'shortcut.rename': 'Omneame',
  'shortcut.nudge': 'Ferskowe (roasterstap)',
  'shortcut.nudge-fine': 'Ferskowe (1px)',
  'shortcut.undo': 'Ûngedien meitsje',
  'shortcut.redo': 'Opnij dwaan',
  'shortcut.zoom-in': 'Ynzoome',
  'shortcut.zoom-out': 'Útzoome',
  'shortcut.fit-view': 'Passend meitsje',
  'shortcut.zoom-100': 'Zoom nei 100%',
  'shortcut.force-save': 'No bewarje',
  'shortcut.context-menu': 'Kontekstmenu iepenje',
  'shortcut.help': 'Fluchtoetsen',
  'shortcut.find': 'Elemint sykje',

  'error.diagramNotFound': 'Diagram net fûn — jou in jildige activeDiagramId mei.',
  'error.overCap':
    'Dit diagram hat in groep fan {total} ferbiningen; rûtsjen giet oant {max} tagelyk, dus dy linen koene net automatysk rûte wurde.',
  'error.tidyRoutingUnattended':
    'Dit diagram is yndield, mar de ferbiningen koene net rûte wurde.',
  'error.tidyRouting':
    'De eleminten binne yndield, mar de ferbiningen koene net rûte wurde. Ferfarskje de side en besykje it opnij.',
  'error.tidyUnattended': 'Dit diagram koe net automatysk yndield wurde.',
  'error.tidy': 'Oprêden is mislearre. Ferfarskje de side en besykje it opnij.',
  'error.tidyTooLarge':
    'Dit diagram is te grut om op te rêden: it hat {count} blokken en oprêden docht der '
    + 'op syn heechst {limit}. Diel it op yn groepen of ferdiel it oer meardere diagrammen.',
  'error.tidyGroup':
    'De groep is oprêden, mar de ferbiningen koene net rûte wurde. Ferfarskje de side en besykje it opnij.',
  'error.tidyGroupFailed':
    'De groep oprêde is mislearre. Ferfarskje de side en besykje it opnij.',
  'error.route':
    'De ferbiningen koene net rûte wurde. Ferfarskje de side en besykje it opnij.',
  'error.routeOne':
    'De ferbining koe net rûte wurde. Ferfarskje de side en besykje it opnij.',
  'error.export': 'De PNG-eksport is mislearre. Ferfarskje de side en besykje it opnij.',
  'note.overCap': 'dit diagram hat mear ferbiningen as rûtsjen oankin',
  'note.reclassify':
    'druk ien kear op ‘Ferbiningen rûtsje’ sadat de besteande linen fan dit diagram bewege meie',

  'format.perMonth': '{amount}/mn.',
  'export.client': 'KLANT',
  'export.title': 'TITEL',
  'export.author': 'AUTEUR',
  'export.date': 'DATUM',
  'export.asOf': 'per {date}',
  'export.aspects': 'ASPEKTEN',

  // --- The C4 corner of a container diagram --------------------------------
  'c4.containerTitle': '[Container] {name}',
  'c4.containerDescription': 'It containerdiagram fan {name}.',
  'c4.applicationTag': '{name} [Applikaasje]',

  'menu.openDocumentation': 'Dokumintaasje iepenje',
  'shortcut.open-documentation': 'Dokumintaasje iepenje',
  'node.hasDocumentation': 'Hat dokumintaasje — rjochtsklik om te iepenjen',
}
