/**
 * Dutch, for the canvas and everything docked to it — menus, inspectors, the toolbar.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a Dutch screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'kind.domainGroup': 'Domeingroep',

  'newName.actor': 'Nieuwe actor',
  'newName.application': 'Nieuwe applicatie',
  'newName.component': 'Nieuw component',
  'newName.externalSystem': 'Nieuw extern systeem',
  'newName.inputChannel': 'Nieuw invoerkanaal',
  'newName.managementTool': 'Nieuwe beheertool',
  'newName.domainGroup': 'Nieuwe groep',

  'lifecycle.planned': 'Gepland',
  'lifecycle.live': 'In gebruik',
  'lifecycle.retiring': 'Uitfaseren',
  'lifecycle.retired': 'Uitgefaseerd',
  'lifecycleNote.planned': 'komt eraan, nog niet in gebruik',
  'lifecycleNote.live': 'actief — zonder badge getoond',
  'lifecycleNote.retiring': 'wordt afgebouwd',
  'lifecycleNote.retired': 'uit dienst, gedimd',

  'aspect.managed': 'Beheerd',
  'aspect.partial': 'Deels',
  'aspect.atRisk': 'Risico',
  'aspect.none': 'Geen',

  'side.auto': 'Automatisch',
  'side.top': 'Boven',
  'side.right': 'Rechts',
  'side.bottom': 'Onder',
  'side.left': 'Links',

  'shape.smooth': 'Vloeiend',
  'shape.orthogonal': 'Haaks',
  'shape.straight': 'Recht',
  'shape.curved': 'Gebogen',

  'align.left': 'Links',
  'align.centerX': 'Midden',
  'align.right': 'Rechts',
  'align.top': 'Boven',
  'align.centerY': 'Midden',
  'align.bottom': 'Onder',
  'zone.resizeBand': 'Baan {name} van formaat veranderen',
  'zone.resizeCanvas': 'Canvas {name} van formaat veranderen',

  'menu.openContainer': 'Containeraanzicht openen',
  'menu.createContainer': 'Containeraanzicht maken',
  'menu.rename': 'Hernoemen',
  'menu.startConnection': 'Koppeling starten naar…',
  'menu.icon': 'Pictogram…',
  'menu.lifecycle': 'Levenscyclus',
  'menu.moveToZone': 'Naar zone verplaatsen',
  'menu.changeKind': 'Soort wijzigen',
  'menu.domainGroup': 'Domeingroep',
  'menu.duplicate': 'Dupliceren',
  'menu.copy': 'Kopiëren',
  'menu.cut': 'Knippen',
  'menu.removeFromDiagram': 'Uit dit aanzicht halen',
  'menu.deleteFromModel': 'Uit het model verwijderen…',
  'menu.boundaryApplication': 'Deze applicatie is de begrenzing van dit aanzicht',
  'menu.addBend': 'Hier een knikpunt toevoegen',
  'menu.removeBend': 'Knikpunt verwijderen',
  'menu.removeAllBends': 'Alle knikpunten verwijderen',
  'menu.noBendPoints': 'Deze lijn heeft geen knikpunten',
  'menu.pinRoute': 'Route vastzetten',
  'menu.unpinRoute': 'Route losmaken',
  'menu.resetRoute': 'Terug naar automatische route',
  'menu.layoutBusy': 'Er loopt een indelingsactie',
  'menu.attachAt': 'Aanhechten aan',
  'menu.attachSource': 'Bron',
  'menu.attachTarget': 'Doel',
  'menu.lineShape': 'Lijnvorm',
  'menu.direction': 'Richting',
  'menu.oneWay': 'Eenrichting',
  'menu.twoWay': 'Tweerichting',
  'menu.reverse': 'Omdraaien',
  'menu.editLabel': 'Label bewerken',
  'menu.resetLabelPosition': 'Labelpositie herstellen',
  'menu.labelAutomatic': 'Het label staat op zijn automatische plek',
  'menu.deleteConnection': 'Koppeling verwijderen',
  'menu.pasteHere': 'Hier plakken',
  'menu.nothingToPaste': 'Niets om te plakken',
  'menu.addHere': 'Hier toevoegen',
  'menu.addDomainGroupHere': 'Hier een domeingroep toevoegen',
  'menu.selectAll': 'Alles selecteren',
  'menu.tidy': 'Indeling opschonen',
  'menu.routeConnections': 'Koppelingen routeren',
  'menu.routeConnectionsAll': 'Alles opnieuw routeren (negeer vastgezette routes)',
  'menu.fitView': 'Passend maken',
  'menu.showGrid': 'Raster tonen',
  'menu.snapToGrid': 'Uitlijnen op raster',
  'menu.align': 'Uitlijnen',
  'menu.distribute': 'Verdelen',
  'menu.distributeHorizontally': 'Horizontaal',
  'menu.distributeVertically': 'Verticaal',
  'menu.needThreeElements': 'Selecteer minstens drie elementen',
  'menu.groupIntoDomainGroup': 'Samenvoegen in een nieuwe domeingroep',
  'menu.needLandscapeElements': 'Selecteer elementen op het applicatielandschap',
  'menu.delete': 'Verwijderen',
  'menu.tidyGroup': 'Deze groep opschonen',
  'menu.groupColor': 'Groepskleur…',
  'menu.selectMembers': 'Leden selecteren',
  'menu.removeGroup': 'Groep verwijderen',
  'menu.renameDiagram': 'Aanzicht hernoemen…',
  'menu.diagramSettings': 'Aanzichtinstellingen…',
  'menu.duplicateDiagram': 'Aanzicht dupliceren',
  'menu.deleteDiagram': 'Aanzicht verwijderen…',
  'menu.lastLandscape': 'Het laatste landschap kan niet worden verwijderd',
  'menu.nodeLabel': 'Elementmenu',
  'menu.edgeLabel': 'Koppelingsmenu',
  'menu.paneLabel': 'Canvasmenu',
  'menu.groupLabel': 'Domeingroepmenu',
  'menu.selectionLabel': 'Selectiemenu',
  'menu.tabLabel': 'Aanzichtmenu',
  'menu.contextLabel': 'Contextmenu',
  'menu.shortcutAria': 'Sneltoets {keys}',

  'palette.aside': 'Elementenpalet',
  'palette.addToCanvas': 'Aan het canvas toevoegen',
  'palette.expand': 'Palet uitklappen',
  'palette.collapse': 'Palet inklappen',
  'palette.place': 'Plaatsen',
  'palette.add': '{name} toevoegen',
  'palette.openOptions': 'Opties voor {name} openen',
  'palette.nameField': 'Naam van {name}',
  'palette.logo': 'Logo',
  'palette.colour': 'Kleur',
  'palette.groupColour': 'Kleur van de domeingroep',
  'palette.resize': 'Breedte van het palet aanpassen',
  'palette.search': 'In het palet zoeken',
  'palette.searchPlaceholder': 'Zoeken…',
  'palette.noMatches': 'Niets komt overeen met “{query}”',
  'palette.section.systems': 'Applicaties & componenten',
  'palette.section.integration': 'Integratie',
  'palette.section.people': 'Mensen & context',
  'paletteDescription.application': 'Een systeem dat de klant draait of afneemt',
  'paletteDescription.component': 'Een onderdeel binnen één applicatie',
  'paletteDescription.inputChannel': 'Hoe werk en gegevens het landschap binnenkomen',
  'paletteDescription.externalSystem': 'Een systeem buiten de invloed van de klant',
  'paletteDescription.managementTool': 'Gereedschap dat het landschap draait en bewaakt',
  'paletteDescription.actor': 'Een persoon of rol die het landschap gebruikt',
  'paletteDescription.domainGroup': 'Een benoemd vlak dat het landschap groepeert',

  'toolbar.newDiagram': 'Nieuw Layer 7-aanzicht',
  'toolbar.readOnly': 'Alleen-lezen',
  'toolbar.undo': 'Ongedaan maken',
  'toolbar.undoTip': 'Ongedaan maken (⌘Z)',
  'toolbar.redo': 'Opnieuw',
  'toolbar.redoTip': 'Opnieuw (⌘⇧Z)',
  'toolbar.tidy': 'Indeling opschonen',
  'toolbar.tidyTip': 'Indeling opschonen (ELK)',
  'toolbar.cancelTidy': 'Opschonen annuleren',
  'toolbar.tidySettings': 'Instellingen voor opschonen',
  'toolbar.routeOnly': 'Alleen koppelingen routeren',
  'toolbar.routeOnlyTip': 'Alleen koppelingen routeren (elementen blijven staan)',
  'toolbar.autoRoute': 'Koppelingen automatisch routeren',
  'toolbar.autoRouteOn':
    'Automatisch routeren: aan — lijnen lopen mee wanneer je een element verplaatst',
  'toolbar.autoRouteOff': 'Automatisch routeren: uit',
  'toolbar.fitView': 'Passend maken',
  'toolbar.exportPng': 'PNG exporteren',
  'toolbar.exportingPng': 'Bezig met PNG exporteren…',
  'export.largeTitle': 'Dit grote aanzicht exporteren?',
  'export.largeBody':
    'Dit bord levert een afbeelding van {width} bij {height}, ongeveer {megapixels} megapixels. '
    + 'Tekenen kan even duren en het venster reageert intussen niet.',
  'export.largeConfirm': 'Toch exporteren',
  'toolbar.lifecycleBadges': 'Levenscyclusbadges tonen of verbergen',
  'toolbar.shortcuts': 'Sneltoetsen',
  'toolbar.search': 'Element zoeken',
  'toolbar.searchTip': 'Een element zoeken (⌘F)',
  'toolbar.minimap': 'Overzichtskaartje tonen of verbergen',
  'toolbar.minimapOn': 'Overzichtskaartje: aan',
  'toolbar.minimapOff': 'Overzichtskaartje: uit',
  'toolbar.languageTip': 'Taal — {name}',
  'toolbar.containerDiagrams': 'Containeraanzichten op dit landschap',
  'toolbar.containerDiagramsOf': 'Containeraanzichten van {name}',
  'toolbar.diagramSettings': 'Aanzichtinstellingen, met de volwassenheidskolommen',
  'toolbar.diagramSettingsOf': 'Instellingen van {name}',
  'toolbar.containerView': 'Containeraanzicht',
  'toolbar.backTo': 'Terug naar {name}',
  'toolbar.backToLandscape': 'Terug naar het landschap',

  'canvas.connectHint': 'Klik een doelelement aan — Esc annuleert',
  'canvas.gridOn': 'Raster: aan',
  'canvas.gridOff': 'Raster: uit',
  'canvas.gridToggle': 'Raster tonen of verbergen',
  'canvas.snapOn': 'Uitlijnen op raster: aan',
  'canvas.snapOff': 'Uitlijnen op raster: uit',
  'canvas.snapToggle': 'Uitlijnen op raster aan of uit',
  'canvas.alignLeft': 'Links uitlijnen',
  'canvas.alignCenterX': 'Horizontale middens uitlijnen',
  'canvas.alignRight': 'Rechts uitlijnen',
  'canvas.alignTop': 'Boven uitlijnen',
  'canvas.alignCenterY': 'Verticale middens uitlijnen',
  'canvas.alignBottom': 'Onder uitlijnen',
  'canvas.distributeHorizontally': 'Horizontaal verdelen',
  'canvas.distributeVertically': 'Verticaal verdelen',
  'canvas.groupName': 'Naam van de domeingroep',
  'canvas.groupNamed': 'Domeingroep {name}',
  'canvas.resizeGroup': 'Domeingroep {name} van formaat veranderen',
  'canvas.groupColour': 'Groepskleur',
  'canvas.minimap': 'Overzichtskaartje',
  'node.actorFigure': 'Actorfiguur',
  'node.external': 'EXTERN',
  'node.hasContainer': 'Heeft een containeraanzicht — dubbelklik om te openen',
  'node.lifecycleAria': 'Levenscyclus: {name}',
  'edge.labelPlaceholder': 'Omschrijving van het koppelvlak…',

  'inspector.aside': 'Inspector',
  'inspector.expand': 'Inspector uitklappen',
  'inspector.collapse': 'Inspector inklappen',
  'inspector.resize': 'Breedte van de inspector aanpassen',
  'inspector.empty':
    'Selecteer een element of koppeling om de eigenschappen te bewerken. Dubbelklik een applicatie om haar containeraanzicht te openen.',
  'inspector.aspectBadges': 'ASPECTBADGES',
  'inspector.selected': '{count} geselecteerd',
  'inspector.elementsOne': '{count} element',
  'inspector.elementsOther': '{count} elementen',
  'inspector.connectionsOne': '{count} koppeling',
  'inspector.connectionsOther': '{count} koppelingen',
  'inspector.groupsOne': '{count} domeingroep',
  'inspector.groupsOther': '{count} domeingroepen',
  'inspector.multiHint':
    'Sleep een geselecteerd element om ze samen te verplaatsen. Shift-klik voegt toe of haalt weg; Escape maakt de selectie leeg.',
  'inspector.bulkTitle': 'OP ALLES TOEPASSEN',
  'inspector.bulkLifecycle': 'Levenscyclus',
  'inspector.bulkColour': 'Accentkleur',
  'inspector.bulkColourAria': 'Accentkleur voor de selectie',
  'inspector.bulkIcon': 'Pictogram',
  'inspector.bulkDomainGroup': 'Domeingroep',
  'inspector.bulkNoChange': 'Ongewijzigd laten',
  'inspector.bulkNote': 'Elke wijziging is één stap in Ongedaan maken over de hele selectie.',

  'field.name': 'Naam',
  'field.category': 'Categorie',
  'field.vendor': 'Leverancier',
  'field.technology': 'Technologie',
  'field.lifecycle': 'Levenscyclus',
  'field.managed': 'Beheerd',
  'field.domainGroup': 'Domeingroep',
  'field.domainGroupPlaceholder': 'bijv. Commercie',
  'field.accentColour': 'Accentkleur',
  'field.shape': 'Vorm',
  'field.icon': 'Pictogram',
  'field.iconSize': 'Pictogramgrootte',
  'field.iconFirst': 'Kies eerst een pictogram',
  'field.placement': 'Plaatsing',
  'field.zone': 'Zone: {name}',
  'field.note': 'Notitie',
  'field.notePlaceholder': 'bijv. AKS, GitHub Actions',
  'field.noteAria': 'Notitie bij {name}',
  'field.notSet': 'Niet ingevuld',
  'field.label': 'Label',
  'field.labelPlaceholder': 'bijv. Stuurt orders',
  'field.labelHelp': 'Regeleindes breken het label op de plaat; het protocol staat eronder',
  'field.protocol': 'Protocol',
  'field.protocolPlaceholder': 'bijv. EDI, Kafka, REST',
  'field.direction': 'Richting',
  'field.directionHelp': 'Bepaalt de standaardpijlpunten; per uiteinde te overrulen bij Weergave',
  'field.oneWay': 'Eenrichting →',
  'field.bidirectional': 'Tweerichting ↔',
  'field.colour': 'Kleur',
  'field.edgeColour': 'Lijnkleur',
  'field.lineStyle': 'Lijnstijl',
  'field.routing': 'Routering',
  'field.routingHelp': 'Handmatige knikpunten gaan hier, als ze er zijn, overheen',
  'field.source': 'Bron',
  'field.target': 'Doel',
  'field.leavesFrom': 'Vertrekt vanaf',
  'field.arrivesAt': 'Komt aan bij',
  'field.resetDefault': 'Terug naar de standaard',
  'field.clear': '{name} wissen',

  'tab.general': 'Algemeen',
  'tab.appearance': 'Weergave',
  'tab.data': 'Gegevens',

  'option.default': 'Standaard',
  'option.rounded': 'Afgerond',
  'option.sharp': 'Scherp',
  'option.subtle': 'Ingetogen',
  'option.stickman': 'Poppetje',
  'option.iconSmall': 'Klein (kop)',
  'option.iconLarge': 'Groot (body)',
  'option.solidDefault': 'Doorgetrokken (standaard)',
  'option.dashed': 'Streepjes',
  'option.dotted': 'Stippen',
  'option.smoothDefault': 'Vloeiend (standaard)',
  'option.arrow': 'Pijl',

  'section.operationalAspects': 'OPERATIONELE ASPECTEN',
  'section.parameters': 'PARAMETERS',
  'section.domainGroup': 'DOMEINGROEP',
  'section.tidyGroup': 'GROEP OPSCHONEN',
  'section.connection': 'Koppeling',
  'section.route': 'Route',

  'element.noData': 'Geen operationele gegevens voor dit element.',
  'element.deleteApplication': 'Applicatie verwijderen…',
  'element.removeDelete': 'Weghalen / verwijderen…',

  'group.membersOne': '{count} element erin',
  'group.membersOther': '{count} elementen erin',
  'group.remove': 'Groep verwijderen',
  'group.removeNote':
    'Het vlak weghalen laat de elementen op het canvas staan — ze horen alleen niet meer bij een groep.',
  'group.tidyApply': '{name} opschonen',
  'group.tidyApplyAny': 'Groep opschonen',

  'route.none': 'Geen',
  'route.auto': 'Automatisch',
  'route.manual': 'Met de hand',
  'route.noteNone': 'Recht tussen de twee elementen getekend; een routeerslag kan hem buigen.',
  'route.noteAuto': 'Door de router gelegd; de volgende routeerslag kan hem verplaatsen.',
  'route.noteManual': 'Automatisch routeren laat deze lijn staan waar je hem legde.',
  'route.bendsOne': '1 knik',
  'route.bendsOther': '{count} knikken',
  'route.pinned': 'vastgezet',
  'route.pin': 'Vastzetten',
  'route.unpin': 'Losmaken',
  'route.resetToAutomatic': 'Terug naar automatisch',
  'route.leavesFromSide': 'Vertrekt vanaf {name}',
  'route.arrivesAtSide': 'Komt aan bij {name}',
  'route.deleteConnection': 'Koppeling verwijderen',

  'tidy.direction': 'Richting',
  'tidy.auto': 'Auto',
  'tidy.across': 'Breed',
  'tidy.down': 'Diep',
  'tidy.hybrid': 'Gemengd',
  'tidy.hybridTip': 'Groepen naast elkaar, de applicaties binnen elke groep onder elkaar',
  'tidy.density': 'Dichtheid',
  'tidy.compact': 'Compact',
  'tidy.normal': 'Normaal',
  'tidy.spacious': 'Ruim',
  'tidy.pinAnchors': 'Aanhechtpunten vastzetten',
  'tidy.pinAnchorsNote': 'Knikpunten en labels die je zelf hebt gelegd blijven staan.',
  'tidy.pinBoundary': 'De applicatiebegrenzing vastzetten',
  'tidy.pinBoundaryNote': 'De begrenzing blijft staan; alleen wat erin zit wordt opnieuw ingedeeld.',
  'tidy.pinGroups': 'Groepsvlakken vastzetten',
  'tidy.pinGroupsNote': 'Groepen blijven staan; alleen wat erin zit wordt opnieuw ingedeeld.',
  'tidy.pinBoundaryContents': 'De inhoud vastzetten',
  'tidy.pinBoundaryContentsNote':
    'De componenten houden hun indeling; de begrenzing mag nog verschuiven.',
  'tidy.pinGroupContents': 'Groepsinhoud vastzetten',
  'tidy.pinGroupContentsNote': 'Wat er in elke groep zit houdt zijn indeling.',

  'logo.search': 'Pictogrammen zoeken',
  'logo.none': 'Geen',
  'logo.upload': 'Een logo uploaden',
  'logo.picker': 'Pictogramkiezer',
  'logo.category.uploaded': 'Geüpload',
  'logo.noMatches': 'Geen pictogrammen komen overeen met “{query}”.',
  'dialog.deleteTitle': '{what} verwijderen?',
  'dialog.deleteThisConnection': 'deze koppeling',
  'dialog.deleteFromModel': 'Verwijdert {what} uit het model. ',
  'dialog.deleteThemFromModel': 'Verwijdert ze uit het model. ',
  'dialog.cascadeOne': '1 koppeling die eraan hangt gaat mee. ',
  'dialog.cascadeOther': '{count} koppelingen die eraan hangen gaan mee. ',
  'dialog.groupBoxesRemoved': 'Groepsvlakken verdwijnen; de elementen erin blijven. ',
  'dialog.canUndo': 'Je kunt dit ongedaan maken.',
  'dialog.deleteElementTitle': '“{name}” verwijderen?',
  'dialog.deleteElementKeeps': 'houdt het element in het model (en op andere aanzichten).',
  'dialog.deleteElementRemoves': 'haalt het overal weg, inclusief de koppelingen.',
  'dialog.removeFromDiagram': 'Uit dit aanzicht halen',
  'dialog.deleteFromModelButton': 'Uit het model verwijderen',
  'dialog.deleteComponentsFirst': 'Verwijder eerst haar componenten of hang ze elders onder',
  'dialog.renameDiagram': 'Aanzicht hernoemen',

  'diagramSettings.title': 'Aanzichtinstellingen',
  'diagramSettings.presentation': 'OP DE TEKENING',
  'diagramSettings.presentationHelp':
    'Wat de geëxporteerde PNG over dit aanzicht vermeldt. Niets hiervan verandert het model.',
  'diagramSettings.author': 'Auteur',
  'diagramSettings.authorPlaceholder': 'Wie het getekend heeft',
  'diagramSettings.client': 'Klant',
  'diagramSettings.clientHelp': 'Laat leeg voor {name}.',
  'diagramSettings.date': 'Datum',
  'diagramSettings.dateHelp': 'Laat leeg om de dag van exporteren te stempelen.',
  'diagramSettings.showTitleBlock': 'Titelblok tekenen',
  'diagramSettings.aspects': 'VOLWASSENHEIDSKOLOMMEN',
  'diagramSettings.aspectsHelp':
    'De badges onder elke applicatie, in deze volgorde. Hernoem ze naar je eigen indeling, geef een badge een eigen code, of laat weg wat je niet bijhoudt.',
  'diagramSettings.showAspects': 'Volwassenheidsbadges tonen',
  'diagramSettings.hiddenNote': 'Verborgen. De kolommen hieronder blijven bewaard en komen terug als je dit weer aanzet.',
  'diagramSettings.columnLabel': 'Kolom',
  'diagramSettings.columnCode': 'Badge',
  'diagramSettings.codePlaceholder': 'auto',
  'diagramSettings.addStandard': 'Standaard toevoegen…',
  'diagramSettings.addCustom': 'Zelf toevoegen',
  'diagramSettings.newColumn': 'Nieuwe kolom',
  'diagramSettings.reset': 'Terug naar de standaard vijf',
  'diagramSettings.remove': '{name} verwijderen',
  'diagramSettings.moveUp': '{name} omhoog',
  'diagramSettings.moveDown': '{name} omlaag',
  'diagramSettings.noColumns': 'Geen kolommen. Applicaties tonen helemaal geen volwassenheidsbadges.',
  'diagramSettings.allStandardUsed': 'Elke standaardkolom staat er al',

  'help.title': 'Sneltoetsen',
  'help.intro':
    'Klik met rechts op een element, een lijn, een domeingroep, een tabblad of het lege canvas voor een menu met alles wat daar kan. De sneltoetsen hieronder staan naast de bijbehorende menu-ingangen.',
  'shortcutGroup.selection': 'Selectie',
  'shortcutGroup.edit': 'Bewerken',
  'shortcutGroup.view': 'Beeld',
  'shortcutGroup.general': 'Algemeen',
  'shortcut.select-all': 'Alles selecteren',
  'shortcut.deselect': 'Selectie opheffen',
  'shortcut.copy': 'Kopiëren',
  'shortcut.paste': 'Plakken',
  'shortcut.cut': 'Knippen',
  'shortcut.duplicate': 'Ter plekke dupliceren',
  'shortcut.delete': 'Verwijderen',
  'shortcut.rename': 'Hernoemen',
  'shortcut.nudge': 'Verschuiven (rasterstap)',
  'shortcut.nudge-fine': 'Verschuiven (1px)',
  'shortcut.undo': 'Ongedaan maken',
  'shortcut.redo': 'Opnieuw',
  'shortcut.zoom-in': 'Inzoomen',
  'shortcut.zoom-out': 'Uitzoomen',
  'shortcut.fit-view': 'Passend maken',
  'shortcut.zoom-100': 'Zoom naar 100%',
  'shortcut.force-save': 'Nu bewaren',
  'shortcut.context-menu': 'Contextmenu openen',
  'shortcut.help': 'Sneltoetsen',
  'shortcut.find': 'Element zoeken',

  'error.diagramNotFound': 'Aanzicht niet gevonden — geef een geldige activeDiagramId mee.',
  'error.overCap':
    'Dit aanzicht heeft een groep van {total} koppelingen; routeren gaat tot {max} tegelijk, dus die lijnen konden niet automatisch worden gerouteerd.',
  'error.tidyRoutingUnattended':
    'Dit aanzicht is ingedeeld, maar de koppelingen konden niet worden gerouteerd.',
  'error.tidyRouting':
    'De elementen zijn ingedeeld, maar de koppelingen konden niet worden gerouteerd. Ververs de pagina en probeer het opnieuw.',
  'error.tidyUnattended': 'Dit aanzicht kon niet automatisch worden ingedeeld.',
  'error.tidy': 'Opschonen is mislukt. Ververs de pagina en probeer het opnieuw.',
  'error.tidyTooLarge':
    'Dit aanzicht is te groot om op te schonen: het heeft {count} blokken en opschonen doet er '
    + 'hoogstens {limit}. Deel het op in groepen of verdeel het over meerdere aanzichten.',
  'error.tidyGroup':
    'De groep is opgeschoond, maar de koppelingen konden niet worden gerouteerd. Ververs de pagina en probeer het opnieuw.',
  'error.tidyGroupFailed':
    'De groep opschonen is mislukt. Ververs de pagina en probeer het opnieuw.',
  'error.route':
    'De koppelingen konden niet worden gerouteerd. Ververs de pagina en probeer het opnieuw.',
  'error.routeOne':
    'De koppeling kon niet worden gerouteerd. Ververs de pagina en probeer het opnieuw.',
  'error.export': 'De PNG-export is mislukt. Ververs de pagina en probeer het opnieuw.',
  'note.overCap': 'dit aanzicht heeft meer koppelingen dan routeren aankan',
  'note.reclassify':
    'druk één keer op ‘Koppelingen routeren’ zodat de bestaande lijnen van dit aanzicht mogen bewegen',

  'format.perMonth': '{amount}/mnd',
  'export.client': 'KLANT',
  'export.title': 'TITEL',
  'export.author': 'AUTEUR',
  'export.date': 'DATUM',
  'export.aspects': 'ASPECTEN',

  'menu.openDocumentation': 'Documentatie openen',
  'shortcut.open-documentation': 'Documentatie openen',
  'node.hasDocumentation': 'Heeft documentatie — rechtsklik om te openen',
}
