// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/**
 * German, for the model speaks: element kinds, zones, the refusals a rule returns.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a German screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {

  'kind.actor': 'Akteur',
  'kind.step': 'Schritt',
  'kind.function': 'Funktion',
  'kind.process': 'Prozess',
  'kind.application': 'Anwendung',
  'kind.component': 'Komponente',
  'kind.platform': 'Plattform',
  'kind.platformService': 'Plattformdienst',
  'placement.notOnACanvas': 'Ein {kind} wird auf dieser Art von Ansicht nicht gezeichnet.',

  'relation.flow': 'Verbindung',
  'relation.supports': 'Unterstützt',
  'relation.serves': 'Bedient',
  'relation.realises': 'Liefert',
  'relation.assigned': 'Zugewiesen an',
  'relation.uses': 'Nutzt',
  'relation.hostedOn': 'Läuft auf',
  'platformArchetype.place': 'Ort',
  'platformArchetype.service': 'Dienst',
  'platformArchetype.network': 'Netzwerk',

  'zone.actors': 'AKTEURE',
  'zone.inputChannels': 'EINGABEKANÄLE',
  'zone.externalSystems': 'EXTERNE SYSTEME',
  'zone.landscape': 'ANWENDUNGSLANDSCHAFT',
  'zone.management': 'VERWALTUNGSEBENE',
  'zoneMenu.actors': 'Akteure',
  'zoneMenu.inputChannels': 'Eingabekanäle',
  'zoneMenu.externalSystems': 'Externe Systeme',
  'zoneMenu.landscape': 'Anwendungslandschaft',
  'zoneMenu.management': 'Verwaltungsebene',
  'kindChange.sameKind': 'Es ist bereits von dieser Art',
  'kindChange.notOnThisDiagram': 'Dieses Element liegt nicht auf diesem Diagramm',
  'kindChange.hasContainerDiagram':
    'Diese Anwendung hat ein Container-Diagramm — löschen Sie zuerst diese Ansicht',
  'kindChange.hasParent': 'Diese Komponente gehört zu einer Anwendung — lösen Sie sie zuerst',
  'kindChange.hasComponents':
    'Diese Anwendung hat Komponenten — verschieben oder löschen Sie diese zuerst',
  'kindChange.notAllowedHere': 'Dieses Diagramm nimmt diese Art nicht auf',

  // --- what the one writer refuses (ADR-0002) ------------------------------
  'command.gone': 'Das ist nicht mehr da',
  'command.lastLandscape': 'Dies ist die letzte Landschaft, und ein Bereich beh\u00e4lt mindestens eine. Legen Sie zuerst eine andere Landschaft an und l\u00f6schen Sie dann diese.',
  'command.datesOutOfOrder': 'Lebenszyklusdaten laufen der Reihe nach: aktiv, dann auslaufend, dann weg, jedes am oder nach dem vorigen. Dieser Tag lie\u00dfe sie r\u00fcckw\u00e4rts laufen, deshalb wurde er nicht gespeichert.',
  'command.refinesEnds': 'Eine Container-Schnittstelle muss unter der Schnittstelle liegen, zu der sie geh\u00f6rt: ihre Quelle unter deren Quelle und ihr Ziel unter deren Ziel, jedes Ende dasselbe Element oder einer seiner Container. \u00c4ndern Sie die Enden, oder setzen Sie \u201eTeil von\u201c auf nichts, um sie zu l\u00f6sen.',
  'command.refinesLevel': 'Diese Schnittstelle geh\u00f6rt selbst schon zu einer anderen, und eine Schnittstelle landet einmal. W\u00e4hlen Sie stattdessen die Anwendungsschnittstelle, zu der sie geh\u00f6rt.',
  'command.hostedOnContainers': 'Eine Anwendung mit Containern läuft dort, wo ihre Container laufen. Sagen Sie es am Container.',
  'command.technologyEnds': 'Läuft auf geht von einer Anwendung oder einem Container zu einer Plattform. Eine Plattform in einer anderen ist darunter abgelegt, sie läuft nicht darauf.',
  'command.taken': 'Etwas hier hat diese Kennung bereits — jemand anders hat sie genommen, während diese Änderung entstand. Bitte noch einmal versuchen.',
  'command.notAField': 'Diese Änderung enthält ein Feld, das dieser Datensatz nicht hat, deshalb wurde nichts davon übernommen.',
  'command.ownedElsewhere': 'Dies ist ein Platzhalter: Lebenszyklus, Daten, Verantwortliche, Hersteller, Name und Beschreibung werden in dem Bereich geschrieben, der ihn definiert. \u00d6ffnen Sie diesen Bereich, um sie zu \u00e4ndern.',
  'restore.absentThen': 'Dies war bei diesem Schnappschuss nicht im Projekt.',
  'restore.absentNow': 'Das Element ist nicht mehr im Projekt; stellen Sie das ganze Projekt wieder her, um es zurückzuholen.',
  'restore.locked': 'Diese Entscheidung wurde angenommen, abgelehnt oder ersetzt, und ein abgeschlossener Eintrag wird nicht geändert. Schreiben Sie eine neue, die sie ersetzt.',
  'logo.category.data': 'Daten',
  'logo.category.integration': 'Integration',
  'logo.category.applications': 'Anwendungen',
  'logo.category.platform': 'Plattform',
  'logo.category.security': 'Sicherheit & Betrieb',
  'logo.category.vendors': 'Anbieter',

  'deletion.nothing': 'nichts',
  'deletion.elementOne': '{count} Element',
  'deletion.elementOther': '{count} Elemente',
  'deletion.connectionOne': '{count} Verbindung',
  'deletion.connectionOther': '{count} Verbindungen',
  'deletion.groupOne': '{count} Gruppe',
  'deletion.groupOther': '{count} Gruppen',
  'deletion.joined': '{head} und {last}',
  'deletion.withStandIns': '{what} — davon {count} Platzhalter, die dort bleiben, wo sie definiert sind',
  'shell.logoBadType': 'Nur SVG- und PNG-Dateien können als Logo hinzugefügt werden.',
  'shell.logoTooBig': 'Dieses Logo ist zu groß ({size} kB). Die Grenze liegt bei {max} kB.',
  'shell.logoUnreadable': 'Diese Datei konnte nicht gelesen werden.',
  'shell.imageBadType': 'Nur PNG-, JPEG-, SVG- und WebP-Dateien können in ein Dokument aufgenommen werden.',
  'shell.imageBadName': 'So kann ein Bild nicht heißen: Ein Name hat keine leeren Teile, keine Leerzeichen und keine Klammern und endet mit seinem Typ, etwa diagrams/context.png.',
  'shell.imageTooBig': 'Dieses Bild ist zu groß ({size} kB). Die Grenze liegt bei {max} kB.',
  'shell.imageUnreadable': 'Diese Datei konnte nicht gelesen werden.',

  'activity.nothing': 'Nichts',
  'activity.elementAdded': '{name} hinzugefügt',
  'activity.elementChanged': '{name} geändert',
  'activity.elementDeleted': '{name} gelöscht',
  'activity.standInsRefreshed': '{count} Platzhalter aktualisiert',
  'activity.elementLinked': '{name} verknüpft',
  'activity.relationAdded': 'Verbindung gezeichnet',
  'activity.relationChanged': 'Verbindung geändert',
  'activity.relationDeleted': 'Verbindung gelöscht',
  'activity.rowAdded': 'Zeile gezeichnet ({type})',
  'activity.rowChanged': 'Zeile geändert ({type})',
  'activity.rowDeleted': 'Zeile gelöscht ({type})',
  'activity.usesSet': 'Festgelegt, was {name} nutzt ({count} Zeilen)',
  'activity.movedOne': 'Ein Element verschoben',
  'activity.movedMany': '{count} Elemente verschoben',
  'activity.removedOne': 'Ein Element vom Diagramm genommen',
  'activity.removedMany': '{count} Elemente vom Diagramm genommen',
  'activity.routeChanged': 'Linienführung geändert',
  'activity.layoutChanged': 'Anordnung geändert',
  'activity.groupChanged': 'Gruppe {name} geändert',
  'activity.groupRemoved': 'Gruppe {name} entfernt',
  'activity.diagramAdded': 'Diagramm {name} hinzugefügt',
  'activity.diagramRenamed': 'Diagramm umbenannt in {name}',
  'activity.diagramSettings': 'Einstellungen von {name} geändert',
  'activity.diagramChanged': 'Diagramm {name} geändert',
  'activity.diagramDeleted': 'Diagramm {name} gelöscht',
  'activity.decisionAdded': 'Entscheidung {name} hinzugefügt',
  'activity.decisionChanged': 'Entscheidung {name} geändert',
  'activity.decisionRemoved': 'Entscheidung {name} entfernt',
  'activity.planAdded': 'Plan {name} hinzugefügt',
  'activity.planChanged': 'Plan {name} geändert',
  'activity.planRemoved': 'Plan {name} entfernt',
  'activity.observationAdded': 'Beobachtung {name} festgehalten',
  'activity.observationChanged': 'Beobachtung {name} geändert',
  'activity.observationRemoved': 'Beobachtung {name} entfernt',
  'activity.causeAdded': 'Ursache {name} hinzugefügt',
  'activity.causeChanged': 'Ursache {name} geändert',
  'activity.causeRemoved': 'Ursache {name} entfernt',
  'activity.solutionAdded': 'Lösung {name} hinzugefügt',
  'activity.solutionChanged': 'Lösung {name} geändert',
  'activity.solutionRemoved': 'Lösung {name} entfernt',
  'activity.experimentAdded': 'Experiment {name} hinzugefügt',
  'activity.experimentChanged': 'Experiment {name} geändert',
  'activity.experimentRemoved': 'Experiment {name} entfernt',
  'activity.projectSettings': 'Projekteinstellungen geändert',
  'activity.diagramRestored': 'Diagramm {name} wiederhergestellt auf den Stand vom {asOf}',
  'activity.descriptionRestored': 'Beschreibung von {name} wiederhergestellt auf den Stand vom {asOf}',
  'activity.decisionRestored': 'Entscheidung {name} wiederhergestellt auf den Stand vom {asOf}',
  'activity.projectRestored': 'Das ganze Projekt wiederhergestellt auf den Stand vom {asOf}',
}
