/**
 * German, for the documentation page and the markdown around it.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a German screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'field.description': 'Beschreibung',
  'field.descriptionMarkdown': 'Beschreibung (Markdown)',
  'field.descriptionPlaceholder': 'Was tut dieses Element? Markdown wird unterstützt.',
  'field.edit': 'Bearbeiten',
  'field.preview': 'Vorschau',
  'field.editDescription': 'Beschreibung bearbeiten',
  'field.previewDescription': 'Vorschau der Beschreibung',

  'doc.shortDescription': 'Kurzbeschreibung',
  'doc.owner': 'Verantwortlich',
  'doc.criticality': 'Geschäftskritikalität',
  'doc.users': 'Nutzer',
  'doc.dataClassification': 'Datenklassifizierung',
  'doc.lastReviewed': 'Zuletzt geprüft',
  'doc.purpose': 'Zweck',
  'doc.keyFunctions': 'Kernfunktionen',
  'doc.interfaces': 'Schnittstellen',
  'doc.data': 'Daten',
  'doc.operations': 'Betrieb',
  'doc.decisions': 'Entscheidungen und offene Punkte',
  'field.openDocumentation': 'Als Seite öffnen',
  'doc.title': 'Dokumentation',
  'doc.plans': 'Pläne',
  'doc.read': 'Lesen',
  'doc.edit': 'Bearbeiten',
  'doc.close': 'Dokumentation schließen',
  'doc.previous': 'Vorheriges Element',
  'doc.next': 'Nächstes Element',
  'doc.contents': 'Auf dieser Seite',
  'doc.source': 'Dokumentationsquelle (Markdown)',
  'doc.insertTemplate': 'Mit der Vorlage beginnen',
  'doc.emptyHint': 'Wechseln Sie zu Bearbeiten, um zu schreiben, oder beginnen Sie mit der Vorlage.',
  'doc.markdownHint': 'Markdown. [[Name]] verweist auf ein anderes Element.',
  'doc.markdownImageHint': 'Markdown. [[Name]] verweist auf ein anderes Element; fügen Sie ein Bild ein oder ziehen Sie es hierher, um es hinzuzufügen.',
  'doc.pictures': 'Bilder',
  'doc.picturesNone': 'Noch keine Bilder in diesem Projekt. Fügen Sie eines in den Text ein oder ziehen Sie es hinein.',
  'doc.pictureUsedHere': 'Auf dieser Seite verwendet',
  'doc.insertPicture': 'Einfügen',
  'doc.deletePicture': 'Bild löschen',
  'doc.deletePictureTitle': '{file} löschen?',
  'doc.deletePictureUsedBy': 'Es wird angezeigt in: {labels}. Dort erscheint künftig die Bildunterschrift. Die Datei wird beim nächsten Speichern aus dem Projekt entfernt, und das lässt sich nicht rückgängig machen.',
  'doc.deletePictureUnused': 'Kein Dokument zeigt es. Die Datei wird beim nächsten Speichern aus dem Projekt entfernt, und das lässt sich nicht rückgängig machen.',

  'docHelp.markdown': 'Hilfe zu Markdown',
  'docHelp.title': 'Schreiben in Markdown',
  'docHelp.intro': 'Einfacher Text mit ein paar Zeichen. Das zeichnet die Seite:',
  'docHelp.heading': 'Überschriften; die ersten drei Ebenen erscheinen in der Gliederung',
  'docHelp.emphasis': 'Fett und kursiv, auch mit ⌘B und ⌘I auf einer Auswahl',
  'docHelp.lists': 'Aufzählungen und nummerierte Listen; Tab rückt ein',
  'docHelp.tasks': 'Eine Aufgabenliste',
  'docHelp.elementLink': 'Ein Verweis auf ein anderes Element, über seinen Namen',
  'docHelp.link': 'Ein Link ins Web, außerhalb der App geöffnet',
  'docHelp.image': 'Ein Bild aus diesem Projekt; einfügen oder hineinziehen, um eines hinzuzufügen',
  'docHelp.table': 'Eine Tabelle',
  'docHelp.quote': 'Ein Zitat',
  'docHelp.code': 'Code, in der Zeile oder als Block',
  'docHelp.mermaid': 'Ein Diagramm, gezeichnet mit Mermaid',
  'docHelp.businessCase': 'Ein Business Case, mit den darunter ausgerechneten Zahlen',
  'docHelp.rule': 'Eine horizontale Linie',
  'docHelp.imagesNote': 'Nur im Projekt gespeicherte Bilder werden gezeichnet. Eine Webadresse erscheint als ihre Bildunterschrift, und die App ruft nie etwas ab.',
  'docHelp.htmlNote': 'HTML wird als Text angezeigt, nicht gerendert.',
  'doc.showPreview': 'Vorschau anzeigen',
  'doc.hidePreview': 'Vorschau ausblenden',
  'adr.mermaidFailed': 'Dieses Diagramm konnte nicht gezeichnet werden.',

  'doc.businessCaseLine': 'Zeile',
  'doc.businessCaseNet': 'Netto',
  'doc.businessCaseCumulative': 'Kumuliert',
  'doc.businessCaseNpv': 'Kapitalwert bei {rate}',
  'doc.businessCaseIrr': 'Interner Zinsfuß',
  'doc.businessCasePayback': 'Amortisation, in Perioden',
  'doc.businessCaseRoi': 'Kapitalrendite',
  'doc.businessCaseRatio': 'Nutzen-Kosten-Verhältnis',
  'doc.businessCaseScore': 'Gewichtete Bewertung {total} von {max}, bewertet von 1 bis {scale}.',
  'doc.businessCaseUnreadable': 'Dieser Business Case enthält noch keine Zahlen.',
  'doc.insertBusinessCase': 'Business Case hinzufügen',
}
