/**
 * Frisian, for the documentation page and the markdown around it.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a Frisian screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'field.description': 'Beskriuwing',
  'field.descriptionMarkdown': 'Beskriuwing (markdown)',
  'field.descriptionPlaceholder': 'Wat docht dit elemint? Markdown mei.',
  'field.edit': 'Bewurkje',
  'field.preview': 'Foarbyld',
  'field.editDescription': 'Beskriuwing bewurkje',
  'field.previewDescription': 'Foarbyld fan de beskriuwing',

  'doc.shortDescription': 'Koarte beskriuwing',
  'doc.owner': 'Eigner',
  'doc.criticality': 'Bedriuwskritikaliteit',
  'doc.users': 'Brûkers',
  'doc.dataClassification': 'Dataklassifikaasje',
  'doc.lastReviewed': 'Lêst beoardiele',
  'doc.purpose': 'Doel',
  'doc.keyFunctions': 'Kearnfunksjes',
  'doc.interfaces': 'Keppelingen',
  'doc.data': 'Gegevens',
  'doc.operations': 'Behear',
  'doc.decisions': 'Besluten en iepen punten',
  'field.openDocumentation': 'As side iepenje',
  'doc.title': 'Dokumintaasje',
  'doc.plans': 'Plannen',
  'doc.read': 'Lêze',
  'doc.edit': 'Bewurkje',
  'doc.close': 'Dokumintaasje slute',
  'doc.previous': 'Foarich elemint',
  'doc.next': 'Folgjend elemint',
  'doc.contents': 'Op dizze side',
  'doc.source': 'Dokumintaasjeboarne (markdown)',
  'doc.insertTemplate': 'Begjin mei it sjabloan',
  'doc.emptyHint': 'Skeakelje nei Bewurkje om te skriuwen, of begjin mei it sjabloan.',
  'doc.markdownHint': 'Markdown. [[Namme]] ferwiist nei in oar elemint.',
  'doc.markdownImageHint': 'Markdown. [[Namme]] ferwiist nei in oar elemint; plak of sleep in ôfbylding om der ien ta te foegjen.',
  'doc.pictures': 'Ofbyldingen',
  'doc.picturesNone': 'Noch gjin ôfbyldingen yn dit projekt. Plak of sleep der ien yn de tekst.',
  'doc.pictureUsedHere': 'Op dizze side brûkt',
  'doc.insertPicture': 'Ynfoegje',
  'doc.deletePicture': 'Ofbylding fuortsmite',
  'doc.deletePictureTitle': '{file} fuortsmite?',
  'doc.deletePictureUsedBy': 'Wurdt toand yn: {labels}. Dêr ferskynt tenei it byskrift. It bestân ferdwynt by de folgjende kear bewarjen út it projekt, en dat is net werom te draaien.',
  'doc.deletePictureUnused': 'Gjin inkeld dokumint toant dizze. It bestân ferdwynt by de folgjende kear bewarjen út it projekt, en dat is net werom te draaien.',

  'docHelp.markdown': 'Help by markdown',
  'docHelp.title': 'Skriuwe yn markdown',
  'docHelp.intro': 'Gewoane tekst mei in pear tekens. Dit is wat de side tekenet:',
  'docHelp.heading': 'Koppen; de earste trije nivo’s steane yn de ynhâldsopjefte',
  'docHelp.emphasis': 'Fet en kursyf, ek mei ⌘B en ⌘I op in seleksje',
  'docHelp.lists': 'Opsommingen en nûmere listen; Tab springt yn',
  'docHelp.tasks': 'In takenlist',
  'docHelp.elementLink': 'In ferwizing nei in oar elemint, op namme',
  'docHelp.link': 'In keppeling nei it web, bûten de app iepene',
  'docHelp.image': 'In ôfbylding út dit projekt; plak of sleep der ien om ta te foegjen',
  'docHelp.table': 'In tabel',
  'docHelp.quote': 'In sitaat',
  'docHelp.code': 'Koade, yn de rigel of as blok',
  'docHelp.mermaid': 'In diagram, tekene mei Mermaid',
  'docHelp.businessCase': 'In business case, mei de sifers derûnder útrekkene',
  'docHelp.rule': 'In horizontale line',
  'docHelp.imagesNote': 'Allinnich ôfbyldingen dy’t yn it projekt bewarre binne wurde tekene. In webadres ferskynt as syn byskrift, en de app hellet nea wat op.',
  'docHelp.htmlNote': 'HTML wurdt as tekst toand, net werjûn.',
  'doc.showPreview': 'Foarbyld toane',
  'doc.hidePreview': 'Foarbyld ferbergje',
  'adr.mermaidFailed': 'Dit diagram koe net tekene wurde.',
  'doc.bpmnFailed': 'Dit proses koe net tekene wurde.',
  'doc.bpmnMalformed': 'De tekst is gjin goed foarme XML.',
  'doc.bpmnNotBpmn': 'Dit is gjin BPMN-dokumint: der stiet gjin definitions-elemint oan de woartel.',
  'doc.bpmnNoDiagram': 'Dizze BPMN hat gjin diagramseksje, dus neat seit wêr\'t wat stiet.',

  'doc.businessCaseLine': 'Rigel',
  'doc.businessCaseNet': 'Netto',
  'doc.businessCaseCumulative': 'Kumulatyf',
  'doc.businessCaseNpv': 'Netto kontante wearde by {rate}',
  'doc.businessCaseIrr': 'Ynterne rintabiliteit',
  'doc.businessCasePayback': 'Werombeteltiid, yn perioaden',
  'doc.businessCaseRoi': 'Rendemint op ynvestearring',
  'doc.businessCaseRatio': 'Baten-kostenferhâlding',
  'doc.businessCaseScore': 'Weage skoare {total} fan {max}, beoardiele fan 1 oant {scale}.',
  'doc.businessCaseUnreadable': 'Dizze business case befettet noch gjin sifers.',
  'doc.insertBusinessCase': 'Business case tafoegje',
}
