/**
 * Dutch, for the documentation page and the markdown around it.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a Dutch screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'field.description': 'Omschrijving',
  'field.descriptionMarkdown': 'Omschrijving (markdown)',
  'field.descriptionPlaceholder': 'Wat doet dit element? Markdown mag.',
  'field.edit': 'Bewerken',
  'field.preview': 'Voorbeeld',
  'field.editDescription': 'Omschrijving bewerken',
  'field.previewDescription': 'Voorbeeld van de omschrijving',

  'doc.shortDescription': 'Korte omschrijving',
  'doc.owner': 'Eigenaar',
  'doc.criticality': 'Bedrijfskritikaliteit',
  'doc.users': 'Gebruikers',
  'doc.dataClassification': 'Dataclassificatie',
  'doc.lastReviewed': 'Laatst beoordeeld',
  'doc.purpose': 'Doel',
  'doc.keyFunctions': 'Kernfuncties',
  'doc.interfaces': 'Koppelingen',
  'doc.data': 'Gegevens',
  'doc.operations': 'Beheer',
  'doc.decisions': 'Besluiten en open punten',
  'field.openDocumentation': 'Als pagina openen',
  'doc.title': 'Documentatie',
  'doc.plans': 'Plannen',
  'doc.read': 'Lezen',
  'doc.edit': 'Bewerken',
  'doc.close': 'Documentatie sluiten',
  'doc.resizeFields': 'De kolom met velden vergroten of verkleinen',
  'doc.previous': 'Vorig element',
  'doc.next': 'Volgend element',
  'doc.contents': 'Op deze pagina',
  'doc.source': 'Documentatiebron (markdown)',
  'doc.insertTemplate': 'Begin met het sjabloon',
  'doc.emptyHint': 'Schakel naar Bewerken om te schrijven, of begin met het sjabloon.',
  'doc.markdownHint': 'Markdown. [[Naam]] verwijst naar een ander element.',
  'doc.markdownImageHint': 'Markdown. [[Naam]] verwijst naar een ander element; plak of sleep een afbeelding om er een toe te voegen.',
  'doc.pictures': 'Afbeeldingen',
  'doc.picturesNone': 'Nog geen afbeeldingen in dit project. Plak of sleep er een in de tekst.',
  'doc.pictureUsedHere': 'Op deze pagina gebruikt',
  'doc.insertPicture': 'Invoegen',
  'doc.deletePicture': 'Afbeelding verwijderen',
  'doc.deletePictureTitle': '{file} verwijderen?',
  'doc.deletePictureUsedBy': 'Wordt getoond in: {labels}. Daar verschijnt voortaan het bijschrift. Het bestand verdwijnt bij de volgende keer opslaan uit het project, en dat is niet ongedaan te maken.',
  'doc.deletePictureUnused': 'Geen enkel document toont deze. Het bestand verdwijnt bij de volgende keer opslaan uit het project, en dat is niet ongedaan te maken.',

  'docHelp.markdown': 'Hulp bij markdown',
  'docHelp.title': 'Schrijven in markdown',
  'docHelp.intro': 'Gewone tekst met een paar tekens. Dit is wat de pagina tekent:',
  'docHelp.heading': 'Koppen; de eerste drie niveaus staan in de inhoudsopgave',
  'docHelp.emphasis': 'Vet en cursief, ook met ⌘B en ⌘I op een selectie',
  'docHelp.lists': 'Opsommingen en genummerde lijsten; Tab springt in',
  'docHelp.tasks': 'Een takenlijst',
  'docHelp.elementLink': 'Een verwijzing naar een ander element, op naam',
  'docHelp.link': 'Een link naar het web, geopend buiten de app',
  'docHelp.image': 'Een afbeelding uit dit project; plak of sleep er een om toe te voegen',
  'docHelp.table': 'Een tabel',
  'docHelp.quote': 'Een citaat',
  'docHelp.code': 'Code, in de regel of als blok',
  'docHelp.mermaid': 'Een diagram, getekend met Mermaid',
  'docHelp.businessCase': 'Een business case, met de cijfers eronder uitgerekend',
  'docHelp.rule': 'Een horizontale lijn',
  'docHelp.imagesNote': 'Alleen afbeeldingen die in het project bewaard zijn worden getekend. Een webadres verschijnt als zijn bijschrift, en de app haalt nooit iets op.',
  'docHelp.htmlNote': 'HTML wordt als tekst getoond, niet weergegeven.',
  'doc.showPreview': 'Voorbeeld tonen',
  'doc.hidePreview': 'Voorbeeld verbergen',
  'adr.mermaidFailed': 'Dit diagram kon niet worden getekend.',
  'doc.bpmnFailed': 'Dit proces kon niet getekend worden.',
  'doc.bpmnMalformed': 'De tekst is geen welgevormde XML.',
  'doc.bpmnNotBpmn': 'Dit is geen BPMN-document: er staat geen definitions-element aan de wortel.',
  'doc.bpmnNoDiagram': 'Deze BPMN heeft geen diagramsectie, dus niets zegt waar iets staat.',

  'doc.businessCaseLine': 'Regel',
  'doc.businessCaseNet': 'Netto',
  'doc.businessCaseCumulative': 'Cumulatief',
  'doc.businessCaseNpv': 'Netto contante waarde bij {rate}',
  'doc.businessCaseIrr': 'Interne rentabiliteit',
  'doc.businessCasePayback': 'Terugverdientijd, in perioden',
  'doc.businessCaseRoi': 'Rendement op investering',
  'doc.businessCaseRatio': 'Baten-kostenverhouding',
  'doc.businessCaseScore': 'Gewogen score {total} van {max}, beoordeeld van 1 tot {scale}.',
  'doc.businessCaseUnreadable': 'Deze business case bevat nog geen cijfers.',
  'doc.insertBusinessCase': 'Business case toevoegen',
}
