/** Deutsch, für die Geschäftsarchitektur (ADR-0012 §4, §6). Typisiert aus `en.ts`. */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'sheet.page': 'Geschäftsarchitektur',
  'sheet.close': 'Geschäftsarchitektur schließen',

  'sheet.stakeholders': 'Beteiligte',
  'sheet.outside': 'Extern',
  'sheet.showRail': 'Beteiligte anzeigen',
  'sheet.hideRail': 'Beteiligte ausblenden',
  'sheet.noStakeholders': 'Noch keine Beteiligten.',

  'sheet.commonLane': 'Alle Kunden',
  'sheet.passThrough': 'Wie die Zeile darüber',
  'sheet.outsideStep': '{name} — außerhalb der Organisation erledigt',
  'sheet.noJourney': 'Noch keine Kundenreise auf diesem Blatt.',

  'sheet.appsOne': '1 Anwendung',
  'sheet.appsOther': '{count} Anwendungen',
  'sheet.people': 'Menschen',
  'sheet.nothingYet': 'noch nichts',
  'sheet.noAreas': 'Noch keine Bereiche auf diesem Blatt.',
  'sheet.emptyHint': 'Beginnen Sie mit einer Kundenreise oben oder mit einem Bereich für die Fähigkeiten.',

  'sheet.newJourney': 'Neue Kundenreise',
  'sheet.newArea': 'Neuer Bereich',
  'sheet.addPhase': '+ Phase',
  'sheet.addPhaseTo': 'Phase zu {name} hinzufügen',
  'sheet.addStep': '+ Schritt',
  'sheet.addStepTo': 'Schritt in {phase} hinzufügen, {lane}',
  'sheet.addLane': '+ Bahn…',
  'sheet.addArea': '+ Bereich',
  'sheet.addGrouping': '+ Gruppe',
  'sheet.addGroupingTo': 'Gruppe zu {name} hinzufügen',
  'sheet.addCapability': '+ Fähigkeit',
  'sheet.addCapabilityTo': 'Fähigkeit zu {name} hinzufügen',
  'sheet.addStakeholder': '+ Beteiligter',
  'sheet.addStakeholderTo': 'Beteiligten unter {name} hinzufügen',
  'sheet.addGroup': '+ Gruppe',
  'sheet.addGroupHint': 'Gruppe von Beteiligten hinzufügen',

  'sheet.nameJourney': 'Neue Kundenreise',
  'sheet.nameFirstPhase': 'Beginn',
  'sheet.namePhase': 'Neue Phase',
  'sheet.nameStep': 'Neuer Schritt',
  'sheet.nameArea': 'Neuer Bereich',
  'sheet.nameGrouping': 'Neue Gruppe',
  'sheet.nameCapability': 'Neue Fähigkeit',
  'sheet.nameStakeholder': 'Neuer Beteiligter',
  'sheet.nameGroup': 'Neue Gruppe',
  'sheet.untitled': 'Ohne Titel',

  'sheet.laneTitle': 'Ein eigener Weg',
  'sheet.laneWho': 'Wessen Weg es ist',
  'sheet.laneSomebodyNew': 'Jemand, der noch nicht dabei ist',
  'sheet.laneName': 'Der Name',
  'sheet.laneWhere': 'Zweigt ab bei',
  'sheet.laneAdd': 'Bahn hinzufügen',
  'sheet.outsideOrganisation': 'Außerhalb der Organisation',

  'sheet.settings': 'Was dieses Blatt zeigt',
  'sheet.settingsJourney': 'Die Kundenreise oben',
  'sheet.settingsAreas': 'Die Bereiche, in dieser Reihenfolge',
  'sheet.settingsLanes': 'Die Bahnen, in dieser Reihenfolge',
  'sheet.settingsNoLanes': 'Noch keine eigene Zeile — eine Bahn erscheint, sobald ein Schritt auf ihr liegt.',
  'sheet.settingsRail': 'Beteiligte am Rand zeichnen',
  'sheet.settingsDraw': '{name} zeichnen',

  'sheet.deleteThis': '{name} löschen',
  'sheet.deleteChildrenFirst': 'Löschen Sie zuerst, was darin steckt',
  'sheet.insideOne': 'Darin steckt 1 Sache',
  'sheet.insideOther': 'Darin stecken {count} Sachen',

  'sheet.supportedBy': 'Unterstützt von…',
  'sheet.doneBy': 'Erledigt von…',

  'sheet.switchedBoard': '{name} wird gezeigt, dort ist es gezeichnet',

  'sheet.unmapped': 'Noch keiner Domäne zugeordnet',
  'sheet.unmappedCount': '{count} warten',

  'sheet.details': 'Details',
  'sheet.nothingSelected': 'Wählen Sie etwas auf dem Blatt, um es hier zu sehen.',
  'sheet.parent': 'Gehört zu',
  'sheet.parentRoot': 'Nichts — dies steht ganz oben',
  'sheet.parentCycle': 'Steckt hier schon darin',
  'sheet.order': 'Unter seinesgleichen',
  'sheet.moveUp': 'Nach oben',
  'sheet.moveDown': 'Nach unten',
  'sheet.lane': 'Wessen Weg',
  'sheet.laneCommon': 'Der Weg, den alle gehen',
  'sheet.lifecycle': 'Lebenszyklus',
  'sheet.date.live': 'Live ab',
  'sheet.date.retiring': 'Abschaltung ab',
  'sheet.date.retired': 'Weg am',
  'sheet.description': 'Beschreibung',
  'sheet.coverage': 'Abgedeckt durch',
  'sheet.coverageNobody': 'Noch nichts und niemand',
  'sheet.coveragePeople': 'Menschen, ohne System',
  'sheet.open': '{name} öffnen',

  'map.page': 'Unternehmenskarte',
  'map.close': 'Unternehmenskarte schließen',
  'map.function': 'Fähigkeit',
  'map.people': 'Menschen',
  'map.coverage': 'Abdeckung',
  'map.thisScope': 'Diese Ebene',
  'map.summary': '{covered} abgedeckt · {manual} durch Menschen · {uncovered} ungedeckt',
  'map.uncovered': 'ungedeckt',
  'map.byPeople': 'Menschen',
  'map.gapsOne': '1 Lücke',
  'map.gapsOther': '{count} Lücken',
  'map.supportsTip': '{application} unterstützt {function}',
  'map.rolledUpTip': '{application} unterstützt etwas unter {function}',
  'map.peopleTip': 'Erledigt von {names}',
  'map.unknownApplication': 'Niemand in der Organisation definiert dies',
  'map.noFunctions': 'Noch keine Fähigkeiten, die sich abbilden ließen.',
  'map.noFunctionsHint': 'Fähigkeiten entstehen auf dem Blatt der Geschäftsarchitektur; die Karte zeichnet, was sie unterstützt.',
  'map.noApplications': 'Noch nichts unterstützt diese Fähigkeiten.',
}
