/** Frysk, foar de bedriuwsarsjitektuer (ADR-0012 §4, §6). Typearre fanút `en.ts`. */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'sheet.page': 'Bedriuwsarsjitektuer',
  'sheet.close': 'Bedriuwsarsjitektuer slute',

  'sheet.stakeholders': 'Belanghawwenden',
  'sheet.outside': 'Ekstern',
  'sheet.showRail': 'Belanghawwenden sjen litte',
  'sheet.hideRail': 'Belanghawwenden ferstopje',
  'sheet.noStakeholders': 'Noch gjin belanghawwenden.',

  'sheet.commonLane': 'Alle klanten',
  'sheet.passThrough': 'Lykas de rige hjirboppe',
  'sheet.outsideStep': '{name} — bûten de organisaasje dien',
  'sheet.noJourney': 'Noch gjin klantreis op dit blêd.',

  'sheet.appsOne': '1 applikaasje',
  'sheet.appsOther': '{count} applikaasjes',
  'sheet.people': 'minsken',
  'sheet.nothingYet': 'noch neat',
  'sheet.noAreas': 'Noch gjin gebieten op dit blêd.',
  'sheet.emptyHint': 'Begjin mei in klantreis boppe-oan, of mei in gebiet om capabilities yn te setten.',

  'sheet.newJourney': 'Nije klantreis',
  'sheet.newArea': 'Nij gebiet',
  'sheet.addPhase': '+ faze',
  'sheet.addPhaseTo': 'Faze taheakje oan {name}',
  'sheet.addStep': '+ stap',
  'sheet.addStepTo': 'Stap taheakje yn {phase}, {lane}',
  'sheet.addLane': '+ baan…',
  'sheet.addArea': '+ gebiet',
  'sheet.addGrouping': '+ groep',
  'sheet.addGroupingTo': 'Groep taheakje oan {name}',
  'sheet.addCapability': '+ capability',
  'sheet.addCapabilityTo': 'Capability taheakje oan {name}',
  'sheet.addStakeholder': '+ belanghawwende',
  'sheet.addStakeholderTo': 'Belanghawwende taheakje ûnder {name}',
  'sheet.addGroup': '+ groep',
  'sheet.addGroupHint': 'Groep belanghawwenden taheakje',

  'sheet.nameJourney': 'Nije klantreis',
  'sheet.nameFirstPhase': 'Begjin',
  'sheet.namePhase': 'Nije faze',
  'sheet.nameStep': 'Nije stap',
  'sheet.nameArea': 'Nij gebiet',
  'sheet.nameGrouping': 'Nije groep',
  'sheet.nameCapability': 'Nije capability',
  'sheet.nameStakeholder': 'Nije belanghawwende',
  'sheet.nameGroup': 'Nije groep',
  'sheet.untitled': 'Nammeleas',

  'sheet.laneTitle': 'In eigen paad',
  'sheet.laneWho': 'Waans paad it is',
  'sheet.laneSomebodyNew': 'Immen dy’t der noch net stiet',
  'sheet.laneName': 'Harren namme',
  'sheet.laneWhere': 'Splitst by',
  'sheet.laneAdd': 'Baan taheakje',
  'sheet.outsideOrganisation': 'Bûten de organisaasje',

  'sheet.settings': 'Wat dit blêd tekenet',
  'sheet.settingsJourney': 'De klantreis boppe-oan',
  'sheet.settingsAreas': 'De gebieten, op folchoarder',
  'sheet.settingsLanes': 'De banen, op folchoarder',
  'sheet.settingsNoLanes': 'Noch gjin eigen rige — in baan ferskynt sa’t der in stap op stiet.',
  'sheet.settingsRail': 'Belanghawwenden dernjonken tekenje',
  'sheet.settingsDraw': '{name} tekenje',

  'sheet.deleteThis': '{name} fuortsmite',
  'sheet.deleteChildrenFirst': 'Smyt earst fuort wat deryn sit',
  'sheet.insideOne': 'Der sit 1 ding yn',
  'sheet.insideOther': 'Der sitte {count} dingen yn',

  'sheet.supportedBy': 'Stipe troch…',
  'sheet.doneBy': 'Dien troch…',

  'sheet.switchedBoard': '{name} wurdt toand; dêr stiet it op',

  'sheet.unmapped': 'Noch net oan in domein tawiisd',
  'sheet.unmappedCount': '{count} wachtsje',

  'sheet.details': 'Details',
  'sheet.nothingSelected': 'Kies wat op it blêd om it hjir te sjen.',
  'sheet.parent': 'Falt ûnder',
  'sheet.parentRoot': 'Neat — dit stiet boppe-oan',
  'sheet.parentCycle': 'Sit hjir al yn',
  'sheet.order': 'Tusken de buorlju',
  'sheet.moveUp': 'Nei boppen',
  'sheet.moveDown': 'Nei ûnderen',
  'sheet.lane': 'Waans paad',
  'sheet.laneCommon': 'It paad dat elkenien rint',
  'sheet.lifecycle': 'Libbenssyklus',
  'sheet.date.live': 'Live fan',
  'sheet.date.retiring': 'Ofbouwe fan',
  'sheet.date.retired': 'Fuort op',
  'sheet.description': 'Beskriuwing',
  'sheet.coverage': 'Ynfolle troch',
  'sheet.coverageNobody': 'Noch neat en nimmen',
  'sheet.coveragePeople': 'Minsken, sûnder systeem',
  'sheet.open': '{name} iepenje',

  'map.page': 'Bedriuwskaart',
  'map.close': 'Bedriuwskaart slute',
  'map.function': 'Capability',
  'map.people': 'Minsken',
  'map.coverage': 'Dekking',
  'map.thisScope': 'Dit nivo',
  'map.summary': '{covered} dutsen · {manual} troch minsken · {uncovered} net dutsen',
  'map.uncovered': 'net dutsen',
  'map.byPeople': 'minsken',
  'map.gapsOne': '1 gat',
  'map.gapsOther': '{count} gatten',
  'map.supportsTip': '{application} stipet {function}',
  'map.rolledUpTip': '{application} stipet wat ûnder {function}',
  'map.peopleTip': 'Dien troch {names}',
  'map.unknownApplication': 'Nimmen yn de organisaasje definiearret dit',
  'map.noFunctions': 'Noch gjin capabilities om yn kaart te bringen.',
  'map.noFunctionsHint': 'Capabilities meitsje jo op it blêd mei de bedriuwsarsjitektuer; de kaart tekenet wat se stipet.',
  'map.noApplications': 'Noch neat stipet dizze capabilities.',
}
