/** Nederlands, voor de bedrijfsarchitectuur (ADR-0012 §4, §6). Getypeerd vanuit `en.ts`. */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'sheet.page': 'Bedrijfsarchitectuur',
  'sheet.close': 'Bedrijfsarchitectuur sluiten',

  'sheet.stakeholders': 'Belanghebbenden',
  'sheet.outside': 'Extern',
  'sheet.showRail': 'Belanghebbenden tonen',
  'sheet.hideRail': 'Belanghebbenden verbergen',
  'sheet.noStakeholders': 'Nog geen belanghebbenden.',

  'sheet.commonLane': 'Alle klanten',
  'sheet.passThrough': 'Zoals de rij hierboven',
  'sheet.outsideStep': '{name} — buiten de organisatie gedaan',
  'sheet.noJourney': 'Nog geen klantreis op dit blad.',

  'sheet.appsOne': '1 applicatie',
  'sheet.appsOther': '{count} applicaties',
  'sheet.people': 'mensen',
  'sheet.nothingYet': 'nog niets',
  'sheet.noAreas': 'Nog geen gebieden op dit blad.',
  'sheet.emptyHint': 'Begin met een klantreis bovenaan, of met een gebied om capabilities in te zetten.',

  'sheet.newJourney': 'Nieuwe klantreis',
  'sheet.newArea': 'Nieuw gebied',
  'sheet.addPhase': '+ fase',
  'sheet.addPhaseTo': 'Fase toevoegen aan {name}',
  'sheet.addStep': '+ stap',
  'sheet.addStepTo': 'Stap toevoegen in {phase}, {lane}',
  'sheet.addLane': '+ baan…',
  'sheet.addArea': '+ gebied',
  'sheet.addGrouping': '+ groep',
  'sheet.addGroupingTo': 'Groep toevoegen aan {name}',
  'sheet.addCapability': '+ capability',
  'sheet.addCapabilityTo': 'Capability toevoegen aan {name}',
  'sheet.addStakeholder': '+ belanghebbende',
  'sheet.addStakeholderTo': 'Belanghebbende toevoegen onder {name}',
  'sheet.addGroup': '+ groep',
  'sheet.addGroupHint': 'Groep belanghebbenden toevoegen',

  'sheet.nameJourney': 'Nieuwe klantreis',
  'sheet.nameFirstPhase': 'Begin',
  'sheet.namePhase': 'Nieuwe fase',
  'sheet.nameStep': 'Nieuwe stap',
  'sheet.nameArea': 'Nieuw gebied',
  'sheet.nameGrouping': 'Nieuwe groep',
  'sheet.nameCapability': 'Nieuwe capability',
  'sheet.nameStakeholder': 'Nieuwe belanghebbende',
  'sheet.nameGroup': 'Nieuwe groep',
  'sheet.untitled': 'Naamloos',

  'sheet.laneTitle': 'Een eigen pad',
  'sheet.laneWho': 'Wiens pad het is',
  'sheet.laneSomebodyNew': 'Iemand die er nog niet staat',
  'sheet.laneName': 'Hun naam',
  'sheet.laneWhere': 'Splitst bij',
  'sheet.laneAdd': 'Baan toevoegen',
  'sheet.outsideOrganisation': 'Buiten de organisatie',

  'sheet.settings': 'Wat dit blad tekent',
  'sheet.settingsJourney': 'De klantreis bovenaan',
  'sheet.settingsAreas': 'De gebieden, op volgorde',
  'sheet.settingsLanes': 'De banen, op volgorde',
  'sheet.settingsNoLanes': 'Nog geen eigen rij — een baan verschijnt zodra er een stap op staat.',
  'sheet.settingsRail': 'Belanghebbenden ernaast tekenen',
  'sheet.settingsDraw': '{name} tekenen',

  'sheet.deleteThis': '{name} verwijderen',
  'sheet.deleteChildrenFirst': 'Verwijder eerst wat erin zit',
  'sheet.insideOne': 'Er zit 1 ding in',
  'sheet.insideOther': 'Er zitten {count} dingen in',

  'sheet.supportedBy': 'Ondersteund door…',
  'sheet.doneBy': 'Gedaan door…',

  'sheet.switchedBoard': '{name} wordt getoond; daar staat het op',

  'sheet.unmapped': 'Nog niet aan een domein toegewezen',
  'sheet.unmappedCount': '{count} wachten',

  'sheet.details': 'Details',
  'sheet.nothingSelected': 'Kies iets op het blad om het hier te zien.',
  'sheet.parent': 'Valt onder',
  'sheet.parentRoot': 'Niets — dit staat bovenaan',
  'sheet.parentCycle': 'Zit hier al in',
  'sheet.order': 'Tussen de buren',
  'sheet.moveUp': 'Naar boven',
  'sheet.moveDown': 'Naar beneden',
  'sheet.lane': 'Wiens pad',
  'sheet.laneCommon': 'Het pad dat iedereen loopt',
  'sheet.lifecycle': 'Levenscyclus',
  'sheet.date.live': 'Live vanaf',
  'sheet.date.retiring': 'Uitfaseren vanaf',
  'sheet.date.retired': 'Weg op',
  'sheet.description': 'Beschrijving',
  'sheet.coverage': 'Ingevuld door',
  'sheet.coverageNobody': 'Nog niets en niemand',
  'sheet.coveragePeople': 'Mensen, zonder systeem',
  'sheet.open': '{name} openen',

  'map.page': 'Bedrijfskaart',
  'map.close': 'Bedrijfskaart sluiten',
  'map.function': 'Capability',
  'map.people': 'Mensen',
  'map.coverage': 'Dekking',
  'map.thisScope': 'Dit niveau',
  'map.summary': '{covered} gedekt · {manual} door mensen · {uncovered} ongedekt',
  'map.uncovered': 'ongedekt',
  'map.byPeople': 'mensen',
  'map.gapsOne': '1 gat',
  'map.gapsOther': '{count} gaten',
  'map.supportsTip': '{application} ondersteunt {function}',
  'map.rolledUpTip': '{application} ondersteunt iets onder {function}',
  'map.peopleTip': 'Gedaan door {names}',
  'map.unknownApplication': 'Niemand in de organisatie definieert dit',
  'map.noFunctions': 'Nog geen capabilities om in kaart te brengen.',
  'map.noFunctionsHint': 'Capabilities maak je op het blad met de bedrijfsarchitectuur; de kaart tekent wat ze ondersteunt.',
  'map.noApplications': 'Nog niets ondersteunt deze capabilities.',
}
