/** German, for the platform report (ADR-0013). Typed from the English slice. */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'technology.page': 'Plattformbericht',
  'technology.close': 'Plattformbericht schließen',
  'technology.summary': '{hosted} gehostet · {users} nutzen es · {landings} Schnittstellen darüber',
  'technology.standsOn': 'Steht auf',
  'technology.children': 'Darunter',
  'technology.hosted': 'Läuft hier',
  'technology.users': 'Nutzt es',
  'technology.nothing': 'Noch nichts',
  'technology.unknown': 'Niemand in der Organisation definiert dies',
  'technology.noPlatform': 'Dieser Scope kennt diese Plattform nicht.',
  'technology.open': '{name} öffnen',
  'technology.landings': 'Schnittstellen darüber',
  'technology.noLandings': 'Noch keine Container-Schnittstelle führt darüber.',
  'technology.from': 'Von',
  'technology.to': 'Nach',
  'technology.protocol': 'Wie',
  'technology.partOf': 'Teil von',
  'technology.itsOwn': 'Eine eigenständige Schnittstelle',
  'technology.on': 'auf {name}',
  'service.page': 'Dienstbericht',
  'service.close': 'Dienstbericht schließen',
  'service.summary': '{consumers} nutzen ihn · {scopes} Bereiche · {stranded} gestrandet, wenn er geht',
  'service.shared': 'Geteilt',
  'service.ownTeam': 'Eigenes Team',
  'service.goesOn': 'Zurückgezogen am {day}',
  'service.maintainers': 'Gepflegt von',
  'service.nobody': 'Niemand benannt',
  'service.realisedBy': 'Realisiert durch',
  'service.nothingRealises': 'Noch nichts liefert ihn',
  'service.consumers': 'Wer sich darauf stützt',
  'service.noConsumers': 'Noch nichts nutzt ihn.',
  'service.consumer': 'Anwendung',
  'service.via': 'Über',
  'service.fromScope': 'Aus',
  'service.thisScope': 'Dieser Bereich',
  'service.stranded': 'Bei Rückzug',
  'service.strandedYes': 'Gestrandet',
  'service.strandedNo': 'Rechtzeitig weg',
  'service.unknown': 'Niemand in der Organisation definiert dies',
  'service.noService': 'Dieser Bereich kennt diesen Dienst nicht.',
  'service.open': '{name} öffnen',

  // --- die Technologielandschaft (ADR-0015) --------------------------------
  'landscape.page': 'Technologielandschaft',
  'landscape.close': 'Technologielandschaft schließen',
  'landscape.summary': '{applications} Anwendungen · {services} Dienste · {platforms} Plattformen',
  'landscape.applications': 'Anwendungen',
  'landscape.services': 'Technologiedienste',
  'landscape.platforms': 'Plattformen',
  'landscape.thisScope': 'Dieser Bereich',
  'landscape.filter': 'Anwendungen filtern…',
  'landscape.fold': 'Domänen einklappen',
  'landscape.unfold': 'Domänen ausklappen',
  'landscape.foldedAbove': '{count} Anwendungen: die Domänen beginnen eingeklappt — eine ausklappen oder nach Namen filtern',
  'landscape.domainsMenu': '{count} Domänen',
  'landscape.hideServices': 'Dienste ausblenden',
  'landscape.showServices': 'Dienste einblenden',
  'landscape.servicesHidden': '{count} Dienste ausgeblendet — die Linien führen direkt zu den Plattformen dahinter',
  'landscape.linesFocus': 'Linien bei Fokus',
  'landscape.linesAll': 'Alle Linien',
  'landscape.hosting': 'Hosting',
  'landscape.onlyTouched': 'Nur was die Auswahl berührt',
  'landscape.applicationsOne': '{count} Anwendung',
  'landscape.applicationsOther': '{count} Anwendungen',
  'landscape.servicesOne': '{count} Dienst',
  'landscape.servicesOther': '{count} Dienste',
  'landscape.usersOne': '{count} Nutzer',
  'landscape.usersOther': '{count} Nutzer',
  'landscape.realisersOne': '{count} Realisierung',
  'landscape.realisersOther': '{count} Realisierungen',
  'landscape.on': 'auf {name}',
  'landscape.placeOnly': 'Ort',
  'landscape.outside': 'außerhalb',
  'landscape.shared': 'geteilt',
  'landscape.planned': 'geplant',
  'landscape.retiring': 'wird abgelöst',
  'landscape.retired': 'abgelöst',
  'landscape.noApplications': 'Noch nichts nutzt diese.',
  'landscape.noServices': 'Noch keine Dienste hier.',
  'landscape.noPlatforms': 'Noch keine Plattformen hier.',
  'landscape.noView': 'Dieser Bereich kennt diese Ansicht nicht.',
  'landscape.hostedOn': 'Läuft auf',
  'landscape.uses': 'Nutzt',
  'landscape.binds': 'Gebunden an',
  'landscape.leverages': 'Nutzt',
  'landscape.leveragesVia': 'für {services}',
  'landscape.realisedBy': 'Realisiert durch',
  'landscape.usedBy': 'Genutzt von',
  'landscape.realises': 'Liefert',
  'landscape.standsUnder': 'Steht unter',
  'landscape.under': 'Darunter',
  'landscape.standingOn': 'Steht darauf',
  'landscape.nothing': 'Nichts',
  'landscape.kindApplication': 'Anwendung',
  'landscape.kindGroup': 'Domäne',
  'landscape.kindService': 'Technologiedienst',
  'landscape.kindPlatform': 'Plattform',
  'landscape.report': 'Bericht',
  'landscape.legendUses': 'nutzt',
  'landscape.legendRealises': 'liefert',
  'landscape.legendLeverages': 'nutzt (abgeleitet)',
  'landscape.legendBinds': 'an eine Plattform gebunden',
  'landscape.legendHosting': 'läuft auf',
  'landscape.addService': 'Einen Dienst hinzufügen',
  'landscape.addServiceUnder': 'Einen Dienst unter {name} hinzufügen',
  'landscape.addPlatform': 'Eine Plattform hinzufügen',
  'landscape.addPlatformUnder': 'Eine Plattform unter {name} hinzufügen',
  'landscape.implied': 'Durch Hosting impliziert',
  'landscape.impliedNote': 'durch Hosting impliziert',
  'landscape.legendImplied': 'nutzt (durch Hosting impliziert)',
}
