/**
 * English, for the platform report (ADR-0013): one platform, what stands on
 * it, and what crosses it.
 *
 * `as const`, so this slice is the schema for its own keys.
 */
export const EN = {
  'technology.page': 'Platform report',
  'technology.close': 'Close the platform report',
  'technology.summary': '{hosted} hosted · {users} using it · {landings} interfaces across it',
  'technology.standsOn': 'Stands on',
  'technology.children': 'Under it',
  'technology.hosted': 'Hosted here',
  'technology.users': 'Uses it',
  'technology.nothing': 'Nothing yet',
  'technology.unknown': 'Nobody in the organisation defines this',
  'technology.noPlatform': 'This scope does not hold that platform.',
  'technology.open': 'Open {name}',
  'technology.landings': 'Interfaces across it',
  'technology.noLandings': 'No container interface crosses it yet.',
  'technology.from': 'From',
  'technology.to': 'To',
  'technology.protocol': 'How',
  'technology.partOf': 'Part of',
  'technology.itsOwn': 'An interface of its own',
  'technology.on': 'on {name}',
  'service.page': 'Service report',
  'service.close': 'Close the service report',
  'service.summary': '{consumers} consuming it · {scopes} scopes · {stranded} stranded if it goes',
  'service.shared': 'Shared',
  'service.ownTeam': 'Own team',
  'service.goesOn': 'Withdrawn on {day}',
  'service.maintainers': 'Maintained by',
  'service.nobody': 'Nobody named',
  'service.realisedBy': 'Realised by',
  'service.nothingRealises': 'Nothing realises it yet',
  'service.consumers': 'Who leans on it',
  'service.noConsumers': 'Nothing uses it yet.',
  'service.consumer': 'Application',
  'service.via': 'Through',
  'service.fromScope': 'From',
  'service.thisScope': 'This scope',
  'service.stranded': 'If withdrawn',
  'service.strandedYes': 'Stranded',
  'service.strandedNo': 'Off it in time',
  'service.unknown': 'Nobody in the organisation defines this',
  'service.noService': 'This scope does not hold that service.',
  'service.open': 'Open {name}',

  // --- the technology landscape (ADR-0015) ---------------------------------
  'landscape.page': 'Technology landscape',
  'landscape.close': 'Close the technology landscape',
  'landscape.summary': '{applications} applications · {services} services · {platforms} platforms',
  'landscape.applications': 'Applications',
  'landscape.services': 'Technology services',
  'landscape.platforms': 'Platforms',
  'landscape.thisScope': 'This scope',
  'landscape.filter': 'Filter applications…',
  'landscape.fold': 'Fold domains',
  'landscape.unfold': 'Unfold domains',
  'landscape.foldedAbove': '{count} applications: the domains start folded — unfold one, or filter by name',
  'landscape.domainsMenu': '{count} domains',
  'landscape.hideServices': 'Hide services',
  'landscape.showServices': 'Show services',
  'landscape.servicesHidden': '{count} services hidden — the lines go straight to the platforms behind them',
  'landscape.linesFocus': 'Lines on focus',
  'landscape.linesAll': 'All lines',
  'landscape.hosting': 'Hosting',
  'landscape.onlyTouched': 'Only what the selection touches',
  'landscape.applicationsOne': '{count} application',
  'landscape.applicationsOther': '{count} applications',
  'landscape.servicesOne': '{count} service',
  'landscape.servicesOther': '{count} services',
  'landscape.usersOne': '{count} user',
  'landscape.usersOther': '{count} users',
  'landscape.realisersOne': '{count} realiser',
  'landscape.realisersOther': '{count} realisers',
  'landscape.on': 'on {name}',
  'landscape.placeOnly': 'place',
  'landscape.outside': 'outside',
  'landscape.shared': 'shared',
  'landscape.planned': 'planned',
  'landscape.retiring': 'retiring',
  'landscape.retired': 'retired',
  'landscape.noApplications': 'Nothing uses these yet.',
  'landscape.noServices': 'No services here yet.',
  'landscape.noPlatforms': 'No platforms here yet.',
  'landscape.noView': 'This scope does not hold that view.',
  'landscape.hostedOn': 'Hosted on',
  'landscape.uses': 'Uses',
  'landscape.binds': 'Binds to',
  'landscape.leverages': 'Leverages',
  'landscape.leveragesVia': 'for {services}',
  'landscape.realisedBy': 'Realised by',
  'landscape.usedBy': 'Used by',
  'landscape.realises': 'Realises',
  'landscape.standsUnder': 'Stands under',
  'landscape.under': 'Under it',
  'landscape.standingOn': 'Standing on it',
  'landscape.nothing': 'Nothing',
  'landscape.kindApplication': 'application',
  'landscape.kindGroup': 'domain',
  'landscape.kindService': 'technology service',
  'landscape.kindPlatform': 'platform',
  'landscape.report': 'Report',
  'landscape.legendUses': 'uses',
  'landscape.legendRealises': 'realises',
  'landscape.legendLeverages': 'leverages (derived)',
  'landscape.legendBinds': 'binds to one platform',
  'landscape.legendHosting': 'hosted on',
} as const
