/** Frisian, for the platform report (ADR-0013). Typed from the English slice. */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'technology.page': 'Platfoarmrapport',
  'technology.close': 'Platfoarmrapport slute',
  'technology.summary': '{hosted} hoste · {users} brûke it · {landings} keppelflakken deroerhinne',
  'technology.standsOn': 'Stiet op',
  'technology.children': 'Derûnder',
  'technology.hosted': 'Draait hjir',
  'technology.users': 'Brûkt it',
  'technology.nothing': 'Noch neat',
  'technology.unknown': 'Nimmen yn de organisaasje definiearret dit',
  'technology.noPlatform': 'Dizze scope ken dat platfoarm net.',
  'technology.open': '{name} iepenje',
  'technology.landings': 'Keppelflakken deroerhinne',
  'technology.noLandings': 'Der rint noch gjin containerkeppelflak oerhinne.',
  'technology.from': 'Fan',
  'technology.to': 'Nei',
  'technology.protocol': 'Hoe',
  'technology.partOf': 'Diel fan',
  'technology.itsOwn': 'In keppelflak op himsels',
  'technology.on': 'op {name}',
  'service.page': 'Tsjinstrapport',
  'service.close': 'Tsjinstrapport slute',
  'service.summary': '{consumers} brûke it · {scopes} scopes · {stranded} strâne as it ferdwynt',
  'service.shared': 'Dield',
  'service.ownTeam': 'Eigen team',
  'service.goesOn': 'Ynlutsen op {day}',
  'service.maintainers': 'Underholden troch',
  'service.nobody': 'Nimmen neamd',
  'service.realisedBy': 'Realisearre troch',
  'service.nothingRealises': 'Noch neat leveret it',
  'service.consumers': 'Wa\'t derop leunt',
  'service.noConsumers': 'Noch neat brûkt it.',
  'service.consumer': 'Applikaasje',
  'service.via': 'Fia',
  'service.fromScope': 'Ut',
  'service.thisScope': 'Dizze scope',
  'service.stranded': 'By ynlûken',
  'service.strandedYes': 'Strâne',
  'service.strandedNo': 'Op \'e tiid fuort',
  'service.unknown': 'Nimmen yn de organisaasje definiearret dit',
  'service.noService': 'Dizze scope ken dy tsjinst net.',
  'service.open': '{name} iepenje',

  // --- it technologylânskip (ADR-0015) -------------------------------------
  'landscape.page': 'Technologylânskip',
  'landscape.close': 'Technologylânskip slute',
  'landscape.summary': '{applications} applikaasjes · {services} tsjinsten · {platforms} platfoarms',
  'landscape.applications': 'Applikaasjes',
  'landscape.services': 'Technologytsjinsten',
  'landscape.platforms': 'Platfoarms',
  'landscape.thisScope': 'Dizze scope',
  'landscape.filter': 'Applikaasjes filterje…',
  'landscape.fold': 'Domeinen tichtfâldzje',
  'landscape.unfold': 'Domeinen iepenfâldzje',
  'landscape.foldedAbove': '{count} applikaasjes: de domeinen begjinne tichtfâlde — fâldzje ien iepen, of filterje op namme',
  'landscape.domainsMenu': '{count} domeinen',
  'landscape.hideServices': 'Tsjinsten ferbergje',
  'landscape.showServices': 'Tsjinsten toane',
  'landscape.servicesHidden': '{count} tsjinsten ferburgen — de linen rinne streekrjocht nei de platfoarms derefter',
  'landscape.linesFocus': 'Linen by fokus',
  'landscape.linesAll': 'Alle linen',
  'landscape.foldHosting': 'Hosting gearfâldzje mei tsjinstlinen',
  'landscape.onlyTouched': 'Allinnich wat de seleksje rekket',
  'landscape.applicationsOne': '{count} applikaasje',
  'landscape.applicationsOther': '{count} applikaasjes',
  'landscape.servicesOne': '{count} tsjinst',
  'landscape.servicesOther': '{count} tsjinsten',
  'landscape.usersOne': '{count} brûker',
  'landscape.usersOther': '{count} brûkers',
  'landscape.realisersOne': '{count} realisaasje',
  'landscape.realisersOther': '{count} realisaasjes',
  'landscape.on': 'op {name}',
  'landscape.placeOnly': 'plak',
  'landscape.outside': 'bûten',
  'landscape.shared': 'dield',
  'landscape.planned': 'pland',
  'landscape.retiring': 'wurdt útfasearre',
  'landscape.retired': 'útfasearre',
  'landscape.noApplications': 'Noch neat brûkt dizze.',
  'landscape.noServices': 'Noch gjin tsjinsten hjir.',
  'landscape.noPlatforms': 'Noch gjin platfoarms hjir.',
  'landscape.noView': 'Dizze scope ken dy werjefte net.',
  'landscape.hostedOn': 'Draait op',
  'landscape.uses': 'Brûkt',
  'landscape.binds': 'Bûn oan',
  'landscape.leverages': 'Brûkt',
  'landscape.leveragesVia': 'foar {services}',
  'landscape.realisedBy': 'Realisearre troch',
  'landscape.usedBy': 'Brûkt troch',
  'landscape.realises': 'Leveret',
  'landscape.standsUnder': 'Falt ûnder',
  'landscape.under': 'Derûnder',
  'landscape.standingOn': 'Stiet derop',
  'landscape.nothing': 'Neat',
  'landscape.kindApplication': 'applikaasje',
  'landscape.kindGroup': 'domein',
  'landscape.kindService': 'technologytsjinst',
  'landscape.kindPlatform': 'platfoarm',
  'landscape.report': 'Rapport',
  'landscape.legendUses': 'brûkt',
  'landscape.legendRealises': 'leveret',
  'landscape.legendLeverages': 'brûkt (ôflaat)',
  'landscape.legendBinds': 'bûn oan ien platfoarm',
  'landscape.legendHosting': 'draait op',
  'landscape.addService': 'In tsjinst tafoegje',
  'landscape.addServiceUnder': 'In tsjinst tafoegje ûnder {name}',
  'landscape.addPlatform': 'In platfoarm tafoegje',
  'landscape.addPlatformUnder': 'In platfoarm tafoegje ûnder {name}',
  'landscape.implied': 'Ymplisyt troch hosting',
  'landscape.impliedNote': 'ymplisyt troch hosting',
  'landscape.legendImplied': 'brûkt (ymplisyt troch hosting)',
  'landscape.sharedRow': 'Dield yn de organisaasje',
  'landscape.sharedRowNote': 'tsjinsten dy\'t oare scopes dield neame · dimd oant wat hjir der ien fan brûkt',
  'landscape.from': 'fan {name}',
  'landscape.realisedByNames': 'realisearre troch {names}',
  'landscape.standInHere': 'plakferfanger hjir',
  'landscape.noServicesStrip': 'gjin tsjinsten yn dizze scope — de linen geane streekrjocht nei de platfoarms',
  'landscape.hostHere': '+ hjir hoste',
  'landscape.use': '+ brûke',
  'landscape.platformsOne': '{count} platfoarm',
  'landscape.platformsOther': '{count} platfoarms',
  'landscape.nothingSaid': 'noch neat sein',
  'landscape.alreadyUses': '{app} brûkt {name} al.',
  'landscape.alreadyHosted': '{app} rint al op {name}.',
  'landscape.dragHint': 'sleep in kaart op in platfoarm of in tsjinst, of selektearje har en brûk de knoppen dy\'t ferskine',
}
