/** Frisian, for the platform report (ADR-0013). Typed from the English slice. */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'technology.page': 'Platfoarmrapport',
  'technology.close': 'Platfoarmrapport slute',
  'technology.summary': '{hosted} hoste · {users} brûke it · {landings} keppelflakken deroerhinne',
  'technology.standsOn': 'Stiet op',
  'technology.children': 'Derûnder',
  'technology.hosted': 'Draait hjir',
  'technology.users': 'Brûkt it',
  'technology.nothing': 'Noch neat',
  'technology.unknown': 'Nimmen yn de organisaasje definiearret dit',
  'technology.noPlatform': 'Dizze scope ken dat platfoarm net.',
  'technology.open': '{name} iepenje',
  'technology.landings': 'Keppelflakken deroerhinne',
  'technology.noLandings': 'Der rint noch gjin containerkeppelflak oerhinne.',
  'technology.from': 'Fan',
  'technology.to': 'Nei',
  'technology.protocol': 'Hoe',
  'technology.partOf': 'Diel fan',
  'technology.itsOwn': 'In keppelflak op himsels',
  'technology.on': 'op {name}',
  'service.page': 'Tsjinstrapport',
  'service.close': 'Tsjinstrapport slute',
  'service.summary': '{consumers} brûke it · {scopes} scopes · {stranded} strâne as it ferdwynt',
  'service.shared': 'Dield',
  'service.ownTeam': 'Eigen team',
  'service.goesOn': 'Ynlutsen op {day}',
  'service.maintainers': 'Underholden troch',
  'service.nobody': 'Nimmen neamd',
  'service.realisedBy': 'Realisearre troch',
  'service.nothingRealises': 'Noch neat realisearret it',
  'service.consumers': 'Wa\'t derop leunt',
  'service.noConsumers': 'Noch neat brûkt it.',
  'service.consumer': 'Applikaasje',
  'service.via': 'Fia',
  'service.fromScope': 'Ut',
  'service.thisScope': 'Dizze scope',
  'service.stranded': 'By ynlûken',
  'service.strandedYes': 'Strâne',
  'service.strandedNo': 'Op \'e tiid fuort',
  'service.unknown': 'Nimmen yn de organisaasje definiearret dit',
  'service.noService': 'Dizze scope ken dy tsjinst net.',
  'service.open': '{name} iepenje',
}
