/** Dutch, for the platform report (ADR-0013). Typed from the English slice. */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'technology.page': 'Platformrapport',
  'technology.close': 'Platformrapport sluiten',
  'technology.summary': '{hosted} gehost · {users} gebruiken het · {landings} koppelvlakken eroverheen',
  'technology.standsOn': 'Staat op',
  'technology.children': 'Eronder',
  'technology.hosted': 'Draait hier',
  'technology.users': 'Gebruikt het',
  'technology.nothing': 'Nog niets',
  'technology.unknown': 'Niemand in de organisatie definieert dit',
  'technology.noPlatform': 'Deze scope kent dat platform niet.',
  'technology.open': '{name} openen',
  'technology.landings': 'Koppelvlakken eroverheen',
  'technology.noLandings': 'Er loopt nog geen containerkoppelvlak overheen.',
  'technology.from': 'Van',
  'technology.to': 'Naar',
  'technology.protocol': 'Hoe',
  'technology.partOf': 'Onderdeel van',
  'technology.itsOwn': 'Een koppelvlak op zichzelf',
  'technology.on': 'op {name}',
  'service.page': 'Dienstrapport',
  'service.close': 'Dienstrapport sluiten',
  'service.summary': '{consumers} gebruiken het · {scopes} scopes · {stranded} gestrand als het verdwijnt',
  'service.shared': 'Gedeeld',
  'service.ownTeam': 'Eigen team',
  'service.goesOn': 'Ingetrokken op {day}',
  'service.maintainers': 'Onderhouden door',
  'service.nobody': 'Niemand genoemd',
  'service.realisedBy': 'Gerealiseerd door',
  'service.nothingRealises': 'Nog niets levert het',
  'service.consumers': 'Wie erop leunt',
  'service.noConsumers': 'Nog niets gebruikt het.',
  'service.consumer': 'Applicatie',
  'service.via': 'Via',
  'service.fromScope': 'Uit',
  'service.thisScope': 'Deze scope',
  'service.stranded': 'Bij intrekking',
  'service.strandedYes': 'Gestrand',
  'service.strandedNo': 'Op tijd weg',
  'service.unknown': 'Niemand in de organisatie definieert dit',
  'service.noService': 'Deze scope kent die dienst niet.',
  'service.open': '{name} openen',

  // --- het technologielandschap (ADR-0015) ---------------------------------
  'landscape.page': 'Technologielandschap',
  'landscape.close': 'Technologielandschap sluiten',
  'landscape.summary': '{applications} applicaties · {services} diensten · {platforms} platformen',
  'landscape.applications': 'Applicaties',
  'landscape.services': 'Technologiediensten',
  'landscape.platforms': 'Platformen',
  'landscape.thisScope': 'Deze scope',
  'landscape.filter': 'Applicaties filteren…',
  'landscape.fold': 'Domeinen dichtvouwen',
  'landscape.unfold': 'Domeinen openvouwen',
  'landscape.foldedAbove': '{count} applicaties: de domeinen beginnen dichtgevouwen — vouw er een open, of filter op naam',
  'landscape.domainsMenu': '{count} domeinen',
  'landscape.hideServices': 'Diensten verbergen',
  'landscape.showServices': 'Diensten tonen',
  'landscape.servicesHidden': '{count} diensten verborgen — de lijnen lopen rechtstreeks naar de platformen erachter',
  'landscape.linesFocus': 'Lijnen bij focus',
  'landscape.linesAll': 'Alle lijnen',
  'landscape.foldHosting': 'Hosting samenvouwen met dienstlijnen',
  'landscape.onlyTouched': 'Alleen wat de selectie raakt',
  'landscape.applicationsOne': '{count} applicatie',
  'landscape.applicationsOther': '{count} applicaties',
  'landscape.servicesOne': '{count} dienst',
  'landscape.servicesOther': '{count} diensten',
  'landscape.usersOne': '{count} gebruiker',
  'landscape.usersOther': '{count} gebruikers',
  'landscape.realisersOne': '{count} realisatie',
  'landscape.realisersOther': '{count} realisaties',
  'landscape.on': 'op {name}',
  'landscape.placeOnly': 'plek',
  'landscape.outside': 'buiten',
  'landscape.shared': 'gedeeld',
  'landscape.planned': 'gepland',
  'landscape.retiring': 'wordt uitgefaseerd',
  'landscape.retired': 'uitgefaseerd',
  'landscape.noApplications': 'Nog niets gebruikt deze.',
  'landscape.noServices': 'Nog geen diensten hier.',
  'landscape.noPlatforms': 'Nog geen platformen hier.',
  'landscape.noView': 'Deze scope kent die weergave niet.',
  'landscape.hostedOn': 'Draait op',
  'landscape.uses': 'Gebruikt',
  'landscape.binds': 'Gebonden aan',
  'landscape.leverages': 'Gebruikt',
  'landscape.leveragesVia': 'voor {services}',
  'landscape.realisedBy': 'Gerealiseerd door',
  'landscape.usedBy': 'Gebruikt door',
  'landscape.realises': 'Levert',
  'landscape.standsUnder': 'Valt onder',
  'landscape.under': 'Eronder',
  'landscape.standingOn': 'Staat erop',
  'landscape.nothing': 'Niets',
  'landscape.kindApplication': 'applicatie',
  'landscape.kindGroup': 'domein',
  'landscape.kindService': 'technologiedienst',
  'landscape.kindPlatform': 'platform',
  'landscape.report': 'Rapport',
  'landscape.legendUses': 'gebruikt',
  'landscape.legendRealises': 'levert',
  'landscape.legendLeverages': 'gebruikt (afgeleid)',
  'landscape.legendBinds': 'gebonden aan één platform',
  'landscape.legendHosting': 'draait op',
  'landscape.addService': 'Een dienst toevoegen',
  'landscape.addServiceUnder': 'Een dienst toevoegen onder {name}',
  'landscape.addPlatform': 'Een platform toevoegen',
  'landscape.addPlatformUnder': 'Een platform toevoegen onder {name}',
  'landscape.implied': 'Impliciet door hosting',
  'landscape.impliedNote': 'impliciet door hosting',
  'landscape.legendImplied': 'gebruikt (impliciet door hosting)',
}
