// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/**
 * Dutch, for the shell around the editor: the picker, the toolbar, the dialogs, the toasts.
 *
 * Typed from the English slice beside it, so a missing translation is a compile
 * error here rather than an English sentence on a Dutch screen. `strings.test.ts`
 * covers what the type cannot: empty values, and placeholders that were dropped
 * or invented in translation.
 */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  /** The rail pack's picker heading. The pack is registered in composition.ts. */
  'logo.category.rail': 'Spoor',

  'shell.saved': 'Bewaard · {time}',
  'shell.notSaved': 'Nog niet bewaard',
  'shell.saveRefused': 'Niet bewaard — opslag weigert',
  'shell.unsaved': 'Nog niet bewaarde wijzigingen',
  'shell.saving': 'Bezig met bewaren…',
  'shell.changedElsewhere': 'Elders gewijzigd',
  'shell.conflict': 'Hier én elders gewijzigd',
  'shell.stepsSending': 'Versturen\u2026',
  'shell.stepsSent': 'Alle wijzigingen verstuurd',
  'shell.changedThere': 'Dit project is elders gewijzigd. Hier staat niets open.',
  'shell.unreadableScope': 'Niet te lezen in deze scope: {files}. Daarom staat hij open om te bekijken en niet om te wijzigen: een wijziging zou verliezen wat erin staat. Zet hem terug uit de geschiedenis, of haal een werkbestand binnen.',
  'shell.unreadableLater': 'Een latere versie van de app heeft deze scope geschreven, en deze kan niet alles ervan lezen ({files}), dus hij staat open om te bekijken en niet om te wijzigen. Werk de app bij om hem te wijzigen.',
  'shell.putBackFromHistory': 'Terugzetten uit de geschiedenis…',
  'shell.bringInWorkingFile': 'Een werkbestand binnenhalen…',
  'shell.unreadNotMoved': 'Deze scope is niet verplaatst: een bestand erin kon niet worden gelezen, en verplaatsen zou het met de oude map hebben verwijderd. Herstel het bestand, of haal het terug uit de geschiedenis, en probeer het opnieuw.',
  'shell.unreadableInTheWay': 'Er is niets geschreven: op dat adres staat al een scope die niet kon worden gelezen, en schrijven zou die hebben vervangen. Herstel de scope.json ervan, of haal die terug uit de geschiedenis, en probeer het opnieuw.',
  'shell.readOnlyRefused': 'Deze scope staat open om te lezen en niet om te wijzigen, dus er is niets gedaan.',
  'shell.conflictThere': 'Dit project is elders gewijzigd, en hier staan wijzigingen open.',
  'shell.unsettledFirst': 'Deze scope is elders gewijzigd terwijl wijzigingen hier niet bewaard zijn. Kies eerst op de balk welke versie blijft.',
  'shell.takeTheirs': 'Die van elders',
  'shell.keepMine': 'Die van mij',
  'shell.saveACopy': 'Kopie bewaren…',
  'shell.keepFailed':
    'Deze browser kon het ontwerp niet bewaren (opslag vol of geblokkeerd). Bewaar een werkbestand, anders is het bij het sluiten van het tabblad weg.',
  'shell.keptAgain': 'Bewaren in deze browser lukt weer.',
  'shell.sourceNotOpened': 'Die bron kon niet worden geopend: {message}',
  'shell.crashed': 'Er ging iets mis op dit scherm.',
  'shell.crashedNote':
    'Je werk tot het laatste bewaarmoment staat er nog. Herlaad om verder te gaan; de diagnostiek zegt wat er gebeurde.',
  'shell.reload': 'Herladen',
  'shell.copyDiagnostics': 'Diagnostiek kopiëren',
  'shell.diagnosticsCopied': 'Gekopieerd',
  'shell.copyFailed': 'Kopiëren lukte niet',
  'shell.bootFailed': 'De app kon niet starten.',
  'shell.bootFailedNote':
    'Je instellingen of het project dat openstond konden niet gelezen worden. Starten zonder dat project helpt meestal; er wordt niets verwijderd.',
  'shell.startFresh': 'Starten zonder het laatste project',
  'shell.unexpectedError': 'Er ging iets onverwachts mis. Herlaad de pagina als het scherm niet meer reageert.',
  'shell.orphanOne':
    'Containeraanzicht “{name}” is verwijderd: de applicatie ging uit het model. Dat aanzicht komt met Ongedaan maken niet terug.',
  'shell.orphanOther':
    '{count} containeraanzichten zijn verwijderd: hun applicaties gingen uit het model. Die aanzichten komen met Ongedaan maken niet terug.',
  'shell.duplicated': '“{name}” gedupliceerd.',
  'shell.deleted': '“{name}” verwijderd.',
  'shell.leftOutPart': '{count} × {label}',
  'shell.savedPicture': 'Afbeelding bewaard.',
  'shell.savedWorkingFile': 'Werkbestand bewaard, verzegeld met je wachtwoord — elke scope, inclusief geometrie, opmaak en eigen logo’s.',
  'seal.setTitle': 'Werkbestand verzegelen',
  'seal.setBody': 'Het bestand wordt met dit wachtwoord verzegeld, en wie het opent typt het opnieuw. Een verloren wachtwoord is niet terug te halen.',
  'seal.enterTitle': 'Verzegeld werkbestand openen',
  'seal.enterBody': 'Dit werkbestand is bij het bewaren met een wachtwoord verzegeld.',
  'seal.password': 'Wachtwoord',
  'seal.repeat': 'Herhaal het wachtwoord',
  'seal.mismatch': 'De twee komen niet overeen.',
  'seal.wrong': 'Dit is niet het wachtwoord waarmee dit bestand is verzegeld, of het bestand is beschadigd.',
  'seal.confirmSet': 'Bewaren',
  'seal.confirmEnter': 'Openen',
  'openInto.title': 'Waar moet “{name}” heen?',
  'openInto.body': 'Een werkbestand is een hele organisatie. Het kan een eigen werkmap worden, of vervangen wat hier open staat.',
  'openInto.hereWarning': 'Vervangen schrijft over “{scope}” en elke scope eronder heen. Waar hier een geschiedenis wordt bijgehouden, wordt eerst een momentopname gemaakt en kan wat er nu staat daaruit teruggezet worden; waar niet, is wat er nu staat weg.',
  'openInto.herePutsBack': '“{scope}” kon niet helemaal worden gelezen; dit zet hem terug uit het bestand, en bewaart wat niet gelezen kon worden.',
  'openInto.here': '“{scope}” hier vervangen',
  'openInto.elsewhere': 'Een nieuwe map…',
  'openInto.unnamedHere': 'de werkmap',
  'openInto.occupiedTitle': 'Deze map is niet leeg',
  'openInto.occupiedBody': 'De map bevat al “{name}”. Het bestand daar openen schrijft eroverheen.',
  'openInto.occupiedConfirm': 'Vervangen',
  'shell.workingFileLoaded': 'Werkbestand “{name}” geladen.',
  'shell.workingSetLoaded': 'Werkbestand “{name}” geladen, met {count} scopes eronder.',
  'shell.workingFileArrived': 'Werkbestand “{name}” geladen en gecontroleerd tegen wat het zegt te bevatten: {scopes} scopes, {views} views en {files} bestanden, allemaal aangekomen.',
  'shell.workingFileArrivedOwn': 'Werkbestand “{name}” geladen en gecontroleerd tegen wat het bevat, omdat een oudere versie het zonder manifest bewaarde: {scopes} scopes, {views} views en {files} bestanden, allemaal aangekomen.',
  'shell.workingFileShort': 'Werkbestand “{name}” is niet volledig aangekomen. Na het laden ontbreekt: {what}.',
  'shell.workingFileShortOwn': 'Werkbestand “{name}” is niet volledig aangekomen. Het heeft geen manifest, omdat een oudere versie het bewaarde, dus het is gecontroleerd tegen wat het bevat. Na het laden ontbreekt: {what}.',
  'shell.workingFilePartMissing': 'Het deel van de app dat werkbestanden leest en schrijft is niet geladen: deze pagina is misschien ouder dan de app op de server, of de verbinding is weg. Er is niets veranderd. Bewaar je werk, laad de pagina daarna opnieuw en probeer het nog eens.',
  'shell.workingFileNotLanded': 'Het werkbestand is niet geladen, en er is niets van geschreven: alle scopes erin komen samen aan of geen enkele. {reason}',
  'shell.workingFileLandedInPart': 'Mogelijk is maar een deel van het werkbestand geschreven: deze map wordt bestand voor bestand geschreven, en het schrijven is halverwege gestopt. {reason}',
  'shell.shortScope': 'de scope “{name}” ({path})',
  'shell.shortView': 'de view “{view}” in “{scope}”',
  'shell.shortFiles': '{count} bestanden van “{scope}”',
  'shell.changedFiles': '{count} bestanden van “{scope}” die anders aankwamen',
  'shell.shortOmitted': '{count} bestanden waarzonder “{scope}” is bewaard, omdat ze niet te lezen waren',
  'shell.shortMore': 'en nog {count}',
  'shell.exportUnreadable': 'Het werkbestand is niet bewaard. Niet te lezen: {paths}; zonder is het niet de hele organisatie.',
  'shell.savedWorkingFileWithout': 'Werkbestand bewaard, verzegeld met je wachtwoord, zonder {count} bestanden die niet te lezen waren: {files}. Het bestand zegt dat zelf, en bij het openen wordt het opnieuw gezegd.',
  'shell.workingSetNotHere': 'Dit bestand bevat een hele werkset en kan alleen in een werkmap worden geopend.',
  'shell.processFailed': 'Het document kon niet worden verwerkt: {message}',
  'shell.saveFileFailed': 'Het bestand kon niet worden bewaard: {message}',
  'shell.moveLeftCopy': 'Verplaatst — maar de kopie in de oude groep kon niet worden verwijderd: {message}',
  'shell.newDiagram': 'Nieuw landschap',
  'shell.newSheet': 'Bedrijfsarchitectuur',
  'shell.newMap': 'Bedrijfskaart',
  'shell.newTechnology': 'Technologielandschap',
  'shell.newDrawing': 'Tekening',
  'shell.drawingNotDrawn': 'Nog niet getekend',
  'shell.add': 'Toevoegen',
  'shell.imagesMissing': 'PNG geëxporteerd, maar deze logo’s ontbreken: {labels}.',
  'shell.logoAdded': 'Logo “{name}” toegevoegd aan de eigen bibliotheek.',
  'shell.copyOf': '{name} (kopie)',
  'shell.containerDiagram': '{name} · containers',
  'shell.deleteDiagramTitle': 'Aanzicht “{name}” verwijderen?',
  'shell.lastLandscape': 'Dit is het laatste landschap; het kan niet worden verwijderd.',
  'shell.deleteLandscapeBody':
    'De plaatsingen, groepen en routes van dit landschap gaan verloren. De elementen zelf blijven in het model, en containeraanzichten blijven staan.',
  'shell.deleteContainerBody':
    'De containers op dit aanzicht gaan mee, en de koppelvlakken die zij droegen verhuizen naar de applicatie. De applicatie zelf blijft op het landschap.',
  'shell.chooseBoard': 'Welk bord?',
  'shell.chooseBoardHint': '{name} staat op meer dan één bord.',
  'shell.chooseBoardAsOf': 'Per {day}',
  'shell.crumbTip': 'Naar {name}',
  'shell.exampleCopied': 'Voorbeeld \u201c{name}\u201d gekopieerd naar een eigen project.',

  // --- projecten en de kiezer ----------------------------------------------
  'picker.examples': 'Voorbeelden',
  'picker.open': 'Openen',
  'picker.order': 'Volgorde',
  'picker.orderName': 'Naam',
  'picker.orderUpdated': 'Onlangs gewijzigd',
  'history.title': 'Geschiedenis',
  'history.snapshot': 'Momentopname…',
  'history.open': 'Geschiedenis…',
  'history.start': 'Geschiedenis bijhouden',
  'history.startBody': 'Hier wordt nog geen geschiedenis bijgehouden. De eerste momentopname begint er een.',
  'history.message': 'Wat er veranderde',
  'history.defaultMessage': 'Momentopname',
  'history.take': 'Vastleggen',
  'history.taken': 'Momentopname vastgelegd.',
  'history.nothingToRecord': 'Er is niets veranderd sinds de vorige momentopname.',
  'history.beforeReplace': 'Voordat een werkbestand dit verving',
  'history.takenBeforeReplace': 'Eerst is een momentopname gemaakt: wat hier stond kan uit de geschiedenis teruggezet worden.',
  'history.failedBeforeReplace': 'Er is niets vervangen: er kon eerst geen momentopname gemaakt worden van wat hier staat. {message}',
  'history.failed': 'De momentopname is niet gelukt: {message}',
  'history.readFailed': 'De geschiedenis kon niet worden gelezen: {message}',
  'history.none': 'Nog geen momentopnames.',
  'history.unavailable': 'Hier kan geen geschiedenis worden bijgehouden. De rest werkt gewoon.',
  'history.compare': 'Vergeleken met het project zoals het nu is',
  'history.unchanged': 'Er is niets veranderd sinds deze momentopname.',
  'history.gone': 'Dit onderdeel bestond bij die momentopname nog niet.',
  'history.by': '{author}',
  'history.subject': 'Toon de geschiedenis van',
  'history.everything': 'Het hele project',
  'history.everywhere': 'Overal waar dit getekend is: {scopes}',
  'history.restorePerScope': 'Terugzetten herstelt wat dit niveau heeft. De pagina’s van de andere niveaus zet je terug in die niveaus.',
  'history.diagrams': 'Aanzichten',
  'history.descriptions': 'Beschrijvingen',
  'history.decisions': 'Besluiten',
  'history.noneFor': 'Nog geen momentopname heeft dit geraakt.',
  'history.unchangedFor': 'Dit is niet veranderd sinds deze momentopname.',
  'history.restore': 'Deze versie terugzetten…',
  'history.restoreProject': 'Het hele project terugzetten…',
  'history.restoreTitle': '{name} terugzetten naar {date}?',
  'history.restoreProjectTitle': 'Het hele project terugzetten naar {date}?',
  'history.restoreBody':
    'Dit maakt {name} weer wat het bij die momentopname was, als een nieuwe wijziging — de geschiedenis houdt alles wat sindsdien gebeurde, en deze stap komt daar bovenop. Tot de volgende momentopname het vastlegt is het met ⌘Z ongedaan te maken.',
  'history.restoreProjectBody':
    'Elk element, elke verbinding, elk aanzicht en elk besluit wordt weer wat het bij die momentopname was, als één nieuwe wijziging bovenop alles wat sindsdien gebeurde. Besluiten die aanvaard, afgewezen of vervangen zijn blijven zoals ze zijn. Tot de volgende momentopname het vastlegt is het met ⌘Z ongedaan te maken.',
  'history.restoreConfirm': 'Terugzetten',
  'history.restored': '{name} teruggezet naar {date}.',
  'history.restoredProject': 'Het hele project teruggezet naar {date}.',
  'history.restoredDropped': ' {count} geplaatste elementen bestaan niet meer en zijn weggelaten.',
  'history.restoredKept': ' {count} afgesloten besluiten zijn gelaten zoals ze zijn.',
  'history.beforePutBack': 'Voordat hij werd teruggezet uit de geschiedenis',
  'history.putBack': 'De hele scope terugzetten…',
  'history.putBackTitle': 'De hele scope terugzetten zoals hij was op {date}?',
  'history.putBackBody':
    'Een deel van deze scope kon niet worden gelezen. Dit maakt hem helemaal weer wat hij bij die momentopname was, het deel dat niet gelezen kon worden inbegrepen, en daarna kan hij weer gewijzigd worden. Wat niet gelezen kon worden wordt eerst bewaard — als versie in de geschiedenis, of apart gezet naast de scope — en waar dat niet kan, wordt niets teruggezet.',
  'history.putBackConfirm': 'Terugzetten',
  'history.putBackDone': 'De scope is terug zoals hij was op {date}, en is weer helemaal te lezen.',
  'history.putBackSetAside': ' Wat niet gelezen kon worden is eerst apart gezet, naast de scope: {files}.',
  'history.putBackKept': ' Een versie van de scope zoals hij was, met wat niet gelezen kon worden, is eerst vastgelegd.',
  'history.saveUnread': 'Bewaar wat niet gelezen kon worden…',
  'history.savedUnread': 'Bewaard wat niet gelezen kon worden.',
  'history.putBackWithout': ' {count} afbeeldingen die hij toen had worden niet meer bewaard, en zijn weggelaten.',
  'history.putBackFailed': 'De scope is niet teruggezet: {message}',
  'history.snapshotNow': 'Momentopname',
  'history.label': 'Label…',
  'history.labelTitle': 'Deze momentopname een label geven',
  'history.labelBody':
    'Een woord voor deze versie — “Aan de directie getoond” — naast de boodschap, nooit in plaats ervan. Het reist mee met de geschiedenis, zodat een collega hetzelfde merkteken op dezelfde plek ziet.',
  'history.labelField': 'Label',
  'history.labelConfirm': 'Label',
  'history.labelled': 'Label gegeven.',
  'history.labelFailed': 'Het label kon niet worden toegevoegd: {reason}',
  'history.labelExists': 'Er is hier al een label met die naam. Kies een ander woord.',
  'history.labelUnnamed': 'Een label heeft een woord nodig.',

  'change.elementAdded': '{name} toegevoegd',
  'change.elementRemoved': '{name} verwijderd',
  'change.elementChanged': '{name} gewijzigd ({fields})',
  'change.connectionAdded': '{name} getekend',
  'change.connectionRemoved': '{name} doorgeknipt',
  'change.connectionChanged': '{name} gewijzigd ({fields})',
  'change.rowAdded': 'Rij getekend ({type}): {name}',
  'change.rowRemoved': 'Rij weggehaald ({type}): {name}',
  'change.rowChanged': 'Rij gewijzigd ({type}): {name} ({fields})',
  'change.diagramAdded': 'Aanzicht {name} toegevoegd',
  'change.diagramRemoved': 'Aanzicht {name} verwijderd',
  'change.diagramChanged': 'Aanzicht {name} gewijzigd ({fields})',
  'change.decisionAdded': 'Besluit {name} toegevoegd',
  'change.decisionRemoved': 'Besluit {name} verwijderd',
  'change.decisionChanged': 'Besluit {name} gewijzigd ({fields})',
  'change.transitionAdded': 'Plan {name} toegevoegd',
  'change.transitionRemoved': 'Plan {name} verwijderd',
  'change.transitionChanged': 'Plan {name} gewijzigd ({fields})',
  'change.observationAdded': 'Waarneming {name} vastgelegd',
  'change.observationRemoved': 'Waarneming {name} verwijderd',
  'change.observationChanged': 'Waarneming {name} gewijzigd ({fields})',
  'change.causeAdded': 'Oorzaak {name} toegevoegd',
  'change.causeRemoved': 'Oorzaak {name} verwijderd',
  'change.causeChanged': 'Oorzaak {name} gewijzigd ({fields})',
  'change.solutionAdded': 'Oplossing {name} toegevoegd',
  'change.solutionRemoved': 'Oplossing {name} verwijderd',
  'change.solutionChanged': 'Oplossing {name} gewijzigd ({fields})',
  'change.experimentAdded': 'Experiment {name} toegevoegd',
  'change.experimentRemoved': 'Experiment {name} verwijderd',
  'change.experimentChanged': 'Experiment {name} gewijzigd ({fields})',
  'change.membershipAdded': '{name} op {on} gezet',
  'change.membershipRemoved': '{name} van {on} gehaald',
  'change.membershipMoved': '{name} op {on} verplaatst naar een andere band of groep',
  'change.geometry': '{count} verplaatst op {name}',
  'change.becameStandIn': '{name} verwijst nu naar {scope}',
  'change.becameDefinition': '{name} wordt nu hier gedefinieerd',

  'source.firstTitle': 'Waar horen je projecten te staan?',
  'source.recent': 'Onlangs gebruikt',
  'picker.never': 'Nog niet bewaard',
  'picker.changed': 'Gewijzigd {when}',
  'picker.delete': 'Verwijderen',
  'picker.deleteTitle': '\u201c{name}\u201d verwijderen?',
  'picker.deleteBody': 'Dit verwijdert {name} en alles wat eronder is ondergebracht. Een werkbestand dat je elders bewaarde blijft staan.',
  'shell.scopeCreated': '\u201c{name}\u201d aangemaakt.',
  'picker.withBoard': 'Begin met een landschapsbord',
  'picker.newScope': 'Nieuw domein of team\u2026',
  'picker.newScopeTitle': 'Nieuw domein of team',
  'picker.scopeName': 'Naam',
  'picker.under': 'Valt onder',
  'picker.addUnder': 'Nieuw domein of team onder {name}',
  'picker.organisation': 'Deze organisatie',
  'picker.reservedName': 'Zo mag een onderdeel niet heten \u2014 die map is al in gebruik voor wat een onderdeel bevat.',
  'scope.kind.organisation': 'Organisatie',
  'scope.kind.domain': 'Domein',
  'scope.kind.programme': 'Programma',
  'scope.kind.team': 'Team',
  'scope.kind.landscape': 'Landschapsscope',
  'picker.create': 'Aanmaken',
  'picker.loadFailed': 'Dat project kon niet geopend worden.',
  'picker.listFailed': 'Je projecten konden niet gelezen worden.',
  'picker.deleteFailed': 'Dat project kon niet verwijderd worden.',
  'settings.title': 'Projectinstellingen',
  'settings.open': 'Instellingen\u2026',
  'settings.projectName': 'Projectnaam',
  'settings.group': 'Groep',
  'settings.groupHelp': 'Een project verhuizen zet het onder een andere groep. De inhoud blijft ongemoeid.',
  'settings.save': 'Bewaren',
  'settings.moved': 'Verhuisd naar {name}.',
  'settings.renamed': 'Hernoemd naar \u201c{name}\u201d.',
  'settings.defaults': 'STANDAARD VOOR DIT PROJECT',
  'settings.defaultsHelp':
    'Waar een aanzicht in dit project op terugvalt. Dit herschrijft nooit een aanzicht dat al is ingesteld.',
  'settings.defaultAuthor': 'Auteur',
  'settings.defaultAuthorHelp': 'Vermeld op een geëxporteerd aanzicht zonder eigen auteur.',
  'settings.defaultColumns': 'De operationele aspecten waarmee een nieuw landschap begint.',

  'prefs.title': 'Voorkeuren',
  'prefs.general': 'ALGEMEEN',
  'prefs.language': 'Taal',
  'prefs.theme': 'Thema',
  'prefs.projectOrder': 'Volgorde van de projectenlijst',
  'prefs.updates': 'UPDATES',
  'prefs.checkAutomatically': 'Automatisch op updates controleren',
  'prefs.updatesNote':
    'Kijkt bij het starten en elke zes uur op de releasepagina. Er wordt niets gedownload zonder te vragen.',
  'prefs.channel': 'Releasekanaal',
  'prefs.channelStable': 'Stabiel',
  'prefs.channelBeta': 'Bèta',
  'prefs.channelNote':
    'Bèta’s zijn builds die vooruitlopen op een release, op dezelfde manier ondertekend en gepubliceerd. Wie het bètakanaal verlaat, houdt wat er geïnstalleerd is.',
  'prefs.writeFailed': 'Die instelling kon niet worden bewaard: {message}',
  'group.title': 'Onderdeelinstellingen',
  'group.open': 'Instellingen…',
  'group.openFor': 'Instellingen voor {name}',
  'group.name': 'Naam',
  'group.nameHelp': 'Hernoemen verplaatst het niet: het adres ({path}) blijft, en “Ondergebracht bij” is wat het verplaatst.',
  'group.client': 'Klant',
  'group.clientHelp': 'Staat op elk geëxporteerd aanzicht. Leeg betekent de dichtstbijzijnde naam erboven.',
  'group.description': 'Omschrijving',
  'group.descriptionPlaceholder': 'Wie ze zijn, wat dit landschap beslaat, bij wie je terechtkunt.',
  'group.links': 'LINKS',
  'group.linksHelp': 'Een wikiruimte, een ticketlijst, een dashboard. Alleen http- en https-adressen.',
  'group.linkLabel': 'Label',
  'group.linkUrl': 'Adres',
  'group.addLink': 'Link toevoegen',
  'group.removeLink': '{name} verwijderen',
  'group.badUrl': 'Moet met http:// of https:// beginnen',
  'group.saved': '{name} opgeslagen.',
  'group.renamed': 'Hernoemd naar “{name}”.',
  'group.saveFailed': 'Dit onderdeel kon niet worden opgeslagen.',
  'agent.title': 'Een agent koppelen',
  'agent.tipOff': 'Een agent koppelen…',
  'agent.tipListening': 'Wacht op een agent op poort {port}',
  'agent.tipConnected': '{name} gekoppeld',
  'agent.what':
    'Je codeer-agent — Claude Code, Codex, Cursor of een andere MCP-client — kan dit landschap lezen, '
    + 'wijzigingen voorstellen en naar diagrammen kijken terwijl jij werkt. Alles wat hij doet staat onder zijn '
    + 'naam in Activiteit en is met ⌘Z ongedaan te maken. Hij koppelt via het standaard Model Context Protocol, '
    + 'alleen op deze machine. Er verlaat niets de computer.',
  'agent.enable': 'Agentverbindingen toestaan',
  'agent.listening': 'Luistert op poort {port}.',
  'agent.connected': '{name} is gekoppeld.',
  'agent.moved':
    'Poort {from} was bezet toen de app startte, dus hij luistert nu op {port}. Een agent die met de oude poort is ingesteld heeft het nieuwe adres nodig.',
  'agent.desktopOnly':
    'Een agent koppelen vraagt de desktop-app — alleen die kan op deze machine luisteren. Open dit project daar en de schakelaar staat hier.',
  'agent.recipes': 'JE CLIENT KOPPELEN',
  'agent.recipesNote': 'De poort en het token hieronder zijn van deze machine. Kies je client en plak.',
  'agent.tabClaude': 'Claude Code',
  'agent.tabClaudeDesktop': 'Claude Desktop',
  'agent.tabCodex': 'Codex',
  'agent.tabCursor': 'Cursor',
  'agent.tabOther': 'Anders',
  'agent.recipeClaude': 'claude mcp add --transport http lvarch {endpoint} --header "Authorization: Bearer {token}"',
  'agent.recipeClaudeDesktop':
    '# Niet het scherm "Add custom connector": dat is voor servers op internet en kan deze machine niet bereiken.\n'
    + '# Claude Desktop start lokale servers via stdio, dus het heeft de mcp-remote-brug in zijn developer-instellingen nodig.\n'
    + '#\n'
    + '# Het makkelijkst: plak dit in Claude Code, dat de instellingen al kent, en herstart daarna Claude Desktop:\n'
    + 'Add the MCP server "lvarch" to my Claude Desktop developer settings (claude_desktop_config.json): '
    + 'command "npx", args ["-y", "mcp-remote", "{endpoint}", "--transport", "http-only", "--header", '
    + '"Authorization: Bearer {token}"].\n'
    + '#\n'
    + '# Of voeg het zelf toe, in Claude Desktop onder Settings → Developer → Edit Config:\n'
    + '{\n  "mcpServers": {\n    "lvarch": {\n      "command": "npx",\n'
    + '      "args": ["-y", "mcp-remote", "{endpoint}", "--transport", "http-only", "--header", "Authorization: Bearer {token}"]\n'
    + '    }\n  }\n}',
  'agent.recipeCodex':
    '# ~/.codex/config.toml\n[mcp_servers.lvarch]\nurl = "{endpoint}"\nhttp_headers = { Authorization = "Bearer {token}" }',
  'agent.recipeCursor':
    '// .cursor/mcp.json\n{\n  "mcpServers": {\n    "lvarch": {\n      "url": "{endpoint}",\n'
    + '      "headers": { "Authorization": "Bearer {token}" }\n    }\n  }\n}',
  'agent.recipeOther': 'Transport: Streamable HTTP\nEindpunt: {endpoint}\nHeader: Authorization: Bearer {token}',
  'agent.copy': 'Kopiëren',
  'agent.copied': 'Gekopieerd',
  'agent.newToken': 'Nieuw token',
  'agent.newTokenNote': 'Elke agent die vóór nu is ingesteld heeft het nieuwe token nodig.',
  'agent.changeFailed': 'Dat kon niet worden gewijzigd: {message}',
  'agent.someone': 'Een agent',
  'agent.driving': '{name} bestuurt de app.',
  'agent.drivingFor': '{name} bestuurt de app: {purpose}',
  'agent.drivingHint': 'Wat je ondertussen aanklikt, kan veranderen wat de agent doet. Stoppen beëindigt de sessie en zegt dat tegen de agent.',
  'agent.stop': 'Stoppen',
  'agent.stoppedToast': '{name} is gestopt. De agent hoort dat bij de volgende aanroep en kan vragen om door te gaan.',

  // --- Delen met een link… (ADR-0033, gewijzigd) -----------------------------
  'share.title': 'Delen met een link',
  'share.what': 'Wie dit werk mag lezen, opent het met deze link hier: dezelfde scope, pagina en hetzelfde record. Wie nog niet is aangemeld, meldt zich eerst aan en komt daarna hier uit.',
  'share.linkLabel': 'Link naar deze plek',
  'share.copy': 'Link kopiëren',
  'share.copied': 'Link gekopieerd',
  'share.copyFailed': 'De link kon niet worden gekopieerd. Selecteer hem in het venster en kopieer hem daar.',
  'share.noAddress': 'Werk dat hier wordt bewaard — in een map, in deze browser of nergens — is niet met een link te openen: niemand anders bereikt het op een adres. Een link kan worden gedeeld waar werk op een server staat waarop iedereen die het mag lezen zich aanmeldt.',
  'share.noPlace': 'Er staat nog geen plek op het scherm om naar te linken. Open een scope of een startpagina en probeer het opnieuw.',
  'shell.documentation': 'Documentatie',
  'shell.documentationTip': 'Open de documentatiepagina van het geselecteerde element',
  'shell.noElements': 'Er is nog niets om te documenteren \u2014 voeg eerst een element toe.',
  'shell.decisions': 'Besluiten',
  'shell.decisionsTip': 'Architectuurbesluiten \u2014 voor de groep, het landschap en elke applicatie',
  'shell.observations': 'Waarnemingen',
  'shell.observationsTip': 'Wat hier en in de scopes eronder gezien is, geanalyseerd naar oorzaken en grondoorzaken',
  'shell.roadmap': 'Roadmap',
  'shell.roadmapTip': 'Het landschap op een tijdas, de plannen daarover, en waarover de datums het oneens zijn',
  'shell.activity': 'Activiteit',
  'shell.activityTip': 'Wat er sinds het openen aan dit project is veranderd',
  'shell.activityEmpty': 'Nog niets',
  'shell.activityAgent': 'AGENT',
  'shell.activityBy': 'DOOR {name}',
  'shell.activityByVia': 'DOOR {name} VIA {client}',
  'shell.activityElsewhere': 'EEN ANDERE AUTEUR',
  'shell.activityYou': 'JIJ',
  'shell.activityYouVia': 'JIJ VIA {client}',
  'shell.activityReading': 'Lezen wat hier is gedaan…',
  'shell.activityTipKept': 'Wat er de laatste tijd aan dit project is gedaan, en door wie',
  'shell.activityUnattended': 'AUTOMATISCH INGEDEELD',
  'shell.alsoHere': 'Ook hier: {names}',
  'shell.search': 'Zoeken',
  'shell.back': 'Terug',
  'shell.forward': 'Vooruit',
  'shell.searchTip': 'Zoek elementen, documentatie en besluiten (\u2318K)',

  // Het organisatiescherm: het thuis van de hoofdonderdeel, dat de kiezer verving.
  'org.kind': 'Wat dit is',
  'org.kindHelp': 'Getoond als label; het verandert verder niets.',
  'org.kindNone': 'Niet gezegd',
  'org.kindOrganisation': 'Organisatie',
  'org.kindDomain': 'Domein',
  'org.kindProgramme': 'Programma',
  'org.kindTeam': 'Team',
  'org.kindLandscape': 'Landschapsscope',
  'org.filedUnder': 'Ondergebracht bij',
  'org.filedUnderHelp': 'Verplaatsen verandert het adres van dit onderdeel en van alles eronder. De inhoud blijft ongemoeid.',

  'org.nameThis': 'Geef deze organisatie een naam',
  'org.forClient': 'Voor {name}',
  'org.lastChanged': 'Laatst gewijzigd {when}',
  'org.subtitle': 'Elke scope hieronder \u2014 een domein, een team, een landschapsscope \u2014 heeft eigen borden, pagina\'s en besluiten.',
  'org.organisationsOne': '{count} organisatie',
  'org.organisationsOther': '{count} organisaties',
  'org.domainsOne': '{count} domein',
  'org.domainsOther': '{count} domeinen',
  'org.programmesOne': '{count} programma',
  'org.programmesOther': '{count} programma\'s',
  'org.teamsOne': '{count} team',
  'org.teamsOther': '{count} teams',
  'org.landscapeScopesOne': '{count} landschapsscope',
  'org.landscapeScopesOther': '{count} landschapsscopes',
  'org.scopesOne': '{count} scope',
  'org.scopesOther': '{count} scopes',
  'org.landscapesOne': '{count} scope met borden',
  'org.landscapesOther': '{count} scopes met borden',
  'org.unreadableOne': 'Eén scope kon niet worden gelezen en wordt niet getoond: {paths}. De map blijft zoals die is, en er wordt niets op die plek aangemaakt.',
  'org.unreadableOther': '{count} scopes konden niet worden gelezen en worden niet getoond: {paths}. De mappen blijven zoals ze zijn, en er wordt niets op die plekken aangemaakt.',
  'org.unreadableRoot': 'Hier kon niets worden gelezen, dus wat erin staat wordt niet getoond. Er is niets in veranderd, en er wordt niets in aangemaakt tot het weer te lezen is.',
  'org.diagramsOne': '{count} diagram',
  'org.diagramsOther': '{count} diagrammen',

  'org.business': 'Bedrijfsarchitectuur',
  'org.describeDocumentation': 'Een pagina voor elk record op de borden van deze scope: eigenaar, leverancier, data en beschrijving.',
  'org.describeBusiness': 'Wat de organisatie doet: haar reizen, de gebieden die ze doorlopen, de functies in elk, en wie verantwoordelijk is.',
  'org.describeDecisions': 'De architectuurbesluiten die hier zijn genomen, genummerd, met hun status en de redenering achter elk.',
  'org.describeRoadmap': 'De plannen om dit landschap te veranderen op een tijdas, met wat elk introduceert en uitfaseert.',
  'org.describeObservations': 'Wat het team hier waarnam, hoe vaak, en de oorzaken en grondoorzaken waarnaar het geanalyseerd is.',
  'org.describeRegister': 'Elke applicatie waar dan ook in de organisatie, met de scope die ervoor instaat en waar ze verder getekend is.',
  'org.describeTechnology': 'Elke platformdienst en elk platform in de organisatie: wat wordt aangeboden, wat het levert, en wie erop leunt.',
  'org.attention': 'Vraagt aandacht',
  'org.attentionOpen': 'Openen waar het te herstellen is',
  'org.attentionMore': 'Alle {count} tonen',
  'org.businessMake': 'Een plaat maken\u2026',
  'org.map': 'Kaart',
  'org.mapMake': 'Een kaart maken\u2026',
  'org.technologyLandscape': 'Landschap',
  'org.technologyLandscapeMake': 'Een landschap maken\u2026',
  'org.journeysOne': '{count} klantreis',
  'org.journeysOther': '{count} klantreizen',
  'org.areasOne': '{count} gebied',
  'org.areasOther': '{count} gebieden',
  'org.functionsOne': '{count} functie',
  'org.functionsOther': '{count} functies',
  'org.stakeholdersOne': '{count} belanghebbende',
  'org.stakeholdersOther': '{count} belanghebbenden',
  'org.unmappedOne': '{count} functie nog niet aan een domein toegewezen',
  'org.unmappedOther': '{count} functies nog niet aan een domein toegewezen',
  'org.allMapped': 'Elke functie is aan een domein toegewezen.',
  'org.boards': 'Borden',
  'org.newBoard': 'Nieuw bord\u2026',
  'org.newBoardLandscape': 'Landschap\u2026',
  'org.newBoardSheet': 'Bedrijfsarchitectuur',
  'org.newBoardMap': 'Enterprisekaart',
  'org.newBoardTechnology': 'Technologielandschap',
  'org.newBoardDrawing': 'Tekening',
  'org.noBoards': 'Op dit niveau is nog niets getekend.',
  'org.boardName': 'Naam',
  'org.viewLayer7': 'Landschap',
  'org.viewContainer': 'Containers',
  'org.viewTechnology': 'Technologielandschap · opgemaakt uit de regels',
  'org.viewDrawing': 'Tekening',
  'org.viewSheet': 'Bedrijfsarchitectuur · opgemaakt uit de bomen',
  'org.viewMap': 'Bedrijfskaart · opgemaakt uit de regels',
  'org.viewAsOf': 'Per {date}',
  'org.viewToday': 'Vandaag',
  'org.onItOne': '{count} erop',
  'org.onItOther': '{count} erop',
  'org.containersOn': 'Containerdiagrammen op {name}',
  'org.containersLoose': 'Containerdiagrammen van applicaties die hier op geen landschap staan',
  'org.describedOne': '{count} van {total} beschreven',
  'org.describedOther': '{count} van {total} beschreven',
  'org.recordsOne': '{count} vastlegging',
  'org.recordsOther': '{count} vastleggingen',
  'org.latest': 'Laatste: {name}',
  'org.plansOne': '{count} plan',
  'org.plansOther': '{count} plannen',
  'org.initiativesOne': '{count} initiatief van eronder',
  'org.initiativesOther': '{count} initiatieven van eronder',
  'org.observationsOne': '{count} waarneming',
  'org.observationsOther': '{count} waarnemingen',
  'org.localBelowOne': '{count} in de scopes eronder',
  'org.localBelowOther': '{count} in de scopes eronder',
  'org.rootCausesOne': '{count} grondoorzaak',
  'org.rootCausesOther': '{count} grondoorzaken',
  'org.noFindings': 'Niets waarover de datums het oneens zijn.',
  'org.statusCount': '{count} {status}',
  'org.register': 'Register',
  'org.technology': 'Technologie',
  'org.nothingHere': 'Op dit niveau nog niets.',

  'org.tree': 'Scopes binnen {name}',
  'org.treeEmpty': 'Er is nog niets ondergebracht bij {name}. Voeg er een domein of een team onder toe.',
  'org.treeEmptyLandscape': 'Een landschap houdt zijn eigen weergaven bij. Voeg er alleen een scope onder toe om het op te splitsen.',
  'org.expand': 'Toon wat onder {name} zit',
  'org.collapse': 'Verberg wat onder {name} zit',

  'org.copyHere': 'In deze map kopi\u00ebren\u2026',

  'register.title': 'Register',
  'register.what': 'Elke applicatie in de organisatie, afgeleid uit de boom.',
  'register.applicationsOne': '{count} applicatie',
  'register.applicationsOther': '{count} applicaties',
  'register.ownedOne': '{count} beheerd door een domein',
  'register.ownedOther': '{count} beheerd door een domein',
  'register.outsideOne': '{count} van buiten',
  'register.outsideOther': '{count} van buiten',
  'register.definedTwiceOne': '{count} dubbel gedefinieerd',
  'register.definedTwiceOther': '{count} dubbel gedefinieerd',
  'register.unattributedOne': '{count} van buiten zonder eigenaar',
  'register.unattributedOther': '{count} van buiten zonder eigenaar',
  'register.staleOne': '{count} met een verouderde verwijzing',
  'register.staleOther': '{count} met verouderde verwijzingen',
  'register.settled': 'Niets waar het register het niet over eens is.',
  'register.empty': 'Nog nergens in deze organisatie is een applicatie gedefinieerd.',
  'register.noMatch': 'Geen applicatie komt overeen met \u201c{query}\u201d.',
  'register.filter': 'Filter',
  'register.order': 'Volgorde',
  'register.byName': 'Op naam',
  'register.byScope': 'Op niveau',
  'register.colName': 'Applicatie',
  'register.colMaster': 'Bijgehouden in',
  'register.colDrawn': 'Ook getekend in',
  'register.colFindings': 'Bevindingen',
  'register.nobody': 'Niemand',
  'register.outsideParty': 'Van buiten \u00b7 {name}',
  'register.outsideUnattributed': 'Van buiten \u00b7 niemand zei van wie',
  'register.drawnNowhere': 'Nergens anders',
  'register.drawnOne': '{count} niveau',
  'register.drawnOther': '{count} niveaus',
  'register.openRow': '{name} openen waar het wordt bijgehouden',
  'register.pageRow': 'De pagina van {name} openen',
  'register.linkRow': 'Koppelen\u2026',
  'register.linkRowTip': '{scope} openen en het record daar naar het andere laten verwijzen',
  'techRegister.title': 'Technologie',
  'techRegister.what': 'Elke platformdienst en elk platform in de organisatie, afgeleid uit de boom: wat wordt aangeboden, wat het levert, en wie erop leunt.',
  'techRegister.servicesOne': '{count} dienst',
  'techRegister.servicesOther': '{count} diensten',
  'techRegister.platformsOne': '{count} platform',
  'techRegister.platformsOther': '{count} platforms',
  'techRegister.sharedOne': '{count} gedeeld',
  'techRegister.sharedOther': '{count} gedeeld',
  'techRegister.offeredOne': '{count} aangeboden, niet als gedeeld gemarkeerd',
  'techRegister.offeredOther': '{count} aangeboden, niet als gedeeld gemarkeerd',
  'techRegister.unrealisedOne': '{count} zonder iets dat het levert',
  'techRegister.unrealisedOther': '{count} zonder iets dat ze levert',
  'techRegister.settled': 'Niets waar de technologie over van mening verschilt.',
  'techRegister.unrealisedSentence': '{name} wordt aangeboden, maar geen platform levert het \u2014 voeg het platform toe dat het levert, of trek de dienst in.',
  'techRegister.empty': 'Nergens in deze organisatie is al een platformdienst of platform gedefinieerd.',
  'techRegister.noMatch': 'Niets in de technologie komt overeen met \u201c{query}\u201d.',
  'techRegister.byKind': 'Op soort',
  'techRegister.colName': 'Dienst of platform',
  'techRegister.colWho': 'Onderhouden door · valt onder',
  'techRegister.colShared': 'Gedeeld',
  'techRegister.colUse': 'Gebruikt door · host',
  'techRegister.colRealised': 'Geleverd door · levert',
  'techRegister.shared': 'Gedeeld',
  'techRegister.ownTeam': 'Eigen team',
  'techRegister.nobodyMaintains': 'Niemand genoemd',
  'techRegister.partOf': 'In {name}',
  'techRegister.hostsOne': '{count} gehost',
  'techRegister.hostsOther': '{count} gehost',
  'techRegister.unrealised': 'Niets levert het',
  'techRegister.realisesNothing': 'Levert niets',
  'techRegister.forService': 'Voor {name}',

  'gesture.move': 'Verplaatsen\u2026',
  'gesture.moveTip': 'Dit record naar een ander niveau verplaatsen, of laten verwijzen naar een definitie elders',
  'gesture.title': '{name} verplaatsen',
  'gesture.what': 'Wat er moet gebeuren',
  'gesture.link': 'Koppelen',
  'gesture.linkWhat': 'Deze definitie opgeven en verwijzen naar die van een ander niveau. Beschrijving, data en eigenaar zijn dan van dat niveau: hier getoond, daar gewijzigd.',
  'gesture.promote': 'Omhoog',
  'gesture.promoteWhat': 'De definitie naar een niveau hierboven verplaatsen en hier een verwijzing achterlaten.',
  'gesture.demote': 'Omlaag',
  'gesture.demoteWhat': 'De definitie naar een niveau hieronder verplaatsen en hier een verwijzing achterlaten.',
  'gesture.transfer': 'Overdragen',
  'gesture.transferWhat': 'De definitie naar een ander niveau verplaatsen.',
  'gesture.to': 'Naar',
  'gesture.keepStandIn': 'Hier een verwijzing achterlaten',
  'gesture.keepStandInHelp': 'Zonder verwijzing tekent dit niveau het niet meer.',
  'gesture.go': 'Verplaatsen',
  'gesture.confirmTitle': '{scope} {name} laten beheren?',
  'gesture.confirmBody': 'Dit schrijft twee niveaus: eerst {scope}, dan dit. Ongedaan maken stopt daar \u2014 verplaats het record opnieuw om het terug te zetten.',
  'gesture.moved': '{scope} beheert {name} nu',
  'gesture.linked': '{name} verwijst nu naar het record in {scope}',
  'gesture.writeFailed': 'Dat niveau kon niet worden geschreven: {message}',
  'gesture.leftCopy': '{scope} heeft het nu, maar dit niveau kon niet worden geschreven, dus het record staat op twee plaatsen. {message}',

  'library.title': 'Bestaande applicatie toevoegen',
  'library.hint': 'Elke applicatie in de organisatie die nog niet op dit bord staat.',
  'library.search': 'Zoek in het register',
  'library.searchPlaceholder': 'Naam of id…',
  'library.none': 'Elke applicatie in de organisatie staat al op dit bord.',
  'library.noMatches': 'Niets komt overeen met “{query}”',
  'library.heldHere': 'Op dit niveau, niet op dit bord',
  'library.definedIn': 'Gedefinieerd in {scope}',
  'library.nobodyDefines': 'Niemand definieert deze',
  'library.ownTitle': 'Dit niveau {name} laten beheren?',
  'library.ownBody': 'Geen enkel niveau in de organisatie definieert {name}. Beheer het hier en dit niveau wordt de eigenaar; teken het alleen en de vraag blijft open.',
  'library.placeTitle': 'Hoe moet {name} hier verschijnen?',
  'library.placeDomain': 'Een applicatie uit een ander domein',
  'library.placeDomainWhat': 'Op het landschap, getekend als de applicatie die het is. Dubbelklikken opent het waar het gedefinieerd is.',
  'library.placeExternal': 'Een externe verwijzing',
  'library.placeExternalWhat': 'In de externe band, getekend als een systeem buiten dit landschap.',
  'library.own': 'Hier beheren',
  'library.drawOnly': 'Alleen tekenen',
  'library.drawn': '{name} staat op het bord',
  'library.standsIn': '{name} staat op het bord en verwijst naar het record in {scope}',
  'library.owned': 'Dit niveau beheert {name} nu',

}
