// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** German, for the roadmap (ADR-0009). Typed from `en.ts`. */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'roadmap.title': 'Fahrplan',
  'roadmap.open': 'Fahrplan',
  'roadmap.close': 'Fahrplan schließen',
  'roadmap.empty': 'Noch nichts hier hat ein Datum.',
  'roadmap.emptyHint': 'Geben Sie einer Anwendung ein Lebenszyklusdatum oder schreiben Sie einen Plan, dann erscheint er hier.',
  'roadmap.today': 'Heute',
  'roadmap.showing': 'Zeigt',
  'roadmap.applications': 'Anwendungen',
  'roadmap.relationsCount': '{count} Relationen',
  'roadmap.plans': 'Pläne',
  'roadmap.newPlan': 'Neuer Plan',
  'roadmap.newPlanTitle': 'Wie heißt der Plan?',
  'roadmap.noPlans': 'Noch keine Pläne.',
  'roadmap.planFrom': 'Von',
  'roadmap.planTo': 'Bis',
  'roadmap.planPorted': '{done} von {total} Schnittstellen verschoben',
  'roadmap.windowFrom': 'Anzeigen ab',
  'roadmap.windowTo': 'Anzeigen bis',
  'roadmap.windowClear': 'Ganze Zeitachse',
  'roadmap.shadowRun': 'Parallelbetrieb',
  'roadmap.owner': 'Verantwortlich',
  'roadmap.fromBelow': 'Initiativen aus den Bereichen darunter',
  'roadmap.initiative': 'Initiative',
  'roadmap.initiativeHelp': 'Auch auf dem Fahrplan jedes Bereichs darüber',
  'roadmap.openInitiative': 'In {scope} öffnen',
  'roadmap.showBelowChanges': 'Zeigen, was die Initiativen darunter ändern',
  'roadmap.milestones': 'Meilensteine',
  'roadmap.touches': 'Was er ändert',
  'roadmap.restsOn': 'Entscheidungen, auf denen er beruht',
  'roadmap.status': 'Status',
  'roadmap.shift': 'Verschieben…',
  'roadmap.shiftDays': 'Anzahl Tage, vor oder zurück',
  'roadmap.shiftHelp': 'Verschiebt das Zeitfenster und jeden Meilenstein, sowie die Daten dessen, was er einführt und abschaltet. Ein Schritt.',
  'roadmap.delete': 'Diesen Plan löschen',
  'roadmap.deleteConfirm': '„{name}“ löschen?',
  'roadmap.scrubHelp': 'Ziehen, um das Board hinter dieser Seite auf einen Tag zu bringen.',
  'plan.draft': 'Entwurf',
  'plan.agreed': 'Vereinbart',
  'plan.running': 'Läuft',
  'plan.done': 'Abgeschlossen',
  'plan.abandoned': 'Aufgegeben',
  'plan.introduces': 'Führt ein',
  'plan.retires': 'Schaltet ab',
  'plan.changes': 'Ändert',
  'plan.page': 'Plan',
  'plan.close': 'Zurück zum Fahrplan',
  'plan.read': 'Lesen',
  'plan.edit': 'Bearbeiten',
  'plan.source': 'Quelltext des Plans (Markdown)',
  'plan.bodyEmpty': 'Noch nichts geschrieben.',
  'plan.role': 'Rolle',
  'plan.addElement': 'Element',
  'plan.addApplication': 'Anwendung',
  'plan.add': 'Hinzufügen',
  'plan.remove': 'Entfernen',
  'plan.noElements': 'Nennt noch nichts. Fügen Sie hinzu, was er einführt, abschaltet oder ändert.',
  'plan.date.live': 'Live ab',
  'plan.date.retiring': 'Abschaltung ab',
  'plan.date.retired': 'Weg am',
  'plan.milestoneName': 'Meilenstein',
  'plan.milestoneDate': 'Datum',
  'plan.noMilestones': 'Noch keine Meilensteine.',
  'plan.decision': 'Entscheidung',
  'plan.noDecisions': 'Beruht noch auf keiner festgehaltenen Entscheidung.',
  'plan.fullPage': 'Ganze Seite',
  'plan.showFacts': 'Fakten anzeigen',
  'plan.resizeInterfaces': 'Größe der Schnittstellenliste ändern',
  'plan.interfaces': 'Schnittstellen',
  'plan.noInterfaces': 'Noch nichts zu übertragen: Nennen Sie, was der Plan abschaltet und was er einführt, dann erscheinen die Linien des Ersteren hier.',
  'plan.counterpart': 'Mit',
  'plan.protocol': 'Protokoll',
  'plan.movesTo': 'Geht nach',
  'plan.on': 'Am',
  'plan.ported': 'Übertragen',
  'plan.planned': 'Geplant',
  'plan.notPlanned': 'Noch nicht geplant',
  'plan.portAll': 'Alle übrigen übertragen',
  'plan.unport': 'Zurücknehmen',
  'plan.gateTitle': 'Bevor er auf {status} gesetzt werden kann',
  'plan.gate.window': 'Von und Bis sind gesetzt, und Bis liegt nicht vor Von',
  'plan.gate.owner': 'Jemand ist dafür verantwortlich',
  'plan.gate.names': 'Er nennt etwas, das er einführt, ablöst oder ändert',
  'plan.gate.decisions': 'Jede Entscheidung, auf der er beruht, ist angenommen',
  'plan.gate.started': 'Von ist erreicht',
  'plan.gate.introducedLive': 'Alles, was er einführt, hat ein Datum, an dem es in Betrieb geht',
  'plan.gate.retiredDated': 'Alles, was er ablöst, hat ein Datum, an dem es wegfällt',
  'plan.gate.interfacesPorted': 'Jede Schnittstelle hat ein Datum, an dem sie umzieht',
  'plan.gateHint.window': 'Beide Tage des Zeitraums, Von und Bis, mit Bis am oder nach Von.',
  'plan.gateHint.owner': 'Ein Name unter Verantwortlich: die Person oder das Team, das für den Plan einsteht.',
  'plan.gateHint.names': 'Mindestens ein Element unter „Was er ändert“, eingeführt, abgelöst oder geändert.',
  'plan.gateHint.decisions': 'Jeder Eintrag unter „Entscheidungen, auf denen er beruht“ muss auf der Entscheidungsseite angenommen sein. Ein Plan, der auf einem Vorschlag beruht, hat etwas zugestimmt, das niemand entschieden hat.',
  'plan.gateHint.started': 'Von ist heute oder früher: Ein Plan läuft ab seinem ersten Tag, nicht vorher.',
  'plan.gateHint.introducedLive': 'Jedes Element, das er einführt, braucht einen Tag unter „Live ab“, in seiner Zeile unter „Was er ändert“.',
  'plan.gateHint.retiredDated': 'Jedes Element, das er ablöst, braucht einen Tag unter „Weg am“, in seiner Zeile unter „Was er ändert“.',
  'plan.gateHint.interfacesPorted': 'Jede Zeile der Tabelle Schnittstellen braucht einen Tag, an dem sie umzieht, einzeln oder mit „Alle übrigen übertragen“.',
  'plan.gateHint.notAccepted': 'Noch nicht angenommen: {names}.',
  'plan.gateHint.withStatus': '{name} ({status})',
  'plan.gateHint.undated': 'Noch ohne diesen Tag: {names}.',
  'plan.gateHint.standInLive': 'In einem anderen Bereich geführt: {names}. Der Live-Tag eines Platzhalters wird dort gesetzt, wo das Element definiert ist, und erreicht keinen Plan hier. Führen Sie ihn also mit einem Plan jenes Bereichs ein, oder nennen Sie ihn hier als geändert.',
  'plan.gateHint.standInGone': 'In einem anderen Bereich geführt: {names}. Ein Platzhalter wird dort datiert, wo das Element definiert ist: Geben Sie ihm dort einen Tag unter „Weg am“, dann ist diese Zeile erfüllt.',
  'plan.gateHint.inScope': '{name} in {scope}',
  'plan.gateHint.gone': 'Einiges, was der Plan nennt, gibt es hier nicht mehr. Entfernen Sie die Zeilen mit „nicht mehr hier“, dann ist diese Zeile erfüllt.',
  'plan.goneElement': 'Ein Element, das nicht mehr hier ist',
  'plan.goneDecision': 'Eine Entscheidung, die nicht mehr hier ist',
  'plan.standInDates': 'Seine Daten führt {scope}, wo es definiert ist; setzen Sie sie dort.',
  'plan.standInDatesSomewhere': 'Seine Daten führt der Bereich, der es definiert; setzen Sie sie dort.',
  'plan.standInGoneOn': 'Weg am {day}, laut {scope}.',
  'plan.windowBackwards': 'Bis kann nicht vor Von liegen.',
  // Replace… (ADR-0010): the three inputs, and the words the gesture writes.
  'replace.title': '{name} ersetzen',
  'replace.arrives': 'Ersetzt durch',
  'replace.newApplication': 'Eine neue Anwendung, nach dem Bild dieser',
  'replace.newName': '{name} (neu)',
  'replace.existing': 'Eine, die bereits existiert',
  'replace.which': 'Welche',
  'replace.shape': 'Was mit ihr geschieht',
  'replace.goes': '{name} geht bei der Umstellung',
  'replace.stays': 'Ein Teil zieht um; {name} bleibt',
  'replace.also': 'Geht ebenfalls darin auf',
  'replace.alsoField': 'Eine weitere Anwendung, die darin aufgeht',
  'replace.shadowFrom': 'Parallelbetrieb ab',
  'replace.cutover': 'Umstellung',
  'replace.help': 'Ab dem Parallelbetrieb ist die neue live und zapft die alte für ihre Daten an; die Schnittstellen landen weiterhin auf der alten, bis jede einzeln übertragen ist. Mit der Umstellung ist die alte weg, und der Abgriff wurde am Tag davor geschlossen. Welche Schnittstelle wann umzieht, wird auf dem Plan festgelegt.',
  'replace.start': 'Plan starten',
  'replace.planTitle': '{from} durch {to} ersetzen',
  'replace.tap': 'Schattenabgriff',
  'replace.shadowMilestone': 'Parallelbetrieb beginnt',
  'replace.cutoverMilestone': 'Umstellung',
  'plan.template': `## Ziel

## Umfang

## Vorgehen und Phasen

## Business Case

{businessCase}

## Risiken

## Rückfallplan
`,
  'check.title': 'Wo sich die Daten widersprechen',
  'roadmap.deleteBody': 'Der Plan und seine Meilensteine gehen. Die Daten, die er auf Anwendungen gesetzt hat, bleiben bestehen, und Sie können dies rückgängig machen.',
  'check.none': 'Die Daten stimmen miteinander überein.',
  'check.retiresWithDependants': '{name} wird am {detail} abgeschaltet, während noch {count} Verbindungen live sind.',
  'check.successorTooLate': 'Der Nachfolger von {name} geht erst live, nachdem es weg ist: {detail}.',
  'check.successorMissing': '{name} wird am {detail} abgeschaltet, und kein Nachfolger ist benannt.',
  'check.lineOutlivesEnd': 'Die Zeile „{name}“ ({type}) ist noch gültig, nachdem {detail} abgeschaltet wurde.',
  'check.planOverdue': '{name} sollte am {detail} fertig sein und läuft noch.',
  'check.platformRetiresFirst': '{name} steht noch auf {detail}, nachdem es abgelöst wurde.',
  'check.impliedInterface': '{count} Container-Schnittstellen zwischen {name} und {detail} ohne Schnittstelle auf Anwendungsebene.',
  'check.accept': 'Übernehmen',
  'check.staleness': 'Dies zeigt, wo die Daten einander widersprechen. Ob eine Landschaft veraltet ist, kann es nicht sagen.',
}
