/** German, for the roadmap (ADR-0009). Typed from `en.ts`. */
import type { EN } from './en'

export const DE: Record<keyof typeof EN, string> = {
  'roadmap.title': 'Fahrplan',
  'roadmap.open': 'Fahrplan',
  'roadmap.close': 'Fahrplan schließen',
  'roadmap.empty': 'Noch nichts hier hat ein Datum.',
  'roadmap.emptyHint': 'Geben Sie einer Anwendung ein Lebenszyklusdatum oder schreiben Sie einen Plan, dann erscheint er hier.',
  'roadmap.today': 'Heute',
  'roadmap.showing': 'Zeigt',
  'roadmap.applications': 'Anwendungen',
  'roadmap.plans': 'Pläne',
  'roadmap.newPlan': 'Neuer Plan',
  'roadmap.newPlanTitle': 'Wie heißt der Plan?',
  'roadmap.noPlans': 'Noch keine Pläne.',
  'roadmap.planFrom': 'Von',
  'roadmap.planTo': 'Bis',
  'roadmap.planPorted': '{done} von {total} Schnittstellen übertragen',
  'roadmap.windowFrom': 'Anzeigen ab',
  'roadmap.windowTo': 'Anzeigen bis',
  'roadmap.windowClear': 'Ganze Zeitachse',
  'roadmap.shadowRun': 'Parallelbetrieb',
  'roadmap.owner': 'Verantwortlich',
  'roadmap.milestones': 'Meilensteine',
  'roadmap.touches': 'Was er ändert',
  'roadmap.restsOn': 'Entscheidungen, auf denen er beruht',
  'roadmap.status': 'Status',
  'roadmap.shift': 'Verschieben…',
  'roadmap.shiftDays': 'Anzahl Tage, vor oder zurück',
  'roadmap.shiftHelp': 'Verschiebt das Zeitfenster und jeden Meilenstein, sowie die Daten dessen, was er einführt und abschaltet. Ein Schritt.',
  'roadmap.delete': 'Diesen Plan löschen',
  'roadmap.deleteConfirm': '„{name}“ löschen? Die Daten, die er auf Anwendungen gesetzt hat, bleiben bestehen.',
  'roadmap.scrubHelp': 'Ziehen, um das Board hinter dieser Seite auf einen Tag zu bringen.',
  'plan.draft': 'Entwurf',
  'plan.agreed': 'Vereinbart',
  'plan.running': 'Läuft',
  'plan.done': 'Abgeschlossen',
  'plan.abandoned': 'Aufgegeben',
  'plan.introduces': 'Führt ein',
  'plan.retires': 'Schaltet ab',
  'plan.changes': 'Ändert',
  'plan.page': 'Plan',
  'plan.close': 'Zurück zum Fahrplan',
  'plan.read': 'Lesen',
  'plan.edit': 'Bearbeiten',
  'plan.source': 'Quelltext des Plans (Markdown)',
  'plan.bodyEmpty': 'Noch nichts geschrieben.',
  'plan.role': 'Rolle',
  'plan.addElement': 'Anwendung',
  'plan.add': 'Hinzufügen',
  'plan.remove': 'Entfernen',
  'plan.noElements': 'Nennt noch nichts. Fügen Sie hinzu, was er einführt, abschaltet oder ändert.',
  'plan.date.live': 'Live ab',
  'plan.date.retiring': 'Abschaltung ab',
  'plan.date.retired': 'Weg am',
  'plan.milestoneName': 'Meilenstein',
  'plan.milestoneDate': 'Datum',
  'plan.noMilestones': 'Noch keine Meilensteine.',
  'plan.decision': 'Entscheidung',
  'plan.noDecisions': 'Beruht noch auf keiner festgehaltenen Entscheidung.',
  'plan.fullPage': 'Ganze Seite',
  'plan.showFacts': 'Fakten anzeigen',
  'plan.resizeInterfaces': 'Größe der Schnittstellenliste ändern',
  'plan.interfaces': 'Schnittstellen',
  'plan.noInterfaces': 'Noch nichts zu übertragen: Nennen Sie, was der Plan abschaltet und was er einführt, dann erscheinen die Linien des Ersteren hier.',
  'plan.counterpart': 'Mit',
  'plan.protocol': 'Protokoll',
  'plan.movesTo': 'Geht nach',
  'plan.on': 'Am',
  'plan.ported': 'Übertragen',
  'plan.planned': 'Geplant',
  'plan.notPlanned': 'Noch nicht geplant',
  'plan.portAll': 'Alle übrigen übertragen',
  'plan.unport': 'Zurücknehmen',
  // Replace… (ADR-0010): the three inputs, and the words the gesture writes.
  'replace.title': '{name} ersetzen',
  'replace.arrives': 'Ersetzt durch',
  'replace.newApplication': 'Eine neue Anwendung, nach dem Bild dieser',
  'replace.newName': '{name} (neu)',
  'replace.existing': 'Eine, die bereits existiert',
  'replace.which': 'Welche',
  'replace.shape': 'Was mit ihr geschieht',
  'replace.goes': '{name} geht bei der Umstellung',
  'replace.stays': 'Ein Teil zieht um; {name} bleibt',
  'replace.also': 'Geht ebenfalls darin auf',
  'replace.alsoField': 'Eine weitere Anwendung, die darin aufgeht',
  'replace.shadowFrom': 'Parallelbetrieb ab',
  'replace.cutover': 'Umstellung',
  'replace.help': 'Ab dem Parallelbetrieb ist die neue live und zapft die alte für ihre Daten an; die Schnittstellen landen weiterhin auf der alten, bis jede einzeln übertragen ist. Mit der Umstellung ist die alte weg, und der Abgriff wurde am Tag davor geschlossen. Welche Schnittstelle wann umzieht, wird auf dem Plan festgelegt.',
  'replace.start': 'Plan starten',
  'replace.planTitle': '{from} durch {to} ersetzen',
  'replace.tap': 'Schattenabgriff',
  'replace.shadowMilestone': 'Parallelbetrieb beginnt',
  'replace.cutoverMilestone': 'Umstellung',
  'plan.template': `## Ziel

## Umfang

## Vorgehen und Phasen

## Business Case

{businessCase}

## Risiken

## Rückfallplan
`,
  'check.title': 'Worin sich die Daten widersprechen',
  'check.none': 'Die Daten stimmen miteinander überein.',
  'check.retiresWithDependants': '{name} wird am {detail} abgeschaltet, während noch {count} Verbindungen live sind.',
  'check.successorTooLate': 'Der Nachfolger von {name} geht erst live, nachdem es weg ist: {detail}.',
  'check.successorMissing': '{name} wird am {detail} abgeschaltet, und kein Nachfolger ist benannt.',
  'check.lineOutlivesEnd': '„{name}“ ist noch gültig, nachdem {detail} abgeschaltet wurde.',
  'check.planOverdue': '{name} sollte am {detail} fertig sein und läuft noch.',
  'check.staleness': 'Dies zeigt, wo die Daten einander widersprechen. Ob eine Landschaft veraltet ist, kann es nicht sagen.',
}
