/** Frisian, for the roadmap (ADR-0009). Typed from `en.ts`. */
import type { EN } from './en'

export const FY: Record<keyof typeof EN, string> = {
  'roadmap.title': 'Roadmap',
  'roadmap.open': 'Roadmap',
  'roadmap.close': 'Roadmap slute',
  'roadmap.empty': 'Noch neat hat in datum.',
  'roadmap.emptyHint': 'Jou in applikaasje in libbenssyklusdatum of skriuw in plan, dan ferskynt it hjir.',
  'roadmap.today': 'Hjoed',
  'roadmap.showing': 'Toant',
  'roadmap.applications': 'Applikaasjes',
  'roadmap.relations': 'Relaasjes',
  'roadmap.plans': 'Plannen',
  'roadmap.newPlan': 'Nij plan',
  'roadmap.newPlanTitle': 'Hoe hjit it plan?',
  'roadmap.noPlans': 'Noch gjin plannen.',
  'roadmap.planFrom': 'Fan',
  'roadmap.planTo': 'Oant',
  'roadmap.planPorted': '{done} fan {total} keppelflakken oerset',
  'roadmap.windowFrom': 'Toan fan',
  'roadmap.windowTo': 'Toan oant',
  'roadmap.windowClear': 'Hiele tiidline',
  'roadmap.shadowRun': 'Skaadrin',
  'roadmap.owner': 'Eigner',
  'roadmap.milestones': 'Mylpealen',
  'roadmap.touches': 'Wat it feroaret',
  'roadmap.restsOn': 'Besluten dêr\'t it op stipet',
  'roadmap.status': 'Status',
  'roadmap.shift': 'Ferskowe…',
  'roadmap.shiftDays': 'Tal dagen, foarút of werom',
  'roadmap.shiftHelp': 'Ferskoot it tiidfinster en elke mylpeal, en de datums fan wat it ynfiert en ôfbout. Ien stap.',
  'roadmap.delete': 'Dit plan fuortsmite',
  'roadmap.deleteConfirm': '“{name}” fuortsmite? De datums dy\'t it op applikaasjes set hat, bliuwe stean.',
  'roadmap.scrubHelp': 'Sleep om it boerd efter dizze side nei in dei te bringen.',
  'plan.draft': 'Konsept',
  'plan.agreed': 'Akkoart',
  'plan.running': 'Rint',
  'plan.done': 'Klear',
  'plan.abandoned': 'Opjûn',
  'plan.introduces': 'Fiert yn',
  'plan.retires': 'Bout ôf',
  'plan.changes': 'Feroaret',
  'plan.page': 'Plan',
  'plan.close': 'Werom nei de roadmap',
  'plan.read': 'Lêze',
  'plan.edit': 'Bewurkje',
  'plan.source': 'Boarne fan it plan (markdown)',
  'plan.bodyEmpty': 'Noch neat skreaun.',
  'plan.role': 'Rol',
  'plan.addElement': 'Applikaasje',
  'plan.add': 'Tafoegje',
  'plan.remove': 'Fuortsmite',
  'plan.noElements': 'Neamt noch neat. Foegje ta wat it ynfiert, ôfbout of feroaret.',
  'plan.date.live': 'Live fan',
  'plan.date.retiring': 'Ofbouwe fan',
  'plan.date.retired': 'Fuort op',
  'plan.milestoneName': 'Mylpeal',
  'plan.milestoneDate': 'Datum',
  'plan.noMilestones': 'Noch gjin mylpealen.',
  'plan.decision': 'Beslút',
  'plan.noDecisions': 'Stipet noch op gjin fêstlein beslút.',
  'plan.fullPage': 'Folsleine side',
  'plan.showFacts': 'Toan de feiten',
  'plan.resizeInterfaces': 'Keppelflakkenlist grutter of lytser meitsje',
  'plan.interfaces': 'Keppelflakken',
  'plan.noInterfaces': 'Noch neat te ferpleatsen: neam wat it plan ôfbout en wat it ynfiert, dan ferskine de linen fan it earste hjir.',
  'plan.counterpart': 'Mei',
  'plan.protocol': 'Protokol',
  'plan.movesTo': 'Giet nei',
  'plan.on': 'Op',
  'plan.ported': 'Ferpleatst',
  'plan.planned': 'Pland',
  'plan.notPlanned': 'Noch net pland',
  'plan.portAll': 'Rest oersette',
  'plan.unport': 'Weromnimme',
  // Replace… (ADR-0010): the three inputs, and the words the gesture writes.
  'replace.title': '{name} ferfange',
  'replace.arrives': 'Ferfongen troch',
  'replace.newApplication': 'In nije applikaasje, nei it byld fan dizze',
  'replace.newName': '{name} (nij)',
  'replace.existing': 'Ien dy\'t al bestiet',
  'replace.which': 'Hokker',
  'replace.shape': 'Wat dermei bart',
  'replace.goes': '{name} ferdwynt by de oerskeakeling',
  'replace.stays': 'In part ferhuzet; {name} bliuwt',
  'replace.also': 'Giet der ek yn op',
  'replace.alsoField': 'Noch in applikaasje dy\'t deryn opgiet',
  'replace.shadowFrom': 'Skaadrin fan',
  'replace.cutover': 'Oerskeakeling',
  'replace.help': 'Fan de skaadrin ôf is de nije live en tapet dy de âlde ôf foar syn data; de keppelflakken komme noch op de âlde oan oant elk ferhuze is. By de oerskeakeling is de âlde fuort, en de tap is de dei derfoar sletten. Hokker keppelflak wannear ferhuzet, stiet op it plan.',
  'replace.start': 'Plan starte',
  'replace.planTitle': '{from} ferfange troch {to}',
  'replace.tap': 'skaadtap',
  'replace.shadowMilestone': 'Skaadrin begjint',
  'replace.cutoverMilestone': 'Oerskeakeling',
  'plan.template': `## Doel

## Omfang

## Oanpak en fazen

## Businesscase

{businessCase}

## Risiko's

## Weromfalsenario
`,
  'check.title': 'Wêr\'t de datums it net oer iens binne',
  'check.none': 'De datums binne ûnderinoar konsistint.',
  'check.retiresWithDependants': '{name} wurdt ôfboud op {detail} wylst der noch {count} keppelingen live binne.',
  'check.successorTooLate': 'De opfolger fan {name} giet pas live neidat it fuort is: {detail}.',
  'check.successorMissing': '{name} wurdt ôfboud op {detail} en der is gjin opfolger neamd.',
  'check.lineOutlivesEnd': 'De rige “{name}” ({type}) is noch jildich neidat {detail} ôfboud is.',
  'check.planOverdue': '{name} soe op {detail} klear wêze en rint noch.',
  'check.staleness': 'Dit toant wêr\'t de datums inoar tsjinsprekke. It kin net sjen oft in lânskip ferâldere is.',
}
