/** Nederlands, voor de roadmap (ADR-0009). Getypeerd vanuit `en.ts`. */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'roadmap.title': 'Roadmap',
  'roadmap.open': 'Roadmap',
  'roadmap.close': 'Roadmap sluiten',
  'roadmap.empty': 'Nog niets heeft een datum.',
  'roadmap.emptyHint': 'Geef een applicatie een levenscyclusdatum of schrijf een plan, dan verschijnt het hier.',
  'roadmap.today': 'Vandaag',
  'roadmap.showing': 'Toont',
  'roadmap.applications': 'Applicaties',
  'roadmap.plans': 'Plannen',
  'roadmap.newPlan': 'Nieuw plan',
  'roadmap.newPlanTitle': 'Hoe heet het plan?',
  'roadmap.noPlans': 'Nog geen plannen.',
  'roadmap.planWindow': '{from} tot {to}',
  'roadmap.planOpen': 'geen einddatum',
  'roadmap.planUndated': 'nog niet gedateerd',
  'roadmap.owner': 'Eigenaar',
  'roadmap.milestones': 'Mijlpalen',
  'roadmap.touches': 'Wat het verandert',
  'roadmap.restsOn': 'Besluiten waarop het steunt',
  'roadmap.status': 'Status',
  'roadmap.shift': 'Verschuiven…',
  'roadmap.shiftDays': 'Aantal dagen, vooruit of terug',
  'roadmap.shiftHelp': 'Verschuift het venster en elke mijlpaal, en de datums van wat het invoert en uitfaseert. Eén stap.',
  'roadmap.delete': 'Dit plan verwijderen',
  'roadmap.deleteConfirm': '“{name}” verwijderen? De datums die het op applicaties zette blijven staan.',
  'roadmap.scrubHelp': 'Sleep om het bord achter deze pagina naar een dag te brengen.',
  'plan.draft': 'Concept',
  'plan.agreed': 'Akkoord',
  'plan.running': 'Loopt',
  'plan.done': 'Gereed',
  'plan.abandoned': 'Gestaakt',
  'plan.introduces': 'Voert in',
  'plan.retires': 'Faseert uit',
  'plan.changes': 'Wijzigt',
  'check.title': 'Waarover de datums het oneens zijn',
  'check.none': 'De datums zijn onderling consistent.',
  'check.retiresWithDependants': '{name} wordt uitgefaseerd op {detail} terwijl er nog {count} koppelingen live zijn.',
  'check.successorTooLate': 'De opvolger van {name} gaat pas live nadat het weg is: {detail}.',
  'check.successorMissing': '{name} wordt uitgefaseerd op {detail} en er is geen opvolger benoemd.',
  'check.lineOutlivesEnd': '“{name}” is nog geldig nadat {detail} is uitgefaseerd.',
  'check.planOverdue': '{name} zou op {detail} klaar zijn en loopt nog.',
  'check.staleness': 'Dit toont waar de datums elkaar tegenspreken. Het kan niet zien of een landschap verouderd is.',
}
