// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2024–2026 Lionsville Group BV

/** Nederlands, voor de roadmap (ADR-0009). Getypeerd vanuit `en.ts`. */
import type { EN } from './en'

export const NL: Record<keyof typeof EN, string> = {
  'roadmap.title': 'Roadmap',
  'roadmap.open': 'Roadmap',
  'roadmap.close': 'Roadmap sluiten',
  'roadmap.empty': 'Nog niets heeft een datum.',
  'roadmap.emptyHint': 'Geef een applicatie een levenscyclusdatum of schrijf een plan, dan verschijnt het hier.',
  'roadmap.today': 'Vandaag',
  'roadmap.showing': 'Toont',
  'roadmap.applications': 'Applicaties',
  'roadmap.relationsCount': '{count} relaties',
  'roadmap.plans': 'Plannen',
  'roadmap.newPlan': 'Nieuw plan',
  'roadmap.newPlanTitle': 'Hoe heet het plan?',
  'roadmap.noPlans': 'Nog geen plannen.',
  'roadmap.planFrom': 'Van',
  'roadmap.planTo': 'Tot',
  'roadmap.planPorted': '{done} van {total} koppelingen verplaatst',
  'roadmap.windowFrom': 'Toon vanaf',
  'roadmap.windowTo': 'Toon tot',
  'roadmap.windowClear': 'Hele as',
  'roadmap.shadowRun': 'Schaduwdraaien',
  'roadmap.owner': 'Eigenaar',
  'roadmap.fromBelow': 'Initiatieven uit de niveaus eronder',
  'roadmap.initiative': 'Initiatief',
  'roadmap.initiativeHelp': 'Ook op de roadmap van elk niveau hierboven',
  'roadmap.openInitiative': 'Openen in {scope}',
  'roadmap.showBelowChanges': 'Toon wat de initiatieven eronder veranderen',
  'roadmap.milestones': 'Mijlpalen',
  'roadmap.touches': 'Wat het verandert',
  'roadmap.restsOn': 'Besluiten waarop het steunt',
  'roadmap.status': 'Status',
  'roadmap.shift': 'Verschuiven…',
  'roadmap.shiftDays': 'Aantal dagen, vooruit of terug',
  'roadmap.shiftHelp': 'Verschuift het venster en elke mijlpaal, en de datums van wat het invoert en uitfaseert. Eén stap.',
  'roadmap.delete': 'Dit plan verwijderen',
  'roadmap.deleteConfirm': '“{name}” verwijderen?',
  'roadmap.scrubHelp': 'Sleep om het bord achter deze pagina naar een dag te brengen.',
  'plan.draft': 'Concept',
  'plan.agreed': 'Akkoord',
  'plan.running': 'Loopt',
  'plan.done': 'Gereed',
  'plan.abandoned': 'Gestaakt',
  'plan.introduces': 'Voert in',
  'plan.retires': 'Faseert uit',
  'plan.changes': 'Wijzigt',
  'plan.page': 'Plan',
  'plan.close': 'Terug naar de roadmap',
  'plan.read': 'Lezen',
  'plan.edit': 'Bewerken',
  'plan.source': 'Bron van het plan (markdown)',
  'plan.bodyEmpty': 'Nog niets geschreven.',
  'plan.role': 'Rol',
  'plan.addElement': 'Element',
  'plan.addApplication': 'Applicatie',
  'plan.add': 'Toevoegen',
  'plan.remove': 'Verwijderen',
  'plan.noElements': 'Benoemt nog niets. Voeg toe wat het invoert, uitfaseert of wijzigt.',
  'plan.date.live': 'Live vanaf',
  'plan.date.retiring': 'Uitfaseren vanaf',
  'plan.date.retired': 'Weg op',
  'plan.milestoneName': 'Mijlpaal',
  'plan.milestoneDate': 'Datum',
  'plan.noMilestones': 'Nog geen mijlpalen.',
  'plan.decision': 'Besluit',
  'plan.noDecisions': 'Steunt nog op geen vastgelegd besluit.',
  'plan.fullPage': 'Volledige pagina',
  'plan.showFacts': 'Toon de feiten',
  'plan.resizeInterfaces': 'Koppelingenlijst vergroten of verkleinen',
  'plan.interfaces': 'Koppelingen',
  'plan.noInterfaces': 'Nog niets te verplaatsen: benoem wat het plan uitfaseert en wat het invoert, dan verschijnen de lijnen van het eerste hier.',
  'plan.counterpart': 'Met',
  'plan.protocol': 'Protocol',
  'plan.movesTo': 'Gaat naar',
  'plan.on': 'Op',
  'plan.ported': 'Verplaatst',
  'plan.planned': 'Gepland',
  'plan.notPlanned': 'Nog niet gepland',
  'plan.portAll': 'Rest overzetten',
  'plan.unport': 'Terugnemen',
  'plan.gateTitle': 'Voordat het naar {status} kan',
  'plan.gate.window': 'Van en Tot zijn ingevuld, en Tot ligt niet v\u00f3\u00f3r Van',
  'plan.gate.owner': 'Iemand is er eigenaar van',
  'plan.gate.names': 'Het noemt iets dat het invoert, uitfaseert of wijzigt',
  'plan.gate.decisions': 'Elk besluit waarop het steunt is aanvaard',
  'plan.gate.started': 'Van is aangebroken',
  'plan.gate.introducedLive': 'Alles wat het invoert heeft een datum waarop het live gaat',
  'plan.gate.retiredDated': 'Alles wat het uitfaseert heeft een datum waarop het verdwijnt',
  'plan.gate.interfacesPorted': 'Elke koppeling heeft een datum waarop ze verhuist',
  'plan.gateHint.window': 'Beide dagen van het venster, Van en Tot, met Tot op of na Van.',
  'plan.gateHint.owner': 'Een naam bij Eigenaar: de persoon of het team dat voor het plan instaat.',
  'plan.gateHint.names': 'Minstens één element onder “Wat het verandert”, ingevoerd, uitgefaseerd of gewijzigd.',
  'plan.gateHint.decisions': 'Elk record onder “Besluiten waarop het steunt” moet op de besluitenpagina aanvaard zijn. Een plan dat op een voorstel steunt, heeft ingestemd met iets waarover niemand besliste.',
  'plan.gateHint.started': 'Van is vandaag of eerder: een plan loopt vanaf zijn eerste dag, niet eerder.',
  'plan.gateHint.introducedLive': 'Elk element dat het invoert heeft een dag bij “Live vanaf” nodig, in zijn regel onder “Wat het verandert”.',
  'plan.gateHint.retiredDated': 'Elk element dat het uitfaseert heeft een dag bij “Weg op” nodig, in zijn regel onder “Wat het verandert”.',
  'plan.gateHint.interfacesPorted': 'Elke regel van de tabel Koppelingen heeft een dag nodig waarop ze verhuist, één voor één of met “Rest overzetten”.',
  'plan.gateHint.notAccepted': 'Nog niet aanvaard: {names}.',
  'plan.gateHint.withStatus': '{name} ({status})',
  'plan.gateHint.undated': 'Nog zonder die dag: {names}.',
  'plan.gateHint.standInLive': 'Vastgelegd in een andere scope: {names}. De live-datum van een verwijzing staat waar het gedefinieerd is en komt niet bij een plan hier. Voer het dus in met een plan van die scope, of noem het hier als gewijzigd.',
  'plan.gateHint.standInGone': 'Vastgelegd in een andere scope: {names}. Een verwijzing wordt gedateerd waar het gedefinieerd is: geef het daar een dag bij “Weg op”, dan is deze regel klaar.',
  'plan.gateHint.inScope': '{name} in {scope}',
  'plan.gateHint.gone': 'Een deel van wat het plan noemt is er niet meer. Verwijder de regels met “niet meer hier”, dan is deze regel klaar.',
  'plan.goneElement': 'Een element dat niet meer hier is',
  'plan.goneDecision': 'Een besluit dat niet meer hier is',
  'plan.standInDates': 'De data staan in {scope}, dat het definieert; zet ze daar.',
  'plan.standInDatesSomewhere': 'De data staan in de scope die het definieert; zet ze daar.',
  'plan.standInGoneOn': 'Weg op {day}, volgens {scope}.',
  'plan.windowBackwards': 'Tot kan niet v\u00f3\u00f3r Van liggen.',
  // Replace… (ADR-0010): the three inputs, and the words the gesture writes.
  'replace.title': '{name} vervangen',
  'replace.arrives': 'Vervangen door',
  'replace.newApplication': 'Een nieuwe applicatie, naar het beeld van deze',
  'replace.newName': '{name} (nieuw)',
  'replace.existing': 'Een die al bestaat',
  'replace.which': 'Welke',
  'replace.shape': 'Wat ermee gebeurt',
  'replace.goes': '{name} verdwijnt bij de cutover',
  'replace.stays': 'Een deel verhuist; {name} blijft',
  'replace.also': 'Gaat er ook in op',
  'replace.alsoField': 'Nog een applicatie die erin opgaat',
  'replace.shadowFrom': 'Schaduwdraaien vanaf',
  'replace.cutover': 'Cutover',
  'replace.help': 'Vanaf het schaduwdraaien is de nieuwe live en tapt die de oude af voor zijn data; de koppelingen komen nog op de oude aan tot elk is verhuisd. Op de cutover is de oude weg, en de tap is de dag ervoor gesloten. Welke koppeling wanneer verhuist staat op het plan.',
  'replace.start': 'Plan starten',
  'replace.planTitle': '{from} vervangen door {to}',
  'replace.tap': 'schaduwtap',
  'replace.shadowMilestone': 'Schaduwdraaien begint',
  'replace.cutoverMilestone': 'Cutover',
  'plan.template': `## Doel

## Scope

## Aanpak en fasen

## Businesscase

{businessCase}

## Risico's

## Terugvalscenario
`,
  'check.title': 'Waar de datums het oneens zijn',
  'roadmap.deleteBody': 'Het plan en zijn mijlpalen verdwijnen. De datums die het op applicaties zette blijven staan, en je kunt dit ongedaan maken.',
  'check.none': 'De datums zijn onderling consistent.',
  'check.retiresWithDependants': '{name} wordt uitgefaseerd op {detail} terwijl er nog {count} koppelingen live zijn.',
  'check.successorTooLate': 'De opvolger van {name} gaat pas live nadat het weg is: {detail}.',
  'check.successorMissing': '{name} wordt uitgefaseerd op {detail} en er is geen opvolger benoemd.',
  'check.lineOutlivesEnd': 'De rij “{name}” ({type}) is nog geldig nadat {detail} is uitgefaseerd.',
  'check.planOverdue': '{name} zou op {detail} klaar zijn en loopt nog.',
  'check.platformRetiresFirst': '{name} staat nog op {detail} nadat dat is uitgefaseerd.',
  'check.impliedInterface': '{count} koppelvlakken op containerniveau tussen {name} en {detail} zonder koppelvlak op applicatieniveau.',
  'check.accept': 'Overnemen',
  'check.staleness': 'Dit toont waar de datums elkaar tegenspreken. Het kan niet zien of een landschap verouderd is.',
}
